/****************************************************************************
*
*    Copyright 2012 - 2016 Vivante Corporation, Santa Clara, California.
*    All Rights Reserved.
*
*    Permission is hereby granted, free of charge, to any person obtaining
*    a copy of this software and associated documentation files (the
*    'Software'), to deal in the Software without restriction, including
*    without limitation the rights to use, copy, modify, merge, publish,
*    distribute, sub license, and/or sell copies of the Software, and to
*    permit persons to whom the Software is furnished to do so, subject
*    to the following conditions:
*
*    The above copyright notice and this permission notice (including the
*    next paragraph) shall be included in all copies or substantial
*    portions of the Software.
*
*    THE SOFTWARE IS PROVIDED 'AS IS', WITHOUT WARRANTY OF ANY KIND,
*    EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
*    MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT.
*    IN NO EVENT SHALL VIVANTE AND/OR ITS SUPPLIERS BE LIABLE FOR ANY
*    CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
*    TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
*    SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*
*****************************************************************************/


/* Generated by resources.mk. */
/* Do NOT edit this file. */

#include <stdio.h>

#ifdef __cplusplus
extern "C" {
#endif

#include "shaders/chiclet.frag.c"
#include "shaders/chiclet.vert.c"
#include "shaders/content.frag.c"
#include "shaders/content.vert.c"
#include "shaders/env.frag.c"
#include "shaders/env.vert.c"
#include "textures/envcube.dds.c"
#include "textures/envelope.dds.c"
#include "textures/Vivante-Logo.Black.Square.dds.c"
#include "textures/3dmark06_samurai.dds.c"
#include "textures/photo_album.dds.c"
#include "textures/firefox.dds.c"
#include "textures/3dmark07_taiji.dds.c"
#include "textures/vgmark_navi.dds.c"
#include "textures/vgmark_flash.dds.c"
#include "textures/cover_flow.dds.c"

Resource* resources[MAX_RESOURCES] =
{
    &_chiclet_frag,
    &_chiclet_vert,
    &_content_frag,
    &_content_vert,
    &_env_frag,
    &_env_vert,
    &_envcube_dds,
    &_envelope_dds,
    &_Vivante_Logo_Black_Square_dds,
    &_3dmark06_samurai_dds,
    &_photo_album_dds,
    &_firefox_dds,
    &_3dmark07_taiji_dds,
    &_vgmark_navi_dds,
    &_vgmark_flash_dds,
    &_cover_flow_dds,
    NULL,
};

#ifdef __cplusplus
}
#endif

