.PHONY: all clean

rc :=                           \
    shaders/chiclet.frag           \
    shaders/chiclet.vert           \
    shaders/content.frag            \
    shaders/content.vert            \
    shaders/env.frag                \
    shaders/env.vert                \
    textures/envcube.dds            \
    textures/envelope.dds           \
    textures/Vivante-Logo.Black.Square.dds  \
    textures/3dmark06_samurai.dds           \
    textures/photo_album.dds            \
    textures/firefox.dds                \
    textures/3dmark07_taiji.dds         \
    textures/vgmark_navi.dds            \
    textures/vgmark_flash.dds           \
    textures/cover_flow.dds         \
    ${NULL}

RES := ../bin/resource

strcuts := $(notdir $(rc))
strcuts := $(addprefix _, $(strcuts))

dot := .
strcuts := $(subst $(dot),_, $(strcuts))
strcuts := $(subst -,_, $(strcuts))

all:
	@echo "/* Generated by resources.mk. */" > resources.c
	@echo "/* Do NOT edit this file. */" >> resources.c
	@echo >>resources.c
	@echo "#include <stdio.h>" >>resources.c
	@echo >>resources.c
	@echo "#"ifdef __cplusplus >>resources.c
	@echo extern \"C\" \{ >>resources.c
	@echo "#"endif >>resources.c
	@echo >>resources.c
	@for a in $(rc); do $(RES) $$a; echo "#"include \"$$a.c\" >>resources.c; done;
	@echo >> resources.c
	@echo Resource* resources[MAX_RESOURCES] = >>resources.c
	@echo \{ >>resources.c
	@for a in $(strcuts); do echo "	&$$a," >>resources.c; done;
	@echo "	NULL," >> resources.c
	@echo \}\; >>resources.c
	@echo >> resources.c
	@echo "#"ifdef __cplusplus >>resources.c
	@echo \} >>resources.c
	@echo "#endif" >>resources.c
	@echo >> resources.c

clean:
	@-rm textures/*.c
	@-rm shaders/*.c
	@-rm resources.c

