#!/bin/bash

export BUILD_OPTION_EGL_API_WL=1
export BUILD_OPTION_EGL_API_FB=1
export BUILD_OPTION_GL4_DRI_BUILD=1
export BUILD_OPTION_EGL_API_GBM=1
export GBM_LIBS=

./driver_build_sample.sh $*

unset BUILD_OPTION_EGL_API_WL
unset BUILD_OPTION_EGL_API_FB
unset BUILD_OPTION_GL4_DRI_BUILD
unset BUILD_OPTION_EGL_API_GBM
unset GBM_LIBS
