##############################################################################
#
#    Copyright 2012 - 2015 Vivante Corporation, Santa Clara, California.
#    All Rights Reserved.
#
#    Permission is hereby granted, free of charge, to any person obtaining
#    a copy of this software and associated documentation files (the
#    'Software'), to deal in the Software without restriction, including
#    without limitation the rights to use, copy, modify, merge, publish,
#    distribute, sub license, and/or sell copies of the Software, and to
#    permit persons to whom the Software is furnished to do so, subject
#    to the following conditions:
#
#    The above copyright notice and this permission notice (including the
#    next paragraph) shall be included in all copies or substantial
#    portions of the Software.
#
#    THE SOFTWARE IS PROVIDED 'AS IS', WITHOUT WARRANTY OF ANY KIND,
#    EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
#    MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT.
#    IN NO EVENT SHALL VIVANTE AND/OR ITS SUPPLIERS BE LIABLE FOR ANY
#    CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
#    TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
#    SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
##############################################################################


#
# Linux build file for vv_launcher lib: glutils
#

################################################################################
# Include the common difinitions.
TOP_DIR	:= ../../
include $(TOP_DIR)/makefile.linux.def

################################################################################
# Define the program.

STATIC		:= 1
TARGET_NAME	:= libglutils.a

################################################################################
# Describe object files.

OBJECTS = 	$(OBJ_DIR)/check.o \
			$(OBJ_DIR)/dds.o \
			$(OBJ_DIR)/log.o \
			$(OBJ_DIR)/program.o \
			$(OBJ_DIR)/Texture2D.o \
			$(OBJ_DIR)/Texture2DRenderSurface.o \
			$(OBJ_DIR)/TextureCube.o

###############################################################################
# Additional include directories.
CFLAGS	+=	-I$(TOP_DIR)/lib

################################################################################
# Include the common makefile.

include $(AQROOT)/common.target

