##############################################################################
#
#    Copyright 2012 - 2017 Vivante Corporation, Santa Clara, California.
#    All Rights Reserved.
#
#    Permission is hereby granted, free of charge, to any person obtaining
#    a copy of this software and associated documentation files (the
#    'Software'), to deal in the Software without restriction, including
#    without limitation the rights to use, copy, modify, merge, publish,
#    distribute, sub license, and/or sell copies of the Software, and to
#    permit persons to whom the Software is furnished to do so, subject
#    to the following conditions:
#
#    The above copyright notice and this permission notice (including the
#    next paragraph) shall be included in all copies or substantial
#    portions of the Software.
#
#    THE SOFTWARE IS PROVIDED 'AS IS', WITHOUT WARRANTY OF ANY KIND,
#    EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
#    MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT.
#    IN NO EVENT SHALL VIVANTE AND/OR ITS SUPPLIERS BE LIABLE FOR ANY
#    CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
#    TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
#    SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
##############################################################################


#
# Driver part of OpenVX.
#

#############################################################################
# Include common definitions.

include ../makefile.linux.def

INCLUDE += -I $(VIVANTE_SDK_DIR)/include
CFLAGS += $(INCLUDE)

#############################################################################
# Macros.

#CFLAGS  += -DHAVE_NEON=1 -march=armv7-a -mfpu=neon -ftree-vectorize -ffast-math -mfloat-abi=hard

#CFLAGS += -std=c99

ifeq ($(NO_SHOW_ON_SCREEN),1)
    CFLAGS += -DNO_SHOW
endif

PROGRAM = 1

TARGET_NAME = vx_tutorial2

#############################################################################
# Objects.

OBJECTS         =   $(OBJ_DIR)/vx_tutorial2.o

################################################################################
LIBS += -L $(VIVANTE_SDK_DIR)//drivers
LIBS += -l dl -l pthread -l m -l stdc++
LIBS += -l OpenVX -l OpenVXU

################################################################################
# Define the macros used in common makefile.

# installation directory
INSTALL_DIR := $(SDK_DIR)/samples/ovx

################################################################################
# Include the common makefile.

include $(AQROOT)/common.target

################################################################################
# Extra installation.

install: extra_install

.PHONY: extra_install
extra_install:
	@-mkdir -p $(INSTALL_DIR)
	@-cp -f lena_gray.bmp $(INSTALL_DIR)
	@-cp -f $(VIVANTE_SDK_DIR)/include/CL/cl_viv_vx_ext.h $(INSTALL_DIR)
