/****************************************************************************
*
*    Copyright (c) 2005 - 2017 by Vivante Corp.  All rights reserved.
*
*    The material in this file is confidential and contains trade secrets
*    of Vivante Corporation. This is proprietary information owned by
*    Vivante Corporation. No part of this work may be disclosed,
*    reproduced, copied, transmitted, or used in any way for any purpose,
*    without the express written permission of Vivante Corporation.
*
*****************************************************************************/


/* $XFree86: xc/programs/Xserver/GL/glx/g_disptab_EXT.h,v 1.5 2004/01/28 18:11:50 alanh Exp $ */
/* DO NOT EDIT - THIS FILE IS AUTOMATICALLY GENERATED */
#ifdef HAVE_DIX_CONFIG_H
#include <dix-config.h>
#endif

#ifndef _GLX_g_disptab_EXT_h_
#define _GLX_g_disptab_EXT_h_
/*
** License Applicability. Except to the extent portions of this file are
** made subject to an alternative license as permitted in the SGI Free
** Software License B, Version 1.1 (the "License"), the contents of this
** file are subject only to the provisions of the License. You may not use
** this file except in compliance with the License. You may obtain a copy
** of the License at Silicon Graphics, Inc., attn: Legal Services, 1600
** Amphitheatre Parkway, Mountain View, CA 94043-1351, or at:
**
** http://oss.sgi.com/projects/FreeB
**
** Note that, as provided in the License, the Software is distributed on an
** "AS IS" basis, with ALL EXPRESS AND IMPLIED WARRANTIES AND CONDITIONS
** DISCLAIMED, INCLUDING, WITHOUT LIMITATION, ANY IMPLIED WARRANTIES AND
** CONDITIONS OF MERCHANTABILITY, SATISFACTORY QUALITY, FITNESS FOR A
** PARTICULAR PURPOSE, AND NON-INFRINGEMENT.
**
** Original Code. The Original Code is: OpenGL Sample Implementation,
** Version 1.2.1, released January 26, 2000, developed by Silicon Graphics,
** Inc. The Original Code is Copyright (c) 1991-2000 Silicon Graphics, Inc.
** Copyright in any portions created by third parties is as indicated
** elsewhere herein. All Rights Reserved.
**
** Additional Notice Provisions: This software was created using the
** OpenGL(R) version 1.2.1 Sample Implementation published by SGI, but has
** not been independently verified as being compliant with the OpenGL(R)
** version 1.2.1 Specification.
*/

extern int __glXDisp_AreTexturesResidentEXT(__GLXclientState*, GLbyte*);
extern int __glXDisp_DeleteTexturesEXT(__GLXclientState*, GLbyte*);
extern int __glXDisp_GenTexturesEXT(__GLXclientState*, GLbyte*);
extern int __glXDisp_IsTextureEXT(__GLXclientState*, GLbyte*);

extern GLvoid __glXDisp_ColorTable(GLbyte*);
extern GLvoid __glXDisp_ColorTableParameterfv(GLbyte*);
extern GLvoid __glXDisp_ColorTableParameteriv(GLbyte*);
extern GLvoid __glXDisp_CopyColorTable(GLbyte*);
extern GLvoid __glXDisp_BlendColor(GLbyte*);
extern GLvoid __glXDisp_BlendEquation(GLbyte*);
extern GLvoid __glXDisp_TexSubImage1D(GLbyte*);
extern GLvoid __glXDisp_TexSubImage2D(GLbyte*);
extern GLvoid __glXDisp_ConvolutionFilter1D(GLbyte*);
extern GLvoid __glXDisp_ConvolutionFilter2D(GLbyte*);
extern GLvoid __glXDisp_ConvolutionParameterf(GLbyte*);
extern GLvoid __glXDisp_ConvolutionParameterfv(GLbyte*);
extern GLvoid __glXDisp_ConvolutionParameteri(GLbyte*);
extern GLvoid __glXDisp_ConvolutionParameteriv(GLbyte*);
extern GLvoid __glXDisp_CopyConvolutionFilter1D(GLbyte*);
extern GLvoid __glXDisp_CopyConvolutionFilter2D(GLbyte*);
extern GLvoid __glXDisp_SeparableFilter2D(GLbyte*);
extern GLvoid __glXDisp_Histogram(GLbyte*);
extern GLvoid __glXDisp_Minmax(GLbyte*);
extern GLvoid __glXDisp_ResetHistogram(GLbyte*);
extern GLvoid __glXDisp_ResetMinmax(GLbyte*);
extern GLvoid __glXDisp_TexImage3D(GLbyte*);
extern GLvoid __glXDisp_TexSubImage3D(GLbyte*);
extern GLvoid __glXDisp_DrawArraysEXT(GLbyte*);
extern GLvoid __glXDisp_BindTexture(GLbyte*);
extern GLvoid __glXDisp_PrioritizeTextures(GLbyte*);
extern GLvoid __glXDisp_CopyTexImage1D(GLbyte*);
extern GLvoid __glXDisp_CopyTexImage2D(GLbyte*);
extern GLvoid __glXDisp_CopyTexSubImage1D(GLbyte*);
extern GLvoid __glXDisp_CopyTexSubImage2D(GLbyte*);
extern GLvoid __glXDisp_CopyTexSubImage3D(GLbyte*);
extern GLvoid __glXDisp_PointParameterfARB(GLbyte*);
extern GLvoid __glXDisp_PointParameterfvARB(GLbyte*);

extern GLvoid __glXDisp_FogCoordfv(GLbyte *);
extern GLvoid __glXDisp_FogCoorddv(GLbyte *);
extern GLvoid __glXDispSwap_FogCoordfv(GLbyte *);
extern GLvoid __glXDispSwap_FogCoorddv(GLbyte *);

extern GLvoid __glXDisp_SecondaryColor3bv(GLbyte *);
extern GLvoid __glXDisp_SecondaryColor3sv(GLbyte *);
extern GLvoid __glXDisp_SecondaryColor3iv(GLbyte *);
extern GLvoid __glXDisp_SecondaryColor3ubv(GLbyte *);
extern GLvoid __glXDisp_SecondaryColor3usv(GLbyte *);
extern GLvoid __glXDisp_SecondaryColor3uiv(GLbyte *);
extern GLvoid __glXDisp_SecondaryColor3fv(GLbyte *);
extern GLvoid __glXDisp_SecondaryColor3dv(GLbyte *);
extern GLvoid __glXDispSwap_SecondaryColor3bv(GLbyte *);
extern GLvoid __glXDispSwap_SecondaryColor3sv(GLbyte *);
extern GLvoid __glXDispSwap_SecondaryColor3iv(GLbyte *);
extern GLvoid __glXDispSwap_SecondaryColor3ubv(GLbyte *);
extern GLvoid __glXDispSwap_SecondaryColor3usv(GLbyte *);
extern GLvoid __glXDispSwap_SecondaryColor3uiv(GLbyte *);
extern GLvoid __glXDispSwap_SecondaryColor3fv(GLbyte *);
extern GLvoid __glXDispSwap_SecondaryColor3dv(GLbyte *);

extern GLvoid __glXDisp_BlendFuncSeparate(GLbyte *);
extern GLvoid __glXDispSwap_BlendFuncSeparate(GLbyte *);

extern GLvoid __glXDisp_PointParameteriNV(GLbyte *);
extern GLvoid __glXDisp_PointParameterivNV(GLbyte *);
extern GLvoid __glXDispSwap_PointParameteriNV(GLbyte *);
extern GLvoid __glXDispSwap_PointParameterivNV(GLbyte *);

extern GLvoid __glXDisp_ActiveStencilFaceEXT(GLbyte*);

extern int __glXDispSwap_AreTexturesResidentEXT(__GLXclientState*, GLbyte*);
extern int __glXDispSwap_DeleteTexturesEXT(__GLXclientState*, GLbyte*);
extern int __glXDispSwap_GenTexturesEXT(__GLXclientState*, GLbyte*);
extern int __glXDispSwap_IsTextureEXT(__GLXclientState*, GLbyte*);

extern GLvoid __glXDispSwap_ColorTable(GLbyte*);
extern GLvoid __glXDispSwap_ColorTableParameterfv(GLbyte*);
extern GLvoid __glXDispSwap_ColorTableParameteriv(GLbyte*);
extern GLvoid __glXDispSwap_CopyColorTable(GLbyte*);
extern GLvoid __glXDispSwap_BlendColor(GLbyte*);
extern GLvoid __glXDispSwap_BlendEquation(GLbyte*);
extern GLvoid __glXDispSwap_TexSubImage1D(GLbyte*);
extern GLvoid __glXDispSwap_TexSubImage2D(GLbyte*);
extern GLvoid __glXDispSwap_ConvolutionFilter1D(GLbyte*);
extern GLvoid __glXDispSwap_ConvolutionFilter2D(GLbyte*);
extern GLvoid __glXDispSwap_ConvolutionParameterf(GLbyte*);
extern GLvoid __glXDispSwap_ConvolutionParameterfv(GLbyte*);
extern GLvoid __glXDispSwap_ConvolutionParameteri(GLbyte*);
extern GLvoid __glXDispSwap_ConvolutionParameteriv(GLbyte*);
extern GLvoid __glXDispSwap_CopyConvolutionFilter1D(GLbyte*);
extern GLvoid __glXDispSwap_CopyConvolutionFilter2D(GLbyte*);
extern GLvoid __glXDispSwap_SeparableFilter2D(GLbyte*);
extern GLvoid __glXDispSwap_Histogram(GLbyte*);
extern GLvoid __glXDispSwap_Minmax(GLbyte*);
extern GLvoid __glXDispSwap_ResetHistogram(GLbyte*);
extern GLvoid __glXDispSwap_ResetMinmax(GLbyte*);
extern GLvoid __glXDispSwap_TexImage3D(GLbyte*);
extern GLvoid __glXDispSwap_TexSubImage3D(GLbyte*);
extern GLvoid __glXDispSwap_DrawArraysEXT(GLbyte*);
extern GLvoid __glXDispSwap_BindTexture(GLbyte*);
extern GLvoid __glXDispSwap_PrioritizeTextures(GLbyte*);
extern GLvoid __glXDispSwap_CopyTexImage1D(GLbyte*);
extern GLvoid __glXDispSwap_CopyTexImage2D(GLbyte*);
extern GLvoid __glXDispSwap_CopyTexSubImage1D(GLbyte*);
extern GLvoid __glXDispSwap_CopyTexSubImage2D(GLbyte*);
extern GLvoid __glXDispSwap_CopyTexSubImage3D(GLbyte*);
extern GLvoid __glXDispSwap_PointParameterfARB(GLbyte*);
extern GLvoid __glXDispSwap_PointParameterfvARB(GLbyte*);
extern GLvoid __glXDispSwap_ActiveStencilFaceEXT(GLbyte*);

#define __GLX_MIN_RENDER_OPCODE_EXT 2053
#define __GLX_MAX_RENDER_OPCODE_EXT 4222
#define __GLX_MIN_VENDPRIV_OPCODE_EXT 11
#define __GLX_MAX_VENDPRIV_OPCODE_EXT 14
#define __GLX_VENDPRIV_TABLE_SIZE_EXT (__GLX_MAX_VENDPRIV_OPCODE_EXT - __GLX_MIN_VENDPRIV_OPCODE_EXT + 1)
#define __GLX_RENDER_TABLE_SIZE_EXT (__GLX_MAX_RENDER_OPCODE_EXT - __GLX_MIN_RENDER_OPCODE_EXT + 1)
extern __GLXdispatchRenderProcPtr __glXRenderTable_EXT[__GLX_RENDER_TABLE_SIZE_EXT];
extern __GLXdispatchVendorPrivProcPtr __glXVendorPrivTable_EXT[__GLX_VENDPRIV_TABLE_SIZE_EXT];
extern __GLXdispatchRenderProcPtr __glXSwapRenderTable_EXT[__GLX_RENDER_TABLE_SIZE_EXT];
extern __GLXdispatchVendorPrivProcPtr __glXSwapVendorPrivTable_EXT[__GLX_VENDPRIV_TABLE_SIZE_EXT];
#endif /* _GLX_g_disptab_EXT_h_ */
