##############################################################################
#
#    Copyright 2012 - 2016 Vivante Corporation, Santa Clara, California.
#    All Rights Reserved.
#
#    Permission is hereby granted, free of charge, to any person obtaining
#    a copy of this software and associated documentation files (the
#    'Software'), to deal in the Software without restriction, including
#    without limitation the rights to use, copy, modify, merge, publish,
#    distribute, sub license, and/or sell copies of the Software, and to
#    permit persons to whom the Software is furnished to do so, subject
#    to the following conditions:
#
#    The above copyright notice and this permission notice (including the
#    next paragraph) shall be included in all copies or substantial
#    portions of the Software.
#
#    THE SOFTWARE IS PROVIDED 'AS IS', WITHOUT WARRANTY OF ANY KIND,
#    EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
#    MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT.
#    IN NO EVENT SHALL VIVANTE AND/OR ITS SUPPLIERS BE LIABLE FOR ANY
#    CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
#    TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
#    SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
##############################################################################


######################################################
# Include common definitions.

include  ../makefile.linux.def

######################################################
# Define the program.

PROGRAM			:= 1
TARGET_NAME		:= structs_and_enums

######################################################
# Describe object files.

OBJECTS			:=	$(OBJ_DIR)/main.o \
				$(OBJ_DIR)/const_constant.o \
				$(OBJ_DIR)/const_constant_enum.o \
				$(OBJ_DIR)/const_global.o \
				$(OBJ_DIR)/const_global_enum.o \
				$(OBJ_DIR)/const_local.o \
				$(OBJ_DIR)/const_local_enum.o \
				$(OBJ_DIR)/const_private.o \
				$(OBJ_DIR)/const_private_enum.o \
				$(OBJ_DIR)/restrict_constant.o \
				$(OBJ_DIR)/restrict_constant_enum.o \
				$(OBJ_DIR)/restrict_global.o \
				$(OBJ_DIR)/restrict_global_enum.o \
				$(OBJ_DIR)/restrict_local.o \
				$(OBJ_DIR)/restrict_local_enum.o \
				$(OBJ_DIR)/restrict_private.o \
				$(OBJ_DIR)/restrict_private_enum.o \
				$(OBJ_DIR)/volatile_constant_enum.o \
				$(OBJ_DIR)/volatile_global.o \
				$(OBJ_DIR)/volatile_global_enum.o \
				$(OBJ_DIR)/volatile_local.o \
				$(OBJ_DIR)/volatile_local_enum.o \
				$(OBJ_DIR)/volatile_private.o \
				$(OBJ_DIR)/volatile_private_enum.o \
				$(OBJ_DIR)/volatile_constant.o \
				$(OBJ_DIR)/rounding_mode.o

######################################################
# Describe installation directory
#
INSTALL_DIR		:= $(SDK_DIR)/samples/cl11/UnitTest/test_vivante

######################################################
# Include the common makefile.

include $(AQROOT)/common.target

######################################################
# Extra installation.

install: extra_install

.PHONY: extra_install

extra_install:
	@mkdir -p $(INSTALL_DIR)

