/****************************************************************************
*
*    Copyright (c) 2005 - 2019 by Vivante Corp.  All rights reserved.
*
*    The material in this file is confidential and contains trade secrets
*    of Vivante Corporation. This is proprietary information owned by
*    Vivante Corporation. No part of this work may be disclosed,
*    reproduced, copied, transmitted, or used in any way for any purpose,
*    without the express written permission of Vivante Corporation.
*
*****************************************************************************/


#line 2 "gc_cl_scanner.c"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include "gc_cl_scanner.h"



/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus



/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else    /* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif    /* __STDC__ */
#endif    /* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>

#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 *     if ( condition_holds )
 *        yyless( 5 );
 *    else
 *        do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
    do \
        { \
        /* Undo effects of setting up yytext. */ \
        *yy_cp = yy_hold_char; \
        YY_RESTORE_YY_MORE_OFFSET \
        yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
        YY_DO_BEFORE_ACTION; /* set up yytext again */ \
        } \
    while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
    {
    FILE *yy_input_file;

    char *yy_ch_buf;        /* input buffer */
    char *yy_buf_pos;        /* current position in input buffer */

    /* Size of input buffer in bytes, not including room for EOB
     * characters.
     */
    yy_size_t yy_buf_size;

    /* Number of characters read into yy_ch_buf, not including EOB
     * characters.
     */
    int yy_n_chars;

    /* Whether we "own" the buffer - i.e., we know we created it,
     * and can clRealloc() it to grow it, and should clFree() it to
     * delete it.
     */
    int yy_is_our_buffer;

    /* Whether this is an "interactive" input source; if so, and
     * if we're using stdio for input, then we want to use getc()
     * instead of fread(), to make sure we stop fetching input after
     * each newline.
     */
    int yy_is_interactive;

    /* Whether we're considered to be at the beginning of a line.
     * If so, '^' rules will be active on the next match, otherwise
     * not.
     */
    int yy_at_bol;

    /* Whether to try to fill the input buffer when we reach the
     * end of it.
     */
    int yy_fill_buffer;

    int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
    /* When an EOF's been seen but there's still some text to process
     * then we mark the buffer as YY_EOF_PENDING, to indicate that we
     * shouldn't try reading from the input source any more.  We might
     * still have a bunch of tokens to match, though, because of
     * possible backing-up.
     *
     * When we actually see the EOF, we change the status to "new"
     * (via yyrestart()), so that the user can continue scanning by
     * just pointing yyin at a new input file.
     */
#define YY_BUFFER_EOF_PENDING 2
    };

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;        /* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;        /* whether we need to initialize */
static int yy_start = 0;    /* start state number */

static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
    { \
    if ( ! yy_current_buffer ) \
        yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
    yy_current_buffer->yy_is_interactive = is_interactive; \
    }

#define yy_set_bol(at_bol) \
    { \
    if ( ! yy_current_buffer ) \
        yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
    yy_current_buffer->yy_at_bol = at_bol; \
    }

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef int YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
    yytext_ptr = yy_bp; \
    yytext_ptr -= yy_more_len; \
    yyleng = (int) (yy_cp - yytext_ptr); \
    yy_hold_char = *yy_cp; \
    *yy_cp = '\0'; \
    yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 82
#define YY_END_OF_BUFFER 83
static yyconst short int yy_accept[295] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       83,   81,   79,   79,   56,   81,   62,   67,   81,   40,
       41,   60,   59,   52,   57,   50,   61,   12,   11,   53,
       55,   63,   54,   64,   68,   10,   42,   44,   66,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   46,   65,   48,   58,   79,   70,   62,   76,   81,
       81,   81,   72,   74,   75,   75,   75,   75,   39,   25,
        0,   17,   32,   49,   26,   35,    0,   29,   20,   31,
        0,   69,   21,   38,   51,   14,   73,   80,   30,   14,
       12,    0,    0,   12,   12,    0,   12,   11,   11,   11,

       11,   45,   47,   43,   18,   22,   24,   23,   19,   10,
       36,   28,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   37,
       27,    0,   70,    0,   71,   76,    0,    0,   72,   74,
       75,   75,    0,   73,   75,   16,    0,   14,   80,    0,
       14,   12,   12,   12,   12,   13,   11,   11,   11,   11,
       33,   34,   10,   10,   10,   10,   10,   10,   10,    7,
       10,   10,   10,   10,   10,   10,   10,   10,   10,    0,
        0,   75,   75,    0,   14,   12,    0,   13,   13,   13,
       11,   10,   10,   10,   10,    9,   10,    7,   10,    1,

       10,   10,   10,   10,    0,    0,    0,   13,   13,   13,
       13,   10,   10,    2,    7,   10,    9,   10,   10,    0,
        0,   13,   10,   10,   10,   10,   10,   10,    9,   10,
        7,   10,    0,    0,   15,   10,   10,   10,   10,   10,
       10,   10,   10,    9,   10,   10,   77,   78,   15,   10,
       10,   10,   10,   10,   10,   10,   10,    5,    4,   10,
       10,   10,   10,   10,    6,    3,   10,   10,   10,   10,
       10,   10,    0,    0,    0,    0,   10,   10,   10,    0,
        0,    0,    0,   10,    0,    3,    0,    0,   10,    0,
       10,   10,    8,    0

    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        4,    4,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       22,   23,   24,   25,   24,   26,   27,   28,   29,   30,
       31,   32,   33,    1,   34,   34,   34,   34,   35,   36,
       37,   37,   37,   37,   37,   38,   37,   37,   37,   39,
       37,   37,   37,   37,   40,   37,   37,   41,   37,   37,
       42,    1,   43,   44,   45,    1,   46,   47,   48,   49,

       50,   51,   52,   53,   54,   37,   55,   56,   57,   58,
       59,   60,   61,   62,   63,   64,   65,   66,   37,   67,
       68,   37,   69,   70,   71,   72,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[73] =
    {   0,
        1,    2,    3,    1,    1,    1,    1,    1,    1,    4,
        1,    1,    1,    5,    1,    5,    6,    1,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    1,    1,    1,
        1,    1,    1,    8,    9,   10,   11,   12,   11,   11,
       11,    1,    1,    1,   11,    8,    8,    8,    8,    9,
       10,   11,   11,   11,   11,   12,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,    1,    1,
        1,    1
    } ;

static yyconst short int yy_base[313] =
    {   0,
        0,   71,   72,   78,  137,    0,  204,  230,   81,   89,
      762,  763,  763,  763,   58,  755,   66,   77,    0,  763,
      763,  729,   63,   98,   86,  100,   98,  241,  292,  727,
      763,  105,  727,   72,  763,    0,  763,  763,   99,  691,
      697,  702,  695,   59,  707,  694,  692,  685,  696,  686,
       94,  763,   75,  763,  763,  151,  763,  132,  745,   96,
      692,  683,    0,  190,    0,    0,  145,  131,  763,  763,
      738,  763,  763,  763,  763,  763,  733,  763,  763,  763,
      164,  763,  763,  763,  763,  234,  763,    0,  763,  242,
      113,  224,   96,  180,  123,    0,  181,    0,  235,  233,

      264,  763,  763,  763,  711,  763,  763,  763,  710,    0,
      763,  763,  686,  680,  692,  672,  680,  676,  678,  669,
      674,  685,  671,  664,  675,  669,  667,  662,  671,  763,
      763,  236,  763,  695,  763,  720,  663,  674,    0,  314,
        0,  217,  713,    0,  716,  763,  154,  763,    0,  339,
      331,   91,  763,  679,  659,  288,   97,  763,  670,  641,
      763,  763,  619,  621,  612,  615,  595,  609,  593,  329,
      580,  582,  547,  558,  550,  504,  509,  512,  506,  514,
      511,  763,  559,  351,  365,  763,    0,  256,  245,  328,
      763,  515,  503,  508,  493,  368,  531,  376,  490,    0,

      491,  500,  499,  487,  546,  485,  247,  259,  763,  503,
      479,  357,  484,    0,  391,  495,  403,  443,  436,  448,
      226,  763,  434,  439,  441,  443,  434,  239,  410,  461,
      417,  435,  320,  425,  439,  424,  436,  422,  422,  417,
      421,  419,  446,  436,  443,  412,  458,  763,  763,  398,
      380,  377,  384,  372,  373,  359,  484,  492,  383,  476,
      347,  344,  345,  344,  502,  425,  375,  510,  517,  335,
      332,  319,  327,  298,  295,  293,  524,  297,  281,  279,
      246,  245,  236,  240,  187,  763,  195,  177,  181,  117,
      115,   97,    0,  763,  569,  581,  593,  605,  611,  617,

      629,  641,  647,  659,  666,  671,  672,  682,  694,  702,
      703,  709
    } ;

static yyconst short int yy_def[313] =
    {   0,
      294,    1,  295,  295,  295,    5,  295,  295,  296,  296,
      294,  294,  294,  294,  294,  297,  294,  294,  298,  294,
      294,  294,  294,  294,  294,  294,  294,  294,  294,  294,
      294,  294,  294,  294,  294,  299,  294,  294,  294,  299,
      299,  299,  299,  299,  299,  299,  299,  299,  299,  299,
      299,  294,  294,  294,  294,  294,  294,  294,  294,  294,
      294,  294,  300,  294,  301,  301,  302,  301,  294,  294,
      297,  294,  294,  294,  294,  294,  298,  294,  294,  294,
      294,  294,  294,  294,  294,  303,  294,  304,  294,  303,
       28,  305,  306,  294,  294,  307,  294,   29,  294,  294,

      294,  294,  294,  294,  294,  294,  294,  294,  294,  299,
      294,  294,  299,  299,  299,  299,  299,  299,  299,  299,
      299,  299,  299,  299,  299,  299,  299,  299,  299,  294,
      294,  294,  294,  294,  294,  294,  294,  294,  300,  294,
      301,  302,  308,  301,  309,  294,  310,  294,  304,  294,
      306,  294,  294,  294,  294,  307,  294,  294,  294,  294,
      294,  294,  299,  299,  299,  299,  299,  299,  299,  299,
      299,  299,  299,  299,  299,  299,  299,  299,  299,  294,
      294,  294,  309,  294,  310,  294,  311,  294,  294,  294,
      294,  299,  299,  299,  299,  299,  299,  299,  299,  299,

      299,  299,  299,  299,  294,  294,  311,  294,  294,  294,
      294,  299,  299,  299,  299,  299,  299,  299,  299,  294,
      312,  294,  299,  299,  299,  299,  299,  299,  299,  299,
      299,  299,  294,  294,  312,  299,  299,  299,  299,  299,
      299,  299,  299,  299,  299,  299,  294,  294,  294,  299,
      299,  299,  299,  299,  299,  299,  299,  299,  299,  299,
      299,  299,  299,  299,  299,  294,  299,  299,  299,  299,
      299,  299,  294,  294,  294,  294,  299,  299,  299,  294,
      294,  294,  294,  299,  294,  294,  294,  294,  299,  294,
      299,  299,  299,    0,  294,  294,  294,  294,  294,  294,

      294,  294,  294,  294,  294,  294,  294,  294,  294,  294,
      294,  294
    } ;

static yyconst short int yy_nxt[836] =
    {   0,
       12,   13,   14,   13,   15,   16,   12,   17,   18,   19,
       20,   21,   22,   23,   24,   25,   26,   27,   28,   29,
       29,   29,   29,   29,   29,   29,   29,   30,   31,   32,
       33,   34,   35,   36,   36,   36,   36,   36,   36,   36,
       36,   37,   38,   39,   40,   36,   41,   42,   43,   36,
       44,   36,   45,   46,   36,   47,   36,   36,   36,   36,
       48,   36,   49,   50,   51,   36,   36,   36,   52,   53,
       54,   55,   56,   59,   14,   13,   79,   57,   58,   59,
       14,   13,   13,   14,   66,   75,   67,   69,   70,   60,
       13,   14,   66,   80,   67,   60,   73,   74,   68,   81,

       81,   83,  108,  109,  117,  130,   68,   76,   87,  150,
       87,  150,  103,   88,  118,   88,   84,   85,   86,   86,
       86,   86,   86,   86,   86,   86,   86,   61,   89,  111,
      153,   62,  104,   61,  105,  106,  158,   62,   13,   14,
       13,  125,  112,  144,  131,  293,  143,  126,  145,  127,
      141,  128,  132,  294,   60,  153,  129,  133,  134,  135,
      154,  158,   73,   74,  292,   81,   81,  184,   82,  184,
       63,   63,   63,   63,   63,   63,   63,   63,  155,  294,
      286,   63,   63,   63,   63,   63,   63,   63,   63,   63,
       63,   63,   63,   63,   63,   63,   63,   63,   63,   63,

       63,   63,   63,   63,   63,   13,   14,   13,  140,  140,
      140,  140,  140,  140,  140,  140,  140,  152,  143,  153,
      153,   60,  141,   64,   64,   64,   64,   64,   64,   64,
       64,   13,   14,   13,   82,  291,  152,  132,  290,  234,
       90,  234,  133,  134,  153,  153,  286,   60,  286,   64,
       64,   64,   64,   64,   64,   64,   64,   90,   93,   91,
       91,   91,   91,   91,   91,   91,   92,   92,  147,  148,
      159,  148,  157,   93,  158,   93,  147,  148,   94,  148,
       95,   96,  210,  147,  148,  221,  241,  289,  160,  148,
       93,  147,  148,  208,  288,  209,   97,  148,  209,  158,

      211,  242,  287,  158,  187,   95,  221,   96,   90,  286,
       98,   98,   98,   98,   98,   98,   98,   98,   98,  157,
      209,  247,  248,  209,  285,  188,   93,  189,  158,   99,
      260,  100,  140,  140,  140,  140,  140,  140,  140,  140,
      140,   93,  284,  190,  294,  283,  294,  101,  197,  198,
      198,  198,  189,  282,  198,  281,  100,  151,  151,  151,
      151,  151,  151,  151,  151,  151,  148,  209,  148,  185,
      185,  185,  185,  185,  185,  185,  185,  185,  294,  280,
      294,  148,  260,  208,  266,  266,  148,  216,  217,  217,
      217,  279,  209,  217,  278,  197,  198,  198,  198,  268,

      148,  198,  148,  223,  224,  272,  260,  260,  225,  226,
      230,  231,  231,  231,  271,  148,  231,  264,  263,  227,
      148,  228,  216,  217,  217,  217,  266,  266,  217,  243,
      244,  244,  244,  262,  260,  244,  230,  231,  231,  231,
      261,  260,  231,  235,  235,  235,  235,  235,  235,  235,
      235,  235,  294,  260,  294,  243,  244,  244,  244,  247,
      259,  244,  258,  258,  258,  258,  258,  258,  258,  258,
      244,  256,  273,  255,  249,  254,  249,  253,  274,  252,
      275,  251,  250,  245,  246,  231,  240,  276,  239,  249,
      238,  237,  236,  233,  249,  267,  268,  269,  268,  170,

      232,  268,  257,  265,  265,  265,  265,  265,  265,  265,
      265,  258,  258,  258,  258,  258,  258,  258,  258,  217,
      270,  265,  265,  265,  265,  265,  265,  265,  265,  267,
      268,  269,  268,  229,  222,  268,  267,  277,  269,  268,
      222,  220,  268,  267,  268,  269,  268,  136,  219,  268,
      218,  170,  170,  170,  270,  198,  215,  214,  213,  212,
      149,  270,  206,  205,  204,  203,  202,  170,  270,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   65,   65,   65,   65,   65,   65,   65,   65,   65,
       65,   65,   65,   71,   71,  201,   71,   71,   71,   71,

       71,   71,   71,   71,   71,   77,   77,  200,  199,   77,
       77,   77,   77,   77,   77,   77,   77,  110,  110,  110,
      110,  110,  110,  139,  139,  139,  139,  139,  139,  141,
      196,  170,  141,  141,  141,  141,  141,  141,  141,  141,
      141,  142,  142,  196,  142,  142,  142,  142,  142,  142,
      142,  142,  142,   86,  195,   86,   86,  194,   86,  149,
      149,  193,  149,  149,  149,  149,  149,  149,  149,  149,
      149,   92,   92,  170,   92,  151,  170,  151,  156,  156,
      156,  156,  143,  143,  192,  143,  143,  143,  143,  143,
      143,  143,  143,  143,  183,  183,  191,  183,  183,  183,

      183,  183,  183,  183,  183,  183,  185,  191,  185,  207,
      207,  207,  207,  235,  186,  235,  186,  149,  182,  181,
      180,  136,  135,  179,  178,  177,  176,  175,  174,  173,
      172,  171,  170,  169,  168,  167,  166,  165,  164,  163,
      162,  161,  146,   72,  138,  137,  136,  124,  123,  122,
      121,  120,  119,  116,  115,  114,  113,  107,  102,   78,
       72,  294,   11,  294,  294,  294,  294,  294,  294,  294,
      294,  294,  294,  294,  294,  294,  294,  294,  294,  294,
      294,  294,  294,  294,  294,  294,  294,  294,  294,  294,
      294,  294,  294,  294,  294,  294,  294,  294,  294,  294,

      294,  294,  294,  294,  294,  294,  294,  294,  294,  294,
      294,  294,  294,  294,  294,  294,  294,  294,  294,  294,
      294,  294,  294,  294,  294,  294,  294,  294,  294,  294,
      294,  294,  294,  294,  294
    } ;

static yyconst short int yy_chk[836] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    2,    3,    3,    3,   23,    2,    2,    4,
        4,    4,    9,    9,    9,   18,    9,   15,   15,    3,
       10,   10,   10,   23,   10,    4,   17,   17,    9,   24,

       24,   25,   34,   34,   44,   53,   10,   18,   60,   93,
       27,   93,   32,   60,   44,   27,   25,   25,   26,   26,
       26,   26,   26,   26,   26,   26,   26,    3,   27,   39,
      152,    3,   32,    4,   32,   32,  157,    4,    5,    5,
        5,   51,   39,   68,   53,  292,   67,   51,   68,   51,
       67,   51,   56,   91,    5,  152,   51,   56,   56,   58,
       95,  157,   58,   58,  291,   81,   81,  147,   24,  147,
        5,    5,    5,    5,    5,    5,    5,    5,   95,   91,
      290,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,

        5,    5,    5,    5,    5,    7,    7,    7,   64,   64,
       64,   64,   64,   64,   64,   64,   64,   94,  142,   94,
       97,    7,  142,    7,    7,    7,    7,    7,    7,    7,
        7,    8,    8,    8,   81,  289,   97,  132,  288,  221,
       92,  221,  132,  132,   94,   97,  287,    8,  285,    8,
        8,    8,    8,    8,    8,    8,    8,   28,   92,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   86,   86,
      100,   86,   99,   92,   99,   28,   90,   90,   28,   90,
       28,   28,  189,   86,   86,  207,  228,  284,  100,   86,
       28,   90,   90,  188,  283,  188,   28,   90,  208,   99,

      189,  228,  282,  101,  156,   28,  207,   28,   29,  281,
       29,   29,   29,   29,   29,   29,   29,   29,   29,  101,
      188,  233,  233,  208,  280,  156,   29,  156,  101,   29,
      279,   29,  140,  140,  140,  140,  140,  140,  140,  140,
      140,   29,  278,  156,  151,  276,  151,   29,  170,  170,
      170,  170,  156,  275,  170,  274,   29,  150,  150,  150,
      150,  150,  150,  150,  150,  150,  151,  190,  151,  184,
      184,  184,  184,  184,  184,  184,  184,  184,  185,  273,
      185,  151,  272,  190,  259,  259,  151,  196,  196,  196,
      196,  271,  190,  196,  270,  198,  198,  198,  198,  267,

      185,  198,  185,  212,  212,  264,  263,  262,  212,  212,
      215,  215,  215,  215,  261,  185,  215,  256,  255,  212,
      185,  212,  217,  217,  217,  217,  266,  266,  217,  229,
      229,  229,  229,  254,  253,  229,  231,  231,  231,  231,
      252,  251,  231,  234,  234,  234,  234,  234,  234,  234,
      234,  234,  235,  250,  235,  244,  244,  244,  244,  247,
      246,  244,  245,  245,  245,  245,  245,  245,  245,  245,
      243,  242,  266,  241,  235,  240,  235,  239,  266,  238,
      266,  237,  236,  231,  232,  230,  227,  266,  226,  235,
      225,  224,  223,  220,  235,  260,  260,  260,  260,  219,

      218,  260,  244,  257,  257,  257,  257,  257,  257,  257,
      257,  258,  258,  258,  258,  258,  258,  258,  258,  216,
      260,  265,  265,  265,  265,  265,  265,  265,  265,  268,
      268,  268,  268,  213,  211,  268,  269,  269,  269,  269,
      210,  206,  269,  277,  277,  277,  277,  205,  204,  277,
      203,  202,  201,  199,  268,  197,  195,  194,  193,  192,
      183,  269,  181,  180,  179,  178,  177,  176,  277,  295,
      295,  295,  295,  295,  295,  295,  295,  295,  295,  295,
      295,  296,  296,  296,  296,  296,  296,  296,  296,  296,
      296,  296,  296,  297,  297,  175,  297,  297,  297,  297,

      297,  297,  297,  297,  297,  298,  298,  174,  173,  298,
      298,  298,  298,  298,  298,  298,  298,  299,  299,  299,
      299,  299,  299,  300,  300,  300,  300,  300,  300,  301,
      172,  171,  301,  301,  301,  301,  301,  301,  301,  301,
      301,  302,  302,  169,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  303,  168,  303,  303,  167,  303,  304,
      304,  166,  304,  304,  304,  304,  304,  304,  304,  304,
      304,  305,  305,  165,  305,  306,  164,  306,  307,  307,
      307,  307,  308,  308,  163,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  309,  309,  160,  309,  309,  309,

      309,  309,  309,  309,  309,  309,  310,  159,  310,  311,
      311,  311,  311,  312,  155,  312,  154,  145,  143,  138,
      137,  136,  134,  129,  128,  127,  126,  125,  124,  123,
      122,  121,  120,  119,  118,  117,  116,  115,  114,  113,
      109,  105,   77,   71,   62,   61,   59,   50,   49,   48,
       47,   46,   45,   43,   42,   41,   40,   33,   30,   22,
       16,   11,  294,  294,  294,  294,  294,  294,  294,  294,
      294,  294,  294,  294,  294,  294,  294,  294,  294,  294,
      294,  294,  294,  294,  294,  294,  294,  294,  294,  294,
      294,  294,  294,  294,  294,  294,  294,  294,  294,  294,

      294,  294,  294,  294,  294,  294,  294,  294,  294,  294,
      294,  294,  294,  294,  294,  294,  294,  294,  294,  294,
      294,  294,  294,  294,  294,  294,  294,  294,  294,  294,
      294,  294,  294,  294,  294
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
static int yy_more_flag = 0;
static int yy_more_len = 0;
#define yymore() (yy_more_flag = 1)
#define YY_MORE_ADJ yy_more_len
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "gc_cl.l"
#define INITIAL 0
#line 19 "gc_cl.l"
#include "gc_cl_scanner.h"

static gctUINT CurrentLineNo        = 0;
static gctUINT CurrentStringNo        = 0;
static gctSTRING CurrentFileName    = gcvNULL;

void
clScanComment(
    IN cloCOMPILER Compiler
    );

void
clScanSkipToEOL(
    IN cloCOMPILER Compiler
    );

#define YY_NO_UNISTD_H

/*#define YY_FATAL_ERROR(msg)    \
    clReport(0, 0, clvREPORT_FATAL_ERROR, msg)*/

#define YY_INPUT(buf, result, max_size) \
    { \
         result = clInput(max_size, buf); \
    }

#define YY_DECL \
    gctINT \
    cloCOMPILER_Scan( \
        IN cloCOMPILER Compiler, \
        OUT clsLexToken * Token \
        )

#define DUMP_SOURCE() \
    gcmVERIFY_OK(cloCOMPILER_Dump( \
                            Compiler, \
                            clvDUMP_SOURCE, \
                            "<SOURCE line=\"%d\" string=\"%d\">'%s'</SOURCE>", \
                            CurrentLineNo, \
                            CurrentStringNo, \
                            yytext))

#define DUMP_SOURCE_COMMENT_BEGIN() \
    gcmVERIFY_OK(cloCOMPILER_Dump( \
                            Compiler, \
                            clvDUMP_SOURCE, \
                            "<SOURCE_COMMENT line=\"%d\" string=\"%d\">'%s", \
                            CurrentLineNo, \
                            CurrentStringNo, \
                            yytext))

#define DUMP_SOURCE_COMMENT_END() \
    gcmVERIFY_OK(cloCOMPILER_Dump( \
                            Compiler, \
                            clvDUMP_SOURCE, \
                            "'</SOURCE_COMMENT>"))

#define DUMP_SOURCE_CHAR(ch) \
    gcmVERIFY_OK(cloCOMPILER_Dump( \
                            Compiler, \
                            clvDUMP_SOURCE, \
                            "%c", \
                            ch))


#ifdef CL_SCAN_NO_ACTION

    #define CL_SCAN_DOUBLE_MATRIX_TYPE()    T_DOUBLENXM
    #define CL_SCAN_FLOAT_MATRIX_TYPE)    T_FLOATNXM
    #define CL_SCAN_UNSIGNED_INTEGER_TYPE() T_UINT
    #define CL_SCAN_BUILTIN_DATA_TYPE()    T_BUILTIN_DATA_TYPE
    #define CL_SCAN_VIV_PACKED_DATA_TYPE()    T_VIV_PACKED_DATA_TYPE
    #define CL_SCAN_RESERVED_DATA_TYPE()    T_RESERVED_DATA_TYPE
    #define CL_SCAN_IDENTIFIER()        T_IDENTIFIER
    #define CL_SCAN_BOOLCONSTANT(value)    T_BOOLCONSTANT
    #define CL_SCAN_DEC_INTCONSTANT()    T_INTCONSTANT
    #define CL_SCAN_OCT_INTCONSTANT()    T_INTCONSTANT
    #define CL_SCAN_HEX_INTCONSTANT()    T_INTCONSTANT
    #define CL_SCAN_FLOATCONSTANT()        T_FLOATCONSTANT
    #define CL_SCAN_HEXFLOATCONSTANT()    T_FLOATCONSTANT
    #define CL_SCAN_CHARCONSTANT()        T_CHARCONSTANT
    #define CL_SCAN_STRING_LITERAL()    T_STRING_LITERAL
    #define CL_SCAN_OPERATOR(type)        (type)
    #define CL_SCAN_SPECIAL_OPERATOR(extension, type)    (type)
    #define CL_SCAN_FIELD_SELECTION()    T_FIELD_SELECTION

#else

    #define CL_SCAN_FLOAT_MATRIX_TYPE()        \
        clScanMatrixType(Compiler, CurrentLineNo, CurrentStringNo, T_FLOATNXM, yytext, Token)
    #define CL_SCAN_DOUBLE_MATRIX_TYPE()        \
        clScanMatrixType(Compiler, CurrentLineNo, CurrentStringNo, T_DOUBLENXM, yytext, Token)
    #define CL_SCAN_UNSIGNED_INTEGER_TYPE()        \
        clScanConvToUnsignedType(Compiler, CurrentLineNo, CurrentStringNo, yytext, Token)
    #define CL_SCAN_BUILTIN_DATA_TYPE()        \
        clScanBuiltinDataType(Compiler, CurrentLineNo, CurrentStringNo, yytext, Token)
    #define CL_SCAN_VIV_PACKED_DATA_TYPE()        \
        clScanVivPackedDataType(Compiler, CurrentLineNo, CurrentStringNo, yytext, Token)
    #define CL_SCAN_RESERVED_DATA_TYPE()        \
        clScanReservedDataType(Compiler, CurrentLineNo, CurrentStringNo, yytext, Token)
    #define CL_SCAN_IDENTIFIER()        \
        clScanIdentifier(Compiler, CurrentLineNo, CurrentStringNo, yytext, Token)

    #define CL_SCAN_BOOLCONSTANT(value)    \
        clScanBoolConstant(Compiler, CurrentLineNo, CurrentStringNo, value, Token)

    #define CL_SCAN_DEC_INTCONSTANT()    \
        clScanDecIntConstant(Compiler, CurrentLineNo, CurrentStringNo, yytext, Token)

    #define CL_SCAN_OCT_INTCONSTANT()    \
        clScanOctIntConstant(Compiler, CurrentLineNo, CurrentStringNo, yytext, Token)

    #define CL_SCAN_HEX_INTCONSTANT()    \
        clScanHexIntConstant(Compiler, CurrentLineNo, CurrentStringNo, yytext, Token)

    #define CL_SCAN_FLOATCONSTANT()        \
        clScanFloatConstant(Compiler, CurrentLineNo, CurrentStringNo, yytext, Token)

    #define CL_SCAN_HEXFLOATCONSTANT()        \
        clScanHexFloatConstant(Compiler, CurrentLineNo, CurrentStringNo, yytext, Token)

    #define CL_SCAN_CHARCONSTANT()        \
        clScanCharConstant(Compiler, CurrentLineNo, CurrentStringNo, yytext, Token)

    #define CL_SCAN_STRING_LITERAL()        \
        clScanStringLiteral(Compiler, CurrentLineNo, CurrentStringNo, yytext, Token)

    #define CL_SCAN_OPERATOR(type)        \
        clScanOperator(Compiler, CurrentLineNo, CurrentStringNo, yytext, type, Token)

    #define CL_SCAN_SPECIAL_OPERATOR(extension, type)        \
        clScanSpecialOperator(Compiler, extension, CurrentLineNo, CurrentStringNo, yytext, type, Token)

    #define CL_SCAN_FIELD_SELECTION()    \
        clScanFieldSelection(Compiler, CurrentLineNo, CurrentStringNo, yytext, Token)

#endif /* CL_SCAN_NO_ACTION */

#define ECHO        do { /* Do nothing */ } while (gcvFALSE)
#define YY_NEVER_INTERACTIVE 1
/*
%option nounput
*/
#define START_OF_DIRECTIVE 1

#define SCAN_FIELD_SELECTION 2

#define SCAN_DIRECTIVE_LINE_NO 3

#define SCAN_DIRECTIVE_FILE_NAME 4

#line 823 "gc_cl_scanner.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus

#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
    if ( yy_current_buffer->yy_is_interactive ) \
        { \
        int c = '*', n; \
        for ( n = 0; n < max_size && \
                 (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
            buf[n] = (char) c; \
        if ( c == '\n' ) \
            buf[n++] = (char) c; \
        if ( c == EOF && ferror( yyin ) ) \
            YY_FATAL_ERROR( "input in flex scanner failed" ); \
        result = n; \
        } \
    else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
          && ferror( yyin ) ) \
        YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
    if ( yyleng > 0 ) \
        yy_current_buffer->yy_at_bol = \
                (yytext[yyleng - 1] == '\n'); \
    YY_USER_ACTION

YY_DECL
    {
    register yy_state_type yy_current_state;
    register char *yy_cp = NULL, *yy_bp = NULL;
    register int yy_act;

#line 217 "gc_cl.l"


#line 980 "gc_cl_scanner.c"

    if ( yy_init )
        {
        yy_init = 0;

#ifdef YY_USER_INIT
        YY_USER_INIT;
#endif

        if ( ! yy_start )
            yy_start = 1;    /* first start state */

        if ( ! yyin )
            yyin = stdin;

        if ( ! yyout )
            yyout = stdout;

        if ( ! yy_current_buffer )
            yy_current_buffer =
                yy_create_buffer( yyin, YY_BUF_SIZE );

        yy_load_buffer_state();
        }

    while ( 1 )        /* loops until end-of-file is reached */
        {
        yy_more_len = 0;
        if ( yy_more_flag )
            {
            yy_more_len = yy_c_buf_p - yytext_ptr;
            yy_more_flag = 0;
            }
        yy_cp = yy_c_buf_p;

        /* Support of yytext. */
        *yy_cp = yy_hold_char;

        /* yy_bp points to the position in yy_ch_buf of the start of
         * the current run.
         */
        yy_bp = yy_cp;

        yy_current_state = yy_start;
        yy_current_state += YY_AT_BOL();
yy_match:
        do
            {
            register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
            if ( yy_accept[yy_current_state] )
                {
                yy_last_accepting_state = yy_current_state;
                yy_last_accepting_cpos = yy_cp;
                }
            while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
                {
                yy_current_state = (int) yy_def[yy_current_state];
                if ( yy_current_state >= 295 )
                    yy_c = yy_meta[(unsigned int) yy_c];
                }
            yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
            ++yy_cp;
            }
        while ( yy_base[yy_current_state] != 763 );

yy_find_action:
        yy_act = yy_accept[yy_current_state];
        if ( yy_act == 0 )
            { /* have to back up */
            yy_cp = yy_last_accepting_cpos;
            yy_current_state = yy_last_accepting_state;
            yy_act = yy_accept[yy_current_state];
            }

        YY_DO_BEFORE_ACTION;


do_action:    /* This label is used only to access EOF actions. */


        switch ( yy_act )
    { /* beginning of action switch */
            case 0: /* must back up */
            /* undo the effects of YY_DO_BEFORE_ACTION */
            *yy_cp = yy_hold_char;
            yy_cp = yy_last_accepting_cpos;
            yy_current_state = yy_last_accepting_state;
            goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 219 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_BOOLCONSTANT(gcvTRUE); }
    YY_BREAK
case 2:
YY_RULE_SETUP
#line 220 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_BOOLCONSTANT(gcvFALSE); }
    YY_BREAK
case 3:
YY_RULE_SETUP
#line 222 "gc_cl.l"
{ DUMP_SOURCE();
                            return CL_SCAN_UNSIGNED_INTEGER_TYPE(); }
    YY_BREAK
case 4:
YY_RULE_SETUP
#line 224 "gc_cl.l"
{ DUMP_SOURCE();
                            return CL_SCAN_UNSIGNED_INTEGER_TYPE(); }
    YY_BREAK
case 5:
YY_RULE_SETUP
#line 226 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_FLOAT_MATRIX_TYPE(); }
    YY_BREAK
case 6:
YY_RULE_SETUP
#line 227 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_DOUBLE_MATRIX_TYPE(); }
    YY_BREAK
case 7:
YY_RULE_SETUP
#line 228 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_BUILTIN_DATA_TYPE(); }
    YY_BREAK
case 8:
YY_RULE_SETUP
#line 229 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_VIV_PACKED_DATA_TYPE(); }
    YY_BREAK
case 9:
YY_RULE_SETUP
#line 230 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_RESERVED_DATA_TYPE(); }
    YY_BREAK
case 10:
YY_RULE_SETUP
#line 231 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_IDENTIFIER(); }
    YY_BREAK
case 11:
YY_RULE_SETUP
#line 233 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_DEC_INTCONSTANT(); }
    YY_BREAK
case 12:
YY_RULE_SETUP
#line 234 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OCT_INTCONSTANT(); }
    YY_BREAK
case 13:
YY_RULE_SETUP
#line 235 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_HEX_INTCONSTANT(); }
    YY_BREAK
case 14:
YY_RULE_SETUP
#line 237 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_FLOATCONSTANT(); }
    YY_BREAK
case 15:
YY_RULE_SETUP
#line 238 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_HEXFLOATCONSTANT(); }
    YY_BREAK
case 16:
YY_RULE_SETUP
#line 240 "gc_cl.l"
{
                          /*check if char before closing quote is a '\' */
                          if(yytext[yyleng - 2] == '\\') {
                             yyless(yyleng - 1); /* return last quote ' */
                             yymore();
                          }
                          else {
                            DUMP_SOURCE(); return CL_SCAN_CHARCONSTANT();
                          }
                        }
    YY_BREAK
case 17:
YY_RULE_SETUP
#line 251 "gc_cl.l"
{
                          /*check if char before closing quote is a '\' */
                          if(yytext[yyleng - 2] == '\\') {
                             yyless(yyleng - 1); /* return last quote " */
                             yymore();
                          }
                          else {
                            DUMP_SOURCE(); return CL_SCAN_STRING_LITERAL();
                          }
                        }
    YY_BREAK
case 18:
YY_RULE_SETUP
#line 262 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR(T_LSHIFT_OP); }
    YY_BREAK
case 19:
YY_RULE_SETUP
#line 263 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR(T_RSHIFT_OP); }
    YY_BREAK
case 20:
YY_RULE_SETUP
#line 264 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR(T_INC_OP); }
    YY_BREAK
case 21:
YY_RULE_SETUP
#line 265 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR(T_DEC_OP); }
    YY_BREAK
case 22:
YY_RULE_SETUP
#line 266 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR(T_LE_OP); }
    YY_BREAK
case 23:
YY_RULE_SETUP
#line 267 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR(T_GE_OP); }
    YY_BREAK
case 24:
YY_RULE_SETUP
#line 268 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR(T_EQ_OP); }
    YY_BREAK
case 25:
YY_RULE_SETUP
#line 269 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR(T_NE_OP); }
    YY_BREAK
case 26:
YY_RULE_SETUP
#line 270 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR(T_AND_OP); }
    YY_BREAK
case 27:
YY_RULE_SETUP
#line 271 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR(T_OR_OP); }
    YY_BREAK
case 28:
YY_RULE_SETUP
#line 272 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR(T_XOR_OP); }
    YY_BREAK
case 29:
YY_RULE_SETUP
#line 273 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR(T_MUL_ASSIGN); }
    YY_BREAK
case 30:
YY_RULE_SETUP
#line 274 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR(T_DIV_ASSIGN); }
    YY_BREAK
case 31:
YY_RULE_SETUP
#line 275 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR(T_ADD_ASSIGN); }
    YY_BREAK
case 32:
YY_RULE_SETUP
#line 276 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR(T_MOD_ASSIGN); }
    YY_BREAK
case 33:
YY_RULE_SETUP
#line 277 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR(T_LEFT_ASSIGN); }
    YY_BREAK
case 34:
YY_RULE_SETUP
#line 278 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR(T_RIGHT_ASSIGN); }
    YY_BREAK
case 35:
YY_RULE_SETUP
#line 279 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR(T_AND_ASSIGN); }
    YY_BREAK
case 36:
YY_RULE_SETUP
#line 280 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR(T_XOR_ASSIGN); }
    YY_BREAK
case 37:
YY_RULE_SETUP
#line 281 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR(T_OR_ASSIGN); }
    YY_BREAK
case 38:
YY_RULE_SETUP
#line 282 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR(T_SUB_ASSIGN); }
    YY_BREAK
case 39:
YY_RULE_SETUP
#line 283 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_SPECIAL_OPERATOR(clvEXTENSION_VASM, T_ASM_OPND_BRACKET); }
    YY_BREAK
case 40:
YY_RULE_SETUP
#line 285 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR('('); }
    YY_BREAK
case 41:
YY_RULE_SETUP
#line 286 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR(')'); }
    YY_BREAK
case 42:
YY_RULE_SETUP
#line 287 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR('['); }
    YY_BREAK
case 43:
YY_RULE_SETUP
#line 288 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR('['); }
    YY_BREAK
case 44:
YY_RULE_SETUP
#line 289 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR(']'); }
    YY_BREAK
case 45:
YY_RULE_SETUP
#line 290 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR(']'); }
    YY_BREAK
case 46:
YY_RULE_SETUP
#line 291 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR('{'); }
    YY_BREAK
case 47:
YY_RULE_SETUP
#line 292 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR('{'); }
    YY_BREAK
case 48:
YY_RULE_SETUP
#line 293 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR('}'); }
    YY_BREAK
case 49:
YY_RULE_SETUP
#line 294 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR('}'); }
    YY_BREAK
case 50:
YY_RULE_SETUP
#line 295 "gc_cl.l"
{ BEGIN(SCAN_FIELD_SELECTION);
                            DUMP_SOURCE(); return CL_SCAN_OPERATOR('.'); }
    YY_BREAK
case 51:
YY_RULE_SETUP
#line 297 "gc_cl.l"
{ BEGIN(SCAN_FIELD_SELECTION);
                          DUMP_SOURCE(); return CL_SCAN_OPERATOR(T_STRUCT_UNION_PTR); }
    YY_BREAK
case 52:
YY_RULE_SETUP
#line 299 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR(','); }
    YY_BREAK
case 53:
YY_RULE_SETUP
#line 300 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR(':'); }
    YY_BREAK
case 54:
YY_RULE_SETUP
#line 301 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR('='); }
    YY_BREAK
case 55:
YY_RULE_SETUP
#line 302 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR(';'); }
    YY_BREAK
case 56:
YY_RULE_SETUP
#line 303 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR('!'); }
    YY_BREAK
case 57:
YY_RULE_SETUP
#line 304 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR('-'); }
    YY_BREAK
case 58:
YY_RULE_SETUP
#line 305 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR('~'); }
    YY_BREAK
case 59:
YY_RULE_SETUP
#line 306 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR('+'); }
    YY_BREAK
case 60:
YY_RULE_SETUP
#line 307 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR('*'); }
    YY_BREAK
case 61:
YY_RULE_SETUP
#line 308 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR('/'); }
    YY_BREAK
case 62:
YY_RULE_SETUP
#line 309 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR('%'); }
    YY_BREAK
case 63:
YY_RULE_SETUP
#line 310 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR('<'); }
    YY_BREAK
case 64:
YY_RULE_SETUP
#line 311 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR('>'); }
    YY_BREAK
case 65:
YY_RULE_SETUP
#line 312 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR('|'); }
    YY_BREAK
case 66:
YY_RULE_SETUP
#line 313 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR('^'); }
    YY_BREAK
case 67:
YY_RULE_SETUP
#line 314 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR('&'); }
    YY_BREAK
case 68:
YY_RULE_SETUP
#line 315 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR('?'); }
    YY_BREAK
case 69:
YY_RULE_SETUP
#line 316 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR(T_INITIALIZER_END); }
    YY_BREAK
case 70:
YY_RULE_SETUP
#line 318 "gc_cl.l"
{ DUMP_SOURCE(); BEGIN(START_OF_DIRECTIVE); }
    YY_BREAK
case 71:
YY_RULE_SETUP
#line 320 "gc_cl.l"
{ DUMP_SOURCE(); BEGIN(START_OF_DIRECTIVE); }
    YY_BREAK
case 72:
YY_RULE_SETUP
#line 322 "gc_cl.l"
{ BEGIN(INITIAL);
                          DUMP_SOURCE(); return CL_SCAN_FIELD_SELECTION(); }
    YY_BREAK
case 73:
YY_RULE_SETUP
#line 326 "gc_cl.l"
{ DUMP_SOURCE_COMMENT_BEGIN(); clScanComment(Compiler); }
    YY_BREAK
case 74:
YY_RULE_SETUP
#line 328 "gc_cl.l"
{ gctINT lineNo;
                              DUMP_SOURCE();
                             gcoOS_StrToInt(yytext, &lineNo);
                          cloCOMPILER_SetCurrentLineNo(Compiler, lineNo - 1);
                              BEGIN(SCAN_DIRECTIVE_FILE_NAME); }
    YY_BREAK
case 75:
YY_RULE_SETUP
#line 333 "gc_cl.l"
{ DUMP_SOURCE();
                              cloCOMPILER_SetCurrentFileName(Compiler, yytext);
                                                  clScanSkipToEOL(Compiler);
                                                  BEGIN(INITIAL); }
    YY_BREAK
case 76:
YY_RULE_SETUP
#line 337 "gc_cl.l"
{ DUMP_SOURCE();
                              BEGIN(SCAN_DIRECTIVE_LINE_NO);}
    YY_BREAK
case 77:
YY_RULE_SETUP
#line 340 "gc_cl.l"
{ DUMP_SOURCE();
                                                  clScanSkipToEOL(Compiler);
                          BEGIN(INITIAL);    }
    YY_BREAK
case 78:
YY_RULE_SETUP
#line 344 "gc_cl.l"
{ DUMP_SOURCE(); BEGIN(INITIAL);}
    YY_BREAK
case 79:
YY_RULE_SETUP
#line 346 "gc_cl.l"
{ DUMP_SOURCE(); /* Ignore */ }
    YY_BREAK
case 80:
YY_RULE_SETUP
#line 348 "gc_cl.l"
{ DUMP_SOURCE(); /* Ignore */ }
    YY_BREAK
case 81:
YY_RULE_SETUP
#line 350 "gc_cl.l"
{ DUMP_SOURCE();
                                  cloCOMPILER_Report(
                                        Compiler,
                                        CurrentLineNo,
                                        CurrentStringNo,
                                        clvREPORT_ERROR,
                                        "unexpected character: '%s'", yytext); }
    YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(START_OF_DIRECTIVE):
case YY_STATE_EOF(SCAN_FIELD_SELECTION):
case YY_STATE_EOF(SCAN_DIRECTIVE_LINE_NO):
case YY_STATE_EOF(SCAN_DIRECTIVE_FILE_NAME):
#line 358 "gc_cl.l"
{ yy_delete_buffer(YY_CURRENT_BUFFER); yyterminate(); }
    YY_BREAK
case 82:
YY_RULE_SETUP
#line 360 "gc_cl.l"
ECHO;
    YY_BREAK
#line 1527 "gc_cl_scanner.c"

    case YY_END_OF_BUFFER:
        {
        /* Amount of text matched not including the EOB char. */
        int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

        /* Undo the effects of YY_DO_BEFORE_ACTION. */
        *yy_cp = yy_hold_char;
        YY_RESTORE_YY_MORE_OFFSET

        if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
            {
            /* We're scanning a new file or input source.  It's
             * possible that this happened because the user
             * just pointed yyin at a new source and called
             * yylex().  If so, then we have to assure
             * consistency between yy_current_buffer and our
             * globals.  Here is the right place to do so, because
             * this is the first action (other than possibly a
             * back-up) that will match for the new input source.
             */
            yy_n_chars = yy_current_buffer->yy_n_chars;
            yy_current_buffer->yy_input_file = yyin;
            yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
            }

        /* Note that here we test for yy_c_buf_p "<=" to the position
         * of the first EOB in the buffer, since yy_c_buf_p will
         * already have been incremented past the NUL character
         * (since all states make transitions on EOB to the
         * end-of-buffer state).  Contrast this with the test
         * in input().
         */
        if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
            { /* This was really a NUL. */
            yy_state_type yy_next_state;

            yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

            yy_current_state = yy_get_previous_state();

            /* Okay, we're now positioned to make the NUL
             * transition.  We couldn't have
             * yy_get_previous_state() go ahead and do it
             * for us because it doesn't know how to deal
             * with the possibility of jamming (and we don't
             * want to build jamming into it because then it
             * will run more slowly).
             */

            yy_next_state = yy_try_NUL_trans( yy_current_state );

            yy_bp = yytext_ptr + YY_MORE_ADJ;

            if ( yy_next_state )
                {
                /* Consume the NUL. */
                yy_cp = ++yy_c_buf_p;
                yy_current_state = yy_next_state;
                goto yy_match;
                }

            else
                {
                yy_cp = yy_c_buf_p;
                goto yy_find_action;
                }
            }

        else switch ( yy_get_next_buffer() )
            {
            case EOB_ACT_END_OF_FILE:
                {
                yy_did_buffer_switch_on_eof = 0;

                if ( yywrap() )
                    {
                    /* Note: because we've taken care in
                     * yy_get_next_buffer() to have set up
                     * yytext, we can now set up
                     * yy_c_buf_p so that if some total
                     * hoser (like flex itself) wants to
                     * call the scanner after we return the
                     * YY_NULL, it'll still work - another
                     * YY_NULL will get returned.
                     */
                    yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

                    yy_act = YY_STATE_EOF(YY_START);
                    goto do_action;
                    }

                else
                    {
                    if ( ! yy_did_buffer_switch_on_eof )
                        YY_NEW_FILE;
                    }
                break;
                }

            case EOB_ACT_CONTINUE_SCAN:
                yy_c_buf_p =
                    yytext_ptr + yy_amount_of_matched_text;

                yy_current_state = yy_get_previous_state();

                yy_cp = yy_c_buf_p;
                yy_bp = yytext_ptr + YY_MORE_ADJ;
                goto yy_match;

            case EOB_ACT_LAST_MATCH:
                yy_c_buf_p =
                &yy_current_buffer->yy_ch_buf[yy_n_chars];

                yy_current_state = yy_get_previous_state();

                yy_cp = yy_c_buf_p;
                yy_bp = yytext_ptr + YY_MORE_ADJ;
                goto yy_find_action;
            }
        break;
        }

    default:
        YY_FATAL_ERROR(
            "fatal flex scanner internal error--no action found" );
    } /* end of action switch */
        } /* end of scanning one token */
    } /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *    EOB_ACT_LAST_MATCH -
 *    EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *    EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
    {
    register char *dest = yy_current_buffer->yy_ch_buf;
    register char *source = yytext_ptr;
    register int number_to_move, i;
    int ret_val;

    if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
        YY_FATAL_ERROR(
        "fatal flex scanner internal error--end of buffer missed" );

    if ( yy_current_buffer->yy_fill_buffer == 0 )
        { /* Don't try to fill the buffer, so this is an EOF. */
        if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
            {
            /* We matched a single character, the EOB, so
             * treat this as a final EOF.
             */
            return EOB_ACT_END_OF_FILE;
            }

        else
            {
            /* We matched some text prior to the EOB, first
             * process it.
             */
            return EOB_ACT_LAST_MATCH;
            }
        }

    /* Try to read more data. */

    /* First move last chars to start of buffer. */
    number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

    for ( i = 0; i < number_to_move; ++i )
        *(dest++) = *(source++);

    if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
        /* don't do the read, it's not guaranteed to return an EOF,
         * just force an EOF
         */
        yy_current_buffer->yy_n_chars = yy_n_chars = 0;

    else
        {
        int num_to_read =
            yy_current_buffer->yy_buf_size - number_to_move - 1;

        while ( num_to_read <= 0 )
            { /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
            YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

            /* just a shorter name for the current buffer */
            YY_BUFFER_STATE b = yy_current_buffer;

            int yy_c_buf_p_offset =
                (int) (yy_c_buf_p - b->yy_ch_buf);

            if ( b->yy_is_our_buffer )
                {
                int new_size = b->yy_buf_size * 2;

                if ( new_size <= 0 )
                    b->yy_buf_size += b->yy_buf_size / 8;
                else
                    b->yy_buf_size *= 2;

                b->yy_ch_buf = (char *)
                    /* Include room in for 2 EOB chars. */
                    yy_flex_realloc( (void *) b->yy_ch_buf,
                             b->yy_buf_size + 2 );
                }
            else
                /* Can't grow it, we don't own it. */
                b->yy_ch_buf = 0;

            if ( ! b->yy_ch_buf )
                YY_FATAL_ERROR(
                "fatal error - scanner input buffer overflow" );

            yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

            num_to_read = yy_current_buffer->yy_buf_size -
                        number_to_move - 1;
#endif
            }

        if ( num_to_read > YY_READ_BUF_SIZE )
            num_to_read = YY_READ_BUF_SIZE;

        /* Read in more data. */
        YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
            yy_n_chars, num_to_read );

        yy_current_buffer->yy_n_chars = yy_n_chars;
        }

    if ( yy_n_chars == 0 )
        {
        if ( number_to_move == YY_MORE_ADJ )
            {
            ret_val = EOB_ACT_END_OF_FILE;
            yyrestart( yyin );
            }

        else
            {
            ret_val = EOB_ACT_LAST_MATCH;
            yy_current_buffer->yy_buffer_status =
                YY_BUFFER_EOF_PENDING;
            }
        }

    else
        ret_val = EOB_ACT_CONTINUE_SCAN;

    yy_n_chars += number_to_move;
    yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
    yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

    yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

    return ret_val;
    }


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
    {
    register yy_state_type yy_current_state;
    register char *yy_cp;

    yy_current_state = yy_start;
    yy_current_state += YY_AT_BOL();

    for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
        {
        register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
        if ( yy_accept[yy_current_state] )
            {
            yy_last_accepting_state = yy_current_state;
            yy_last_accepting_cpos = yy_cp;
            }
        while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
            {
            yy_current_state = (int) yy_def[yy_current_state];
            if ( yy_current_state >= 295 )
                yy_c = yy_meta[(unsigned int) yy_c];
            }
        yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
        }

    return yy_current_state;
    }


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *    next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
    {
    register int yy_is_jam;
    register char *yy_cp = yy_c_buf_p;

    register YY_CHAR yy_c = 1;
    if ( yy_accept[yy_current_state] )
        {
        yy_last_accepting_state = yy_current_state;
        yy_last_accepting_cpos = yy_cp;
        }
    while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
        {
        yy_current_state = (int) yy_def[yy_current_state];
        if ( yy_current_state >= 295 )
            yy_c = yy_meta[(unsigned int) yy_c];
        }
    yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
    yy_is_jam = (yy_current_state == 294);

    return yy_is_jam ? 0 : yy_current_state;
    }


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
    {
    register char *yy_cp = yy_c_buf_p;

    /* undo effects of setting up yytext */
    *yy_cp = yy_hold_char;

    if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
        { /* need to shift things up to make room */
        /* +2 for EOB chars. */
        register int number_to_move = yy_n_chars + 2;
        register char *dest = &yy_current_buffer->yy_ch_buf[
                    yy_current_buffer->yy_buf_size + 2];
        register char *source =
                &yy_current_buffer->yy_ch_buf[number_to_move];

        while ( source > yy_current_buffer->yy_ch_buf )
            *--dest = *--source;

        yy_cp += (int) (dest - source);
        yy_bp += (int) (dest - source);
        yy_current_buffer->yy_n_chars =
            yy_n_chars = yy_current_buffer->yy_buf_size;

        if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
            YY_FATAL_ERROR( "flex scanner push-back overflow" );
        }

    *--yy_cp = (char) c;


    yytext_ptr = yy_bp;
    yy_hold_char = *yy_cp;
    yy_c_buf_p = yy_cp;
    }
#endif    /* ifndef YY_NO_UNPUT */


#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
    {
    int c;

    *yy_c_buf_p = yy_hold_char;

    if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
        {
        /* yy_c_buf_p now points to the character we want to return.
         * If this occurs *before* the EOB characters, then it's a
         * valid NUL; if not, then we've hit the end of the buffer.
         */
        if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
            /* This was really a NUL. */
            *yy_c_buf_p = '\0';

        else
            { /* need more input */
            int offset = yy_c_buf_p - yytext_ptr;
            ++yy_c_buf_p;

            switch ( yy_get_next_buffer() )
                {
                case EOB_ACT_LAST_MATCH:
                    /* This happens because yy_g_n_b()
                     * sees that we've accumulated a
                     * token and flags that we need to
                     * try matching the token before
                     * proceeding.  But for input(),
                     * there's no matching to consider.
                     * So convert the EOB_ACT_LAST_MATCH
                     * to EOB_ACT_END_OF_FILE.
                     */

                    /* Reset buffer status. */
                    yyrestart( yyin );

                    /* fall through */

                case EOB_ACT_END_OF_FILE:
                    {
                    if ( yywrap() )
                        return EOF;

                    if ( ! yy_did_buffer_switch_on_eof )
                        YY_NEW_FILE;
#ifdef __cplusplus
                    return yyinput();
#else
                    return input();
#endif
                    }

                case EOB_ACT_CONTINUE_SCAN:
                    yy_c_buf_p = yytext_ptr + offset;
                    break;
                }
            }
        }

    c = *(unsigned char *) yy_c_buf_p;    /* cast for 8-bit char's */
    *yy_c_buf_p = '\0';    /* preserve yytext */
    yy_hold_char = *++yy_c_buf_p;

    yy_current_buffer->yy_at_bol = (c == '\n');

    return c;
    }
#endif /* YY_NO_INPUT */

#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
    {
    if ( ! yy_current_buffer )
        yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

    yy_init_buffer( yy_current_buffer, input_file );
    yy_load_buffer_state();
    }


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
    {
    if ( yy_current_buffer == new_buffer )
        return;

    if ( yy_current_buffer )
        {
        /* Flush out information for old buffer. */
        *yy_c_buf_p = yy_hold_char;
        yy_current_buffer->yy_buf_pos = yy_c_buf_p;
        yy_current_buffer->yy_n_chars = yy_n_chars;
        }

    yy_current_buffer = new_buffer;
    yy_load_buffer_state();

    /* We don't actually know whether we did this switch during
     * EOF (yywrap()) processing, but the only time this flag
     * is looked at is after yywrap() is called, so it's safe
     * to go ahead and always set it.
     */
    yy_did_buffer_switch_on_eof = 1;
    }


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
    {
    yy_n_chars = yy_current_buffer->yy_n_chars;
    yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
    yyin = yy_current_buffer->yy_input_file;
    yy_hold_char = *yy_c_buf_p;
    }


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
    {
    YY_BUFFER_STATE b;

    b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
    if ( ! b )
        YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

    b->yy_buf_size = size;

    /* yy_ch_buf has to be 2 characters longer than the size given because
     * we need to put in 2 end-of-buffer characters.
     */
    b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
    if ( ! b->yy_ch_buf )
        YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

    b->yy_is_our_buffer = 1;

    yy_init_buffer( b, file );

    return b;
    }


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
    {
    if ( ! b )
        return;

    if ( b == yy_current_buffer )
        yy_current_buffer = (YY_BUFFER_STATE) 0;

    if ( b->yy_is_our_buffer )
        yy_flex_free( (void *) b->yy_ch_buf );

    yy_flex_free( (void *) b );
    }



#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


    {
    yy_flush_buffer( b );

    b->yy_input_file = file;
    b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
    b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
    b->yy_is_interactive = 0;
#else
    b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
    }


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

    {
    if ( ! b )
        return;

    b->yy_n_chars = 0;

    /* We always need two end-of-buffer characters.  The first causes
     * a transition to the end-of-buffer state.  The second causes
     * a jam in that state.
     */
    b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
    b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

    b->yy_buf_pos = &b->yy_ch_buf[0];

    b->yy_at_bol = 1;
    b->yy_buffer_status = YY_BUFFER_NEW;

    if ( b == yy_current_buffer )
        yy_load_buffer_state();
    }


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
    {
    YY_BUFFER_STATE b;

    if ( size < 2 ||
         base[size-2] != YY_END_OF_BUFFER_CHAR ||
         base[size-1] != YY_END_OF_BUFFER_CHAR )
        /* They forgot to leave room for the EOB's. */
        return 0;

    b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
    if ( ! b )
        YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

    b->yy_buf_size = size - 2;    /* "- 2" to take care of EOB's */
    b->yy_buf_pos = b->yy_ch_buf = base;
    b->yy_is_our_buffer = 0;
    b->yy_input_file = 0;
    b->yy_n_chars = b->yy_buf_size;
    b->yy_is_interactive = 0;
    b->yy_at_bol = 1;
    b->yy_fill_buffer = 0;
    b->yy_buffer_status = YY_BUFFER_NEW;

    yy_switch_to_buffer( b );

    return b;
    }
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
    {
    int len;
    for ( len = 0; yy_str[len]; ++len )
        ;

    return yy_scan_bytes( yy_str, len );
    }
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
    {
    YY_BUFFER_STATE b;
    char *buf;
    yy_size_t n;
    int i;

    /* Get memory for full buffer, including space for trailing EOB's. */
    n = len + 2;
    buf = (char *) yy_flex_alloc( n );
    if ( ! buf )
        YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

    for ( i = 0; i < len; ++i )
        buf[i] = bytes[i];

    buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

    b = yy_scan_buffer( buf, n );
    if ( ! b )
        YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

    /* It's okay to grow etc. this buffer, and we should throw it
     * away when we're done.
     */
    b->yy_is_our_buffer = 1;

    return b;
    }
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
    {
    if ( yy_start_stack_ptr >= yy_start_stack_depth )
        {
        yy_size_t new_size;

        yy_start_stack_depth += YY_START_STACK_INCR;
        new_size = yy_start_stack_depth * sizeof( int );

        if ( ! yy_start_stack )
            yy_start_stack = (int *) yy_flex_alloc( new_size );

        else
            yy_start_stack = (int *) yy_flex_realloc(
                    (void *) yy_start_stack, new_size );

        if ( ! yy_start_stack )
            YY_FATAL_ERROR(
            "out of memory expanding start-condition stack" );
        }

    yy_start_stack[yy_start_stack_ptr++] = YY_START;

    BEGIN(new_state);
    }
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
    {
    if ( --yy_start_stack_ptr < 0 )
        YY_FATAL_ERROR( "start-condition stack underflow" );

    BEGIN(yy_start_stack[yy_start_stack_ptr]);
    }
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
    {
    return yy_start_stack[yy_start_stack_ptr - 1];
    }
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
    {

    clReport(0, 0, clvREPORT_FATAL_ERROR, (char *)msg);
    }



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
    do \
        { \
        /* Undo effects of setting up yytext. */ \
        yytext[yyleng] = yy_hold_char; \
        yy_c_buf_p = yytext + n; \
        yy_hold_char = *yy_c_buf_p; \
        *yy_c_buf_p = '\0'; \
        yyleng = n; \
        } \
    while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
    {
    register int i;
    for ( i = 0; i < n; ++i )
        s1[i] = s2[i];
    }
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
    {
    register int n;
    for ( n = 0; s[n]; ++n )
        ;

    return n;
    }
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
    {
    return (void *) clMalloc( size );
    }

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
    {
    /* The cast to (char *) in the following accommodates both
     * implementations that use char* generic pointers, and those
     * that use void* generic pointers.  It works with the latter
     * because both ANSI C and C++ allow castless assignment from
     * any pointer type to void*, and deal with argument conversions
     * as though doing an assignment.
     */
    return (void *) clRealloc( (char *) ptr, size );
    }

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
    {
    clFree( ptr );
    }

#if YY_MAIN
int main()
    {
    yylex();
    return 0;
    }
#endif
#line 360 "gc_cl.l"


void
clScanComment(IN cloCOMPILER Compiler)
{
    gctINT ch;

    while (gcvTRUE) {
        while ((ch = input()) != '*' && ch != EOF) DUMP_SOURCE_CHAR(ch);

        if (ch == EOF) {
            cloCOMPILER_Report(Compiler,
                    CurrentLineNo,
                    CurrentStringNo,
                    clvREPORT_ERROR,
                    "invalid comment: unexpected end of file");
            break;
        }
        DUMP_SOURCE_CHAR(ch);
        while ((ch = input()) == '*') DUMP_SOURCE_CHAR(ch);
        if (ch == EOF) {
            cloCOMPILER_Report(Compiler,
                    CurrentLineNo,
                    CurrentStringNo,
                    clvREPORT_ERROR,
                    "invalid comment: unexpected end of file");
            break;
        }
        else if (ch == '/') {
            DUMP_SOURCE_CHAR(ch);
            break;
        }
        else {
            DUMP_SOURCE_CHAR(ch);
        }
    }
    DUMP_SOURCE_COMMENT_END();
}

void
clScanSkipToEOL(IN cloCOMPILER Compiler)
{
    gctINT ch;
    while ((ch = input()) != '\n' && ch != EOF) DUMP_SOURCE_CHAR(ch);
    return;
}

gceSTATUS
clScanSetCurrentFileName(
IN cloCOMPILER Compiler,
IN gctSTRING FileName
)
{
   /* Verify the arguments. */
   clmVERIFY_OBJECT(Compiler, clvOBJ_COMPILER);
   CurrentFileName = FileName;
   return gcvSTATUS_OK;
}

gceSTATUS
clScanSetCurrentLineNo(
IN cloCOMPILER Compiler,
IN gctUINT LineNo
)
{
    /* Verify the arguments. */
    clmVERIFY_OBJECT(Compiler, clvOBJ_COMPILER);
    CurrentLineNo = LineNo;
    return gcvSTATUS_OK;
}

gceSTATUS
clScanSetCurrentStringNo(
IN cloCOMPILER Compiler,
IN gctUINT StringNo
)
{
    /* Verify the arguments. */
    clmVERIFY_OBJECT(Compiler, clvOBJ_COMPILER);
    CurrentStringNo    = StringNo;
    return gcvSTATUS_OK;
}

gceSTATUS
clScanLookAhead(
IN cloCOMPILER Compiler,
IN gctINT LookAheadChr
)
{
  gctINT ch;
  while ((ch = input()) != EOF) {
     if((ch ==  ' ') || (ch == '\t')) { /* skip white spaces */
          DUMP_SOURCE_CHAR(ch);
          continue;
     }
     unput(ch);
     if(ch == LookAheadChr) { /*found the lookahead*/
        return gcvSTATUS_OK;
     }
     else break;
  }
  if(yyleng == 1 && yytext[0] == LookAheadChr) {
     return gcvSTATUS_OK;
  }
  return gcvSTATUS_NOT_FOUND;
}

gceSTATUS
clScanLookAheadWithSkip(
IN cloCOMPILER Compiler,
IN gctINT LookAheadChr,
IN gctINT SkipChar
)
{
  gctINT ch;
  gctINT skipCount = 0;
  gctINT i;

  while ((ch = input()) != EOF) {
     if((ch ==  ' ') || (ch == '\t')) { /* skip white spaces */
          DUMP_SOURCE_CHAR(ch);
          continue;
     }
     else if(ch == SkipChar) { /* Is skip character */
          skipCount++;
          continue;
     }

     unput(ch);

     /*put back the skipped chararacters*/
     for(i = 0; i < skipCount; i++)
     {
        unput(SkipChar);
     }
     if(ch == LookAheadChr) { /*found the lookahead*/
        return gcvSTATUS_OK;
     }
     else break;
  }
  if(yyleng == 1 && yytext[0] == LookAheadChr) {
     return gcvSTATUS_OK;
  }
  return gcvSTATUS_NOT_FOUND;
}

void
clScanDeleteBuffer(
IN cloCOMPILER Compiler
)
{
   yy_delete_buffer(YY_CURRENT_BUFFER);
}

extern void
yyerror(char *msg)
{
    char *formatString = "%s at '%s'";
    char *where = yytext;
    if(yyleng <= 1 && *yytext < 0)where = "end of file";
    clReport(CurrentLineNo,
        CurrentStringNo,
        clvREPORT_ERROR,
        formatString,
        msg,
        where);

}
