/****************************************************************************
*
*    Copyright (c) 2005 - 2016 by Vivante Corp.  All rights reserved.
*
*    The material in this file is confidential and contains trade secrets
*    of Vivante Corporation. This is proprietary information owned by
*    Vivante Corporation. No part of this work may be disclosed,
*    reproduced, copied, transmitted, or used in any way for any purpose,
*    without the express written permission of Vivante Corporation.
*
*****************************************************************************/


#line 2 "gc_cl_scanner.c"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include "gc_cl_scanner.h"
#ifndef NULL
#define NULL ((void *)0)
#endif
#ifndef EOF
#define EOF     (-1)
#endif
#if !defined(UNDER_CE) || UNDER_CE >=800
#define FILE    void
#define stdin   NULL
#define stdout  NULL
#else
typedef void FILE;
#endif



/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus


/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else    /* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif    /* __STDC__ */
#endif    /* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 *     if ( condition_holds )
 *        yyless( 5 );
 *    else
 *        do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
    do \
        { \
        /* Undo effects of setting up yytext. */ \
        *yy_cp = yy_hold_char; \
        YY_RESTORE_YY_MORE_OFFSET \
        yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
        YY_DO_BEFORE_ACTION; /* set up yytext again */ \
        } \
    while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
    {
    FILE *yy_input_file;

    char *yy_ch_buf;        /* input buffer */
    char *yy_buf_pos;        /* current position in input buffer */

    /* Size of input buffer in bytes, not including room for EOB
     * characters.
     */
    yy_size_t yy_buf_size;

    /* Number of characters read into yy_ch_buf, not including EOB
     * characters.
     */
    int yy_n_chars;

    /* Whether we "own" the buffer - i.e., we know we created it,
     * and can clRealloc() it to grow it, and should clFree() it to
     * delete it.
     */
    int yy_is_our_buffer;

    /* Whether this is an "interactive" input source; if so, and
     * if we're using stdio for input, then we want to use getc()
     * instead of fread(), to make sure we stop fetching input after
     * each newline.
     */
    int yy_is_interactive;

    /* Whether we're considered to be at the beginning of a line.
     * If so, '^' rules will be active on the next match, otherwise
     * not.
     */
    int yy_at_bol;

    /* Whether to try to fill the input buffer when we reach the
     * end of it.
     */
    int yy_fill_buffer;

    int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
    /* When an EOF's been seen but there's still some text to process
     * then we mark the buffer as YY_EOF_PENDING, to indicate that we
     * shouldn't try reading from the input source any more.  We might
     * still have a bunch of tokens to match, though, because of
     * possible backing-up.
     *
     * When we actually see the EOF, we change the status to "new"
     * (via yyrestart()), so that the user can continue scanning by
     * just pointing yyin at a new input file.
     */
#define YY_BUFFER_EOF_PENDING 2
    };

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;        /* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;        /* whether we need to initialize */
static int yy_start = 0;    /* start state number */

static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
    { \
    if ( ! yy_current_buffer ) \
        yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
    yy_current_buffer->yy_is_interactive = is_interactive; \
    }

#define yy_set_bol(at_bol) \
    { \
    if ( ! yy_current_buffer ) \
        yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
    yy_current_buffer->yy_at_bol = at_bol; \
    }

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef int YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
    yytext_ptr = yy_bp; \
    yytext_ptr -= yy_more_len; \
    yyleng = (int) (yy_cp - yytext_ptr); \
    yy_hold_char = *yy_cp; \
    *yy_cp = '\0'; \
    yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 81
#define YY_END_OF_BUFFER 82
static yyconst short int yy_accept[294] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       82,   80,   78,   78,   55,   80,   61,   66,   80,   39,
       40,   59,   58,   51,   56,   49,   60,   12,   11,   52,
       54,   62,   53,   63,   67,   10,   41,   43,   65,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   45,   64,   47,   57,   78,   69,   61,   75,   80,
       80,   80,   71,   73,   74,   74,   74,   74,   25,    0,
       17,   32,   48,   26,   35,    0,   29,   20,   31,    0,
       68,   21,   38,   50,   14,   72,   79,   30,   14,   12,
        0,    0,   12,   12,    0,   12,   11,   11,   11,   11,

       44,   46,   42,   18,   22,   24,   23,   19,   10,   36,
       28,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   37,   27,
        0,   69,    0,   70,   75,    0,    0,   71,   73,   74,
       74,    0,   72,   74,   16,    0,   14,   79,    0,   14,
       12,   12,   12,   12,   13,   11,   11,   11,   11,   33,
       34,   10,   10,   10,   10,   10,   10,   10,    7,   10,
       10,   10,   10,   10,   10,   10,   10,   10,    0,    0,
       74,   74,    0,   14,   12,    0,   13,   13,   13,   11,
       10,   10,   10,   10,    9,   10,    7,   10,    1,   10,

       10,   10,   10,    0,    0,    0,   13,   13,   13,   13,
       10,   10,    2,    7,   10,    9,   10,   10,    0,    0,
       13,   10,   10,   10,   10,   10,   10,    9,   10,    7,
       10,    0,    0,   15,   10,   10,   10,   10,   10,   10,
       10,   10,    9,   10,   10,   76,   77,   15,   10,   10,
       10,   10,   10,   10,   10,   10,    5,    4,   10,   10,
       10,   10,   10,    6,    3,   10,   10,   10,   10,   10,
       10,    0,    0,    0,    0,   10,   10,   10,    0,    0,
        0,    0,   10,    0,    3,    0,    0,   10,    0,   10,
       10,    8,    0

    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        4,    4,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       22,   23,   24,   25,   24,   26,   27,   28,   29,   30,
       31,   32,   33,    1,   34,   34,   34,   34,   35,   36,
       37,   37,   37,   37,   37,   38,   37,   37,   37,   39,
       37,   37,   37,   37,   40,   37,   37,   41,   37,   37,
       42,    1,   43,   44,   45,    1,   46,   47,   48,   49,

       50,   51,   52,   53,   54,   37,   55,   56,   57,   58,
       59,   60,   61,   62,   63,   64,   65,   66,   37,   67,
       68,   37,   69,   70,   71,   72,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[73] =
    {   0,
        1,    2,    3,    1,    1,    1,    1,    1,    1,    4,
        1,    1,    1,    5,    1,    5,    6,    1,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    1,    1,    1,
        1,    1,    1,    8,    9,   10,   11,   12,   11,   11,
       11,    1,    1,    1,   11,    8,    8,    8,    8,    9,
       10,   11,   11,   11,   11,   12,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,    1,    1,
        1,    1
    } ;

static yyconst short int yy_base[312] =
    {   0,
        0,   71,   72,   78,  137,    0,  204,  230,   81,   89,
      761,  762,  762,  762,  729,  753,   57,   77,    0,  762,
      762,  727,   63,   95,   84,   98,   96,  241,  292,  725,
      762,  105,  725,   70,  762,    0,  762,  762,   98,  689,
      695,  700,  693,   91,  705,  692,  690,  683,  694,  684,
       95,  762,   74,  762,  762,  104,  762,  128,  743,  113,
      690,  681,    0,  190,    0,    0,  144,  139,  762,  736,
      762,  762,  762,  762,  762,  731,  762,  762,  762,  165,
      762,  762,  762,  762,  234,  762,    0,  762,  242,   63,
      224,  147,  180,  124,    0,  114,    0,  181,  233,  264,

      762,  762,  762,  709,  762,  762,  762,  708,    0,  762,
      762,  684,  678,  690,  670,  678,  674,  676,  667,  672,
      683,  669,  662,  673,  667,  665,  660,  669,  762,  762,
      235,  762,  693,  762,  718,  661,  671,    0,  314,    0,
      163,  704,    0,  697,  762,  224,  762,    0,  339,  331,
      235,  762,  649,  623,  288,  256,  762,  638,  608,  762,
      762,  594,  601,  584,  587,  570,  565,  559,  329,  546,
      521,  507,  518,  521,  502,  507,  509,  503,  511,  508,
      762,  557,  351,  365,  762,    0,  345,  245,  328,  762,
      513,  500,  505,  490,  368,  528,  376,  487,    0,  488,

      492,  491,  475,  534,  465,  184,  259,  762,  465,  446,
      359,  446,    0,  397,  470,  405,  436,  429,  445,  233,
      762,  430,  435,  437,  439,  431,  225,  412,  457,  419,
      430,  284,  427,  441,  419,  430,  416,  417,  404,  409,
      403,  419,  438,  445,  394,  435,  762,  762,  380,  353,
      350,  362,  347,  362,  346,  486,  494,  292,  478,  336,
      336,  333,  330,  504,  427,  361,  512,  519,  320,  296,
      290,  293,  285,  272,  272,  526,  277,  272,  264,  243,
      245,  243,  191,  173,  762,  129,  102,   93,   81,   60,
       54,    0,  762,  571,  583,  595,  607,  613,  619,  631,

      643,  649,  661,  668,  673,  674,  684,  696,  704,  705,
      711
    } ;

static yyconst short int yy_def[312] =
    {   0,
      293,    1,  294,  294,  294,    5,  294,  294,  295,  295,
      293,  293,  293,  293,  293,  296,  293,  293,  297,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  298,  293,  293,  293,  298,
      298,  298,  298,  298,  298,  298,  298,  298,  298,  298,
      298,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  299,  293,  300,  300,  301,  300,  293,  296,
      293,  293,  293,  293,  293,  297,  293,  293,  293,  293,
      293,  293,  293,  293,  302,  293,  303,  293,  302,   28,
      304,  305,  293,  293,  306,  293,   29,  293,  293,  293,

      293,  293,  293,  293,  293,  293,  293,  293,  298,  293,
      293,  298,  298,  298,  298,  298,  298,  298,  298,  298,
      298,  298,  298,  298,  298,  298,  298,  298,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  299,  293,  300,
      301,  307,  300,  308,  293,  309,  293,  303,  293,  305,
      293,  293,  293,  293,  306,  293,  293,  293,  293,  293,
      293,  298,  298,  298,  298,  298,  298,  298,  298,  298,
      298,  298,  298,  298,  298,  298,  298,  298,  293,  293,
      293,  308,  293,  309,  293,  310,  293,  293,  293,  293,
      298,  298,  298,  298,  298,  298,  298,  298,  298,  298,

      298,  298,  298,  293,  293,  310,  293,  293,  293,  293,
      298,  298,  298,  298,  298,  298,  298,  298,  293,  311,
      293,  298,  298,  298,  298,  298,  298,  298,  298,  298,
      298,  293,  293,  311,  298,  298,  298,  298,  298,  298,
      298,  298,  298,  298,  298,  293,  293,  293,  298,  298,
      298,  298,  298,  298,  298,  298,  298,  298,  298,  298,
      298,  298,  298,  298,  293,  298,  298,  298,  298,  298,
      298,  293,  293,  293,  293,  298,  298,  298,  293,  293,
      293,  293,  298,  293,  293,  293,  293,  298,  293,  298,
      298,  298,    0,  293,  293,  293,  293,  293,  293,  293,

      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293
    } ;

static yyconst short int yy_nxt[835] =
    {   0,
       12,   13,   14,   13,   15,   16,   12,   17,   18,   19,
       20,   21,   22,   23,   24,   25,   26,   27,   28,   29,
       29,   29,   29,   29,   29,   29,   29,   30,   31,   32,
       33,   34,   35,   36,   36,   36,   36,   36,   36,   36,
       36,   37,   38,   39,   40,   36,   41,   42,   43,   36,
       44,   36,   45,   46,   36,   47,   36,   36,   36,   36,
       48,   36,   49,   50,   51,   36,   36,   36,   52,   53,
       54,   55,   56,   59,   14,   13,   78,   57,   58,   59,
       14,   13,   13,   14,   66,   74,   67,   72,   73,   60,
       13,   14,   66,   79,   67,   60,   80,   80,   68,   82,

      107,  108,  292,  293,  129,  131,   68,   75,   86,  291,
      132,  133,  102,   87,   83,   84,   85,   85,   85,   85,
       85,   85,   85,   85,   85,   86,   88,   61,  110,  293,
       87,   62,  103,   61,  104,  105,  116,   62,   13,   14,
       13,  111,  124,  130,  285,  142,  117,  290,  125,  140,
      126,  143,  127,  152,   60,  134,  144,  128,   72,   73,
      149,  153,  149,  289,  142,   81,   80,   80,  140,  151,
       63,   63,   63,   63,   63,   63,   63,   63,  152,  154,
      285,   63,   63,   63,   63,   63,   63,   63,   63,   63,
       63,   63,   63,   63,   63,   63,   63,   63,   63,   63,

       63,   63,   63,   63,   63,   13,   14,   13,  139,  139,
      139,  139,  139,  139,  139,  139,  139,  151,  156,  152,
      157,   60,  220,   64,   64,   64,   64,   64,   64,   64,
       64,   13,   14,   13,  285,   81,  131,  183,  288,  183,
       89,  132,  133,  220,  152,  157,  233,   60,  233,   64,
       64,   64,   64,   64,   64,   64,   64,   89,   92,   90,
       90,   90,   90,   90,   90,   90,   91,   91,  146,  147,
      158,  147,  240,   92,  152,   92,  146,  147,   93,  147,
       94,   95,  209,  146,  147,  246,  247,  241,  159,  147,
       92,  146,  147,  265,  265,  157,   96,  147,  208,  152,

      210,  287,  286,  157,  186,   94,  285,   95,   89,  284,
       97,   97,   97,   97,   97,   97,   97,   97,   97,  156,
      157,  259,  283,  208,  282,  187,   92,  188,  157,   98,
      281,   99,  139,  139,  139,  139,  139,  139,  139,  139,
      139,   92,  280,  189,  293,  279,  293,  100,  196,  197,
      197,  197,  188,  259,  197,  278,   99,  150,  150,  150,
      150,  150,  150,  150,  150,  150,  147,  208,  147,  184,
      184,  184,  184,  184,  184,  184,  184,  184,  293,  277,
      293,  147,  207,  207,  208,  267,  147,  215,  216,  216,
      216,  271,  208,  216,  259,  196,  197,  197,  197,  259,

      147,  197,  147,  270,  263,  222,  223,  262,  261,  208,
      224,  225,  259,  260,  259,  147,  229,  230,  230,  230,
      147,  226,  230,  227,  215,  216,  216,  216,  265,  265,
      216,  242,  243,  243,  243,  259,  246,  243,  229,  230,
      230,  230,  258,  243,  230,  234,  234,  234,  234,  234,
      234,  234,  234,  234,  293,  255,  293,  242,  243,  243,
      243,  254,  253,  243,  257,  257,  257,  257,  257,  257,
      257,  257,  252,  251,  272,  250,  248,  249,  248,  245,
      273,  230,  274,  239,  238,  244,  237,  236,  235,  275,
      232,  248,  169,  231,  216,  228,  248,  266,  267,  268,

      267,  221,  221,  267,  256,  264,  264,  264,  264,  264,
      264,  264,  264,  257,  257,  257,  257,  257,  257,  257,
      257,  219,  269,  264,  264,  264,  264,  264,  264,  264,
      264,  266,  267,  268,  267,  135,  218,  267,  266,  276,
      268,  267,  217,  169,  267,  266,  267,  268,  267,  169,
      169,  267,  197,  214,  213,  212,  269,  211,  148,  205,
      204,  203,  202,  269,  201,  169,  200,  199,  198,  195,
      269,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   65,   65,   65,   65,   65,   65,   65,
       65,   65,   65,   65,   65,   70,   70,  169,   70,   70,

       70,   70,   70,   70,   70,   70,   70,   76,   76,  195,
      194,   76,   76,   76,   76,   76,   76,   76,   76,  109,
      109,  109,  109,  109,  109,  138,  138,  138,  138,  138,
      138,  140,  193,  192,  140,  140,  140,  140,  140,  140,
      140,  140,  140,  141,  141,  169,  141,  141,  141,  141,
      141,  141,  141,  141,  141,   85,  169,   85,   85,  191,
       85,  148,  148,  190,  148,  148,  148,  148,  148,  148,
      148,  148,  148,   91,   91,  190,   91,  150,  185,  150,
      155,  155,  155,  155,  142,  142,  185,  142,  142,  142,
      142,  142,  142,  142,  142,  142,  182,  182,  148,  182,

      182,  182,  182,  182,  182,  182,  182,  182,  184,  181,
      184,  206,  206,  206,  206,  234,  180,  234,  179,  135,
      134,  178,  177,  176,  175,  174,  173,  172,  171,  170,
      169,  168,  167,  166,  165,  164,  163,  162,  161,  160,
      145,   71,  137,  136,  135,  123,  122,  121,  120,  119,
      118,  115,  114,  113,  112,  106,  101,   77,   71,   69,
      293,   11,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,

      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293
    } ;

static yyconst short int yy_chk[835] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    2,    3,    3,    3,   23,    2,    2,    4,
        4,    4,    9,    9,    9,   18,    9,   17,   17,    3,
       10,   10,   10,   23,   10,    4,   24,   24,    9,   25,

       34,   34,  291,   90,   53,   56,   10,   18,   27,  290,
       56,   56,   32,   27,   25,   25,   26,   26,   26,   26,
       26,   26,   26,   26,   26,   60,   27,    3,   39,   90,
       60,    3,   32,    4,   32,   32,   44,    4,    5,    5,
        5,   39,   51,   53,  289,   67,   44,  288,   51,   67,
       51,   68,   51,   96,    5,   58,   68,   51,   58,   58,
       92,   94,   92,  287,  141,   24,   80,   80,  141,   96,
        5,    5,    5,    5,    5,    5,    5,    5,   96,   94,
      286,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,

        5,    5,    5,    5,    5,    7,    7,    7,   64,   64,
       64,   64,   64,   64,   64,   64,   64,   93,   98,   93,
       98,    7,  206,    7,    7,    7,    7,    7,    7,    7,
        7,    8,    8,    8,  284,   80,  131,  146,  283,  146,
       91,  131,  131,  206,   93,   98,  220,    8,  220,    8,
        8,    8,    8,    8,    8,    8,    8,   28,   91,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   85,   85,
       99,   85,  227,   91,  151,   28,   89,   89,   28,   89,
       28,   28,  188,   85,   85,  232,  232,  227,   99,   85,
       28,   89,   89,  258,  258,  156,   28,   89,  207,  151,

      188,  282,  281,  100,  155,   28,  280,   28,   29,  279,
       29,   29,   29,   29,   29,   29,   29,   29,   29,  100,
      156,  278,  277,  207,  275,  155,   29,  155,  100,   29,
      274,   29,  139,  139,  139,  139,  139,  139,  139,  139,
      139,   29,  273,  155,  150,  272,  150,   29,  169,  169,
      169,  169,  155,  271,  169,  270,   29,  149,  149,  149,
      149,  149,  149,  149,  149,  149,  150,  189,  150,  183,
      183,  183,  183,  183,  183,  183,  183,  183,  184,  269,
      184,  150,  187,  189,  187,  266,  150,  195,  195,  195,
      195,  263,  189,  195,  262,  197,  197,  197,  197,  261,

      184,  197,  184,  260,  255,  211,  211,  254,  253,  187,
      211,  211,  252,  251,  250,  184,  214,  214,  214,  214,
      184,  211,  214,  211,  216,  216,  216,  216,  265,  265,
      216,  228,  228,  228,  228,  249,  246,  228,  230,  230,
      230,  230,  245,  242,  230,  233,  233,  233,  233,  233,
      233,  233,  233,  233,  234,  241,  234,  243,  243,  243,
      243,  240,  239,  243,  244,  244,  244,  244,  244,  244,
      244,  244,  238,  237,  265,  236,  234,  235,  234,  231,
      265,  229,  265,  226,  225,  230,  224,  223,  222,  265,
      219,  234,  218,  217,  215,  212,  234,  259,  259,  259,

      259,  210,  209,  259,  243,  256,  256,  256,  256,  256,
      256,  256,  256,  257,  257,  257,  257,  257,  257,  257,
      257,  205,  259,  264,  264,  264,  264,  264,  264,  264,
      264,  267,  267,  267,  267,  204,  203,  267,  268,  268,
      268,  268,  202,  201,  268,  276,  276,  276,  276,  200,
      198,  276,  196,  194,  193,  192,  267,  191,  182,  180,
      179,  178,  177,  268,  176,  175,  174,  173,  172,  171,
      276,  294,  294,  294,  294,  294,  294,  294,  294,  294,
      294,  294,  294,  295,  295,  295,  295,  295,  295,  295,
      295,  295,  295,  295,  295,  296,  296,  170,  296,  296,

      296,  296,  296,  296,  296,  296,  296,  297,  297,  168,
      167,  297,  297,  297,  297,  297,  297,  297,  297,  298,
      298,  298,  298,  298,  298,  299,  299,  299,  299,  299,
      299,  300,  166,  165,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  301,  301,  164,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  302,  163,  302,  302,  162,
      302,  303,  303,  159,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  304,  304,  158,  304,  305,  154,  305,
      306,  306,  306,  306,  307,  307,  153,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  308,  308,  144,  308,

      308,  308,  308,  308,  308,  308,  308,  308,  309,  142,
      309,  310,  310,  310,  310,  311,  137,  311,  136,  135,
      133,  128,  127,  126,  125,  124,  123,  122,  121,  120,
      119,  118,  117,  116,  115,  114,  113,  112,  108,  104,
       76,   70,   62,   61,   59,   50,   49,   48,   47,   46,
       45,   43,   42,   41,   40,   33,   30,   22,   16,   15,
       11,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,

      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
static int yy_more_flag = 0;
static int yy_more_len = 0;
#define yymore() (yy_more_flag = 1)
#define YY_MORE_ADJ yy_more_len
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "gc_cl.l"
#define INITIAL 0
#line 19 "gc_cl.l"
#include "gc_cl_scanner.h"

static gctUINT CurrentLineNo        = 0;
static gctUINT CurrentStringNo        = 0;
static gctSTRING CurrentFileName    = gcvNULL;

void
clScanComment(
    IN cloCOMPILER Compiler
    );

void
clScanSkipToEOL(
    IN cloCOMPILER Compiler
    );

#define YY_NO_UNISTD_H

/*#define YY_FATAL_ERROR(msg)    \
    clReport(0, 0, clvREPORT_FATAL_ERROR, msg)*/

#define YY_INPUT(buf, result, max_size) \
    { \
         result = clInput(max_size, buf); \
    }

#define YY_DECL \
    gctINT \
    cloCOMPILER_Scan( \
        IN cloCOMPILER Compiler, \
        OUT clsLexToken * Token \
        )

#define DUMP_SOURCE() \
    gcmVERIFY_OK(cloCOMPILER_Dump( \
                            Compiler, \
                            clvDUMP_SOURCE, \
                            "<SOURCE line=\"%d\" string=\"%d\">'%s'</SOURCE>", \
                            CurrentLineNo, \
                            CurrentStringNo, \
                            yytext))

#define DUMP_SOURCE_COMMENT_BEGIN() \
    gcmVERIFY_OK(cloCOMPILER_Dump( \
                            Compiler, \
                            clvDUMP_SOURCE, \
                            "<SOURCE_COMMENT line=\"%d\" string=\"%d\">'%s", \
                            CurrentLineNo, \
                            CurrentStringNo, \
                            yytext))

#define DUMP_SOURCE_COMMENT_END() \
    gcmVERIFY_OK(cloCOMPILER_Dump( \
                            Compiler, \
                            clvDUMP_SOURCE, \
                            "'</SOURCE_COMMENT>"))

#define DUMP_SOURCE_CHAR(ch) \
    gcmVERIFY_OK(cloCOMPILER_Dump( \
                            Compiler, \
                            clvDUMP_SOURCE, \
                            "%c", \
                            ch))


#ifdef CL_SCAN_NO_ACTION

    #define CL_SCAN_DOUBLE_MATRIX_TYPE()    T_DOUBLENXM
    #define CL_SCAN_FLOAT_MATRIX_TYPE)    T_FLOATNXM
    #define CL_SCAN_UNSIGNED_INTEGER_TYPE() T_UINT
    #define CL_SCAN_BUILTIN_DATA_TYPE()    T_BUILTIN_DATA_TYPE
    #define CL_SCAN_VIV_PACKED_DATA_TYPE()    T_VIV_PACKED_DATA_TYPE
    #define CL_SCAN_RESERVED_DATA_TYPE()    T_RESERVED_DATA_TYPE
    #define CL_SCAN_IDENTIFIER()        T_IDENTIFIER
    #define CL_SCAN_BOOLCONSTANT(value)    T_BOOLCONSTANT
    #define CL_SCAN_DEC_INTCONSTANT()    T_INTCONSTANT
    #define CL_SCAN_OCT_INTCONSTANT()    T_INTCONSTANT
    #define CL_SCAN_HEX_INTCONSTANT()    T_INTCONSTANT
    #define CL_SCAN_FLOATCONSTANT()        T_FLOATCONSTANT
    #define CL_SCAN_HEXFLOATCONSTANT()    T_FLOATCONSTANT
    #define CL_SCAN_CHARCONSTANT()        T_CHARCONSTANT
    #define CL_SCAN_STRING_LITERAL()    T_STRING_LITERAL
    #define CL_SCAN_OPERATOR(type)        (type)
    #define CL_SCAN_FIELD_SELECTION()    T_FIELD_SELECTION

#else

    #define CL_SCAN_FLOAT_MATRIX_TYPE()        \
        clScanMatrixType(Compiler, CurrentLineNo, CurrentStringNo, T_FLOATNXM, yytext, Token)
    #define CL_SCAN_DOUBLE_MATRIX_TYPE()        \
        clScanMatrixType(Compiler, CurrentLineNo, CurrentStringNo, T_DOUBLENXM, yytext, Token)
    #define CL_SCAN_UNSIGNED_INTEGER_TYPE()        \
        clScanConvToUnsignedType(Compiler, CurrentLineNo, CurrentStringNo, yytext, Token)
    #define CL_SCAN_BUILTIN_DATA_TYPE()        \
        clScanBuiltinDataType(Compiler, CurrentLineNo, CurrentStringNo, yytext, Token)
    #define CL_SCAN_VIV_PACKED_DATA_TYPE()        \
        clScanVivPackedDataType(Compiler, CurrentLineNo, CurrentStringNo, yytext, Token)
    #define CL_SCAN_RESERVED_DATA_TYPE()        \
        clScanReservedDataType(Compiler, CurrentLineNo, CurrentStringNo, yytext, Token)
    #define CL_SCAN_IDENTIFIER()        \
        clScanIdentifier(Compiler, CurrentLineNo, CurrentStringNo, yytext, Token)

    #define CL_SCAN_BOOLCONSTANT(value)    \
        clScanBoolConstant(Compiler, CurrentLineNo, CurrentStringNo, value, Token)

    #define CL_SCAN_DEC_INTCONSTANT()    \
        clScanDecIntConstant(Compiler, CurrentLineNo, CurrentStringNo, yytext, Token)

    #define CL_SCAN_OCT_INTCONSTANT()    \
        clScanOctIntConstant(Compiler, CurrentLineNo, CurrentStringNo, yytext, Token)

    #define CL_SCAN_HEX_INTCONSTANT()    \
        clScanHexIntConstant(Compiler, CurrentLineNo, CurrentStringNo, yytext, Token)

    #define CL_SCAN_FLOATCONSTANT()        \
        clScanFloatConstant(Compiler, CurrentLineNo, CurrentStringNo, yytext, Token)

    #define CL_SCAN_HEXFLOATCONSTANT()        \
        clScanHexFloatConstant(Compiler, CurrentLineNo, CurrentStringNo, yytext, Token)

    #define CL_SCAN_CHARCONSTANT()        \
        clScanCharConstant(Compiler, CurrentLineNo, CurrentStringNo, yytext, Token)

    #define CL_SCAN_STRING_LITERAL()        \
        clScanStringLiteral(Compiler, CurrentLineNo, CurrentStringNo, yytext, Token)

    #define CL_SCAN_OPERATOR(type)        \
        clScanOperator(Compiler, CurrentLineNo, CurrentStringNo, yytext, type, Token)

    #define CL_SCAN_FIELD_SELECTION()    \
        clScanFieldSelection(Compiler, CurrentLineNo, CurrentStringNo, yytext, Token)

#endif /* CL_SCAN_NO_ACTION */

#define ECHO        do { /* Do nothing */ } while (gcvFALSE)
#define YY_NEVER_INTERACTIVE 1
/*
%option nounput
*/
#define START_OF_DIRECTIVE 1

#define SCAN_FIELD_SELECTION 2

#define SCAN_DIRECTIVE_LINE_NO 3

#define SCAN_DIRECTIVE_FILE_NAME 4

#line 819 "gc_cl_scanner.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
    if ( yy_current_buffer->yy_is_interactive ) \
        { \
        int c = '*', n; \
        for ( n = 0; n < max_size && \
                 (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
            buf[n] = (char) c; \
        if ( c == '\n' ) \
            buf[n++] = (char) c; \
        if ( c == EOF && ferror( yyin ) ) \
            YY_FATAL_ERROR( "input in flex scanner failed" ); \
        result = n; \
        } \
    else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
          && ferror( yyin ) ) \
        YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
    if ( yyleng > 0 ) \
        yy_current_buffer->yy_at_bol = \
                (yytext[yyleng - 1] == '\n'); \
    YY_USER_ACTION

YY_DECL
    {
    register yy_state_type yy_current_state;
    register char *yy_cp = NULL, *yy_bp = NULL;
    register int yy_act;

#line 213 "gc_cl.l"


#line 976 "gc_cl_scanner.c"

    if ( yy_init )
        {
        yy_init = 0;

#ifdef YY_USER_INIT
        YY_USER_INIT;
#endif

        if ( ! yy_start )
            yy_start = 1;    /* first start state */

        if ( ! yyin )
            yyin = stdin;

        if ( ! yyout )
            yyout = stdout;

        if ( ! yy_current_buffer )
            yy_current_buffer =
                yy_create_buffer( yyin, YY_BUF_SIZE );

        yy_load_buffer_state();
        }

    while ( 1 )        /* loops until end-of-file is reached */
        {
        yy_more_len = 0;
        if ( yy_more_flag )
            {
            yy_more_len = yy_c_buf_p - yytext_ptr;
            yy_more_flag = 0;
            }
        yy_cp = yy_c_buf_p;

        /* Support of yytext. */
        *yy_cp = yy_hold_char;

        /* yy_bp points to the position in yy_ch_buf of the start of
         * the current run.
         */
        yy_bp = yy_cp;

        yy_current_state = yy_start;
        yy_current_state += YY_AT_BOL();
yy_match:
        do
            {
            register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
            if ( yy_accept[yy_current_state] )
                {
                yy_last_accepting_state = yy_current_state;
                yy_last_accepting_cpos = yy_cp;
                }
            while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
                {
                yy_current_state = (int) yy_def[yy_current_state];
                if ( yy_current_state >= 294 )
                    yy_c = yy_meta[(unsigned int) yy_c];
                }
            yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
            ++yy_cp;
            }
        while ( yy_base[yy_current_state] != 762 );

yy_find_action:
        yy_act = yy_accept[yy_current_state];
        if ( yy_act == 0 )
            { /* have to back up */
            yy_cp = yy_last_accepting_cpos;
            yy_current_state = yy_last_accepting_state;
            yy_act = yy_accept[yy_current_state];
            }

        YY_DO_BEFORE_ACTION;


do_action:    /* This label is used only to access EOF actions. */


        switch ( yy_act )
    { /* beginning of action switch */
            case 0: /* must back up */
            /* undo the effects of YY_DO_BEFORE_ACTION */
            *yy_cp = yy_hold_char;
            yy_cp = yy_last_accepting_cpos;
            yy_current_state = yy_last_accepting_state;
            goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 215 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_BOOLCONSTANT(gcvTRUE); }
    YY_BREAK
case 2:
YY_RULE_SETUP
#line 216 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_BOOLCONSTANT(gcvFALSE); }
    YY_BREAK
case 3:
YY_RULE_SETUP
#line 218 "gc_cl.l"
{ DUMP_SOURCE();
                            return CL_SCAN_UNSIGNED_INTEGER_TYPE(); }
    YY_BREAK
case 4:
YY_RULE_SETUP
#line 220 "gc_cl.l"
{ DUMP_SOURCE();
                            return CL_SCAN_UNSIGNED_INTEGER_TYPE(); }
    YY_BREAK
case 5:
YY_RULE_SETUP
#line 222 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_FLOAT_MATRIX_TYPE(); }
    YY_BREAK
case 6:
YY_RULE_SETUP
#line 223 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_DOUBLE_MATRIX_TYPE(); }
    YY_BREAK
case 7:
YY_RULE_SETUP
#line 224 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_BUILTIN_DATA_TYPE(); }
    YY_BREAK
case 8:
YY_RULE_SETUP
#line 225 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_VIV_PACKED_DATA_TYPE(); }
    YY_BREAK
case 9:
YY_RULE_SETUP
#line 226 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_RESERVED_DATA_TYPE(); }
    YY_BREAK
case 10:
YY_RULE_SETUP
#line 227 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_IDENTIFIER(); }
    YY_BREAK
case 11:
YY_RULE_SETUP
#line 229 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_DEC_INTCONSTANT(); }
    YY_BREAK
case 12:
YY_RULE_SETUP
#line 230 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OCT_INTCONSTANT(); }
    YY_BREAK
case 13:
YY_RULE_SETUP
#line 231 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_HEX_INTCONSTANT(); }
    YY_BREAK
case 14:
YY_RULE_SETUP
#line 233 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_FLOATCONSTANT(); }
    YY_BREAK
case 15:
YY_RULE_SETUP
#line 234 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_HEXFLOATCONSTANT(); }
    YY_BREAK
case 16:
YY_RULE_SETUP
#line 236 "gc_cl.l"
{
                          /*check if char before closing quote is a '\' */
                          if(yytext[yyleng - 2] == '\\') {
                             yyless(yyleng - 1); /* return last quote ' */
                             yymore();
                          }
                          else {
                            DUMP_SOURCE(); return CL_SCAN_CHARCONSTANT();
                          }
                        }
    YY_BREAK
case 17:
YY_RULE_SETUP
#line 247 "gc_cl.l"
{
                          /*check if char before closing quote is a '\' */
                          if(yytext[yyleng - 2] == '\\') {
                             yyless(yyleng - 1); /* return last quote " */
                             yymore();
                          }
                          else {
                            DUMP_SOURCE(); return CL_SCAN_STRING_LITERAL();
                          }
                        }
    YY_BREAK
case 18:
YY_RULE_SETUP
#line 258 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR(T_LSHIFT_OP); }
    YY_BREAK
case 19:
YY_RULE_SETUP
#line 259 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR(T_RSHIFT_OP); }
    YY_BREAK
case 20:
YY_RULE_SETUP
#line 260 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR(T_INC_OP); }
    YY_BREAK
case 21:
YY_RULE_SETUP
#line 261 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR(T_DEC_OP); }
    YY_BREAK
case 22:
YY_RULE_SETUP
#line 262 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR(T_LE_OP); }
    YY_BREAK
case 23:
YY_RULE_SETUP
#line 263 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR(T_GE_OP); }
    YY_BREAK
case 24:
YY_RULE_SETUP
#line 264 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR(T_EQ_OP); }
    YY_BREAK
case 25:
YY_RULE_SETUP
#line 265 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR(T_NE_OP); }
    YY_BREAK
case 26:
YY_RULE_SETUP
#line 266 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR(T_AND_OP); }
    YY_BREAK
case 27:
YY_RULE_SETUP
#line 267 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR(T_OR_OP); }
    YY_BREAK
case 28:
YY_RULE_SETUP
#line 268 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR(T_XOR_OP); }
    YY_BREAK
case 29:
YY_RULE_SETUP
#line 269 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR(T_MUL_ASSIGN); }
    YY_BREAK
case 30:
YY_RULE_SETUP
#line 270 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR(T_DIV_ASSIGN); }
    YY_BREAK
case 31:
YY_RULE_SETUP
#line 271 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR(T_ADD_ASSIGN); }
    YY_BREAK
case 32:
YY_RULE_SETUP
#line 272 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR(T_MOD_ASSIGN); }
    YY_BREAK
case 33:
YY_RULE_SETUP
#line 273 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR(T_LEFT_ASSIGN); }
    YY_BREAK
case 34:
YY_RULE_SETUP
#line 274 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR(T_RIGHT_ASSIGN); }
    YY_BREAK
case 35:
YY_RULE_SETUP
#line 275 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR(T_AND_ASSIGN); }
    YY_BREAK
case 36:
YY_RULE_SETUP
#line 276 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR(T_XOR_ASSIGN); }
    YY_BREAK
case 37:
YY_RULE_SETUP
#line 277 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR(T_OR_ASSIGN); }
    YY_BREAK
case 38:
YY_RULE_SETUP
#line 278 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR(T_SUB_ASSIGN); }
    YY_BREAK
case 39:
YY_RULE_SETUP
#line 280 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR('('); }
    YY_BREAK
case 40:
YY_RULE_SETUP
#line 281 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR(')'); }
    YY_BREAK
case 41:
YY_RULE_SETUP
#line 282 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR('['); }
    YY_BREAK
case 42:
YY_RULE_SETUP
#line 283 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR('['); }
    YY_BREAK
case 43:
YY_RULE_SETUP
#line 284 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR(']'); }
    YY_BREAK
case 44:
YY_RULE_SETUP
#line 285 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR(']'); }
    YY_BREAK
case 45:
YY_RULE_SETUP
#line 286 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR('{'); }
    YY_BREAK
case 46:
YY_RULE_SETUP
#line 287 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR('{'); }
    YY_BREAK
case 47:
YY_RULE_SETUP
#line 288 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR('}'); }
    YY_BREAK
case 48:
YY_RULE_SETUP
#line 289 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR('}'); }
    YY_BREAK
case 49:
YY_RULE_SETUP
#line 290 "gc_cl.l"
{ BEGIN(SCAN_FIELD_SELECTION);
                            DUMP_SOURCE(); return CL_SCAN_OPERATOR('.'); }
    YY_BREAK
case 50:
YY_RULE_SETUP
#line 292 "gc_cl.l"
{ BEGIN(SCAN_FIELD_SELECTION);
                          DUMP_SOURCE(); return CL_SCAN_OPERATOR(T_STRUCT_UNION_PTR); }
    YY_BREAK
case 51:
YY_RULE_SETUP
#line 294 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR(','); }
    YY_BREAK
case 52:
YY_RULE_SETUP
#line 295 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR(':'); }
    YY_BREAK
case 53:
YY_RULE_SETUP
#line 296 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR('='); }
    YY_BREAK
case 54:
YY_RULE_SETUP
#line 297 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR(';'); }
    YY_BREAK
case 55:
YY_RULE_SETUP
#line 298 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR('!'); }
    YY_BREAK
case 56:
YY_RULE_SETUP
#line 299 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR('-'); }
    YY_BREAK
case 57:
YY_RULE_SETUP
#line 300 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR('~'); }
    YY_BREAK
case 58:
YY_RULE_SETUP
#line 301 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR('+'); }
    YY_BREAK
case 59:
YY_RULE_SETUP
#line 302 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR('*'); }
    YY_BREAK
case 60:
YY_RULE_SETUP
#line 303 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR('/'); }
    YY_BREAK
case 61:
YY_RULE_SETUP
#line 304 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR('%'); }
    YY_BREAK
case 62:
YY_RULE_SETUP
#line 305 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR('<'); }
    YY_BREAK
case 63:
YY_RULE_SETUP
#line 306 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR('>'); }
    YY_BREAK
case 64:
YY_RULE_SETUP
#line 307 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR('|'); }
    YY_BREAK
case 65:
YY_RULE_SETUP
#line 308 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR('^'); }
    YY_BREAK
case 66:
YY_RULE_SETUP
#line 309 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR('&'); }
    YY_BREAK
case 67:
YY_RULE_SETUP
#line 310 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR('?'); }
    YY_BREAK
case 68:
YY_RULE_SETUP
#line 311 "gc_cl.l"
{ DUMP_SOURCE(); return CL_SCAN_OPERATOR(T_INITIALIZER_END); }
    YY_BREAK
case 69:
YY_RULE_SETUP
#line 313 "gc_cl.l"
{ DUMP_SOURCE(); BEGIN(START_OF_DIRECTIVE); }
    YY_BREAK
case 70:
YY_RULE_SETUP
#line 315 "gc_cl.l"
{ DUMP_SOURCE(); BEGIN(START_OF_DIRECTIVE); }
    YY_BREAK
case 71:
YY_RULE_SETUP
#line 317 "gc_cl.l"
{ BEGIN(INITIAL);
                          DUMP_SOURCE(); return CL_SCAN_FIELD_SELECTION(); }
    YY_BREAK
case 72:
YY_RULE_SETUP
#line 321 "gc_cl.l"
{ DUMP_SOURCE_COMMENT_BEGIN(); clScanComment(Compiler); }
    YY_BREAK
case 73:
YY_RULE_SETUP
#line 323 "gc_cl.l"
{ gctINT lineNo;
                              DUMP_SOURCE();
                             gcoOS_StrToInt(yytext, &lineNo);
                          cloCOMPILER_SetCurrentLineNo(Compiler, lineNo - 1);
                              BEGIN(SCAN_DIRECTIVE_FILE_NAME); }
    YY_BREAK
case 74:
YY_RULE_SETUP
#line 328 "gc_cl.l"
{ DUMP_SOURCE();
                              cloCOMPILER_SetCurrentFileName(Compiler, yytext);
                                                  clScanSkipToEOL(Compiler);
                                                  BEGIN(INITIAL); }
    YY_BREAK
case 75:
YY_RULE_SETUP
#line 332 "gc_cl.l"
{ DUMP_SOURCE();
                              BEGIN(SCAN_DIRECTIVE_LINE_NO);}
    YY_BREAK
case 76:
YY_RULE_SETUP
#line 335 "gc_cl.l"
{ DUMP_SOURCE();
                                                  clScanSkipToEOL(Compiler);
                          BEGIN(INITIAL);    }
    YY_BREAK
case 77:
YY_RULE_SETUP
#line 339 "gc_cl.l"
{ DUMP_SOURCE(); BEGIN(INITIAL);}
    YY_BREAK
case 78:
YY_RULE_SETUP
#line 341 "gc_cl.l"
{ DUMP_SOURCE(); /* Ignore */ }
    YY_BREAK
case 79:
YY_RULE_SETUP
#line 343 "gc_cl.l"
{ DUMP_SOURCE(); /* Ignore */ }
    YY_BREAK
case 80:
YY_RULE_SETUP
#line 345 "gc_cl.l"
{ DUMP_SOURCE();
                                  cloCOMPILER_Report(
                                        Compiler,
                                        CurrentLineNo,
                                        CurrentStringNo,
                                        clvREPORT_ERROR,
                                        "unexpected character: '%s'", yytext); }
    YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(START_OF_DIRECTIVE):
case YY_STATE_EOF(SCAN_FIELD_SELECTION):
case YY_STATE_EOF(SCAN_DIRECTIVE_LINE_NO):
case YY_STATE_EOF(SCAN_DIRECTIVE_FILE_NAME):
#line 353 "gc_cl.l"
{ yy_delete_buffer(YY_CURRENT_BUFFER); yyterminate(); }
    YY_BREAK
case 81:
YY_RULE_SETUP
#line 355 "gc_cl.l"
ECHO;
    YY_BREAK
#line 1518 "gc_cl_scanner.c"

    case YY_END_OF_BUFFER:
        {
        /* Amount of text matched not including the EOB char. */
        int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

        /* Undo the effects of YY_DO_BEFORE_ACTION. */
        *yy_cp = yy_hold_char;
        YY_RESTORE_YY_MORE_OFFSET

        if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
            {
            /* We're scanning a new file or input source.  It's
             * possible that this happened because the user
             * just pointed yyin at a new source and called
             * yylex().  If so, then we have to assure
             * consistency between yy_current_buffer and our
             * globals.  Here is the right place to do so, because
             * this is the first action (other than possibly a
             * back-up) that will match for the new input source.
             */
            yy_n_chars = yy_current_buffer->yy_n_chars;
            yy_current_buffer->yy_input_file = yyin;
            yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
            }

        /* Note that here we test for yy_c_buf_p "<=" to the position
         * of the first EOB in the buffer, since yy_c_buf_p will
         * already have been incremented past the NUL character
         * (since all states make transitions on EOB to the
         * end-of-buffer state).  Contrast this with the test
         * in input().
         */
        if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
            { /* This was really a NUL. */
            yy_state_type yy_next_state;

            yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

            yy_current_state = yy_get_previous_state();

            /* Okay, we're now positioned to make the NUL
             * transition.  We couldn't have
             * yy_get_previous_state() go ahead and do it
             * for us because it doesn't know how to deal
             * with the possibility of jamming (and we don't
             * want to build jamming into it because then it
             * will run more slowly).
             */

            yy_next_state = yy_try_NUL_trans( yy_current_state );

            yy_bp = yytext_ptr + YY_MORE_ADJ;

            if ( yy_next_state )
                {
                /* Consume the NUL. */
                yy_cp = ++yy_c_buf_p;
                yy_current_state = yy_next_state;
                goto yy_match;
                }

            else
                {
                yy_cp = yy_c_buf_p;
                goto yy_find_action;
                }
            }

        else switch ( yy_get_next_buffer() )
            {
            case EOB_ACT_END_OF_FILE:
                {
                yy_did_buffer_switch_on_eof = 0;

                if ( yywrap() )
                    {
                    /* Note: because we've taken care in
                     * yy_get_next_buffer() to have set up
                     * yytext, we can now set up
                     * yy_c_buf_p so that if some total
                     * hoser (like flex itself) wants to
                     * call the scanner after we return the
                     * YY_NULL, it'll still work - another
                     * YY_NULL will get returned.
                     */
                    yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

                    yy_act = YY_STATE_EOF(YY_START);
                    goto do_action;
                    }

                else
                    {
                    if ( ! yy_did_buffer_switch_on_eof )
                        YY_NEW_FILE;
                    }
                break;
                }

            case EOB_ACT_CONTINUE_SCAN:
                yy_c_buf_p =
                    yytext_ptr + yy_amount_of_matched_text;

                yy_current_state = yy_get_previous_state();

                yy_cp = yy_c_buf_p;
                yy_bp = yytext_ptr + YY_MORE_ADJ;
                goto yy_match;

            case EOB_ACT_LAST_MATCH:
                yy_c_buf_p =
                &yy_current_buffer->yy_ch_buf[yy_n_chars];

                yy_current_state = yy_get_previous_state();

                yy_cp = yy_c_buf_p;
                yy_bp = yytext_ptr + YY_MORE_ADJ;
                goto yy_find_action;
            }
        break;
        }

    default:
        YY_FATAL_ERROR(
            "fatal flex scanner internal error--no action found" );
    } /* end of action switch */
        } /* end of scanning one token */
    } /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *    EOB_ACT_LAST_MATCH -
 *    EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *    EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
    {
    register char *dest = yy_current_buffer->yy_ch_buf;
    register char *source = yytext_ptr;
    register int number_to_move, i;
    int ret_val;

    if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
        YY_FATAL_ERROR(
        "fatal flex scanner internal error--end of buffer missed" );

    if ( yy_current_buffer->yy_fill_buffer == 0 )
        { /* Don't try to fill the buffer, so this is an EOF. */
        if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
            {
            /* We matched a single character, the EOB, so
             * treat this as a final EOF.
             */
            return EOB_ACT_END_OF_FILE;
            }

        else
            {
            /* We matched some text prior to the EOB, first
             * process it.
             */
            return EOB_ACT_LAST_MATCH;
            }
        }

    /* Try to read more data. */

    /* First move last chars to start of buffer. */
    number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

    for ( i = 0; i < number_to_move; ++i )
        *(dest++) = *(source++);

    if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
        /* don't do the read, it's not guaranteed to return an EOF,
         * just force an EOF
         */
        yy_current_buffer->yy_n_chars = yy_n_chars = 0;

    else
        {
        int num_to_read =
            yy_current_buffer->yy_buf_size - number_to_move - 1;

        while ( num_to_read <= 0 )
            { /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
            YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

            /* just a shorter name for the current buffer */
            YY_BUFFER_STATE b = yy_current_buffer;

            int yy_c_buf_p_offset =
                (int) (yy_c_buf_p - b->yy_ch_buf);

            if ( b->yy_is_our_buffer )
                {
                int new_size = b->yy_buf_size * 2;

                if ( new_size <= 0 )
                    b->yy_buf_size += b->yy_buf_size / 8;
                else
                    b->yy_buf_size *= 2;

                b->yy_ch_buf = (char *)
                    /* Include room in for 2 EOB chars. */
                    yy_flex_realloc( (void *) b->yy_ch_buf,
                             b->yy_buf_size + 2 );
                }
            else
                /* Can't grow it, we don't own it. */
                b->yy_ch_buf = 0;

            if ( ! b->yy_ch_buf )
                YY_FATAL_ERROR(
                "fatal error - scanner input buffer overflow" );

            yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

            num_to_read = yy_current_buffer->yy_buf_size -
                        number_to_move - 1;
#endif
            }

        if ( num_to_read > YY_READ_BUF_SIZE )
            num_to_read = YY_READ_BUF_SIZE;

        /* Read in more data. */
        YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
            yy_n_chars, num_to_read );

        yy_current_buffer->yy_n_chars = yy_n_chars;
        }

    if ( yy_n_chars == 0 )
        {
        if ( number_to_move == YY_MORE_ADJ )
            {
            ret_val = EOB_ACT_END_OF_FILE;
            yyrestart( yyin );
            }

        else
            {
            ret_val = EOB_ACT_LAST_MATCH;
            yy_current_buffer->yy_buffer_status =
                YY_BUFFER_EOF_PENDING;
            }
        }

    else
        ret_val = EOB_ACT_CONTINUE_SCAN;

    yy_n_chars += number_to_move;
    yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
    yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

    yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

    return ret_val;
    }


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
    {
    register yy_state_type yy_current_state;
    register char *yy_cp;

    yy_current_state = yy_start;
    yy_current_state += YY_AT_BOL();

    for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
        {
        register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
        if ( yy_accept[yy_current_state] )
            {
            yy_last_accepting_state = yy_current_state;
            yy_last_accepting_cpos = yy_cp;
            }
        while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
            {
            yy_current_state = (int) yy_def[yy_current_state];
            if ( yy_current_state >= 294 )
                yy_c = yy_meta[(unsigned int) yy_c];
            }
        yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
        }

    return yy_current_state;
    }


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *    next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
    {
    register int yy_is_jam;
    register char *yy_cp = yy_c_buf_p;

    register YY_CHAR yy_c = 1;
    if ( yy_accept[yy_current_state] )
        {
        yy_last_accepting_state = yy_current_state;
        yy_last_accepting_cpos = yy_cp;
        }
    while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
        {
        yy_current_state = (int) yy_def[yy_current_state];
        if ( yy_current_state >= 294 )
            yy_c = yy_meta[(unsigned int) yy_c];
        }
    yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
    yy_is_jam = (yy_current_state == 293);

    return yy_is_jam ? 0 : yy_current_state;
    }


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
    {
    register char *yy_cp = yy_c_buf_p;

    /* undo effects of setting up yytext */
    *yy_cp = yy_hold_char;

    if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
        { /* need to shift things up to make room */
        /* +2 for EOB chars. */
        register int number_to_move = yy_n_chars + 2;
        register char *dest = &yy_current_buffer->yy_ch_buf[
                    yy_current_buffer->yy_buf_size + 2];
        register char *source =
                &yy_current_buffer->yy_ch_buf[number_to_move];

        while ( source > yy_current_buffer->yy_ch_buf )
            *--dest = *--source;

        yy_cp += (int) (dest - source);
        yy_bp += (int) (dest - source);
        yy_current_buffer->yy_n_chars =
            yy_n_chars = yy_current_buffer->yy_buf_size;

        if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
            YY_FATAL_ERROR( "flex scanner push-back overflow" );
        }

    *--yy_cp = (char) c;


    yytext_ptr = yy_bp;
    yy_hold_char = *yy_cp;
    yy_c_buf_p = yy_cp;
    }
#endif    /* ifndef YY_NO_UNPUT */


#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
    {
    int c;

    *yy_c_buf_p = yy_hold_char;

    if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
        {
        /* yy_c_buf_p now points to the character we want to return.
         * If this occurs *before* the EOB characters, then it's a
         * valid NUL; if not, then we've hit the end of the buffer.
         */
        if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
            /* This was really a NUL. */
            *yy_c_buf_p = '\0';

        else
            { /* need more input */
            int offset = yy_c_buf_p - yytext_ptr;
            ++yy_c_buf_p;

            switch ( yy_get_next_buffer() )
                {
                case EOB_ACT_LAST_MATCH:
                    /* This happens because yy_g_n_b()
                     * sees that we've accumulated a
                     * token and flags that we need to
                     * try matching the token before
                     * proceeding.  But for input(),
                     * there's no matching to consider.
                     * So convert the EOB_ACT_LAST_MATCH
                     * to EOB_ACT_END_OF_FILE.
                     */

                    /* Reset buffer status. */
                    yyrestart( yyin );

                    /* fall through */

                case EOB_ACT_END_OF_FILE:
                    {
                    if ( yywrap() )
                        return EOF;

                    if ( ! yy_did_buffer_switch_on_eof )
                        YY_NEW_FILE;
#ifdef __cplusplus
                    return yyinput();
#else
                    return input();
#endif
                    }

                case EOB_ACT_CONTINUE_SCAN:
                    yy_c_buf_p = yytext_ptr + offset;
                    break;
                }
            }
        }

    c = *(unsigned char *) yy_c_buf_p;    /* cast for 8-bit char's */
    *yy_c_buf_p = '\0';    /* preserve yytext */
    yy_hold_char = *++yy_c_buf_p;

    yy_current_buffer->yy_at_bol = (c == '\n');

    return c;
    }
#endif /* YY_NO_INPUT */

#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
    {
    if ( ! yy_current_buffer )
        yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

    yy_init_buffer( yy_current_buffer, input_file );
    yy_load_buffer_state();
    }


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
    {
    if ( yy_current_buffer == new_buffer )
        return;

    if ( yy_current_buffer )
        {
        /* Flush out information for old buffer. */
        *yy_c_buf_p = yy_hold_char;
        yy_current_buffer->yy_buf_pos = yy_c_buf_p;
        yy_current_buffer->yy_n_chars = yy_n_chars;
        }

    yy_current_buffer = new_buffer;
    yy_load_buffer_state();

    /* We don't actually know whether we did this switch during
     * EOF (yywrap()) processing, but the only time this flag
     * is looked at is after yywrap() is called, so it's safe
     * to go ahead and always set it.
     */
    yy_did_buffer_switch_on_eof = 1;
    }


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
    {
    yy_n_chars = yy_current_buffer->yy_n_chars;
    yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
    yyin = yy_current_buffer->yy_input_file;
    yy_hold_char = *yy_c_buf_p;
    }


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
    {
    YY_BUFFER_STATE b;

    b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
    if ( ! b )
        YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

    b->yy_buf_size = size;

    /* yy_ch_buf has to be 2 characters longer than the size given because
     * we need to put in 2 end-of-buffer characters.
     */
    b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
    if ( ! b->yy_ch_buf )
        YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

    b->yy_is_our_buffer = 1;

    yy_init_buffer( b, file );

    return b;
    }


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
    {
    if ( ! b )
        return;

    if ( b == yy_current_buffer )
        yy_current_buffer = (YY_BUFFER_STATE) 0;

    if ( b->yy_is_our_buffer )
        yy_flex_free( (void *) b->yy_ch_buf );

    yy_flex_free( (void *) b );
    }



#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


    {
    yy_flush_buffer( b );

    b->yy_input_file = file;
    b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
    b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
    b->yy_is_interactive = 0;
#else
    b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
    }


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

    {
    if ( ! b )
        return;

    b->yy_n_chars = 0;

    /* We always need two end-of-buffer characters.  The first causes
     * a transition to the end-of-buffer state.  The second causes
     * a jam in that state.
     */
    b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
    b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

    b->yy_buf_pos = &b->yy_ch_buf[0];

    b->yy_at_bol = 1;
    b->yy_buffer_status = YY_BUFFER_NEW;

    if ( b == yy_current_buffer )
        yy_load_buffer_state();
    }


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
    {
    YY_BUFFER_STATE b;

    if ( size < 2 ||
         base[size-2] != YY_END_OF_BUFFER_CHAR ||
         base[size-1] != YY_END_OF_BUFFER_CHAR )
        /* They forgot to leave room for the EOB's. */
        return 0;

    b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
    if ( ! b )
        YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

    b->yy_buf_size = size - 2;    /* "- 2" to take care of EOB's */
    b->yy_buf_pos = b->yy_ch_buf = base;
    b->yy_is_our_buffer = 0;
    b->yy_input_file = 0;
    b->yy_n_chars = b->yy_buf_size;
    b->yy_is_interactive = 0;
    b->yy_at_bol = 1;
    b->yy_fill_buffer = 0;
    b->yy_buffer_status = YY_BUFFER_NEW;

    yy_switch_to_buffer( b );

    return b;
    }
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
    {
    int len;
    for ( len = 0; yy_str[len]; ++len )
        ;

    return yy_scan_bytes( yy_str, len );
    }
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
    {
    YY_BUFFER_STATE b;
    char *buf;
    yy_size_t n;
    int i;

    /* Get memory for full buffer, including space for trailing EOB's. */
    n = len + 2;
    buf = (char *) yy_flex_alloc( n );
    if ( ! buf )
        YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

    for ( i = 0; i < len; ++i )
        buf[i] = bytes[i];

    buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

    b = yy_scan_buffer( buf, n );
    if ( ! b )
        YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

    /* It's okay to grow etc. this buffer, and we should throw it
     * away when we're done.
     */
    b->yy_is_our_buffer = 1;

    return b;
    }
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
    {
    if ( yy_start_stack_ptr >= yy_start_stack_depth )
        {
        yy_size_t new_size;

        yy_start_stack_depth += YY_START_STACK_INCR;
        new_size = yy_start_stack_depth * sizeof( int );

        if ( ! yy_start_stack )
            yy_start_stack = (int *) yy_flex_alloc( new_size );

        else
            yy_start_stack = (int *) yy_flex_realloc(
                    (void *) yy_start_stack, new_size );

        if ( ! yy_start_stack )
            YY_FATAL_ERROR(
            "out of memory expanding start-condition stack" );
        }

    yy_start_stack[yy_start_stack_ptr++] = YY_START;

    BEGIN(new_state);
    }
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
    {
    if ( --yy_start_stack_ptr < 0 )
        YY_FATAL_ERROR( "start-condition stack underflow" );

    BEGIN(yy_start_stack[yy_start_stack_ptr]);
    }
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
    {
    return yy_start_stack[yy_start_stack_ptr - 1];
    }
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
    {
    clReport(0, 0, clvREPORT_FATAL_ERROR, (char *)msg);
    }



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
    do \
        { \
        /* Undo effects of setting up yytext. */ \
        yytext[yyleng] = yy_hold_char; \
        yy_c_buf_p = yytext + n; \
        yy_hold_char = *yy_c_buf_p; \
        *yy_c_buf_p = '\0'; \
        yyleng = n; \
        } \
    while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
    {
    register int i;
    for ( i = 0; i < n; ++i )
        s1[i] = s2[i];
    }
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
    {
    register int n;
    for ( n = 0; s[n]; ++n )
        ;

    return n;
    }
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
    {
    return (void *) clMalloc( size );
    }

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
    {
    /* The cast to (char *) in the following accommodates both
     * implementations that use char* generic pointers, and those
     * that use void* generic pointers.  It works with the latter
     * because both ANSI C and C++ allow castless assignment from
     * any pointer type to void*, and deal with argument conversions
     * as though doing an assignment.
     */
    return (void *) clRealloc( (char *) ptr, size );
    }

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
    {
    clFree( ptr );
    }

#if YY_MAIN
int main()
    {
    yylex();
    return 0;
    }
#endif
#line 355 "gc_cl.l"


void
clScanComment(IN cloCOMPILER Compiler)
{
    gctINT ch;

    while (gcvTRUE) {
        while ((ch = input()) != '*' && ch != EOF) DUMP_SOURCE_CHAR(ch);

        if (ch == EOF) {
            cloCOMPILER_Report(Compiler,
                    CurrentLineNo,
                    CurrentStringNo,
                    clvREPORT_ERROR,
                    "invalid comment: unexpected end of file");
            break;
        }
        DUMP_SOURCE_CHAR(ch);
        while ((ch = input()) == '*') DUMP_SOURCE_CHAR(ch);
        if (ch == EOF) {
            cloCOMPILER_Report(Compiler,
                    CurrentLineNo,
                    CurrentStringNo,
                    clvREPORT_ERROR,
                    "invalid comment: unexpected end of file");
            break;
        }
        else if (ch == '/') {
            DUMP_SOURCE_CHAR(ch);
            break;
        }
        else {
            DUMP_SOURCE_CHAR(ch);
        }
    }
    DUMP_SOURCE_COMMENT_END();
}

void
clScanSkipToEOL(IN cloCOMPILER Compiler)
{
    gctINT ch;
    while ((ch = input()) != '\n' && ch != EOF) DUMP_SOURCE_CHAR(ch);
    return;
}

gceSTATUS
clScanSetCurrentFileName(
IN cloCOMPILER Compiler,
IN gctSTRING FileName
)
{
   /* Verify the arguments. */
   clmVERIFY_OBJECT(Compiler, clvOBJ_COMPILER);
   CurrentFileName = FileName;
   return gcvSTATUS_OK;
}

gceSTATUS
clScanSetCurrentLineNo(
IN cloCOMPILER Compiler,
IN gctUINT LineNo
)
{
    /* Verify the arguments. */
    clmVERIFY_OBJECT(Compiler, clvOBJ_COMPILER);
    CurrentLineNo = LineNo;
    return gcvSTATUS_OK;
}

gceSTATUS
clScanSetCurrentStringNo(
IN cloCOMPILER Compiler,
IN gctUINT StringNo
)
{
    /* Verify the arguments. */
    clmVERIFY_OBJECT(Compiler, clvOBJ_COMPILER);
    CurrentStringNo    = StringNo;
    return gcvSTATUS_OK;
}

gceSTATUS
clScanLookAhead(
IN cloCOMPILER Compiler,
IN gctINT LookAheadChr
)
{
  gctINT ch;
  while ((ch = input()) != EOF) {
     if((ch ==  ' ') || (ch == '\t')) { /* skip white spaces */
          DUMP_SOURCE_CHAR(ch);
          continue;
     }
     unput(ch);
     if(ch == LookAheadChr) { /*found the lookahead*/
        return gcvSTATUS_OK;
     }
     else break;
  }
  if(yyleng == 1 && yytext[0] == LookAheadChr) {
     return gcvSTATUS_OK;
  }
  return gcvSTATUS_NOT_FOUND;
}

gceSTATUS
clScanLookAheadWithSkip(
IN cloCOMPILER Compiler,
IN gctINT LookAheadChr,
IN gctINT SkipChar
)
{
  gctINT ch;
  gctINT skipCount = 0;
  gctINT i;

  while ((ch = input()) != EOF) {
     if((ch ==  ' ') || (ch == '\t')) { /* skip white spaces */
          DUMP_SOURCE_CHAR(ch);
          continue;
     }
     else if(ch == SkipChar) { /* Is skip character */
          skipCount++;
          continue;
     }

     unput(ch);

     /*put back the skipped chararacters*/
     for(i = 0; i < skipCount; i++)
     {
        unput(SkipChar);
     }
     if(ch == LookAheadChr) { /*found the lookahead*/
        return gcvSTATUS_OK;
     }
     else break;
  }
  if(yyleng == 1 && yytext[0] == LookAheadChr) {
     return gcvSTATUS_OK;
  }
  return gcvSTATUS_NOT_FOUND;
}

void
clScanDeleteBuffer(
IN cloCOMPILER Compiler
)
{
   yy_delete_buffer(YY_CURRENT_BUFFER);
}

extern void
yyerror(char *msg)
{
    char *formatString = "%s at '%s'";
    char *where = yytext;
    if(yyleng <= 1 && *yytext < 0)where = "end of file";
    clReport(CurrentLineNo,
        CurrentStringNo,
        clvREPORT_ERROR,
        formatString,
        msg,
        where);

}
