##############################################################################
#
#    Copyright 2012 - 2020 Vivante Corporation, Santa Clara, California.
#    All Rights Reserved.
#
#    Permission is hereby granted, free of charge, to any person obtaining
#    a copy of this software and associated documentation files (the
#    'Software'), to deal in the Software without restriction, including
#    without limitation the rights to use, copy, modify, merge, publish,
#    distribute, sub license, and/or sell copies of the Software, and to
#    permit persons to whom the Software is furnished to do so, subject
#    to the following conditions:
#
#    The above copyright notice and this permission notice (including the
#    next paragraph) shall be included in all copies or substantial
#    portions of the Software.
#
#    THE SOFTWARE IS PROVIDED 'AS IS', WITHOUT WARRANTY OF ANY KIND,
#    EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
#    MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT.
#    IN NO EVENT SHALL VIVANTE AND/OR ITS SUPPLIERS BE LIABLE FOR ANY
#    CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
#    TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
#    SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
##############################################################################


#
# Linux build file for the DFB unit tests.
#

################################################################################
# Include common definitions.

include ../makefile.linux.def

################################################################################
# Supply additional include directories.

CFLAGS += $(INCLUDE)

################################################################################
# Supply definitions.

CFLAGS += $(CDEFS)

################################################################################
# Supply misc flags.

CFLAGS += -DDATADIR=\"data\"

################################################################################
# Describe object files.

OBJECTS :=	blit_colorkeyed.o

OBJS	:=	$(addprefix $(OBJ_DIR)/,$(OBJECTS))
OBJECTS	:=	$(OBJS)

################################################################################
# Define a shortcut for the main target.

PROGRAM		:= 1
TARGET_NAME	:= blit_colorkeyed

################################################################################
# Define the macros used in common makefile.

################################################################################
# Include the common makefile.

include $(AQROOT)/common.target

################################################################################
# Extra source code.
