##############################################################################
#
#    Copyright 2012 - 2019 Vivante Corporation, Santa Clara, California.
#    All Rights Reserved.
#
#    Permission is hereby granted, free of charge, to any person obtaining
#    a copy of this software and associated documentation files (the
#    'Software'), to deal in the Software without restriction, including
#    without limitation the rights to use, copy, modify, merge, publish,
#    distribute, sub license, and/or sell copies of the Software, and to
#    permit persons to whom the Software is furnished to do so, subject
#    to the following conditions:
#
#    The above copyright notice and this permission notice (including the
#    next paragraph) shall be included in all copies or substantial
#    portions of the Software.
#
#    THE SOFTWARE IS PROVIDED 'AS IS', WITHOUT WARRANTY OF ANY KIND,
#    EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
#    MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT.
#    IN NO EVENT SHALL VIVANTE AND/OR ITS SUPPLIERS BE LIABLE FOR ANY
#    CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
#    TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
#    SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
##############################################################################


#
# Driver part of OpenCL 1.1.
#

#############################################################################
# Include common definitions.

include $(AQROOT)/makefile.linux.def

#############################################################################
ifeq ($(gcdSTATIC_LINK),1)
  STATIC            := 1
  TARGET_NAME = libtutorial4_kernel.a
else
  DYNAMIC = 1
  TARGET_NAME = libtutorial4_kernel.so
endif


OBJECTS		= $(OBJ_DIR)/tutorial4_kernel.o \

################################################################################
# Add extra flags for object files.

INCLUDE += -I $(VIVANTE_SDK_DIR)/include
CFLAGS += $(INCLUDE)
CFLAGS += -fPIC
#LFLAGS += -Wl
################################################################################
# Add extra library path.

ifeq ($(DYNAMIC),1)
CFLAGS += -shared
LIBS += -L $(VIVANTE_SDK_DIR)/drivers
LIBS += -l OpenVX
LIBS += -l dl -l pthread -l m
endif

################################################################################
# Add extra include path.

################################################################################
# installation directory

INSTALL_DIR	:= $(SDK_DIR)/samples/ovx

################################################################################
# Include the common makefile.

include $(AQROOT)/common.target

################################################################################
################################################################################



