#!/bin/bash

pushd ..

export AQROOT=$PWD/../../../
export AQARCH=$AQROOT/arch/XAQ2

TOP_DIR=$AQROOT

KERNEL_ID=3.10.31fsl15
FIXED_ARCH_TYPE=arm
export KERNEL_DIR=/home/software/Linux/freescale/linux_3.10.31_alpha/linux-2.6

FSL_YOCTO_TOOLCHAIN=/home/software/Linux/freescale/poky/1.6
if [ ! -d "$FSL_YOCTO_TOOLCHAIN" ]; then
   FSL_YOCTO_TOOLCHAIN=/opt/poky/1.6
fi

export TOOLCHAIN=$FSL_YOCTO_TOOLCHAIN/sysroots/x86_64-pokysdk-linux/usr

export CPU_TYPE=cortex-a9
export CPU_ARCH=armv7-a

export ROOTFS=/home/software/Linux/freescale/test-internal-gui-imx6sxsabresd-20140428042617

export CFLAGS="-D__ARM_PCS_VFP --sysroot=$ROOTFS"
export LFLAGS="--sysroot=$ROOTFS"
export FPU=vfp
export FLOAT_ABI=hard

export X11_ARM_DIR=$ROOTFS/usr
export ROOTFS_USR=$ROOTFS/usr
export ROOTFS_DIR=$ROOTFS/usr
export PATH=$TOOLCHAIN/bin:$TOOLCHAIN/bin/arm-poky-linux-gnueabi:$PATH
export CROSS_COMPILE=arm-poky-linux-gnueabi-
export YOCTO_DRI_BUILD=1
export BUILD_HALTI=1
export EGL_API_DRI=1
export EGL_API_FB=0
export USE_VDK=1
export DEBUG=0
export VIVANTE_ENABLE_VG=0

export USE_DESTRUCTOR=1
export USE_LOADTIME_OPT=1
export NO_DMA_COHERENT=0
export ENABLE_ARM_L2_CACHE=1
export ENABLE_GPU_CLOCK_BY_DRIVER=1
export USE_PLATFORM_DRIVER=1
export USE_3D_VG=0
export USE_NEON=0
export ENABLE_NONPAGED_MEMORY_BUFFERABLE=1
export NONPAGED_MEMORY_BUFFERABLE=1
export USE_POWER_MANAGEMENT=1
export USE_BANK_ALIGNMENT=1
export BANK_BIT_START=13
export BANK_BIT_END=15
export BANK_CHANNEL_BIT=12

cd $TOP_DIR

make -f makefile.linux $target V_TARGET=clean || exit
make -f makefile.linux -j8 $target V_TARGET=install

cd driver/X
. ./crsfastbuild.sh
. ./crsfastbuild.sh install


cd $PWD/../../

popd

