/****************************************************************************
*
*    Copyright (c) 2005 - 2020 by Vivante Corp.  All rights reserved.
*
*    The material in this file is confidential and contains trade secrets
*    of Vivante Corporation. This is proprietary information owned by
*    Vivante Corporation. No part of this work may be disclosed,
*    reproduced, copied, transmitted, or used in any way for any purpose,
*    without the express written permission of Vivante Corporation.
*
*****************************************************************************/


#ifndef __g_imfncs_h_
#define __g_imfncs_h_
/* Vertex info function interfaces */
extern GLvoid GL_APIENTRY  __glim_Begin_Info( __GLcontext *gc, GLenum);
extern GLvoid GL_APIENTRY  __glim_End_Info(__GLcontext *gc);
extern GLvoid GL_APIENTRY  __glim_Color3b_Info(__GLcontext *gc, GLbyte, GLbyte, GLbyte);
extern GLvoid GL_APIENTRY  __glim_Color3bv_Info(__GLcontext *gc, const GLbyte *);
extern GLvoid GL_APIENTRY  __glim_Color3d_Info(__GLcontext *gc, GLdouble, GLdouble, GLdouble);
extern GLvoid GL_APIENTRY  __glim_Color3dv_Info(__GLcontext *gc, const GLdouble *);
extern GLvoid GL_APIENTRY  __glim_Color3f_Info(__GLcontext *gc, GLfloat, GLfloat, GLfloat);
extern GLvoid GL_APIENTRY  __glim_Color3fv_Info(__GLcontext *gc, const GLfloat *);
extern GLvoid GL_APIENTRY  __glim_Color3i_Info( __GLcontext *gc, GLint, GLint, GLint);
extern GLvoid GL_APIENTRY  __glim_Color3iv_Info(__GLcontext *gc, const GLint *);
extern GLvoid GL_APIENTRY  __glim_Color3s_Info(__GLcontext *gc, GLshort, GLshort, GLshort);
extern GLvoid GL_APIENTRY  __glim_Color3sv_Info(__GLcontext *gc, const GLshort *);
extern GLvoid GL_APIENTRY  __glim_Color3ub_Info(__GLcontext *gc, GLubyte, GLubyte, GLubyte);
extern GLvoid GL_APIENTRY  __glim_Color3ubv_Info(__GLcontext *gc, const GLubyte *);
extern GLvoid GL_APIENTRY  __glim_Color3ui_Info(__GLcontext *gc, GLuint, GLuint, GLuint);
extern GLvoid GL_APIENTRY  __glim_Color3uiv_Info(__GLcontext *gc, const GLuint *);
extern GLvoid GL_APIENTRY  __glim_Color3us_Info(__GLcontext *gc, GLushort, GLushort, GLushort);
extern GLvoid GL_APIENTRY  __glim_Color3usv_Info(__GLcontext *gc, const GLushort *);
extern GLvoid GL_APIENTRY  __glim_Color4b_Info(__GLcontext *gc, GLbyte, GLbyte, GLbyte, GLbyte);
extern GLvoid GL_APIENTRY  __glim_Color4bv_Info(__GLcontext *gc, const GLbyte *);
extern GLvoid GL_APIENTRY  __glim_Color4d_Info(__GLcontext *gc, GLdouble, GLdouble, GLdouble, GLdouble);
extern GLvoid GL_APIENTRY  __glim_Color4dv_Info(__GLcontext *gc, const GLdouble *);
extern GLvoid GL_APIENTRY  __glim_Color4f_Info(__GLcontext *gc, GLfloat, GLfloat, GLfloat, GLfloat);
extern GLvoid GL_APIENTRY  __glim_Color4fv_Info(__GLcontext *gc, const GLfloat *);
extern GLvoid GL_APIENTRY  __glim_Color4i_Info(__GLcontext *gc, GLint, GLint, GLint, GLint);
extern GLvoid GL_APIENTRY  __glim_Color4iv_Info(__GLcontext *gc, const GLint *);
extern GLvoid GL_APIENTRY  __glim_Color4s_Info(__GLcontext *gc, GLshort, GLshort, GLshort, GLshort);
extern GLvoid GL_APIENTRY  __glim_Color4sv_Info(__GLcontext *gc, const GLshort *);
extern GLvoid GL_APIENTRY  __glim_Color4ub_Info(__GLcontext *gc, GLubyte, GLubyte, GLubyte, GLubyte);
extern GLvoid GL_APIENTRY  __glim_Color4ubv_Info(__GLcontext *gc, const GLubyte *);
extern GLvoid GL_APIENTRY  __glim_Color4ui_Info(__GLcontext *gc, GLuint, GLuint, GLuint, GLuint);
extern GLvoid GL_APIENTRY  __glim_Color4uiv_Info(__GLcontext *gc, const GLuint *);
extern GLvoid GL_APIENTRY  __glim_Color4us_Info(__GLcontext *gc, GLushort, GLushort, GLushort, GLushort);
extern GLvoid GL_APIENTRY  __glim_Color4usv_Info(__GLcontext *gc, const GLushort *);
extern GLvoid GL_APIENTRY  __glim_Normal3b_Info(__GLcontext *gc, GLbyte, GLbyte, GLbyte);
extern GLvoid GL_APIENTRY  __glim_Normal3bv_Info(__GLcontext *gc, const GLbyte *);
extern GLvoid GL_APIENTRY  __glim_Normal3d_Info(__GLcontext *gc, GLdouble, GLdouble, GLdouble);
extern GLvoid GL_APIENTRY  __glim_Normal3dv_Info(__GLcontext *gc, const GLdouble *);
extern GLvoid GL_APIENTRY  __glim_Normal3f_Info(__GLcontext *gc, GLfloat, GLfloat, GLfloat);
extern GLvoid GL_APIENTRY  __glim_Normal3fv_Info(__GLcontext *gc, const GLfloat *);
extern GLvoid GL_APIENTRY  __glim_Normal3i_Info(__GLcontext *gc, GLint, GLint, GLint);
extern GLvoid GL_APIENTRY  __glim_Normal3iv_Info(__GLcontext *gc, const GLint *);
extern GLvoid GL_APIENTRY  __glim_Normal3s_Info(__GLcontext *gc, GLshort, GLshort, GLshort);
extern GLvoid GL_APIENTRY  __glim_Normal3sv_Info(__GLcontext *gc, const GLshort *);
extern GLvoid GL_APIENTRY  __glim_TexCoord1d_Info(__GLcontext *gc, GLdouble);
extern GLvoid GL_APIENTRY  __glim_TexCoord1dv_Info(__GLcontext *gc, const GLdouble *);
extern GLvoid GL_APIENTRY  __glim_TexCoord1f_Info(__GLcontext *gc, GLfloat);
extern GLvoid GL_APIENTRY  __glim_TexCoord1fv_Info(__GLcontext *gc, const GLfloat *);
extern GLvoid GL_APIENTRY  __glim_TexCoord1i_Info(__GLcontext *gc, GLint);
extern GLvoid GL_APIENTRY  __glim_TexCoord1iv_Info(__GLcontext *gc, const GLint *);
extern GLvoid GL_APIENTRY  __glim_TexCoord1s_Info(__GLcontext *gc, GLshort);
extern GLvoid GL_APIENTRY  __glim_TexCoord1sv_Info(__GLcontext *gc, const GLshort *);
extern GLvoid GL_APIENTRY  __glim_TexCoord2d_Info(__GLcontext *gc, GLdouble, GLdouble);
extern GLvoid GL_APIENTRY  __glim_TexCoord2dv_Info(__GLcontext *gc, const GLdouble *);
extern GLvoid GL_APIENTRY  __glim_TexCoord2f_Info(__GLcontext *gc, GLfloat, GLfloat);
extern GLvoid GL_APIENTRY  __glim_TexCoord2fv_Info(__GLcontext *gc, const GLfloat *);
extern GLvoid GL_APIENTRY  __glim_TexCoord2i_Info(__GLcontext *gc, GLint, GLint);
extern GLvoid GL_APIENTRY  __glim_TexCoord2iv_Info(__GLcontext *gc, const GLint *);
extern GLvoid GL_APIENTRY  __glim_TexCoord2s_Info(__GLcontext *gc, GLshort, GLshort);
extern GLvoid GL_APIENTRY  __glim_TexCoord2sv_Info(__GLcontext *gc, const GLshort *);
extern GLvoid GL_APIENTRY  __glim_TexCoord3d_Info(__GLcontext *gc, GLdouble, GLdouble, GLdouble);
extern GLvoid GL_APIENTRY  __glim_TexCoord3dv_Info(__GLcontext *gc, const GLdouble *);
extern GLvoid GL_APIENTRY  __glim_TexCoord3f_Info(__GLcontext *gc, GLfloat, GLfloat, GLfloat);
extern GLvoid GL_APIENTRY  __glim_TexCoord3fv_Info(__GLcontext *gc, const GLfloat *);
extern GLvoid GL_APIENTRY  __glim_TexCoord3i_Info(__GLcontext *gc, GLint, GLint, GLint);
extern GLvoid GL_APIENTRY  __glim_TexCoord3iv_Info(__GLcontext *gc, const GLint *);
extern GLvoid GL_APIENTRY  __glim_TexCoord3s_Info(__GLcontext *gc, GLshort, GLshort, GLshort);
extern GLvoid GL_APIENTRY  __glim_TexCoord3sv_Info(__GLcontext *gc, const GLshort *);
extern GLvoid GL_APIENTRY  __glim_TexCoord4d_Info(__GLcontext *gc, GLdouble, GLdouble, GLdouble, GLdouble);
extern GLvoid GL_APIENTRY  __glim_TexCoord4dv_Info(__GLcontext *gc, const GLdouble *);
extern GLvoid GL_APIENTRY  __glim_TexCoord4f_Info(__GLcontext *gc, GLfloat, GLfloat, GLfloat, GLfloat);
extern GLvoid GL_APIENTRY  __glim_TexCoord4fv_Info(__GLcontext *gc, const GLfloat *);
extern GLvoid GL_APIENTRY  __glim_TexCoord4i_Info(__GLcontext *gc, GLint, GLint, GLint, GLint);
extern GLvoid GL_APIENTRY  __glim_TexCoord4iv_Info(__GLcontext *gc, const GLint *);
extern GLvoid GL_APIENTRY  __glim_TexCoord4s_Info(__GLcontext *gc, GLshort, GLshort, GLshort, GLshort);
extern GLvoid GL_APIENTRY  __glim_TexCoord4sv_Info(__GLcontext *gc, const GLshort *);
extern GLvoid GL_APIENTRY  __glim_Vertex2d_Info(__GLcontext *gc, GLdouble, GLdouble);
extern GLvoid GL_APIENTRY  __glim_Vertex2dv_Info(__GLcontext *gc, const GLdouble *);
extern GLvoid GL_APIENTRY  __glim_Vertex2f_Info(__GLcontext *gc, GLfloat, GLfloat);
extern GLvoid GL_APIENTRY  __glim_Vertex2fv_Info(__GLcontext *gc, const GLfloat *);
extern GLvoid GL_APIENTRY  __glim_Vertex2i_Info(__GLcontext *gc, GLint, GLint);
extern GLvoid GL_APIENTRY  __glim_Vertex2iv_Info(__GLcontext *gc, const GLint *);
extern GLvoid GL_APIENTRY  __glim_Vertex2s_Info(__GLcontext *gc, GLshort, GLshort);
extern GLvoid GL_APIENTRY  __glim_Vertex2sv_Info(__GLcontext *gc, const GLshort *);
extern GLvoid GL_APIENTRY  __glim_Vertex3d_Info(__GLcontext *gc, GLdouble, GLdouble, GLdouble);
extern GLvoid GL_APIENTRY  __glim_Vertex3dv_Info(__GLcontext *gc, const GLdouble *);
extern GLvoid GL_APIENTRY  __glim_Vertex3f_Info(__GLcontext *gc, GLfloat, GLfloat, GLfloat);
extern GLvoid GL_APIENTRY  __glim_Vertex3fv_Info(__GLcontext *gc, const GLfloat *);
extern GLvoid GL_APIENTRY  __glim_Vertex3i_Info(__GLcontext *gc, GLint, GLint, GLint);
extern GLvoid GL_APIENTRY  __glim_Vertex3iv_Info(__GLcontext *gc, const GLint *);
extern GLvoid GL_APIENTRY  __glim_Vertex3s_Info(__GLcontext *gc, GLshort, GLshort, GLshort);
extern GLvoid GL_APIENTRY  __glim_Vertex3sv_Info(__GLcontext *gc, const GLshort *);
extern GLvoid GL_APIENTRY  __glim_Vertex4d_Info(__GLcontext *gc, GLdouble, GLdouble, GLdouble, GLdouble);
extern GLvoid GL_APIENTRY  __glim_Vertex4dv_Info(__GLcontext *gc, const GLdouble *);
extern GLvoid GL_APIENTRY  __glim_Vertex4f_Info(__GLcontext *gc, GLfloat, GLfloat, GLfloat, GLfloat);
extern GLvoid GL_APIENTRY  __glim_Vertex4fv_Info(__GLcontext *gc, const GLfloat *);
extern GLvoid GL_APIENTRY  __glim_Vertex4i_Info(__GLcontext *gc, GLint, GLint, GLint, GLint);
extern GLvoid GL_APIENTRY  __glim_Vertex4iv_Info(__GLcontext *gc, const GLint *);
extern GLvoid GL_APIENTRY  __glim_Vertex4s_Info(__GLcontext *gc, GLshort, GLshort, GLshort, GLshort);
extern GLvoid GL_APIENTRY  __glim_Vertex4sv_Info(__GLcontext *gc, const GLshort *);
extern GLvoid GL_APIENTRY  __glim_SecondaryColor3b_Info(__GLcontext *gc, GLbyte, GLbyte, GLbyte);
extern GLvoid GL_APIENTRY  __glim_SecondaryColor3bv_Info(__GLcontext *gc, const GLbyte *);
extern GLvoid GL_APIENTRY  __glim_SecondaryColor3d_Info(__GLcontext *gc, GLdouble, GLdouble, GLdouble);
extern GLvoid GL_APIENTRY  __glim_SecondaryColor3dv_Info(__GLcontext *gc, const GLdouble *);
extern GLvoid GL_APIENTRY  __glim_SecondaryColor3f_Info(__GLcontext *gc, GLfloat, GLfloat, GLfloat);
extern GLvoid GL_APIENTRY  __glim_SecondaryColor3fv_Info(__GLcontext *gc, const GLfloat *);
extern GLvoid GL_APIENTRY  __glim_SecondaryColor3i_Info(__GLcontext *gc, GLint, GLint, GLint);
extern GLvoid GL_APIENTRY  __glim_SecondaryColor3iv_Info(__GLcontext *gc, const GLint *);
extern GLvoid GL_APIENTRY  __glim_SecondaryColor3s_Info(__GLcontext *gc, GLshort, GLshort, GLshort);
extern GLvoid GL_APIENTRY  __glim_SecondaryColor3sv_Info(__GLcontext *gc, const GLshort *);
extern GLvoid GL_APIENTRY  __glim_SecondaryColor3ub_Info(__GLcontext *gc, GLubyte, GLubyte, GLubyte);
extern GLvoid GL_APIENTRY  __glim_SecondaryColor3ubv_Info(__GLcontext *gc, const GLubyte *);
extern GLvoid GL_APIENTRY  __glim_SecondaryColor3ui_Info(__GLcontext *gc, GLuint, GLuint, GLuint);
extern GLvoid GL_APIENTRY  __glim_SecondaryColor3uiv_Info(__GLcontext *gc, const GLuint *);
extern GLvoid GL_APIENTRY  __glim_SecondaryColor3us_Info(__GLcontext *gc, GLushort, GLushort, GLushort);
extern GLvoid GL_APIENTRY  __glim_SecondaryColor3usv_Info(__GLcontext *gc, const GLushort *);
extern GLvoid GL_APIENTRY  __glim_FogCoordf_Info(__GLcontext *gc, GLfloat);
extern GLvoid GL_APIENTRY  __glim_FogCoordfv_Info(__GLcontext *gc, const GLfloat *);
extern GLvoid GL_APIENTRY  __glim_FogCoordd_Info(__GLcontext *gc, GLdouble);
extern GLvoid GL_APIENTRY  __glim_FogCoorddv_Info(__GLcontext *gc, const GLdouble *);
extern GLvoid GL_APIENTRY  __glim_MultiTexCoord1d_Info(__GLcontext *gc, GLenum, GLdouble);
extern GLvoid GL_APIENTRY  __glim_MultiTexCoord1dv_Info(__GLcontext *gc, GLenum, const GLdouble *);
extern GLvoid GL_APIENTRY  __glim_MultiTexCoord1f_Info(__GLcontext *gc, GLenum, GLfloat);
extern GLvoid GL_APIENTRY  __glim_MultiTexCoord1fv_Info(__GLcontext *gc, GLenum, const GLfloat *);
extern GLvoid GL_APIENTRY  __glim_MultiTexCoord1i_Info(__GLcontext *gc, GLenum, GLint);
extern GLvoid GL_APIENTRY  __glim_MultiTexCoord1iv_Info(__GLcontext *gc, GLenum, const GLint *);
extern GLvoid GL_APIENTRY  __glim_MultiTexCoord1s_Info(__GLcontext *gc, GLenum, GLshort);
extern GLvoid GL_APIENTRY  __glim_MultiTexCoord1sv_Info(__GLcontext *gc, GLenum, const GLshort *);
extern GLvoid GL_APIENTRY  __glim_MultiTexCoord2d_Info(__GLcontext *gc, GLenum, GLdouble, GLdouble);
extern GLvoid GL_APIENTRY  __glim_MultiTexCoord2dv_Info(__GLcontext *gc, GLenum, const GLdouble *);
extern GLvoid GL_APIENTRY  __glim_MultiTexCoord2f_Info(__GLcontext *gc, GLenum, GLfloat, GLfloat);
extern GLvoid GL_APIENTRY  __glim_MultiTexCoord2fv_Info(__GLcontext *gc, GLenum, const GLfloat *);
extern GLvoid GL_APIENTRY  __glim_MultiTexCoord2i_Info(__GLcontext *gc, GLenum, GLint, GLint);
extern GLvoid GL_APIENTRY  __glim_MultiTexCoord2iv_Info(__GLcontext *gc, GLenum, const GLint *);
extern GLvoid GL_APIENTRY  __glim_MultiTexCoord2s_Info(__GLcontext *gc, GLenum, GLshort, GLshort);
extern GLvoid GL_APIENTRY  __glim_MultiTexCoord2sv_Info(__GLcontext *gc, GLenum, const GLshort *);
extern GLvoid GL_APIENTRY  __glim_MultiTexCoord3d_Info(__GLcontext *gc, GLenum, GLdouble, GLdouble, GLdouble);
extern GLvoid GL_APIENTRY  __glim_MultiTexCoord3dv_Info(__GLcontext *gc, GLenum, const GLdouble *);
extern GLvoid GL_APIENTRY  __glim_MultiTexCoord3f_Info(__GLcontext *gc, GLenum, GLfloat, GLfloat, GLfloat);
extern GLvoid GL_APIENTRY  __glim_MultiTexCoord3fv_Info(__GLcontext *gc, GLenum, const GLfloat *);
extern GLvoid GL_APIENTRY  __glim_MultiTexCoord3i_Info(__GLcontext *gc, GLenum, GLint, GLint, GLint);
extern GLvoid GL_APIENTRY  __glim_MultiTexCoord3iv_Info(__GLcontext *gc, GLenum, const GLint *);
extern GLvoid GL_APIENTRY  __glim_MultiTexCoord3s_Info(__GLcontext *gc, GLenum, GLshort, GLshort, GLshort);
extern GLvoid GL_APIENTRY  __glim_MultiTexCoord3sv_Info(__GLcontext *gc, GLenum, const GLshort *);
extern GLvoid GL_APIENTRY  __glim_MultiTexCoord4d_Info(__GLcontext *gc, GLenum, GLdouble, GLdouble, GLdouble, GLdouble);
extern GLvoid GL_APIENTRY  __glim_MultiTexCoord4dv_Info(__GLcontext *gc, GLenum, const GLdouble *);
extern GLvoid GL_APIENTRY  __glim_MultiTexCoord4f_Info(__GLcontext *gc, GLenum, GLfloat, GLfloat, GLfloat, GLfloat);
extern GLvoid GL_APIENTRY  __glim_MultiTexCoord4fv_Info(__GLcontext *gc, GLenum, const GLfloat *);
extern GLvoid GL_APIENTRY  __glim_MultiTexCoord4i_Info(__GLcontext *gc, GLenum, GLint, GLint, GLint, GLint);
extern GLvoid GL_APIENTRY  __glim_MultiTexCoord4iv_Info(__GLcontext *gc, GLenum, const GLint *);
extern GLvoid GL_APIENTRY  __glim_MultiTexCoord4s_Info(__GLcontext *gc, GLenum, GLshort, GLshort, GLshort, GLshort);
extern GLvoid GL_APIENTRY  __glim_MultiTexCoord4sv_Info(__GLcontext *gc, GLenum, const GLshort *);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib1d_Info(__GLcontext *gc, GLuint, GLdouble);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib1dv_Info(__GLcontext *gc, GLuint, const GLdouble *);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib1f_Info(__GLcontext *gc, GLuint, GLfloat);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib1fv_Info(__GLcontext *gc, GLuint, const GLfloat *);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib1s_Info(__GLcontext *gc, GLuint, GLshort);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib1sv_Info(__GLcontext *gc, GLuint, const GLshort *);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib2d_Info(__GLcontext *gc, GLuint, GLdouble, GLdouble);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib2dv_Info(__GLcontext *gc, GLuint, const GLdouble *);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib2f_Info(__GLcontext *gc, GLuint, GLfloat, GLfloat);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib2fv_Info(__GLcontext *gc, GLuint, const GLfloat *);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib2s_Info(__GLcontext *gc, GLuint, GLshort, GLshort);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib2sv_Info(__GLcontext *gc, GLuint, const GLshort *);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib3d_Info(__GLcontext *gc, GLuint, GLdouble, GLdouble, GLdouble);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib3dv_Info(__GLcontext *gc, GLuint, const GLdouble *);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib3f_Info(__GLcontext *gc, GLuint, GLfloat, GLfloat, GLfloat);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib3fv_Info(__GLcontext *gc, GLuint, const GLfloat *);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib3s_Info(__GLcontext *gc, GLuint, GLshort, GLshort, GLshort);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib3sv_Info(__GLcontext *gc, GLuint, const GLshort *);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib4Nbv_Info(__GLcontext *gc, GLuint, const GLbyte *);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib4Niv_Info(__GLcontext *gc, GLuint, const GLint *);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib4Nsv_Info(__GLcontext *gc, GLuint, const GLshort *);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib4Nub_Info(__GLcontext *gc, GLuint, GLubyte, GLubyte, GLubyte, GLubyte);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib4Nubv_Info(__GLcontext *gc, GLuint, const GLubyte *);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib4Nuiv_Info(__GLcontext *gc, GLuint, const GLuint *);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib4Nusv_Info(__GLcontext *gc, GLuint, const GLushort *);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib4bv_Info(__GLcontext *gc, GLuint, const GLbyte *);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib4d_Info(__GLcontext *gc, GLuint, GLdouble, GLdouble, GLdouble, GLdouble);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib4dv_Info(__GLcontext *gc, GLuint, const GLdouble *);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib4f_Info(__GLcontext *gc, GLuint, GLfloat, GLfloat, GLfloat, GLfloat);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib4fv_Info(__GLcontext *gc, GLuint, const GLfloat *);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib4iv_Info(__GLcontext *gc, GLuint, const GLint *);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib4s_Info(__GLcontext *gc, GLuint, GLshort, GLshort, GLshort, GLshort);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib4sv_Info(__GLcontext *gc, GLuint, const GLshort *);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib4ubv_Info(__GLcontext *gc, GLuint, const GLubyte *);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib4uiv_Info(__GLcontext *gc, GLuint, const GLuint *);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib4usv_Info(__GLcontext *gc, GLuint, const GLushort *);

extern GLvoid GL_APIENTRY  __glim_VertexAttribI1iEXT_Info(__GLcontext *gc, GLuint index, GLint x);
extern GLvoid GL_APIENTRY  __glim_VertexAttribI2iEXT_Info(__GLcontext *gc, GLuint index, GLint x, GLint y);
extern GLvoid GL_APIENTRY  __glim_VertexAttribI3iEXT_Info(__GLcontext *gc, GLuint index, GLint x, GLint y, GLint z);
extern GLvoid GL_APIENTRY  __glim_VertexAttribI4iEXT_Info(__GLcontext *gc, GLuint index, GLint x, GLint y, GLint z, GLint w);
extern GLvoid GL_APIENTRY  __glim_VertexAttribI1uiEXT_Info(__GLcontext *gc, GLuint index, GLuint x);
extern GLvoid GL_APIENTRY  __glim_VertexAttribI2uiEXT_Info(__GLcontext *gc, GLuint index, GLuint x, GLuint y);
extern GLvoid GL_APIENTRY  __glim_VertexAttribI3uiEXT_Info(__GLcontext *gc, GLuint index, GLuint x, GLuint y, GLuint z);
extern GLvoid GL_APIENTRY  __glim_VertexAttribI4uiEXT_Info(__GLcontext *gc, GLuint index, GLuint x, GLuint y, GLuint z, GLuint w);
extern GLvoid GL_APIENTRY  __glim_VertexAttribI1ivEXT_Info(__GLcontext *gc, GLuint index, const GLint *v);
extern GLvoid GL_APIENTRY  __glim_VertexAttribI2ivEXT_Info(__GLcontext *gc, GLuint index, const GLint *v);
extern GLvoid GL_APIENTRY  __glim_VertexAttribI3ivEXT_Info(__GLcontext *gc, GLuint index, const GLint *v);
extern GLvoid GL_APIENTRY  __glim_VertexAttribI4ivEXT_Info(__GLcontext *gc, GLuint index, const GLint *v);
extern GLvoid GL_APIENTRY  __glim_VertexAttribI1uivEXT_Info(__GLcontext *gc, GLuint index, const GLuint *v);
extern GLvoid GL_APIENTRY  __glim_VertexAttribI2uivEXT_Info(__GLcontext *gc, GLuint index, const GLuint *v);
extern GLvoid GL_APIENTRY  __glim_VertexAttribI3uivEXT_Info(__GLcontext *gc, GLuint index, const GLuint *v);
extern GLvoid GL_APIENTRY  __glim_VertexAttribI4uivEXT_Info(__GLcontext *gc, GLuint index, const GLuint *v);
extern GLvoid GL_APIENTRY  __glim_VertexAttribI4bvEXT_Info(__GLcontext *gc, GLuint index, const GLbyte *v);
extern GLvoid GL_APIENTRY  __glim_VertexAttribI4svEXT_Info(__GLcontext *gc, GLuint index, const GLshort *v);
extern GLvoid GL_APIENTRY  __glim_VertexAttribI4ubvEXT_Info(__GLcontext *gc, GLuint index, const GLubyte *v);
extern GLvoid GL_APIENTRY  __glim_VertexAttribI4usvEXT_Info(__GLcontext *gc, GLuint index, const GLushort *v);

/* cache function interfaces */
extern GLvoid GL_APIENTRY  __glim_Begin_Cache_First(__GLcontext *gc, GLenum mode);
extern GLvoid GL_APIENTRY  __glim_Begin_Cache(__GLcontext *gc, GLenum mode);
extern GLvoid GL_APIENTRY  __glim_End_Cache(__GLcontext *gc);
extern GLvoid GL_APIENTRY  __glim_Color3b_Cache(__GLcontext *gc, GLbyte, GLbyte, GLbyte);
extern GLvoid GL_APIENTRY  __glim_Color3bv_Cache(__GLcontext *gc, const GLbyte *);
extern GLvoid GL_APIENTRY  __glim_Color3d_Cache(__GLcontext *gc, GLdouble, GLdouble, GLdouble);
extern GLvoid GL_APIENTRY  __glim_Color3dv_Cache(__GLcontext *gc, const GLdouble *);
extern GLvoid GL_APIENTRY  __glim_Color3f_Cache(__GLcontext *gc, GLfloat, GLfloat, GLfloat);
extern GLvoid GL_APIENTRY  __glim_Color3fv_Cache(__GLcontext *gc, const GLfloat *);
extern GLvoid GL_APIENTRY  __glim_Color3i_Cache(__GLcontext *gc, GLint, GLint, GLint);
extern GLvoid GL_APIENTRY  __glim_Color3iv_Cache(__GLcontext *gc, const GLint *);
extern GLvoid GL_APIENTRY  __glim_Color3s_Cache(__GLcontext *gc, GLshort, GLshort, GLshort);
extern GLvoid GL_APIENTRY  __glim_Color3sv_Cache(__GLcontext *gc, const GLshort *);
extern GLvoid GL_APIENTRY  __glim_Color3ub_Cache(__GLcontext *gc, GLubyte, GLubyte, GLubyte);
extern GLvoid GL_APIENTRY  __glim_Color3ubv_Cache(__GLcontext *gc, const GLubyte *);
extern GLvoid GL_APIENTRY  __glim_Color3ui_Cache(__GLcontext *gc, GLuint, GLuint, GLuint);
extern GLvoid GL_APIENTRY  __glim_Color3uiv_Cache(__GLcontext *gc, const GLuint *);
extern GLvoid GL_APIENTRY  __glim_Color3us_Cache(__GLcontext *gc, GLushort, GLushort, GLushort);
extern GLvoid GL_APIENTRY  __glim_Color3usv_Cache(__GLcontext *gc, const GLushort *);
extern GLvoid GL_APIENTRY  __glim_Color4b_Cache(__GLcontext *gc, GLbyte, GLbyte, GLbyte, GLbyte);
extern GLvoid GL_APIENTRY  __glim_Color4bv_Cache(__GLcontext *gc, const GLbyte *);
extern GLvoid GL_APIENTRY  __glim_Color4d_Cache(__GLcontext *gc, GLdouble, GLdouble, GLdouble, GLdouble);
extern GLvoid GL_APIENTRY  __glim_Color4dv_Cache(__GLcontext *gc, const GLdouble *);
extern GLvoid GL_APIENTRY  __glim_Color4f_Cache(__GLcontext *gc, GLfloat, GLfloat, GLfloat, GLfloat);
extern GLvoid GL_APIENTRY  __glim_Color4fv_Cache(__GLcontext *gc, const GLfloat *);
extern GLvoid GL_APIENTRY  __glim_Color4i_Cache(__GLcontext *gc, GLint, GLint, GLint, GLint);
extern GLvoid GL_APIENTRY  __glim_Color4iv_Cache(__GLcontext *gc, const GLint *);
extern GLvoid GL_APIENTRY  __glim_Color4s_Cache(__GLcontext *gc, GLshort, GLshort, GLshort, GLshort);
extern GLvoid GL_APIENTRY  __glim_Color4sv_Cache(__GLcontext *gc, const GLshort *);
extern GLvoid GL_APIENTRY  __glim_Color4ub_Cache(__GLcontext *gc, GLubyte, GLubyte, GLubyte, GLubyte);
extern GLvoid GL_APIENTRY  __glim_Color4ubv_Cache(__GLcontext *gc, const GLubyte *);
extern GLvoid GL_APIENTRY  __glim_Color4ui_Cache(__GLcontext *gc, GLuint, GLuint, GLuint, GLuint);
extern GLvoid GL_APIENTRY  __glim_Color4uiv_Cache(__GLcontext *gc, const GLuint *);
extern GLvoid GL_APIENTRY  __glim_Color4us_Cache(__GLcontext *gc, GLushort, GLushort, GLushort, GLushort);
extern GLvoid GL_APIENTRY  __glim_Color4usv_Cache(__GLcontext *gc, const GLushort *);
extern GLvoid GL_APIENTRY  __glim_Normal3b_Cache(__GLcontext *gc, GLbyte, GLbyte, GLbyte);
extern GLvoid GL_APIENTRY  __glim_Normal3bv_Cache(__GLcontext *gc, const GLbyte *);
extern GLvoid GL_APIENTRY  __glim_Normal3d_Cache(__GLcontext *gc, GLdouble, GLdouble, GLdouble);
extern GLvoid GL_APIENTRY  __glim_Normal3dv_Cache(__GLcontext *gc, const GLdouble *);
extern GLvoid GL_APIENTRY  __glim_Normal3f_Cache(__GLcontext *gc, GLfloat, GLfloat, GLfloat);
extern GLvoid GL_APIENTRY  __glim_Normal3fv_Cache(__GLcontext *gc, const GLfloat *);
extern GLvoid GL_APIENTRY  __glim_Normal3i_Cache(__GLcontext *gc, GLint, GLint, GLint);
extern GLvoid GL_APIENTRY  __glim_Normal3iv_Cache(__GLcontext *gc, const GLint *);
extern GLvoid GL_APIENTRY  __glim_Normal3s_Cache(__GLcontext *gc, GLshort, GLshort, GLshort);
extern GLvoid GL_APIENTRY  __glim_Normal3sv_Cache(__GLcontext *gc, const GLshort *);
extern GLvoid GL_APIENTRY  __glim_TexCoord1d_Cache(__GLcontext *gc, GLdouble);
extern GLvoid GL_APIENTRY  __glim_TexCoord1dv_Cache(__GLcontext *gc, const GLdouble *);
extern GLvoid GL_APIENTRY  __glim_TexCoord1f_Cache(__GLcontext *gc, GLfloat);
extern GLvoid GL_APIENTRY  __glim_TexCoord1fv_Cache(__GLcontext *gc, const GLfloat *);
extern GLvoid GL_APIENTRY  __glim_TexCoord1i_Cache(__GLcontext *gc, GLint);
extern GLvoid GL_APIENTRY  __glim_TexCoord1iv_Cache(__GLcontext *gc, const GLint *);
extern GLvoid GL_APIENTRY  __glim_TexCoord1s_Cache(__GLcontext *gc, GLshort);
extern GLvoid GL_APIENTRY  __glim_TexCoord1sv_Cache(__GLcontext *gc, const GLshort *);
extern GLvoid GL_APIENTRY  __glim_TexCoord2d_Cache(__GLcontext *gc, GLdouble, GLdouble);
extern GLvoid GL_APIENTRY  __glim_TexCoord2dv_Cache(__GLcontext *gc, const GLdouble *);
extern GLvoid GL_APIENTRY  __glim_TexCoord2f_Cache(__GLcontext *gc, GLfloat, GLfloat);
extern GLvoid GL_APIENTRY  __glim_TexCoord2fv_Cache(__GLcontext *gc, const GLfloat *);
extern GLvoid GL_APIENTRY  __glim_TexCoord2i_Cache(__GLcontext *gc, GLint, GLint);
extern GLvoid GL_APIENTRY  __glim_TexCoord2iv_Cache(__GLcontext *gc, const GLint *);
extern GLvoid GL_APIENTRY  __glim_TexCoord2s_Cache(__GLcontext *gc, GLshort, GLshort);
extern GLvoid GL_APIENTRY  __glim_TexCoord2sv_Cache(__GLcontext *gc, const GLshort *);
extern GLvoid GL_APIENTRY  __glim_TexCoord3d_Cache(__GLcontext *gc, GLdouble, GLdouble, GLdouble);
extern GLvoid GL_APIENTRY  __glim_TexCoord3dv_Cache(__GLcontext *gc, const GLdouble *);
extern GLvoid GL_APIENTRY  __glim_TexCoord3f_Cache(__GLcontext *gc, GLfloat, GLfloat, GLfloat);
extern GLvoid GL_APIENTRY  __glim_TexCoord3fv_Cache(__GLcontext *gc, const GLfloat *);
extern GLvoid GL_APIENTRY  __glim_TexCoord3i_Cache(__GLcontext *gc, GLint, GLint, GLint);
extern GLvoid GL_APIENTRY  __glim_TexCoord3iv_Cache(__GLcontext *gc, const GLint *);
extern GLvoid GL_APIENTRY  __glim_TexCoord3s_Cache(__GLcontext *gc, GLshort, GLshort, GLshort);
extern GLvoid GL_APIENTRY  __glim_TexCoord3sv_Cache(__GLcontext *gc, const GLshort *);
extern GLvoid GL_APIENTRY  __glim_TexCoord4d_Cache(__GLcontext *gc, GLdouble, GLdouble, GLdouble, GLdouble);
extern GLvoid GL_APIENTRY  __glim_TexCoord4dv_Cache(__GLcontext *gc, const GLdouble *);
extern GLvoid GL_APIENTRY  __glim_TexCoord4f_Cache(__GLcontext *gc, GLfloat, GLfloat, GLfloat, GLfloat);
extern GLvoid GL_APIENTRY  __glim_TexCoord4fv_Cache(__GLcontext *gc, const GLfloat *);
extern GLvoid GL_APIENTRY  __glim_TexCoord4i_Cache(__GLcontext *gc, GLint, GLint, GLint, GLint);
extern GLvoid GL_APIENTRY  __glim_TexCoord4iv_Cache(__GLcontext *gc, const GLint *);
extern GLvoid GL_APIENTRY  __glim_TexCoord4s_Cache(__GLcontext *gc, GLshort, GLshort, GLshort, GLshort);
extern GLvoid GL_APIENTRY  __glim_TexCoord4sv_Cache(__GLcontext *gc, const GLshort *);
extern GLvoid GL_APIENTRY  __glim_Vertex2d_Cache(__GLcontext *gc, GLdouble, GLdouble);
extern GLvoid GL_APIENTRY  __glim_Vertex2dv_Cache(__GLcontext *gc, const GLdouble *);
extern GLvoid GL_APIENTRY  __glim_Vertex2f_Cache(__GLcontext *gc, GLfloat, GLfloat);
extern GLvoid GL_APIENTRY  __glim_Vertex2fv_Cache(__GLcontext *gc, const GLfloat *);
extern GLvoid GL_APIENTRY  __glim_Vertex2i_Cache(__GLcontext *gc, GLint, GLint);
extern GLvoid GL_APIENTRY  __glim_Vertex2iv_Cache(__GLcontext *gc, const GLint *);
extern GLvoid GL_APIENTRY  __glim_Vertex2s_Cache(__GLcontext *gc, GLshort, GLshort);
extern GLvoid GL_APIENTRY  __glim_Vertex2sv_Cache(__GLcontext *gc, const GLshort *);
extern GLvoid GL_APIENTRY  __glim_Vertex3d_Cache(__GLcontext *gc, GLdouble, GLdouble, GLdouble);
extern GLvoid GL_APIENTRY  __glim_Vertex3dv_Cache(__GLcontext *gc, const GLdouble *);
extern GLvoid GL_APIENTRY  __glim_Vertex3f_Cache(__GLcontext *gc, GLfloat, GLfloat, GLfloat);
extern GLvoid GL_APIENTRY  __glim_Vertex3fv_Cache(__GLcontext *gc, const GLfloat *);
extern GLvoid GL_APIENTRY  __glim_Vertex3i_Cache(__GLcontext *gc, GLint, GLint, GLint);
extern GLvoid GL_APIENTRY  __glim_Vertex3iv_Cache(__GLcontext *gc, const GLint *);
extern GLvoid GL_APIENTRY  __glim_Vertex3s_Cache(__GLcontext *gc, GLshort, GLshort, GLshort);
extern GLvoid GL_APIENTRY  __glim_Vertex3sv_Cache(__GLcontext *gc, const GLshort *);
extern GLvoid GL_APIENTRY  __glim_Vertex4d_Cache(__GLcontext *gc, GLdouble, GLdouble, GLdouble, GLdouble);
extern GLvoid GL_APIENTRY  __glim_Vertex4dv_Cache(__GLcontext *gc, const GLdouble *);
extern GLvoid GL_APIENTRY  __glim_Vertex4f_Cache(__GLcontext *gc, GLfloat, GLfloat, GLfloat, GLfloat);
extern GLvoid GL_APIENTRY  __glim_Vertex4fv_Cache(__GLcontext *gc, const GLfloat *);
extern GLvoid GL_APIENTRY  __glim_Vertex4i_Cache(__GLcontext *gc, GLint, GLint, GLint, GLint);
extern GLvoid GL_APIENTRY  __glim_Vertex4iv_Cache(__GLcontext *gc, const GLint *);
extern GLvoid GL_APIENTRY  __glim_Vertex4s_Cache(__GLcontext *gc, GLshort, GLshort, GLshort, GLshort);
extern GLvoid GL_APIENTRY  __glim_Vertex4sv_Cache(__GLcontext *gc, const GLshort *);
extern GLvoid GL_APIENTRY  __glim_SecondaryColor3b_Cache(__GLcontext *gc, GLbyte, GLbyte, GLbyte);
extern GLvoid GL_APIENTRY  __glim_SecondaryColor3bv_Cache(__GLcontext *gc, const GLbyte *);
extern GLvoid GL_APIENTRY  __glim_SecondaryColor3d_Cache(__GLcontext *gc, GLdouble, GLdouble, GLdouble);
extern GLvoid GL_APIENTRY  __glim_SecondaryColor3dv_Cache(__GLcontext *gc, const GLdouble *);
extern GLvoid GL_APIENTRY  __glim_SecondaryColor3f_Cache(__GLcontext *gc, GLfloat, GLfloat, GLfloat);
extern GLvoid GL_APIENTRY  __glim_SecondaryColor3fv_Cache(__GLcontext *gc, const GLfloat *);
extern GLvoid GL_APIENTRY  __glim_SecondaryColor3i_Cache(__GLcontext *gc, GLint, GLint, GLint);
extern GLvoid GL_APIENTRY  __glim_SecondaryColor3iv_Cache(__GLcontext *gc, const GLint *);
extern GLvoid GL_APIENTRY  __glim_SecondaryColor3s_Cache(__GLcontext *gc, GLshort, GLshort, GLshort);
extern GLvoid GL_APIENTRY  __glim_SecondaryColor3sv_Cache(__GLcontext *gc, const GLshort *);
extern GLvoid GL_APIENTRY  __glim_SecondaryColor3ub_Cache(__GLcontext *gc, GLubyte, GLubyte, GLubyte);
extern GLvoid GL_APIENTRY  __glim_SecondaryColor3ubv_Cache(__GLcontext *gc, const GLubyte *);
extern GLvoid GL_APIENTRY  __glim_SecondaryColor3ui_Cache(__GLcontext *gc, GLuint, GLuint, GLuint);
extern GLvoid GL_APIENTRY  __glim_SecondaryColor3uiv_Cache(__GLcontext *gc, const GLuint *);
extern GLvoid GL_APIENTRY  __glim_SecondaryColor3us_Cache(__GLcontext *gc, GLushort, GLushort, GLushort);
extern GLvoid GL_APIENTRY  __glim_SecondaryColor3usv_Cache(__GLcontext *gc, const GLushort *);
extern GLvoid GL_APIENTRY  __glim_FogCoordf_Cache(__GLcontext *gc, GLfloat);
extern GLvoid GL_APIENTRY  __glim_FogCoordfv_Cache(__GLcontext *gc, const GLfloat *);
extern GLvoid GL_APIENTRY  __glim_FogCoordd_Cache(__GLcontext *gc, GLdouble);
extern GLvoid GL_APIENTRY  __glim_FogCoorddv_Cache(__GLcontext *gc, const GLdouble *);
extern GLvoid GL_APIENTRY  __glim_MultiTexCoord1d_Cache(__GLcontext *gc, GLenum, GLdouble);
extern GLvoid GL_APIENTRY  __glim_MultiTexCoord1dv_Cache(__GLcontext *gc, GLenum, const GLdouble *);
extern GLvoid GL_APIENTRY  __glim_MultiTexCoord1f_Cache(__GLcontext *gc, GLenum, GLfloat);
extern GLvoid GL_APIENTRY  __glim_MultiTexCoord1fv_Cache(__GLcontext *gc, GLenum, const GLfloat *);
extern GLvoid GL_APIENTRY  __glim_MultiTexCoord1i_Cache(__GLcontext *gc, GLenum, GLint);
extern GLvoid GL_APIENTRY  __glim_MultiTexCoord1iv_Cache(__GLcontext *gc, GLenum, const GLint *);
extern GLvoid GL_APIENTRY  __glim_MultiTexCoord1s_Cache(__GLcontext *gc, GLenum, GLshort);
extern GLvoid GL_APIENTRY  __glim_MultiTexCoord1sv_Cache(__GLcontext *gc, GLenum, const GLshort *);
extern GLvoid GL_APIENTRY  __glim_MultiTexCoord2d_Cache(__GLcontext *gc, GLenum, GLdouble, GLdouble);
extern GLvoid GL_APIENTRY  __glim_MultiTexCoord2dv_Cache(__GLcontext *gc, GLenum, const GLdouble *);
extern GLvoid GL_APIENTRY  __glim_MultiTexCoord2f_Cache(__GLcontext *gc, GLenum, GLfloat, GLfloat);
extern GLvoid GL_APIENTRY  __glim_MultiTexCoord2fv_Cache(__GLcontext *gc, GLenum, const GLfloat *);
extern GLvoid GL_APIENTRY  __glim_MultiTexCoord2i_Cache(__GLcontext *gc, GLenum, GLint, GLint);
extern GLvoid GL_APIENTRY  __glim_MultiTexCoord2iv_Cache(__GLcontext *gc, GLenum, const GLint *);
extern GLvoid GL_APIENTRY  __glim_MultiTexCoord2s_Cache(__GLcontext *gc, GLenum, GLshort, GLshort);
extern GLvoid GL_APIENTRY  __glim_MultiTexCoord2sv_Cache(__GLcontext *gc, GLenum, const GLshort *);
extern GLvoid GL_APIENTRY  __glim_MultiTexCoord3d_Cache(__GLcontext *gc, GLenum, GLdouble, GLdouble, GLdouble);
extern GLvoid GL_APIENTRY  __glim_MultiTexCoord3dv_Cache(__GLcontext *gc, GLenum, const GLdouble *);
extern GLvoid GL_APIENTRY  __glim_MultiTexCoord3f_Cache(__GLcontext *gc, GLenum, GLfloat, GLfloat, GLfloat);
extern GLvoid GL_APIENTRY  __glim_MultiTexCoord3fv_Cache(__GLcontext *gc, GLenum, const GLfloat *);
extern GLvoid GL_APIENTRY  __glim_MultiTexCoord3i_Cache(__GLcontext *gc, GLenum, GLint, GLint, GLint);
extern GLvoid GL_APIENTRY  __glim_MultiTexCoord3iv_Cache(__GLcontext *gc, GLenum, const GLint *);
extern GLvoid GL_APIENTRY  __glim_MultiTexCoord3s_Cache(__GLcontext *gc, GLenum, GLshort, GLshort, GLshort);
extern GLvoid GL_APIENTRY  __glim_MultiTexCoord3sv_Cache(__GLcontext *gc, GLenum, const GLshort *);
extern GLvoid GL_APIENTRY  __glim_MultiTexCoord4d_Cache(__GLcontext *gc, GLenum, GLdouble, GLdouble, GLdouble, GLdouble);
extern GLvoid GL_APIENTRY  __glim_MultiTexCoord4dv_Cache(__GLcontext *gc, GLenum, const GLdouble *);
extern GLvoid GL_APIENTRY  __glim_MultiTexCoord4f_Cache(__GLcontext *gc, GLenum, GLfloat, GLfloat, GLfloat, GLfloat);
extern GLvoid GL_APIENTRY  __glim_MultiTexCoord4fv_Cache(__GLcontext *gc, GLenum, const GLfloat *);
extern GLvoid GL_APIENTRY  __glim_MultiTexCoord4i_Cache(__GLcontext *gc, GLenum, GLint, GLint, GLint, GLint);
extern GLvoid GL_APIENTRY  __glim_MultiTexCoord4iv_Cache(__GLcontext *gc, GLenum, const GLint *);
extern GLvoid GL_APIENTRY  __glim_MultiTexCoord4s_Cache(__GLcontext *gc, GLenum, GLshort, GLshort, GLshort, GLshort);
extern GLvoid GL_APIENTRY  __glim_MultiTexCoord4sv_Cache(__GLcontext *gc, GLenum, const GLshort *);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib1d_Cache(__GLcontext *gc, GLuint, GLdouble);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib1dv_Cache(__GLcontext *gc, GLuint, const GLdouble *);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib1f_Cache(__GLcontext *gc, GLuint, GLfloat);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib1fv_Cache(__GLcontext *gc, GLuint, const GLfloat *);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib1s_Cache(__GLcontext *gc, GLuint, GLshort);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib1sv_Cache(__GLcontext *gc, GLuint, const GLshort *);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib2d_Cache(__GLcontext *gc, GLuint, GLdouble, GLdouble);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib2dv_Cache(__GLcontext *gc, GLuint, const GLdouble *);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib2f_Cache(__GLcontext *gc, GLuint, GLfloat, GLfloat);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib2fv_Cache(__GLcontext *gc, GLuint, const GLfloat *);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib2s_Cache(__GLcontext *gc, GLuint, GLshort, GLshort);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib2sv_Cache(__GLcontext *gc, GLuint, const GLshort *);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib3d_Cache(__GLcontext *gc, GLuint, GLdouble, GLdouble, GLdouble);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib3dv_Cache(__GLcontext *gc, GLuint, const GLdouble *);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib3f_Cache(__GLcontext *gc, GLuint, GLfloat, GLfloat, GLfloat);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib3fv_Cache(__GLcontext *gc, GLuint, const GLfloat *);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib3s_Cache(__GLcontext *gc, GLuint, GLshort, GLshort, GLshort);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib3sv_Cache(__GLcontext *gc, GLuint, const GLshort *);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib4Nbv_Cache(__GLcontext *gc, GLuint, const GLbyte *);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib4Niv_Cache(__GLcontext *gc, GLuint, const GLint *);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib4Nsv_Cache(__GLcontext *gc, GLuint, const GLshort *);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib4Nub_Cache(__GLcontext *gc, GLuint, GLubyte, GLubyte, GLubyte, GLubyte);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib4Nubv_Cache(__GLcontext *gc, GLuint, const GLubyte *);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib4Nuiv_Cache(__GLcontext *gc, GLuint, const GLuint *);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib4Nusv_Cache(__GLcontext *gc, GLuint, const GLushort *);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib4bv_Cache(__GLcontext *gc, GLuint, const GLbyte *);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib4d_Cache(__GLcontext *gc, GLuint, GLdouble, GLdouble, GLdouble, GLdouble);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib4dv_Cache(__GLcontext *gc, GLuint, const GLdouble *);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib4f_Cache(__GLcontext *gc, GLuint, GLfloat, GLfloat, GLfloat, GLfloat);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib4fv_Cache(__GLcontext *gc, GLuint, const GLfloat *);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib4iv_Cache(__GLcontext *gc, GLuint, const GLint *);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib4s_Cache(__GLcontext *gc, GLuint, GLshort, GLshort, GLshort, GLshort);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib4sv_Cache(__GLcontext *gc, GLuint, const GLshort *);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib4ubv_Cache(__GLcontext *gc, GLuint, const GLubyte *);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib4uiv_Cache(__GLcontext *gc, GLuint, const GLuint *);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib4usv_Cache(__GLcontext *gc, GLuint, const GLushort *);

extern GLvoid GL_APIENTRY  __glim_VertexAttribI1iEXT_Cache(__GLcontext *gc, GLuint index, GLint x);
extern GLvoid GL_APIENTRY  __glim_VertexAttribI2iEXT_Cache(__GLcontext *gc, GLuint index, GLint x, GLint y);
extern GLvoid GL_APIENTRY  __glim_VertexAttribI3iEXT_Cache(__GLcontext *gc, GLuint index, GLint x, GLint y, GLint z);
extern GLvoid GL_APIENTRY  __glim_VertexAttribI4iEXT_Cache(__GLcontext *gc, GLuint index, GLint x, GLint y, GLint z, GLint w);
extern GLvoid GL_APIENTRY  __glim_VertexAttribI1uiEXT_Cache(__GLcontext *gc, GLuint index, GLuint x);
extern GLvoid GL_APIENTRY  __glim_VertexAttribI2uiEXT_Cache(__GLcontext *gc, GLuint index, GLuint x, GLuint y);
extern GLvoid GL_APIENTRY  __glim_VertexAttribI3uiEXT_Cache(__GLcontext *gc, GLuint index, GLuint x, GLuint y, GLuint z);
extern GLvoid GL_APIENTRY  __glim_VertexAttribI4uiEXT_Cache(__GLcontext *gc, GLuint index, GLuint x, GLuint y, GLuint z, GLuint w);
extern GLvoid GL_APIENTRY  __glim_VertexAttribI1ivEXT_Cache(__GLcontext *gc, GLuint index, const GLint *v);
extern GLvoid GL_APIENTRY  __glim_VertexAttribI2ivEXT_Cache(__GLcontext *gc, GLuint index, const GLint *v);
extern GLvoid GL_APIENTRY  __glim_VertexAttribI3ivEXT_Cache(__GLcontext *gc, GLuint index, const GLint *v);
extern GLvoid GL_APIENTRY  __glim_VertexAttribI4ivEXT_Cache(__GLcontext *gc, GLuint index, const GLint *v);
extern GLvoid GL_APIENTRY  __glim_VertexAttribI1uivEXT_Cache(__GLcontext *gc, GLuint index, const GLuint *v);
extern GLvoid GL_APIENTRY  __glim_VertexAttribI2uivEXT_Cache(__GLcontext *gc, GLuint index, const GLuint *v);
extern GLvoid GL_APIENTRY  __glim_VertexAttribI3uivEXT_Cache(__GLcontext *gc, GLuint index, const GLuint *v);
extern GLvoid GL_APIENTRY  __glim_VertexAttribI4uivEXT_Cache(__GLcontext *gc, GLuint index, const GLuint *v);
extern GLvoid GL_APIENTRY  __glim_VertexAttribI4bvEXT_Cache(__GLcontext *gc, GLuint index, const GLbyte *v);
extern GLvoid GL_APIENTRY  __glim_VertexAttribI4svEXT_Cache(__GLcontext *gc, GLuint index, const GLshort *v);
extern GLvoid GL_APIENTRY  __glim_VertexAttribI4ubvEXT_Cache(__GLcontext *gc, GLuint index, const GLubyte *v);
extern GLvoid GL_APIENTRY  __glim_VertexAttribI4usvEXT_Cache(__GLcontext *gc, GLuint index, const GLushort *v);

extern GLvoid GL_APIENTRY  __glim_End_Error(__GLcontext *gc);

extern GLvoid GL_APIENTRY  __glim_Color3b_Outside(__GLcontext *gc, GLbyte, GLbyte, GLbyte);
extern GLvoid GL_APIENTRY  __glim_Color3bv_Outside(__GLcontext *gc, const GLbyte *);
extern GLvoid GL_APIENTRY  __glim_Color3d_Outside(__GLcontext *gc, GLdouble, GLdouble, GLdouble);
extern GLvoid GL_APIENTRY  __glim_Color3dv_Outside(__GLcontext *gc, const GLdouble *);
extern GLvoid GL_APIENTRY  __glim_Color3f_Outside(__GLcontext *gc, GLfloat, GLfloat, GLfloat);
extern GLvoid GL_APIENTRY  __glim_Color3fv_Outside(__GLcontext *gc, const GLfloat *);
extern GLvoid GL_APIENTRY  __glim_Color3i_Outside(__GLcontext *gc, GLint, GLint, GLint);
extern GLvoid GL_APIENTRY  __glim_Color3iv_Outside(__GLcontext *gc, const GLint *);
extern GLvoid GL_APIENTRY  __glim_Color3s_Outside(__GLcontext *gc, GLshort, GLshort, GLshort);
extern GLvoid GL_APIENTRY  __glim_Color3sv_Outside(__GLcontext *gc, const GLshort *);
extern GLvoid GL_APIENTRY  __glim_Color3ub_Outside(__GLcontext *gc, GLubyte, GLubyte, GLubyte);
extern GLvoid GL_APIENTRY  __glim_Color3ubv_Outside(__GLcontext *gc, const GLubyte *);
extern GLvoid GL_APIENTRY  __glim_Color3ui_Outside(__GLcontext *gc, GLuint, GLuint, GLuint);
extern GLvoid GL_APIENTRY  __glim_Color3uiv_Outside(__GLcontext *gc, const GLuint *);
extern GLvoid GL_APIENTRY  __glim_Color3us_Outside(__GLcontext *gc, GLushort, GLushort, GLushort);
extern GLvoid GL_APIENTRY  __glim_Color3usv_Outside(__GLcontext *gc, const GLushort *);
extern GLvoid GL_APIENTRY  __glim_Color4b_Outside(__GLcontext *gc, GLbyte, GLbyte, GLbyte, GLbyte);
extern GLvoid GL_APIENTRY  __glim_Color4bv_Outside(__GLcontext *gc, const GLbyte *);
extern GLvoid GL_APIENTRY  __glim_Color4d_Outside(__GLcontext *gc, GLdouble, GLdouble, GLdouble, GLdouble);
extern GLvoid GL_APIENTRY  __glim_Color4dv_Outside(__GLcontext *gc, const GLdouble *);
extern GLvoid GL_APIENTRY  __glim_Color4f_Outside(__GLcontext *gc, GLfloat, GLfloat, GLfloat, GLfloat);
extern GLvoid GL_APIENTRY  __glim_Color4fv_Outside(__GLcontext *gc, const GLfloat *);
extern GLvoid GL_APIENTRY  __glim_Color4i_Outside(__GLcontext *gc, GLint, GLint, GLint, GLint);
extern GLvoid GL_APIENTRY  __glim_Color4iv_Outside(__GLcontext *gc, const GLint *);
extern GLvoid GL_APIENTRY  __glim_Color4s_Outside(__GLcontext *gc, GLshort, GLshort, GLshort, GLshort);
extern GLvoid GL_APIENTRY  __glim_Color4sv_Outside(__GLcontext *gc, const GLshort *);
extern GLvoid GL_APIENTRY  __glim_Color4ub_Outside(__GLcontext *gc, GLubyte, GLubyte, GLubyte, GLubyte);
extern GLvoid GL_APIENTRY  __glim_Color4ubv_Outside(__GLcontext *gc, const GLubyte *);
extern GLvoid GL_APIENTRY  __glim_Color4ui_Outside(__GLcontext *gc, GLuint, GLuint, GLuint, GLuint);
extern GLvoid GL_APIENTRY  __glim_Color4uiv_Outside(__GLcontext *gc, const GLuint *);
extern GLvoid GL_APIENTRY  __glim_Color4us_Outside(__GLcontext *gc, GLushort, GLushort, GLushort, GLushort);
extern GLvoid GL_APIENTRY  __glim_Color4usv_Outside(__GLcontext *gc, const GLushort *);
extern GLvoid GL_APIENTRY  __glim_Normal3b_Outside(__GLcontext *gc, GLbyte, GLbyte, GLbyte);
extern GLvoid GL_APIENTRY  __glim_Normal3bv_Outside(__GLcontext *gc, const GLbyte *);
extern GLvoid GL_APIENTRY  __glim_Normal3d_Outside(__GLcontext *gc, GLdouble, GLdouble, GLdouble);
extern GLvoid GL_APIENTRY  __glim_Normal3dv_Outside(__GLcontext *gc, const GLdouble *);
extern GLvoid GL_APIENTRY  __glim_Normal3f_Outside(__GLcontext *gc, GLfloat, GLfloat, GLfloat);
extern GLvoid GL_APIENTRY  __glim_Normal3fv_Outside(__GLcontext *gc, const GLfloat *);
extern GLvoid GL_APIENTRY  __glim_Normal3i_Outside(__GLcontext *gc, GLint, GLint, GLint);
extern GLvoid GL_APIENTRY  __glim_Normal3iv_Outside(__GLcontext *gc, const GLint *);
extern GLvoid GL_APIENTRY  __glim_Normal3s_Outside(__GLcontext *gc, GLshort, GLshort, GLshort);
extern GLvoid GL_APIENTRY  __glim_Normal3sv_Outside(__GLcontext *gc, const GLshort *);
extern GLvoid GL_APIENTRY  __glim_TexCoord1d_Outside(__GLcontext *gc, GLdouble);
extern GLvoid GL_APIENTRY  __glim_TexCoord1dv_Outside(__GLcontext *gc, const GLdouble *);
extern GLvoid GL_APIENTRY  __glim_TexCoord1f_Outside(__GLcontext *gc, GLfloat);
extern GLvoid GL_APIENTRY  __glim_TexCoord1fv_Outside(__GLcontext *gc, const GLfloat *);
extern GLvoid GL_APIENTRY  __glim_TexCoord1i_Outside(__GLcontext *gc, GLint);
extern GLvoid GL_APIENTRY  __glim_TexCoord1iv_Outside(__GLcontext *gc, const GLint *);
extern GLvoid GL_APIENTRY  __glim_TexCoord1s_Outside(__GLcontext *gc, GLshort);
extern GLvoid GL_APIENTRY  __glim_TexCoord1sv_Outside(__GLcontext *gc, const GLshort *);
extern GLvoid GL_APIENTRY  __glim_TexCoord2d_Outside(__GLcontext *gc, GLdouble, GLdouble);
extern GLvoid GL_APIENTRY  __glim_TexCoord2dv_Outside(__GLcontext *gc, const GLdouble *);
extern GLvoid GL_APIENTRY  __glim_TexCoord2f_Outside(__GLcontext *gc, GLfloat, GLfloat);
extern GLvoid GL_APIENTRY  __glim_TexCoord2fv_Outside(__GLcontext *gc, const GLfloat *);
extern GLvoid GL_APIENTRY  __glim_TexCoord2i_Outside(__GLcontext *gc, GLint, GLint);
extern GLvoid GL_APIENTRY  __glim_TexCoord2iv_Outside(__GLcontext *gc, const GLint *);
extern GLvoid GL_APIENTRY  __glim_TexCoord2s_Outside(__GLcontext *gc, GLshort, GLshort);
extern GLvoid GL_APIENTRY  __glim_TexCoord2sv_Outside(__GLcontext *gc, const GLshort *);
extern GLvoid GL_APIENTRY  __glim_TexCoord3d_Outside(__GLcontext *gc, GLdouble, GLdouble, GLdouble);
extern GLvoid GL_APIENTRY  __glim_TexCoord3dv_Outside(__GLcontext *gc, const GLdouble *);
extern GLvoid GL_APIENTRY  __glim_TexCoord3f_Outside(__GLcontext *gc, GLfloat, GLfloat, GLfloat);
extern GLvoid GL_APIENTRY  __glim_TexCoord3fv_Outside(__GLcontext *gc, const GLfloat *);
extern GLvoid GL_APIENTRY  __glim_TexCoord3i_Outside(__GLcontext *gc, GLint, GLint, GLint);
extern GLvoid GL_APIENTRY  __glim_TexCoord3iv_Outside(__GLcontext *gc, const GLint *);
extern GLvoid GL_APIENTRY  __glim_TexCoord3s_Outside(__GLcontext *gc, GLshort, GLshort, GLshort);
extern GLvoid GL_APIENTRY  __glim_TexCoord3sv_Outside(__GLcontext *gc, const GLshort *);
extern GLvoid GL_APIENTRY  __glim_TexCoord4d_Outside(__GLcontext *gc, GLdouble, GLdouble, GLdouble, GLdouble);
extern GLvoid GL_APIENTRY  __glim_TexCoord4dv_Outside(__GLcontext *gc, const GLdouble *);
extern GLvoid GL_APIENTRY  __glim_TexCoord4f_Outside(__GLcontext *gc, GLfloat, GLfloat, GLfloat, GLfloat);
extern GLvoid GL_APIENTRY  __glim_TexCoord4fv_Outside(__GLcontext *gc, const GLfloat *);
extern GLvoid GL_APIENTRY  __glim_TexCoord4i_Outside(__GLcontext *gc, GLint, GLint, GLint, GLint);
extern GLvoid GL_APIENTRY  __glim_TexCoord4iv_Outside(__GLcontext *gc, const GLint *);
extern GLvoid GL_APIENTRY  __glim_TexCoord4s_Outside(__GLcontext *gc, GLshort, GLshort, GLshort, GLshort);
extern GLvoid GL_APIENTRY  __glim_TexCoord4sv_Outside(__GLcontext *gc, const GLshort *);
extern GLvoid GL_APIENTRY  __glim_Vertex2d_Outside(__GLcontext *gc, GLdouble, GLdouble);
extern GLvoid GL_APIENTRY  __glim_Vertex2dv_Outside(__GLcontext *gc, const GLdouble *);
extern GLvoid GL_APIENTRY  __glim_Vertex2f_Outside(__GLcontext *gc, GLfloat, GLfloat);
extern GLvoid GL_APIENTRY  __glim_Vertex2fv_Outside(__GLcontext *gc, const GLfloat *);
extern GLvoid GL_APIENTRY  __glim_Vertex2i_Outside(__GLcontext *gc, GLint, GLint);
extern GLvoid GL_APIENTRY  __glim_Vertex2iv_Outside(__GLcontext *gc, const GLint *);
extern GLvoid GL_APIENTRY  __glim_Vertex2s_Outside(__GLcontext *gc, GLshort, GLshort);
extern GLvoid GL_APIENTRY  __glim_Vertex2sv_Outside(__GLcontext *gc, const GLshort *);
extern GLvoid GL_APIENTRY  __glim_Vertex3d_Outside(__GLcontext *gc, GLdouble, GLdouble, GLdouble);
extern GLvoid GL_APIENTRY  __glim_Vertex3dv_Outside(__GLcontext *gc, const GLdouble *);
extern GLvoid GL_APIENTRY  __glim_Vertex3f_Outside(__GLcontext *gc, GLfloat, GLfloat, GLfloat);
extern GLvoid GL_APIENTRY  __glim_Vertex3fv_Outside(__GLcontext *gc, const GLfloat *);
extern GLvoid GL_APIENTRY  __glim_Vertex3i_Outside(__GLcontext *gc, GLint, GLint, GLint);
extern GLvoid GL_APIENTRY  __glim_Vertex3iv_Outside(__GLcontext *gc, const GLint *);
extern GLvoid GL_APIENTRY  __glim_Vertex3s_Outside(__GLcontext *gc, GLshort, GLshort, GLshort);
extern GLvoid GL_APIENTRY  __glim_Vertex3sv_Outside(__GLcontext *gc, const GLshort *);
extern GLvoid GL_APIENTRY  __glim_Vertex4d_Outside(__GLcontext *gc, GLdouble, GLdouble, GLdouble, GLdouble);
extern GLvoid GL_APIENTRY  __glim_Vertex4dv_Outside(__GLcontext *gc, const GLdouble *);
extern GLvoid GL_APIENTRY  __glim_Vertex4f_Outside(__GLcontext *gc, GLfloat, GLfloat, GLfloat, GLfloat);
extern GLvoid GL_APIENTRY  __glim_Vertex4fv_Outside(__GLcontext *gc, const GLfloat *);
extern GLvoid GL_APIENTRY  __glim_Vertex4i_Outside(__GLcontext *gc, GLint, GLint, GLint, GLint);
extern GLvoid GL_APIENTRY  __glim_Vertex4iv_Outside(__GLcontext *gc, const GLint *);
extern GLvoid GL_APIENTRY  __glim_Vertex4s_Outside(__GLcontext *gc, GLshort, GLshort, GLshort, GLshort);
extern GLvoid GL_APIENTRY  __glim_Vertex4sv_Outside(__GLcontext *gc, const GLshort *);
extern GLvoid GL_APIENTRY  __glim_SecondaryColor3b_Outside(__GLcontext *gc, GLbyte, GLbyte, GLbyte);
extern GLvoid GL_APIENTRY  __glim_SecondaryColor3bv_Outside(__GLcontext *gc, const GLbyte *);
extern GLvoid GL_APIENTRY  __glim_SecondaryColor3d_Outside(__GLcontext *gc, GLdouble, GLdouble, GLdouble);
extern GLvoid GL_APIENTRY  __glim_SecondaryColor3dv_Outside(__GLcontext *gc, const GLdouble *);
extern GLvoid GL_APIENTRY  __glim_SecondaryColor3f_Outside(__GLcontext *gc, GLfloat, GLfloat, GLfloat);
extern GLvoid GL_APIENTRY  __glim_SecondaryColor3fv_Outside(__GLcontext *gc, const GLfloat *);
extern GLvoid GL_APIENTRY  __glim_SecondaryColor3i_Outside(__GLcontext *gc, GLint, GLint, GLint);
extern GLvoid GL_APIENTRY  __glim_SecondaryColor3iv_Outside(__GLcontext *gc, const GLint *);
extern GLvoid GL_APIENTRY  __glim_SecondaryColor3s_Outside(__GLcontext *gc, GLshort, GLshort, GLshort);
extern GLvoid GL_APIENTRY  __glim_SecondaryColor3sv_Outside(__GLcontext *gc, const GLshort *);
extern GLvoid GL_APIENTRY  __glim_SecondaryColor3ub_Outside(__GLcontext *gc, GLubyte, GLubyte, GLubyte);
extern GLvoid GL_APIENTRY  __glim_SecondaryColor3ubv_Outside(__GLcontext *gc, const GLubyte *);
extern GLvoid GL_APIENTRY  __glim_SecondaryColor3ui_Outside(__GLcontext *gc, GLuint, GLuint, GLuint);
extern GLvoid GL_APIENTRY  __glim_SecondaryColor3uiv_Outside(__GLcontext *gc, const GLuint *);
extern GLvoid GL_APIENTRY  __glim_SecondaryColor3us_Outside(__GLcontext *gc, GLushort, GLushort, GLushort);
extern GLvoid GL_APIENTRY  __glim_SecondaryColor3usv_Outside(__GLcontext *gc, const GLushort *);
extern GLvoid GL_APIENTRY  __glim_FogCoordf_Outside(__GLcontext *gc, GLfloat);
extern GLvoid GL_APIENTRY  __glim_FogCoordfv_Outside(__GLcontext *gc, const GLfloat *);
extern GLvoid GL_APIENTRY  __glim_FogCoordd_Outside(__GLcontext *gc, GLdouble);
extern GLvoid GL_APIENTRY  __glim_FogCoorddv_Outside(__GLcontext *gc, const GLdouble *);
extern GLvoid GL_APIENTRY  __glim_MultiTexCoord1d_Outside(__GLcontext *gc, GLenum, GLdouble);
extern GLvoid GL_APIENTRY  __glim_MultiTexCoord1dv_Outside(__GLcontext *gc, GLenum, const GLdouble *);
extern GLvoid GL_APIENTRY  __glim_MultiTexCoord1f_Outside(__GLcontext *gc, GLenum, GLfloat);
extern GLvoid GL_APIENTRY  __glim_MultiTexCoord1fv_Outside(__GLcontext *gc, GLenum, const GLfloat *);
extern GLvoid GL_APIENTRY  __glim_MultiTexCoord1i_Outside(__GLcontext *gc, GLenum, GLint);
extern GLvoid GL_APIENTRY  __glim_MultiTexCoord1iv_Outside(__GLcontext *gc, GLenum, const GLint *);
extern GLvoid GL_APIENTRY  __glim_MultiTexCoord1s_Outside(__GLcontext *gc, GLenum, GLshort);
extern GLvoid GL_APIENTRY  __glim_MultiTexCoord1sv_Outside(__GLcontext *gc, GLenum, const GLshort *);
extern GLvoid GL_APIENTRY  __glim_MultiTexCoord2d_Outside(__GLcontext *gc, GLenum, GLdouble, GLdouble);
extern GLvoid GL_APIENTRY  __glim_MultiTexCoord2dv_Outside(__GLcontext *gc, GLenum, const GLdouble *);
extern GLvoid GL_APIENTRY  __glim_MultiTexCoord2f_Outside(__GLcontext *gc, GLenum, GLfloat, GLfloat);
extern GLvoid GL_APIENTRY  __glim_MultiTexCoord2fv_Outside(__GLcontext *gc, GLenum, const GLfloat *);
extern GLvoid GL_APIENTRY  __glim_MultiTexCoord2i_Outside(__GLcontext *gc, GLenum, GLint, GLint);
extern GLvoid GL_APIENTRY  __glim_MultiTexCoord2iv_Outside(__GLcontext *gc, GLenum, const GLint *);
extern GLvoid GL_APIENTRY  __glim_MultiTexCoord2s_Outside(__GLcontext *gc, GLenum, GLshort, GLshort);
extern GLvoid GL_APIENTRY  __glim_MultiTexCoord2sv_Outside(__GLcontext *gc, GLenum, const GLshort *);
extern GLvoid GL_APIENTRY  __glim_MultiTexCoord3d_Outside(__GLcontext *gc, GLenum, GLdouble, GLdouble, GLdouble);
extern GLvoid GL_APIENTRY  __glim_MultiTexCoord3dv_Outside(__GLcontext *gc, GLenum, const GLdouble *);
extern GLvoid GL_APIENTRY  __glim_MultiTexCoord3f_Outside(__GLcontext *gc, GLenum, GLfloat, GLfloat, GLfloat);
extern GLvoid GL_APIENTRY  __glim_MultiTexCoord3fv_Outside(__GLcontext *gc, GLenum, const GLfloat *);
extern GLvoid GL_APIENTRY  __glim_MultiTexCoord3i_Outside(__GLcontext *gc, GLenum, GLint, GLint, GLint);
extern GLvoid GL_APIENTRY  __glim_MultiTexCoord3iv_Outside(__GLcontext *gc, GLenum, const GLint *);
extern GLvoid GL_APIENTRY  __glim_MultiTexCoord3s_Outside(__GLcontext *gc, GLenum, GLshort, GLshort, GLshort);
extern GLvoid GL_APIENTRY  __glim_MultiTexCoord3sv_Outside(__GLcontext *gc, GLenum, const GLshort *);
extern GLvoid GL_APIENTRY  __glim_MultiTexCoord4d_Outside(__GLcontext *gc, GLenum, GLdouble, GLdouble, GLdouble, GLdouble);
extern GLvoid GL_APIENTRY  __glim_MultiTexCoord4dv_Outside(__GLcontext *gc, GLenum, const GLdouble *);
extern GLvoid GL_APIENTRY  __glim_MultiTexCoord4f_Outside(__GLcontext *gc, GLenum, GLfloat, GLfloat, GLfloat, GLfloat);
extern GLvoid GL_APIENTRY  __glim_MultiTexCoord4fv_Outside(__GLcontext *gc, GLenum, const GLfloat *);
extern GLvoid GL_APIENTRY  __glim_MultiTexCoord4i_Outside(__GLcontext *gc, GLenum, GLint, GLint, GLint, GLint);
extern GLvoid GL_APIENTRY  __glim_MultiTexCoord4iv_Outside(__GLcontext *gc, GLenum, const GLint *);
extern GLvoid GL_APIENTRY  __glim_MultiTexCoord4s_Outside(__GLcontext *gc, GLenum, GLshort, GLshort, GLshort, GLshort);
extern GLvoid GL_APIENTRY  __glim_MultiTexCoord4sv_Outside(__GLcontext *gc, GLenum, const GLshort *);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib1d_Outside(__GLcontext *gc, GLuint, GLdouble);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib1dv_Outside(__GLcontext *gc, GLuint, const GLdouble *);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib1f_Outside(__GLcontext *gc, GLuint, GLfloat);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib1fv_Outside(__GLcontext *gc, GLuint, const GLfloat *);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib1s_Outside(__GLcontext *gc, GLuint, GLshort);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib1sv_Outside(__GLcontext *gc, GLuint, const GLshort *);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib2d_Outside(__GLcontext *gc, GLuint, GLdouble, GLdouble);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib2dv_Outside(__GLcontext *gc, GLuint, const GLdouble *);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib2f_Outside(__GLcontext *gc, GLuint, GLfloat, GLfloat);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib2fv_Outside(__GLcontext *gc, GLuint, const GLfloat *);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib2s_Outside(__GLcontext *gc, GLuint, GLshort, GLshort);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib2sv_Outside(__GLcontext *gc, GLuint, const GLshort *);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib3d_Outside(__GLcontext *gc, GLuint, GLdouble, GLdouble, GLdouble);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib3dv_Outside(__GLcontext *gc, GLuint, const GLdouble *);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib3f_Outside(__GLcontext *gc, GLuint, GLfloat, GLfloat, GLfloat);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib3fv_Outside(__GLcontext *gc, GLuint, const GLfloat *);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib3s_Outside(__GLcontext *gc, GLuint, GLshort, GLshort, GLshort);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib3sv_Outside(__GLcontext *gc, GLuint, const GLshort *);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib4Nbv_Outside(__GLcontext *gc, GLuint, const GLbyte *);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib4Niv_Outside(__GLcontext *gc, GLuint, const GLint *);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib4Nsv_Outside(__GLcontext *gc, GLuint, const GLshort *);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib4Nub_Outside(__GLcontext *gc, GLuint, GLubyte, GLubyte, GLubyte, GLubyte);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib4Nubv_Outside(__GLcontext *gc, GLuint, const GLubyte *);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib4Nuiv_Outside(__GLcontext *gc, GLuint, const GLuint *);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib4Nusv_Outside(__GLcontext *gc, GLuint, const GLushort *);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib4bv_Outside(__GLcontext *gc, GLuint, const GLbyte *);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib4d_Outside(__GLcontext *gc, GLuint, GLdouble, GLdouble, GLdouble, GLdouble);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib4dv_Outside(__GLcontext *gc, GLuint, const GLdouble *);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib4f_Outside(__GLcontext *gc, GLuint, GLfloat, GLfloat, GLfloat, GLfloat);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib4fv_Outside(__GLcontext *gc, GLuint, const GLfloat *);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib4iv_Outside(__GLcontext *gc, GLuint, const GLint *);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib4s_Outside(__GLcontext *gc, GLuint, GLshort, GLshort, GLshort, GLshort);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib4sv_Outside(__GLcontext *gc, GLuint, const GLshort *);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib4ubv_Outside(__GLcontext *gc, GLuint, const GLubyte *);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib4uiv_Outside(__GLcontext *gc, GLuint, const GLuint *);
extern GLvoid GL_APIENTRY  __glim_VertexAttrib4usv_Outside(__GLcontext *gc, GLuint, const GLushort *);
extern GLvoid GL_APIENTRY  __glim_EdgeFlag_Outside(__GLcontext *gc, GLboolean);
extern GLvoid GL_APIENTRY  __glim_EdgeFlagv_Outside(__GLcontext *gc, const GLboolean *);

extern GLvoid GL_APIENTRY  __glim_VertexAttribI1iEXT_Outside(__GLcontext *gc, GLuint index, GLint x);
extern GLvoid GL_APIENTRY  __glim_VertexAttribI2iEXT_Outside(__GLcontext *gc, GLuint index, GLint x, GLint y);
extern GLvoid GL_APIENTRY  __glim_VertexAttribI3iEXT_Outside(__GLcontext *gc, GLuint index, GLint x, GLint y, GLint z);
extern GLvoid GL_APIENTRY  __glim_VertexAttribI4iEXT_Outside(__GLcontext *gc, GLuint index, GLint x, GLint y, GLint z, GLint w);
extern GLvoid GL_APIENTRY  __glim_VertexAttribI1uiEXT_Outside(__GLcontext *gc, GLuint index, GLuint x);
extern GLvoid GL_APIENTRY  __glim_VertexAttribI2uiEXT_Outside(__GLcontext *gc, GLuint index, GLuint x, GLuint y);
extern GLvoid GL_APIENTRY  __glim_VertexAttribI3uiEXT_Outside(__GLcontext *gc, GLuint index, GLuint x, GLuint y, GLuint z);
extern GLvoid GL_APIENTRY  __glim_VertexAttribI4uiEXT_Outside(__GLcontext *gc, GLuint index, GLuint x, GLuint y, GLuint z, GLuint w);
extern GLvoid GL_APIENTRY  __glim_VertexAttribI1ivEXT_Outside(__GLcontext *gc, GLuint index, const GLint *v);
extern GLvoid GL_APIENTRY  __glim_VertexAttribI2ivEXT_Outside(__GLcontext *gc, GLuint index, const GLint *v);
extern GLvoid GL_APIENTRY  __glim_VertexAttribI3ivEXT_Outside(__GLcontext *gc, GLuint index, const GLint *v);
extern GLvoid GL_APIENTRY  __glim_VertexAttribI4ivEXT_Outside(__GLcontext *gc, GLuint index, const GLint *v);
extern GLvoid GL_APIENTRY  __glim_VertexAttribI1uivEXT_Outside(__GLcontext *gc, GLuint index, const GLuint *v);
extern GLvoid GL_APIENTRY  __glim_VertexAttribI2uivEXT_Outside(__GLcontext *gc, GLuint index, const GLuint *v);
extern GLvoid GL_APIENTRY  __glim_VertexAttribI3uivEXT_Outside(__GLcontext *gc, GLuint index, const GLuint *v);
extern GLvoid GL_APIENTRY  __glim_VertexAttribI4uivEXT_Outside(__GLcontext *gc, GLuint index, const GLuint *v);
extern GLvoid GL_APIENTRY  __glim_VertexAttribI4bvEXT_Outside(__GLcontext *gc, GLuint index, const GLbyte *v);
extern GLvoid GL_APIENTRY  __glim_VertexAttribI4svEXT_Outside(__GLcontext *gc, GLuint index, const GLshort *v);
extern GLvoid GL_APIENTRY  __glim_VertexAttribI4ubvEXT_Outside(__GLcontext *gc, GLuint index, const GLubyte *v);
extern GLvoid GL_APIENTRY  __glim_VertexAttribI4usvEXT_Outside(__GLcontext *gc, GLuint index, const GLushort *v);

extern GLvoid GL_APIENTRY  __glim_Normal_Vertex3fv(__GLcontext *gc, const GLfloat *v);
extern GLvoid GL_APIENTRY  __glim_Normal_Vertex3fv_Cache(__GLcontext *gc, const GLfloat *v);

extern GLvoid GL_APIENTRY  __glim_Normal3b_SwitchBack(__GLcontext *gc, GLbyte, GLbyte, GLbyte);
extern GLvoid GL_APIENTRY  __glim_Normal3bv_SwitchBack(__GLcontext *gc, const GLbyte *);
extern GLvoid GL_APIENTRY  __glim_Normal3d_SwitchBack(__GLcontext *gc, GLdouble, GLdouble, GLdouble);
extern GLvoid GL_APIENTRY  __glim_Normal3dv_SwitchBack(__GLcontext *gc, const GLdouble *);
extern GLvoid GL_APIENTRY  __glim_Normal3f_SwitchBack(__GLcontext *gc, GLfloat, GLfloat, GLfloat);
extern GLvoid GL_APIENTRY  __glim_Normal3fv_SwitchBack(__GLcontext *gc, const GLfloat *);
extern GLvoid GL_APIENTRY  __glim_Normal3i_SwitchBack(__GLcontext *gc, GLint, GLint, GLint);
extern GLvoid GL_APIENTRY  __glim_Normal3iv_SwitchBack(__GLcontext *gc, const GLint *);
extern GLvoid GL_APIENTRY  __glim_Normal3s_SwitchBack(__GLcontext *gc, GLshort, GLshort, GLshort);
extern GLvoid GL_APIENTRY  __glim_Normal3sv_SwitchBack(__GLcontext *gc, const GLshort *);

extern GLvoid GL_APIENTRY  __glim_Normal3b_Cache_SwitchBack(__GLcontext *gc, GLbyte, GLbyte, GLbyte);
extern GLvoid GL_APIENTRY  __glim_Normal3bv_Cache_SwitchBack(__GLcontext *gc, const GLbyte *);
extern GLvoid GL_APIENTRY  __glim_Normal3d_Cache_SwitchBack(__GLcontext *gc, GLdouble, GLdouble, GLdouble);
extern GLvoid GL_APIENTRY  __glim_Normal3dv_Cache_SwitchBack(__GLcontext *gc, const GLdouble *);
extern GLvoid GL_APIENTRY  __glim_Normal3f_Cache_SwitchBack(__GLcontext *gc, GLfloat, GLfloat, GLfloat);
extern GLvoid GL_APIENTRY  __glim_Normal3fv_Cache_SwitchBack(__GLcontext *gc, const GLfloat *);
extern GLvoid GL_APIENTRY  __glim_Normal3i_Cache_SwitchBack(__GLcontext *gc, GLint, GLint, GLint);
extern GLvoid GL_APIENTRY  __glim_Normal3iv_Cache_SwitchBack(__GLcontext *gc, const GLint *);
extern GLvoid GL_APIENTRY  __glim_Normal3s_Cache_SwitchBack(__GLcontext *gc, GLshort, GLshort, GLshort);
extern GLvoid GL_APIENTRY  __glim_Normal3sv_Cache_SwitchBack(__GLcontext *gc, const GLshort *);

extern GLvoid GL_APIENTRY  __glim_Vertex3f_SwitchBack(__GLcontext *gc, GLfloat, GLfloat, GLfloat);
extern GLvoid GL_APIENTRY  __glim_Vertex3d_SwitchBack(__GLcontext *gc, GLdouble, GLdouble, GLdouble);
extern GLvoid GL_APIENTRY  __glim_Vertex3dv_SwitchBack(__GLcontext *gc, const GLdouble *);
extern GLvoid GL_APIENTRY  __glim_Vertex3i_SwitchBack(__GLcontext *gc, GLint, GLint, GLint);
extern GLvoid GL_APIENTRY  __glim_Vertex3iv_SwitchBack(__GLcontext *gc, const GLint *);
extern GLvoid GL_APIENTRY  __glim_Vertex3s_SwitchBack(__GLcontext *gc, GLshort, GLshort, GLshort);
extern GLvoid GL_APIENTRY  __glim_Vertex3sv_SwitchBack(__GLcontext *gc, const GLshort *);

extern GLvoid GL_APIENTRY  __glim_Vertex3f_Cache_SwitchBack(__GLcontext *gc, GLfloat, GLfloat, GLfloat);
extern GLvoid GL_APIENTRY  __glim_Vertex3d_Cache_SwitchBack(__GLcontext *gc, GLdouble, GLdouble, GLdouble);
extern GLvoid GL_APIENTRY  __glim_Vertex3dv_Cache_SwitchBack(__GLcontext *gc, const GLdouble *);
extern GLvoid GL_APIENTRY  __glim_Vertex3i_Cache_SwitchBack(__GLcontext *gc, GLint, GLint, GLint);
extern GLvoid GL_APIENTRY  __glim_Vertex3iv_Cache_SwitchBack(__GLcontext *gc, const GLint *);
extern GLvoid GL_APIENTRY  __glim_Vertex3s_Cache_SwitchBack(__GLcontext *gc, GLshort, GLshort, GLshort);
extern GLvoid GL_APIENTRY  __glim_Vertex3sv_Cache_SwitchBack(__GLcontext *gc, const GLshort *);

extern GLvoid GL_APIENTRY  __glim_Color4ubv_4fv(__GLcontext *gc, const GLubyte *v);

#endif
/* __g_imfncs_h_ */

