/****************************************************************************
*
*    Copyright (c) 2005 - 2019 by Vivante Corp.  All rights reserved.
*
*    The material in this file is confidential and contains trade secrets
*    of Vivante Corporation. This is proprietary information owned by
*    Vivante Corporation. No part of this work may be disclosed,
*    reproduced, copied, transmitted, or used in any way for any purpose,
*    without the express written permission of Vivante Corporation.
*
*****************************************************************************/


#ifndef __g_lcfncs_h_
#define __g_lcfncs_h_

extern GLvoid __gllc_InvalidValue(__GLcontext *gc);
extern GLvoid __gllc_InvalidEnum(__GLcontext *gc);
extern GLvoid __gllc_InvalidOperation(__GLcontext *gc);
extern GLvoid __gllc_TableTooLarge(__GLcontext *gc);
extern GLvoid __gllc_Error(__GLcontext *gc, GLenum error);

extern GLvoid APIENTRY __gllc_CallList(__GLcontext *,  GLuint);
extern GLvoid APIENTRY __gllc_CallLists(__GLcontext *,  GLsizei, GLenum, const GLvoid *);
extern GLvoid APIENTRY __gllc_ListBase(__GLcontext *,  GLuint);
extern GLvoid APIENTRY __gllc_Begin(__GLcontext *,  GLenum);
extern GLvoid APIENTRY __gllc_Bitmap(__GLcontext *,  GLsizei, GLsizei, GLfloat, GLfloat, GLfloat, GLfloat, const GLubyte *);
extern GLvoid APIENTRY __gllc_Color3b(__GLcontext *,  GLbyte, GLbyte, GLbyte);
extern GLvoid APIENTRY __gllc_Color3bv(__GLcontext *,  const GLbyte *);
extern GLvoid APIENTRY __gllc_Color3d(__GLcontext *,  GLdouble, GLdouble, GLdouble);
extern GLvoid APIENTRY __gllc_Color3dv(__GLcontext *,  const GLdouble *);
extern GLvoid APIENTRY __gllc_Color3f(__GLcontext *,  GLfloat, GLfloat, GLfloat);
extern GLvoid APIENTRY __gllc_Color3fv(__GLcontext *,  const GLfloat *);
extern GLvoid APIENTRY __gllc_Color3i(__GLcontext *,  GLint, GLint, GLint);
extern GLvoid APIENTRY __gllc_Color3iv(__GLcontext *,  const GLint *);
extern GLvoid APIENTRY __gllc_Color3s(__GLcontext *,  GLshort, GLshort, GLshort);
extern GLvoid APIENTRY __gllc_Color3sv(__GLcontext *,  const GLshort *);
extern GLvoid APIENTRY __gllc_Color3ub(__GLcontext *,  GLubyte, GLubyte, GLubyte);
extern GLvoid APIENTRY __gllc_Color3ubv(__GLcontext *,  const GLubyte *);
extern GLvoid APIENTRY __gllc_Color3ui(__GLcontext *,  GLuint, GLuint, GLuint);
extern GLvoid APIENTRY __gllc_Color3uiv(__GLcontext *,  const GLuint *);
extern GLvoid APIENTRY __gllc_Color3us(__GLcontext *,  GLushort, GLushort, GLushort);
extern GLvoid APIENTRY __gllc_Color3usv(__GLcontext *,  const GLushort *);
extern GLvoid APIENTRY __gllc_Color4b(__GLcontext *,  GLbyte, GLbyte, GLbyte, GLbyte);
extern GLvoid APIENTRY __gllc_Color4bv(__GLcontext *,  const GLbyte *);
extern GLvoid APIENTRY __gllc_Color4d(__GLcontext *,  GLdouble, GLdouble, GLdouble, GLdouble);
extern GLvoid APIENTRY __gllc_Color4dv(__GLcontext *,  const GLdouble *);
extern GLvoid APIENTRY __gllc_Color4f(__GLcontext *,  GLfloat, GLfloat, GLfloat, GLfloat);
extern GLvoid APIENTRY __gllc_Color4fv(__GLcontext *,  const GLfloat *);
extern GLvoid APIENTRY __gllc_Color4i(__GLcontext *,  GLint, GLint, GLint, GLint);
extern GLvoid APIENTRY __gllc_Color4iv(__GLcontext *,  const GLint *);
extern GLvoid APIENTRY __gllc_Color4s(__GLcontext *,  GLshort, GLshort, GLshort, GLshort);
extern GLvoid APIENTRY __gllc_Color4sv(__GLcontext *,  const GLshort *);
extern GLvoid APIENTRY __gllc_Color4ub(__GLcontext *,  GLubyte, GLubyte, GLubyte, GLubyte);
extern GLvoid APIENTRY __gllc_Color4ubv(__GLcontext *,  const GLubyte *);
extern GLvoid APIENTRY __gllc_Color4ui(__GLcontext *,  GLuint, GLuint, GLuint, GLuint);
extern GLvoid APIENTRY __gllc_Color4uiv(__GLcontext *,  const GLuint *);
extern GLvoid APIENTRY __gllc_Color4us(__GLcontext *,  GLushort, GLushort, GLushort, GLushort);
extern GLvoid APIENTRY __gllc_Color4usv(__GLcontext *,  const GLushort *);
extern GLvoid APIENTRY __gllc_EdgeFlag(__GLcontext *,  GLboolean);
extern GLvoid APIENTRY __gllc_EdgeFlagv(__GLcontext *,  const GLboolean *);
extern GLvoid APIENTRY __gllc_End(__GLcontext *);
extern GLvoid APIENTRY __gllc_Indexd(__GLcontext *,  GLdouble);
extern GLvoid APIENTRY __gllc_Indexdv(__GLcontext *,  const GLdouble *);
extern GLvoid APIENTRY __gllc_Indexf(__GLcontext *,  GLfloat);
extern GLvoid APIENTRY __gllc_Indexfv(__GLcontext *,  const GLfloat *);
extern GLvoid APIENTRY __gllc_Indexi(__GLcontext *,  GLint);
extern GLvoid APIENTRY __gllc_Indexiv(__GLcontext *,  const GLint *);
extern GLvoid APIENTRY __gllc_Indexs(__GLcontext *,  GLshort);
extern GLvoid APIENTRY __gllc_Indexsv(__GLcontext *,  const GLshort *);
extern GLvoid APIENTRY __gllc_Normal3b(__GLcontext *,  GLbyte, GLbyte, GLbyte);
extern GLvoid APIENTRY __gllc_Normal3bv(__GLcontext *,  const GLbyte *);
extern GLvoid APIENTRY __gllc_Normal3d(__GLcontext *,  GLdouble, GLdouble, GLdouble);
extern GLvoid APIENTRY __gllc_Normal3dv(__GLcontext *,  const GLdouble *);
extern GLvoid APIENTRY __gllc_Normal3f(__GLcontext *,  GLfloat, GLfloat, GLfloat);
extern GLvoid APIENTRY __gllc_Normal3fv(__GLcontext *,  const GLfloat *);
extern GLvoid APIENTRY __gllc_Normal3i(__GLcontext *,  GLint, GLint, GLint);
extern GLvoid APIENTRY __gllc_Normal3iv(__GLcontext *,  const GLint *);
extern GLvoid APIENTRY __gllc_Normal3s(__GLcontext *,  GLshort, GLshort, GLshort);
extern GLvoid APIENTRY __gllc_Normal3sv(__GLcontext *,  const GLshort *);
extern GLvoid APIENTRY __gllc_RasterPos2d(__GLcontext *,  GLdouble, GLdouble);
extern GLvoid APIENTRY __gllc_RasterPos2dv(__GLcontext *,  const GLdouble *);
extern GLvoid APIENTRY __gllc_RasterPos2f(__GLcontext *,  GLfloat, GLfloat);
extern GLvoid APIENTRY __gllc_RasterPos2fv(__GLcontext *,  const GLfloat *);
extern GLvoid APIENTRY __gllc_RasterPos2i(__GLcontext *,  GLint, GLint);
extern GLvoid APIENTRY __gllc_RasterPos2iv(__GLcontext *,  const GLint *);
extern GLvoid APIENTRY __gllc_RasterPos2s(__GLcontext *,  GLshort, GLshort);
extern GLvoid APIENTRY __gllc_RasterPos2sv(__GLcontext *,  const GLshort *);
extern GLvoid APIENTRY __gllc_RasterPos3d(__GLcontext *,  GLdouble, GLdouble, GLdouble);
extern GLvoid APIENTRY __gllc_RasterPos3dv(__GLcontext *,  const GLdouble *);
extern GLvoid APIENTRY __gllc_RasterPos3f(__GLcontext *,  GLfloat, GLfloat, GLfloat);
extern GLvoid APIENTRY __gllc_RasterPos3fv(__GLcontext *,  const GLfloat *);
extern GLvoid APIENTRY __gllc_RasterPos3i(__GLcontext *,  GLint, GLint, GLint);
extern GLvoid APIENTRY __gllc_RasterPos3iv(__GLcontext *,  const GLint *);
extern GLvoid APIENTRY __gllc_RasterPos3s(__GLcontext *,  GLshort, GLshort, GLshort);
extern GLvoid APIENTRY __gllc_RasterPos3sv(__GLcontext *,  const GLshort *);
extern GLvoid APIENTRY __gllc_RasterPos4d(__GLcontext *,  GLdouble, GLdouble, GLdouble, GLdouble);
extern GLvoid APIENTRY __gllc_RasterPos4dv(__GLcontext *,  const GLdouble *);
extern GLvoid APIENTRY __gllc_RasterPos4f(__GLcontext *,  GLfloat, GLfloat, GLfloat, GLfloat);
extern GLvoid APIENTRY __gllc_RasterPos4fv(__GLcontext *,  const GLfloat *);
extern GLvoid APIENTRY __gllc_RasterPos4i(__GLcontext *,  GLint, GLint, GLint, GLint);
extern GLvoid APIENTRY __gllc_RasterPos4iv(__GLcontext *,  const GLint *);
extern GLvoid APIENTRY __gllc_RasterPos4s(__GLcontext *,  GLshort, GLshort, GLshort, GLshort);
extern GLvoid APIENTRY __gllc_RasterPos4sv(__GLcontext *,  const GLshort *);
extern GLvoid APIENTRY __gllc_Rectd(__GLcontext *,  GLdouble, GLdouble, GLdouble, GLdouble);
extern GLvoid APIENTRY __gllc_Rectdv(__GLcontext *,  const GLdouble *, const GLdouble *);
extern GLvoid APIENTRY __gllc_Rectf(__GLcontext *,  GLfloat, GLfloat, GLfloat, GLfloat);
extern GLvoid APIENTRY __gllc_Rectfv(__GLcontext *,  const GLfloat *, const GLfloat *);
extern GLvoid APIENTRY __gllc_Recti(__GLcontext *,  GLint, GLint, GLint, GLint);
extern GLvoid APIENTRY __gllc_Rectiv(__GLcontext *,  const GLint *, const GLint *);
extern GLvoid APIENTRY __gllc_Rects(__GLcontext *,  GLshort, GLshort, GLshort, GLshort);
extern GLvoid APIENTRY __gllc_Rectsv(__GLcontext *,  const GLshort *, const GLshort *);
extern GLvoid APIENTRY __gllc_TexCoord1d(__GLcontext *,  GLdouble);
extern GLvoid APIENTRY __gllc_TexCoord1dv(__GLcontext *,  const GLdouble *);
extern GLvoid APIENTRY __gllc_TexCoord1f(__GLcontext *,  GLfloat);
extern GLvoid APIENTRY __gllc_TexCoord1fv(__GLcontext *,  const GLfloat *);
extern GLvoid APIENTRY __gllc_TexCoord1i(__GLcontext *,  GLint);
extern GLvoid APIENTRY __gllc_TexCoord1iv(__GLcontext *,  const GLint *);
extern GLvoid APIENTRY __gllc_TexCoord1s(__GLcontext *,  GLshort);
extern GLvoid APIENTRY __gllc_TexCoord1sv(__GLcontext *,  const GLshort *);
extern GLvoid APIENTRY __gllc_TexCoord2d(__GLcontext *,  GLdouble, GLdouble);
extern GLvoid APIENTRY __gllc_TexCoord2dv(__GLcontext *,  const GLdouble *);
extern GLvoid APIENTRY __gllc_TexCoord2f(__GLcontext *,  GLfloat, GLfloat);
extern GLvoid APIENTRY __gllc_TexCoord2fv(__GLcontext *,  const GLfloat *);
extern GLvoid APIENTRY __gllc_TexCoord2i(__GLcontext *,  GLint, GLint);
extern GLvoid APIENTRY __gllc_TexCoord2iv(__GLcontext *,  const GLint *);
extern GLvoid APIENTRY __gllc_TexCoord2s(__GLcontext *,  GLshort, GLshort);
extern GLvoid APIENTRY __gllc_TexCoord2sv(__GLcontext *,  const GLshort *);
extern GLvoid APIENTRY __gllc_TexCoord3d(__GLcontext *,  GLdouble, GLdouble, GLdouble);
extern GLvoid APIENTRY __gllc_TexCoord3dv(__GLcontext *,  const GLdouble *);
extern GLvoid APIENTRY __gllc_TexCoord3f(__GLcontext *,  GLfloat, GLfloat, GLfloat);
extern GLvoid APIENTRY __gllc_TexCoord3fv(__GLcontext *,  const GLfloat *);
extern GLvoid APIENTRY __gllc_TexCoord3i(__GLcontext *,  GLint, GLint, GLint);
extern GLvoid APIENTRY __gllc_TexCoord3iv(__GLcontext *,  const GLint *);
extern GLvoid APIENTRY __gllc_TexCoord3s(__GLcontext *,  GLshort, GLshort, GLshort);
extern GLvoid APIENTRY __gllc_TexCoord3sv(__GLcontext *,  const GLshort *);
extern GLvoid APIENTRY __gllc_TexCoord4d(__GLcontext *,  GLdouble, GLdouble, GLdouble, GLdouble);
extern GLvoid APIENTRY __gllc_TexCoord4dv(__GLcontext *,  const GLdouble *);
extern GLvoid APIENTRY __gllc_TexCoord4f(__GLcontext *,  GLfloat, GLfloat, GLfloat, GLfloat);
extern GLvoid APIENTRY __gllc_TexCoord4fv(__GLcontext *,  const GLfloat *);
extern GLvoid APIENTRY __gllc_TexCoord4i(__GLcontext *,  GLint, GLint, GLint, GLint);
extern GLvoid APIENTRY __gllc_TexCoord4iv(__GLcontext *,  const GLint *);
extern GLvoid APIENTRY __gllc_TexCoord4s(__GLcontext *,  GLshort, GLshort, GLshort, GLshort);
extern GLvoid APIENTRY __gllc_TexCoord4sv(__GLcontext *,  const GLshort *);
extern GLvoid APIENTRY __gllc_Vertex2d(__GLcontext *,  GLdouble, GLdouble);
extern GLvoid APIENTRY __gllc_Vertex2dv(__GLcontext *,  const GLdouble *);
extern GLvoid APIENTRY __gllc_Vertex2f(__GLcontext *,  GLfloat, GLfloat);
extern GLvoid APIENTRY __gllc_Vertex2fv(__GLcontext *,  const GLfloat *);
extern GLvoid APIENTRY __gllc_Vertex2i(__GLcontext *,  GLint, GLint);
extern GLvoid APIENTRY __gllc_Vertex2iv(__GLcontext *,  const GLint *);
extern GLvoid APIENTRY __gllc_Vertex2s(__GLcontext *,  GLshort, GLshort);
extern GLvoid APIENTRY __gllc_Vertex2sv(__GLcontext *,  const GLshort *);
extern GLvoid APIENTRY __gllc_Vertex3d(__GLcontext *,  GLdouble, GLdouble, GLdouble);
extern GLvoid APIENTRY __gllc_Vertex3dv(__GLcontext *,  const GLdouble *);
extern GLvoid APIENTRY __gllc_Vertex3f(__GLcontext *,  GLfloat, GLfloat, GLfloat);
extern GLvoid APIENTRY __gllc_Vertex3fv(__GLcontext *,  const GLfloat *);
extern GLvoid APIENTRY __gllc_Vertex3i(__GLcontext *,  GLint, GLint, GLint);
extern GLvoid APIENTRY __gllc_Vertex3iv(__GLcontext *,  const GLint *);
extern GLvoid APIENTRY __gllc_Vertex3s(__GLcontext *,  GLshort, GLshort, GLshort);
extern GLvoid APIENTRY __gllc_Vertex3sv(__GLcontext *,  const GLshort *);
extern GLvoid APIENTRY __gllc_Vertex4d(__GLcontext *,  GLdouble, GLdouble, GLdouble, GLdouble);
extern GLvoid APIENTRY __gllc_Vertex4dv(__GLcontext *,  const GLdouble *);
extern GLvoid APIENTRY __gllc_Vertex4f(__GLcontext *,  GLfloat, GLfloat, GLfloat, GLfloat);
extern GLvoid APIENTRY __gllc_Vertex4fv(__GLcontext *,  const GLfloat *);
extern GLvoid APIENTRY __gllc_Vertex4i(__GLcontext *,  GLint, GLint, GLint, GLint);
extern GLvoid APIENTRY __gllc_Vertex4iv(__GLcontext *,  const GLint *);
extern GLvoid APIENTRY __gllc_Vertex4s(__GLcontext *,  GLshort, GLshort, GLshort, GLshort);
extern GLvoid APIENTRY __gllc_Vertex4sv(__GLcontext *,  const GLshort *);
extern GLvoid APIENTRY __gllc_DrawElements(__GLcontext *,  GLenum, GLsizei, GLenum, const GLvoid *);
extern GLvoid APIENTRY __gllc_ArrayElement(__GLcontext *,  GLint);
extern GLvoid APIENTRY __gllc_DrawArrays(__GLcontext *,  GLenum, GLint, GLsizei);
extern GLvoid APIENTRY __gllc_ClipPlane(__GLcontext *,  GLenum, const GLdouble *);
extern GLvoid APIENTRY __gllc_ColorMaterial(__GLcontext *,  GLenum, GLenum);
extern GLvoid APIENTRY __gllc_CullFace(__GLcontext *,  GLenum);
extern GLvoid APIENTRY __gllc_Fogf(__GLcontext *,  GLenum, GLfloat);
extern GLvoid APIENTRY __gllc_Fogfv(__GLcontext *,  GLenum, const GLfloat *);
extern GLvoid APIENTRY __gllc_Fogi(__GLcontext *,  GLenum, GLint);
extern GLvoid APIENTRY __gllc_Fogiv(__GLcontext *,  GLenum, const GLint *);
extern GLvoid APIENTRY __gllc_FrontFace(__GLcontext *,  GLenum);
extern GLvoid APIENTRY __gllc_Hint(__GLcontext *,  GLenum, GLenum);
extern GLvoid APIENTRY __gllc_Lightf(__GLcontext *,  GLenum, GLenum, GLfloat);
extern GLvoid APIENTRY __gllc_Lightfv(__GLcontext *,  GLenum, GLenum, const GLfloat *);
extern GLvoid APIENTRY __gllc_Lighti(__GLcontext *,  GLenum, GLenum, GLint);
extern GLvoid APIENTRY __gllc_Lightiv(__GLcontext *,  GLenum, GLenum, const GLint *);
extern GLvoid APIENTRY __gllc_LightModelf(__GLcontext *,  GLenum, GLfloat);
extern GLvoid APIENTRY __gllc_LightModelfv(__GLcontext *,  GLenum, const GLfloat *);
extern GLvoid APIENTRY __gllc_LightModeli(__GLcontext *,  GLenum, GLint);
extern GLvoid APIENTRY __gllc_LightModeliv(__GLcontext *,  GLenum, const GLint *);
extern GLvoid APIENTRY __gllc_LineStipple(__GLcontext *,  GLint, GLushort);
extern GLvoid APIENTRY __gllc_LineWidth(__GLcontext *,  GLfloat);
extern GLvoid APIENTRY __gllc_Materialf(__GLcontext *,  GLenum, GLenum, GLfloat);
extern GLvoid APIENTRY __gllc_Materialfv(__GLcontext *,  GLenum, GLenum, const GLfloat *);
extern GLvoid APIENTRY __gllc_Materiali(__GLcontext *,  GLenum, GLenum, GLint);
extern GLvoid APIENTRY __gllc_Materialiv(__GLcontext *,  GLenum, GLenum, const GLint *);
extern GLvoid APIENTRY __gllc_PointSize(__GLcontext *,  GLfloat);
extern GLvoid APIENTRY __gllc_PolygonMode(__GLcontext *,  GLenum, GLenum);
extern GLvoid APIENTRY __gllc_PolygonStipple(__GLcontext *,  const GLubyte *);
extern GLvoid APIENTRY __gllc_Scissor(__GLcontext *,  GLint, GLint, GLsizei, GLsizei);
extern GLvoid APIENTRY __gllc_ShadeModel(__GLcontext *,  GLenum);
extern GLvoid APIENTRY __gllc_TexParameterf(__GLcontext *,  GLenum, GLenum, GLfloat);
extern GLvoid APIENTRY __gllc_TexParameterfv(__GLcontext *,  GLenum, GLenum, const GLfloat *);
extern GLvoid APIENTRY __gllc_TexParameteri(__GLcontext *,  GLenum, GLenum, GLint);
extern GLvoid APIENTRY __gllc_TexParameteriv(__GLcontext *,  GLenum, GLenum, const GLint *);
extern GLvoid APIENTRY __gllc_TexImage1D(__GLcontext *,  GLenum, GLint, GLint, GLsizei, GLint, GLenum, GLenum, const GLvoid *);
extern GLvoid APIENTRY __gllc_TexImage2D(__GLcontext *,  GLenum, GLint, GLint, GLsizei, GLsizei, GLint, GLenum, GLenum, const GLvoid *);
extern GLvoid APIENTRY __gllc_TexEnvf(__GLcontext *,  GLenum, GLenum, GLfloat);
extern GLvoid APIENTRY __gllc_TexEnvfv(__GLcontext *,  GLenum, GLenum, const GLfloat *);
extern GLvoid APIENTRY __gllc_TexEnvi(__GLcontext *,  GLenum, GLenum, GLint);
extern GLvoid APIENTRY __gllc_TexEnviv(__GLcontext *,  GLenum, GLenum, const GLint *);
extern GLvoid APIENTRY __gllc_TexGend(__GLcontext *,  GLenum, GLenum, GLdouble);
extern GLvoid APIENTRY __gllc_TexGendv(__GLcontext *,  GLenum, GLenum, const GLdouble *);
extern GLvoid APIENTRY __gllc_TexGenf(__GLcontext *,  GLenum, GLenum, GLfloat);
extern GLvoid APIENTRY __gllc_TexGenfv(__GLcontext *,  GLenum, GLenum, const GLfloat *);
extern GLvoid APIENTRY __gllc_TexGeni(__GLcontext *,  GLenum, GLenum, GLint);
extern GLvoid APIENTRY __gllc_TexGeniv(__GLcontext *,  GLenum, GLenum, const GLint *);
extern GLvoid APIENTRY __gllc_InitNames(__GLcontext *);
extern GLvoid APIENTRY __gllc_LoadName(__GLcontext *,  GLuint);
extern GLvoid APIENTRY __gllc_PassThrough(__GLcontext *,  GLfloat);
extern GLvoid APIENTRY __gllc_PopName(__GLcontext *);
extern GLvoid APIENTRY __gllc_PushName(__GLcontext *,  GLuint);
extern GLvoid APIENTRY __gllc_DrawBuffer(__GLcontext *,  GLenum);
extern GLvoid APIENTRY __gllc_Clear(__GLcontext *,  GLbitfield);
extern GLvoid APIENTRY __gllc_ClearAccum(__GLcontext *,  GLfloat, GLfloat, GLfloat, GLfloat);
extern GLvoid APIENTRY __gllc_ClearIndex(__GLcontext *,  GLfloat);
extern GLvoid APIENTRY __gllc_ClearColor(__GLcontext *,  GLclampf, GLclampf, GLclampf, GLclampf);
extern GLvoid APIENTRY __gllc_ClearStencil(__GLcontext *,  GLint);
extern GLvoid APIENTRY __gllc_ClearDepth(__GLcontext *,  GLclampd);
extern GLvoid APIENTRY __gllc_StencilMask(__GLcontext *,  GLuint);
extern GLvoid APIENTRY __gllc_ColorMask(__GLcontext *,  GLboolean, GLboolean, GLboolean, GLboolean);
extern GLvoid APIENTRY __gllc_DepthMask(__GLcontext *,  GLboolean);
extern GLvoid APIENTRY __gllc_IndexMask(__GLcontext *,  GLuint);
extern GLvoid APIENTRY __gllc_Accum(__GLcontext *,  GLenum, GLfloat);
extern GLvoid APIENTRY __gllc_Disable(__GLcontext *,  GLenum);
extern GLvoid APIENTRY __gllc_Enable(__GLcontext *,  GLenum);
extern GLvoid APIENTRY __gllc_PopAttrib(__GLcontext *);
extern GLvoid APIENTRY __gllc_PushAttrib(__GLcontext *,  GLbitfield);
extern GLvoid APIENTRY __gllc_Map1d(__GLcontext *,  GLenum, GLdouble, GLdouble, GLint, GLint, const GLdouble *);
extern GLvoid APIENTRY __gllc_Map1f(__GLcontext *,  GLenum, GLfloat, GLfloat, GLint, GLint, const GLfloat *);
extern GLvoid APIENTRY __gllc_Map2d(__GLcontext *,  GLenum, GLdouble, GLdouble, GLint, GLint, GLdouble, GLdouble, GLint, GLint, const GLdouble *);
extern GLvoid APIENTRY __gllc_Map2f(__GLcontext *,  GLenum, GLfloat, GLfloat, GLint, GLint, GLfloat, GLfloat, GLint, GLint, const GLfloat *);
extern GLvoid APIENTRY __gllc_MapGrid1d(__GLcontext *,  GLint, GLdouble, GLdouble);
extern GLvoid APIENTRY __gllc_MapGrid1f(__GLcontext *,  GLint, GLfloat, GLfloat);
extern GLvoid APIENTRY __gllc_MapGrid2d(__GLcontext *,  GLint, GLdouble, GLdouble, GLint, GLdouble, GLdouble);
extern GLvoid APIENTRY __gllc_MapGrid2f(__GLcontext *,  GLint, GLfloat, GLfloat, GLint, GLfloat, GLfloat);
extern GLvoid APIENTRY __gllc_EvalCoord1d(__GLcontext *,  GLdouble);
extern GLvoid APIENTRY __gllc_EvalCoord1dv(__GLcontext *,  const GLdouble *);
extern GLvoid APIENTRY __gllc_EvalCoord1f(__GLcontext *,  GLfloat);
extern GLvoid APIENTRY __gllc_EvalCoord1fv(__GLcontext *,  const GLfloat *);
extern GLvoid APIENTRY __gllc_EvalCoord2d(__GLcontext *,  GLdouble, GLdouble);
extern GLvoid APIENTRY __gllc_EvalCoord2dv(__GLcontext *,  const GLdouble *);
extern GLvoid APIENTRY __gllc_EvalCoord2f(__GLcontext *,  GLfloat, GLfloat);
extern GLvoid APIENTRY __gllc_EvalCoord2fv(__GLcontext *,  const GLfloat *);
extern GLvoid APIENTRY __gllc_EvalMesh1(__GLcontext *,  GLenum, GLint, GLint);
extern GLvoid APIENTRY __gllc_EvalPoint1(__GLcontext *,  GLint);
extern GLvoid APIENTRY __gllc_EvalMesh2(__GLcontext *,  GLenum, GLint, GLint, GLint, GLint);
extern GLvoid APIENTRY __gllc_EvalPoint2(__GLcontext *,  GLint, GLint);
extern GLvoid APIENTRY __gllc_AlphaFunc(__GLcontext *,  GLenum, GLclampf);
extern GLvoid APIENTRY __gllc_BlendFunc(__GLcontext *,  GLenum, GLenum);
extern GLvoid APIENTRY __gllc_LogicOp(__GLcontext *,  GLenum);
extern GLvoid APIENTRY __gllc_StencilFunc(__GLcontext *,  GLenum, GLint, GLuint);
extern GLvoid APIENTRY __gllc_StencilOp(__GLcontext *,  GLenum, GLenum, GLenum);
extern GLvoid APIENTRY __gllc_DepthFunc(__GLcontext *,  GLenum);
extern GLvoid APIENTRY __gllc_PixelZoom(__GLcontext *,  GLfloat, GLfloat);
extern GLvoid APIENTRY __gllc_PixelTransferf(__GLcontext *,  GLenum, GLfloat);
extern GLvoid APIENTRY __gllc_PixelTransferi(__GLcontext *,  GLenum, GLint);
extern GLvoid APIENTRY __gllc_PixelMapfv(__GLcontext *,  GLenum, GLint, const GLfloat *);
extern GLvoid APIENTRY __gllc_PixelMapuiv(__GLcontext *,  GLenum, GLint, const GLuint *);
extern GLvoid APIENTRY __gllc_PixelMapusv(__GLcontext *,  GLenum, GLint, const GLushort *);
extern GLvoid APIENTRY __gllc_ReadBuffer(__GLcontext *,  GLenum);
extern GLvoid APIENTRY __gllc_CopyPixels(__GLcontext *,  GLint, GLint, GLsizei, GLsizei, GLenum);
extern GLvoid APIENTRY __gllc_DrawPixels(__GLcontext *,  GLsizei, GLsizei, GLenum, GLenum, const GLvoid *);
extern GLvoid APIENTRY __gllc_DepthRange(__GLcontext *,  GLclampd, GLclampd);
extern GLvoid APIENTRY __gllc_Frustum(__GLcontext *,  GLdouble, GLdouble, GLdouble, GLdouble, GLdouble, GLdouble);
extern GLvoid APIENTRY __gllc_LoadIdentity(__GLcontext *);
extern GLvoid APIENTRY __gllc_LoadMatrixf(__GLcontext *,  const GLfloat *);
extern GLvoid APIENTRY __gllc_LoadMatrixd(__GLcontext *,  const GLdouble *);
extern GLvoid APIENTRY __gllc_MatrixMode(__GLcontext *,  GLenum);
extern GLvoid APIENTRY __gllc_MultMatrixf(__GLcontext *,  const GLfloat *);
extern GLvoid APIENTRY __gllc_MultMatrixd(__GLcontext *,  const GLdouble *);
extern GLvoid APIENTRY __gllc_Ortho(__GLcontext *,  GLdouble, GLdouble, GLdouble, GLdouble, GLdouble, GLdouble);
extern GLvoid APIENTRY __gllc_PopMatrix(__GLcontext *);
extern GLvoid APIENTRY __gllc_PushMatrix(__GLcontext *);
extern GLvoid APIENTRY __gllc_Rotated(__GLcontext *,  GLdouble, GLdouble, GLdouble, GLdouble);
extern GLvoid APIENTRY __gllc_Rotatef(__GLcontext *,  GLfloat, GLfloat, GLfloat, GLfloat);
extern GLvoid APIENTRY __gllc_Scaled(__GLcontext *,  GLdouble, GLdouble, GLdouble);
extern GLvoid APIENTRY __gllc_Scalef(__GLcontext *,  GLfloat, GLfloat, GLfloat);
extern GLvoid APIENTRY __gllc_Translated(__GLcontext *,  GLdouble, GLdouble, GLdouble);
extern GLvoid APIENTRY __gllc_Translatef(__GLcontext *,  GLfloat, GLfloat, GLfloat);
extern GLvoid APIENTRY __gllc_Viewport(__GLcontext *,  GLint, GLint, GLsizei, GLsizei);
extern GLvoid APIENTRY __gllc_PolygonOffset(__GLcontext *,  GLfloat, GLfloat);
extern GLvoid APIENTRY __gllc_CopyTexImage1D(__GLcontext *,  GLenum, GLint, GLenum, GLint, GLint, GLsizei, GLint);
extern GLvoid APIENTRY __gllc_CopyTexImage2D(__GLcontext *,  GLenum, GLint, GLenum, GLint, GLint, GLsizei, GLsizei, GLint);
extern GLvoid APIENTRY __gllc_CopyTexSubImage1D(__GLcontext *,  GLenum, GLint, GLint, GLint, GLint, GLsizei);
extern GLvoid APIENTRY __gllc_CopyTexSubImage2D(__GLcontext *,  GLenum, GLint, GLint, GLint, GLint, GLint, GLsizei, GLsizei);
extern GLvoid APIENTRY __gllc_TexSubImage1D(__GLcontext *,  GLenum, GLint, GLint, GLsizei, GLenum, GLenum, const GLvoid *);
extern GLvoid APIENTRY __gllc_TexSubImage2D(__GLcontext *,  GLenum, GLint, GLint, GLint, GLsizei, GLsizei, GLenum, GLenum, const GLvoid *);
extern GLvoid APIENTRY __gllc_BindTexture(__GLcontext *,  GLenum, GLuint);
extern GLvoid APIENTRY __gllc_PrioritizeTextures(__GLcontext *,  GLsizei, const GLuint *, const GLclampf *);
extern GLvoid APIENTRY __gllc_Indexub(__GLcontext *,  GLubyte);
extern GLvoid APIENTRY __gllc_Indexubv(__GLcontext *,  const GLubyte *);

#if GL_VERSION_1_2
extern GLvoid APIENTRY __gllc_DrawRangeElements(__GLcontext *,  GLenum, GLuint, GLuint, GLsizei, GLenum, const GLvoid *);
extern GLvoid APIENTRY __gllc_TexImage3D(__GLcontext *,  GLenum, GLint, GLint, GLsizei, GLsizei, GLsizei, GLint, GLenum, GLenum, const GLvoid *);
extern GLvoid APIENTRY __gllc_TexSubImage3D(__GLcontext *,  GLenum, GLint, GLint, GLint, GLint, GLsizei, GLsizei, GLsizei, GLenum, GLenum, const GLvoid *);
extern GLvoid APIENTRY __gllc_CopyTexSubImage3D(__GLcontext *,  GLenum, GLint, GLint, GLint, GLint, GLint, GLint, GLsizei, GLsizei);
#endif
#if GL_VERSION_1_3
extern GLvoid APIENTRY __gllc_ActiveTexture(__GLcontext *,  GLenum);
extern GLvoid APIENTRY __gllc_MultiTexCoord1d(__GLcontext *,  GLenum, GLdouble);
extern GLvoid APIENTRY __gllc_MultiTexCoord1dv(__GLcontext *,  GLenum, const GLdouble *);
extern GLvoid APIENTRY __gllc_MultiTexCoord1f(__GLcontext *,  GLenum, GLfloat);
extern GLvoid APIENTRY __gllc_MultiTexCoord1fv(__GLcontext *,  GLenum, const GLfloat *);
extern GLvoid APIENTRY __gllc_MultiTexCoord1i(__GLcontext *,  GLenum, GLint);
extern GLvoid APIENTRY __gllc_MultiTexCoord1iv(__GLcontext *,  GLenum, const GLint *);
extern GLvoid APIENTRY __gllc_MultiTexCoord1s(__GLcontext *,  GLenum, GLshort);
extern GLvoid APIENTRY __gllc_MultiTexCoord1sv(__GLcontext *,  GLenum, const GLshort *);
extern GLvoid APIENTRY __gllc_MultiTexCoord2d(__GLcontext *,  GLenum, GLdouble, GLdouble);
extern GLvoid APIENTRY __gllc_MultiTexCoord2dv(__GLcontext *,  GLenum, const GLdouble *);
extern GLvoid APIENTRY __gllc_MultiTexCoord2f(__GLcontext *,  GLenum, GLfloat, GLfloat);
extern GLvoid APIENTRY __gllc_MultiTexCoord2fv(__GLcontext *,  GLenum, const GLfloat *);
extern GLvoid APIENTRY __gllc_MultiTexCoord2i(__GLcontext *,  GLenum, GLint, GLint);
extern GLvoid APIENTRY __gllc_MultiTexCoord2iv(__GLcontext *,  GLenum, const GLint *);
extern GLvoid APIENTRY __gllc_MultiTexCoord2s(__GLcontext *,  GLenum, GLshort, GLshort);
extern GLvoid APIENTRY __gllc_MultiTexCoord2sv(__GLcontext *,  GLenum, const GLshort *);
extern GLvoid APIENTRY __gllc_MultiTexCoord3d(__GLcontext *,  GLenum, GLdouble, GLdouble, GLdouble);
extern GLvoid APIENTRY __gllc_MultiTexCoord3dv(__GLcontext *,  GLenum, const GLdouble *);
extern GLvoid APIENTRY __gllc_MultiTexCoord3f(__GLcontext *,  GLenum, GLfloat, GLfloat, GLfloat);
extern GLvoid APIENTRY __gllc_MultiTexCoord3fv(__GLcontext *,  GLenum, const GLfloat *);
extern GLvoid APIENTRY __gllc_MultiTexCoord3i(__GLcontext *,  GLenum, GLint, GLint, GLint);
extern GLvoid APIENTRY __gllc_MultiTexCoord3iv(__GLcontext *,  GLenum, const GLint *);
extern GLvoid APIENTRY __gllc_MultiTexCoord3s(__GLcontext *,  GLenum, GLshort, GLshort, GLshort);
extern GLvoid APIENTRY __gllc_MultiTexCoord3sv(__GLcontext *,  GLenum, const GLshort *);
extern GLvoid APIENTRY __gllc_MultiTexCoord4d(__GLcontext *,  GLenum, GLdouble, GLdouble, GLdouble, GLdouble);
extern GLvoid APIENTRY __gllc_MultiTexCoord4dv(__GLcontext *,  GLenum, const GLdouble *);
extern GLvoid APIENTRY __gllc_MultiTexCoord4f(__GLcontext *,  GLenum, GLfloat, GLfloat, GLfloat, GLfloat);
extern GLvoid APIENTRY __gllc_MultiTexCoord4fv(__GLcontext *,  GLenum, const GLfloat *);
extern GLvoid APIENTRY __gllc_MultiTexCoord4i(__GLcontext *,  GLenum, GLint, GLint, GLint, GLint);
extern GLvoid APIENTRY __gllc_MultiTexCoord4iv(__GLcontext *,  GLenum, const GLint *);
extern GLvoid APIENTRY __gllc_MultiTexCoord4s(__GLcontext *,  GLenum, GLshort, GLshort, GLshort, GLshort);
extern GLvoid APIENTRY __gllc_MultiTexCoord4sv(__GLcontext *,  GLenum, const GLshort *);
extern GLvoid APIENTRY __gllc_LoadTransposeMatrixf(__GLcontext *,  const GLfloat *);
extern GLvoid APIENTRY __gllc_LoadTransposeMatrixd(__GLcontext *,  const GLdouble *);
extern GLvoid APIENTRY __gllc_MultTransposeMatrixf(__GLcontext *,  const GLfloat *);
extern GLvoid APIENTRY __gllc_MultTransposeMatrixd(__GLcontext *,  const GLdouble *);
extern GLvoid APIENTRY __gllc_SampleCoverage(__GLcontext *,  GLclampf, GLboolean);
extern GLvoid APIENTRY __gllc_CompressedTexImage3D(__GLcontext *,  GLenum, GLint, GLenum, GLsizei, GLsizei, GLsizei, GLint, GLsizei, const GLvoid *);
extern GLvoid APIENTRY __gllc_CompressedTexImage2D(__GLcontext *,  GLenum, GLint, GLenum, GLsizei, GLsizei, GLint, GLsizei, const GLvoid *);
extern GLvoid APIENTRY __gllc_CompressedTexImage1D(__GLcontext *,  GLenum, GLint, GLenum, GLsizei, GLint, GLsizei, const GLvoid *);
extern GLvoid APIENTRY __gllc_CompressedTexSubImage3D(__GLcontext *,  GLenum, GLint, GLint, GLint, GLint, GLsizei, GLsizei, GLsizei, GLenum, GLsizei, const GLvoid *);
extern GLvoid APIENTRY __gllc_CompressedTexSubImage2D(__GLcontext *,  GLenum, GLint, GLint, GLint, GLsizei, GLsizei, GLenum, GLsizei, const GLvoid *);
extern GLvoid APIENTRY __gllc_CompressedTexSubImage1D(__GLcontext *,  GLenum, GLint, GLint, GLsizei, GLenum, GLsizei, const GLvoid *);
#endif
#if GL_VERSION_1_4
extern GLvoid APIENTRY __gllc_BlendFuncSeparate(__GLcontext *,  GLenum, GLenum, GLenum, GLenum);
extern GLvoid APIENTRY __gllc_FogCoordf(__GLcontext *,  GLfloat);
extern GLvoid APIENTRY __gllc_FogCoordfv(__GLcontext *,  const GLfloat *);
extern GLvoid APIENTRY __gllc_FogCoordd(__GLcontext *,  GLdouble);
extern GLvoid APIENTRY __gllc_FogCoorddv(__GLcontext *,  const GLdouble *);
extern GLvoid APIENTRY __gllc_MultiDrawArrays(__GLcontext *,  GLenum, const GLint*, const GLsizei*, GLsizei);
extern GLvoid APIENTRY __gllc_MultiDrawElements(__GLcontext *,  GLenum, const GLsizei *, GLenum, const GLvoid* const*, GLsizei);
extern GLvoid APIENTRY __gllc_PointParameterf(__GLcontext *,  GLenum, GLfloat);
extern GLvoid APIENTRY __gllc_PointParameterfv(__GLcontext *,  GLenum, const GLfloat *);
extern GLvoid APIENTRY __gllc_PointParameteri(__GLcontext *,  GLenum, GLint);
extern GLvoid APIENTRY __gllc_PointParameteriv(__GLcontext *,  GLenum, const GLint *);
extern GLvoid APIENTRY __gllc_SecondaryColor3b(__GLcontext *,  GLbyte, GLbyte, GLbyte);
extern GLvoid APIENTRY __gllc_SecondaryColor3bv(__GLcontext *,  const GLbyte *);
extern GLvoid APIENTRY __gllc_SecondaryColor3d(__GLcontext *,  GLdouble, GLdouble, GLdouble);
extern GLvoid APIENTRY __gllc_SecondaryColor3dv(__GLcontext *,  const GLdouble *);
extern GLvoid APIENTRY __gllc_SecondaryColor3f(__GLcontext *,  GLfloat, GLfloat, GLfloat);
extern GLvoid APIENTRY __gllc_SecondaryColor3fv(__GLcontext *,  const GLfloat *);
extern GLvoid APIENTRY __gllc_SecondaryColor3i(__GLcontext *,  GLint, GLint, GLint);
extern GLvoid APIENTRY __gllc_SecondaryColor3iv(__GLcontext *,  const GLint *);
extern GLvoid APIENTRY __gllc_SecondaryColor3s(__GLcontext *,  GLshort, GLshort, GLshort);
extern GLvoid APIENTRY __gllc_SecondaryColor3sv(__GLcontext *,  const GLshort *);
extern GLvoid APIENTRY __gllc_SecondaryColor3ub(__GLcontext *,  GLubyte, GLubyte, GLubyte);
extern GLvoid APIENTRY __gllc_SecondaryColor3ubv(__GLcontext *,  const GLubyte *);
extern GLvoid APIENTRY __gllc_SecondaryColor3ui(__GLcontext *,  GLuint, GLuint, GLuint);
extern GLvoid APIENTRY __gllc_SecondaryColor3uiv(__GLcontext *,  const GLuint *);
extern GLvoid APIENTRY __gllc_SecondaryColor3us(__GLcontext *,  GLushort, GLushort, GLushort);
extern GLvoid APIENTRY __gllc_SecondaryColor3usv(__GLcontext *,  const GLushort *);
extern GLvoid APIENTRY __gllc_WindowPos2d(__GLcontext *,  GLdouble, GLdouble);
extern GLvoid APIENTRY __gllc_WindowPos2dv(__GLcontext *,  const GLdouble *);
extern GLvoid APIENTRY __gllc_WindowPos2f(__GLcontext *,  GLfloat, GLfloat);
extern GLvoid APIENTRY __gllc_WindowPos2fv(__GLcontext *,  const GLfloat *);
extern GLvoid APIENTRY __gllc_WindowPos2i(__GLcontext *,  GLint, GLint);
extern GLvoid APIENTRY __gllc_WindowPos2iv(__GLcontext *,  const GLint *);
extern GLvoid APIENTRY __gllc_WindowPos2s(__GLcontext *,  GLshort, GLshort);
extern GLvoid APIENTRY __gllc_WindowPos2sv(__GLcontext *,  const GLshort *);
extern GLvoid APIENTRY __gllc_WindowPos3d(__GLcontext *,  GLdouble, GLdouble, GLdouble);
extern GLvoid APIENTRY __gllc_WindowPos3dv(__GLcontext *,  const GLdouble *);
extern GLvoid APIENTRY __gllc_WindowPos3f(__GLcontext *,  GLfloat, GLfloat, GLfloat);
extern GLvoid APIENTRY __gllc_WindowPos3fv(__GLcontext *,  const GLfloat *);
extern GLvoid APIENTRY __gllc_WindowPos3i(__GLcontext *,  GLint, GLint, GLint);
extern GLvoid APIENTRY __gllc_WindowPos3iv(__GLcontext *,  const GLint *);
extern GLvoid APIENTRY __gllc_WindowPos3s(__GLcontext *,  GLshort, GLshort, GLshort);
extern GLvoid APIENTRY __gllc_WindowPos3sv(__GLcontext *,  const GLshort *);
extern GLvoid APIENTRY __gllc_BlendColor(__GLcontext *,  GLclampf, GLclampf, GLclampf, GLclampf);
extern GLvoid APIENTRY __gllc_BlendEquation(__GLcontext *,  GLenum);
#endif
#if GL_VERSION_1_5
extern GLvoid APIENTRY __gllc_BeginQuery(__GLcontext *,  GLenum, GLuint);
extern GLvoid APIENTRY __gllc_EndQuery(__GLcontext *,  GLenum);
#endif
#if GL_VERSION_2_0
extern GLvoid APIENTRY __gllc_BlendEquationSeparate(__GLcontext *,  GLenum, GLenum);
extern GLvoid APIENTRY __gllc_DrawBuffers(__GLcontext *,  GLsizei, const GLenum *);
extern GLvoid APIENTRY __gllc_StencilOpSeparate(__GLcontext *,  GLenum, GLenum, GLenum, GLenum);
extern GLvoid APIENTRY __gllc_StencilFuncSeparate(__GLcontext *,  GLenum, GLenum, GLint, GLuint);
extern GLvoid APIENTRY __gllc_StencilMaskSeparate(__GLcontext *,  GLenum, GLuint);
extern GLvoid APIENTRY __gllc_UseProgram(__GLcontext *,  GLuint);
extern GLvoid APIENTRY __gllc_Uniform1f(__GLcontext *,  GLint, GLfloat);
extern GLvoid APIENTRY __gllc_Uniform2f(__GLcontext *,  GLint, GLfloat, GLfloat);
extern GLvoid APIENTRY __gllc_Uniform3f(__GLcontext *,  GLint, GLfloat, GLfloat, GLfloat);
extern GLvoid APIENTRY __gllc_Uniform4f(__GLcontext *,  GLint, GLfloat, GLfloat, GLfloat, GLfloat);
extern GLvoid APIENTRY __gllc_Uniform1i(__GLcontext *,  GLint, GLint);
extern GLvoid APIENTRY __gllc_Uniform2i(__GLcontext *,  GLint, GLint, GLint);
extern GLvoid APIENTRY __gllc_Uniform3i(__GLcontext *,  GLint, GLint, GLint, GLint);
extern GLvoid APIENTRY __gllc_Uniform4i(__GLcontext *,  GLint, GLint, GLint, GLint, GLint);
extern GLvoid APIENTRY __gllc_Uniform1fv(__GLcontext *,  GLint, GLsizei, const GLfloat *);
extern GLvoid APIENTRY __gllc_Uniform2fv(__GLcontext *,  GLint, GLsizei, const GLfloat *);
extern GLvoid APIENTRY __gllc_Uniform3fv(__GLcontext *,  GLint, GLsizei, const GLfloat *);
extern GLvoid APIENTRY __gllc_Uniform4fv(__GLcontext *,  GLint, GLsizei, const GLfloat *);
extern GLvoid APIENTRY __gllc_Uniform1iv(__GLcontext *,  GLint, GLsizei, const GLint *);
extern GLvoid APIENTRY __gllc_Uniform2iv(__GLcontext *,  GLint, GLsizei, const GLint *);
extern GLvoid APIENTRY __gllc_Uniform3iv(__GLcontext *,  GLint, GLsizei, const GLint *);
extern GLvoid APIENTRY __gllc_Uniform4iv(__GLcontext *,  GLint, GLsizei, const GLint *);
extern GLvoid APIENTRY __gllc_UniformMatrix2fv(__GLcontext *,  GLint, GLsizei, GLboolean, const GLfloat *);
extern GLvoid APIENTRY __gllc_UniformMatrix3fv(__GLcontext *,  GLint, GLsizei, GLboolean, const GLfloat *);
extern GLvoid APIENTRY __gllc_UniformMatrix4fv(__GLcontext *,  GLint, GLsizei, GLboolean, const GLfloat *);
extern GLvoid APIENTRY __gllc_VertexAttrib1d(__GLcontext *,  GLuint, GLdouble);
extern GLvoid APIENTRY __gllc_VertexAttrib1dv(__GLcontext *,  GLuint, const GLdouble *);
extern GLvoid APIENTRY __gllc_VertexAttrib1f(__GLcontext *,  GLuint, GLfloat);
extern GLvoid APIENTRY __gllc_VertexAttrib1fv(__GLcontext *,  GLuint, const GLfloat *);
extern GLvoid APIENTRY __gllc_VertexAttrib1s(__GLcontext *,  GLuint, GLshort);
extern GLvoid APIENTRY __gllc_VertexAttrib1sv(__GLcontext *,  GLuint, const GLshort *);
extern GLvoid APIENTRY __gllc_VertexAttrib2d(__GLcontext *,  GLuint, GLdouble, GLdouble);
extern GLvoid APIENTRY __gllc_VertexAttrib2dv(__GLcontext *,  GLuint, const GLdouble *);
extern GLvoid APIENTRY __gllc_VertexAttrib2f(__GLcontext *,  GLuint, GLfloat, GLfloat);
extern GLvoid APIENTRY __gllc_VertexAttrib2fv(__GLcontext *,  GLuint, const GLfloat *);
extern GLvoid APIENTRY __gllc_VertexAttrib2s(__GLcontext *,  GLuint, GLshort, GLshort);
extern GLvoid APIENTRY __gllc_VertexAttrib2sv(__GLcontext *,  GLuint, const GLshort *);
extern GLvoid APIENTRY __gllc_VertexAttrib3d(__GLcontext *,  GLuint, GLdouble, GLdouble, GLdouble);
extern GLvoid APIENTRY __gllc_VertexAttrib3dv(__GLcontext *,  GLuint, const GLdouble *);
extern GLvoid APIENTRY __gllc_VertexAttrib3f(__GLcontext *,  GLuint, GLfloat, GLfloat, GLfloat);
extern GLvoid APIENTRY __gllc_VertexAttrib3fv(__GLcontext *,  GLuint, const GLfloat *);
extern GLvoid APIENTRY __gllc_VertexAttrib3s(__GLcontext *,  GLuint, GLshort, GLshort, GLshort);
extern GLvoid APIENTRY __gllc_VertexAttrib3sv(__GLcontext *,  GLuint, const GLshort *);
extern GLvoid APIENTRY __gllc_VertexAttrib4Nbv(__GLcontext *,  GLuint, const GLbyte *);
extern GLvoid APIENTRY __gllc_VertexAttrib4Niv(__GLcontext *,  GLuint, const GLint *);
extern GLvoid APIENTRY __gllc_VertexAttrib4Nsv(__GLcontext *,  GLuint, const GLshort *);
extern GLvoid APIENTRY __gllc_VertexAttrib4Nub(__GLcontext *,  GLuint, GLubyte, GLubyte, GLubyte, GLubyte);
extern GLvoid APIENTRY __gllc_VertexAttrib4Nubv(__GLcontext *,  GLuint, const GLubyte *);
extern GLvoid APIENTRY __gllc_VertexAttrib4Nuiv(__GLcontext *,  GLuint, const GLuint *);
extern GLvoid APIENTRY __gllc_VertexAttrib4Nusv(__GLcontext *,  GLuint, const GLushort *);
extern GLvoid APIENTRY __gllc_VertexAttrib4bv(__GLcontext *,  GLuint, const GLbyte *);
extern GLvoid APIENTRY __gllc_VertexAttrib4d(__GLcontext *,  GLuint, GLdouble, GLdouble, GLdouble, GLdouble);
extern GLvoid APIENTRY __gllc_VertexAttrib4dv(__GLcontext *,  GLuint, const GLdouble *);
extern GLvoid APIENTRY __gllc_VertexAttrib4f(__GLcontext *,  GLuint, GLfloat, GLfloat, GLfloat, GLfloat);
extern GLvoid APIENTRY __gllc_VertexAttrib4fv(__GLcontext *,  GLuint, const GLfloat *);
extern GLvoid APIENTRY __gllc_VertexAttrib4iv(__GLcontext *,  GLuint, const GLint *);
extern GLvoid APIENTRY __gllc_VertexAttrib4s(__GLcontext *,  GLuint, GLshort, GLshort, GLshort, GLshort);
extern GLvoid APIENTRY __gllc_VertexAttrib4sv(__GLcontext *,  GLuint, const GLshort *);
extern GLvoid APIENTRY __gllc_VertexAttrib4ubv(__GLcontext *,  GLuint, const GLubyte *);
extern GLvoid APIENTRY __gllc_VertexAttrib4uiv(__GLcontext *,  GLuint, const GLuint *);
extern GLvoid APIENTRY __gllc_VertexAttrib4usv(__GLcontext *,  GLuint, const GLushort *);
#endif

#if GL_VERSION_2_1
extern GLvoid APIENTRY __gllc_UniformMatrix2x3fv(__GLcontext *,  GLint, GLsizei, GLboolean, const GLfloat *);
extern GLvoid APIENTRY __gllc_UniformMatrix2x4fv(__GLcontext *,  GLint, GLsizei, GLboolean, const GLfloat *);
extern GLvoid APIENTRY __gllc_UniformMatrix3x2fv(__GLcontext *,  GLint, GLsizei, GLboolean, const GLfloat *);
extern GLvoid APIENTRY __gllc_UniformMatrix3x4fv(__GLcontext *,  GLint, GLsizei, GLboolean, const GLfloat *);
extern GLvoid APIENTRY __gllc_UniformMatrix4x2fv(__GLcontext *,  GLint, GLsizei, GLboolean, const GLfloat *);
extern GLvoid APIENTRY __gllc_UniformMatrix4x3fv(__GLcontext *,  GLint, GLsizei, GLboolean, const GLfloat *);
#endif


#endif /* __g_lcfncs_h_ */
