/****************************************************************************
*
*    Copyright (c) 2005 - 2017 by Vivante Corp.  All rights reserved.
*
*    The material in this file is confidential and contains trade secrets
*    of Vivante Corporation. This is proprietary information owned by
*    Vivante Corporation. No part of this work may be disclosed,
*    reproduced, copied, transmitted, or used in any way for any purpose,
*    without the express written permission of Vivante Corporation.
*
*****************************************************************************/


#ifndef __gc_im_protos_h__
#define __gc_im_protos_h__

/* OGL type */
extern GLboolean GL_APIENTRY __glim_IsList(__GLcontext *gc,  GLuint list ) ;
extern GLvoid GL_APIENTRY __glim_DeleteLists(__GLcontext *gc,  GLuint list, GLsizei range ) ;
extern GLuint GL_APIENTRY __glim_GenLists(__GLcontext *gc,  GLsizei range ) ;
extern GLvoid GL_APIENTRY __glim_NewList(__GLcontext *gc,  GLuint list, GLenum mode );
extern GLvoid GL_APIENTRY __glim_EndList(__GLcontext *gc) ;
extern GLvoid GL_APIENTRY __glim_CallList(__GLcontext *gc,  GLuint list ) ;
extern GLvoid GL_APIENTRY __glim_CallLists(__GLcontext *gc,  GLsizei n, GLenum type, const GLvoid *lists ) ;
extern GLvoid GL_APIENTRY __glim_ListBase(__GLcontext *gc,  GLuint base ) ;
extern GLvoid GL_APIENTRY __glim_Begin(__GLcontext *gc,  GLenum mode ) ;
extern GLvoid GL_APIENTRY __glim_Bitmap(__GLcontext *gc,  GLsizei width, GLsizei height, GLfloat xorig, GLfloat yorig, GLfloat xmove, GLfloat ymove, const GLubyte *bitmap ) ;
extern GLvoid GL_APIENTRY __glim_Color3b(__GLcontext *gc,  GLbyte red, GLbyte green, GLbyte blue );
extern GLvoid GL_APIENTRY __glim_Color3d(__GLcontext *gc,  GLdouble red, GLdouble green, GLdouble blue );
extern GLvoid GL_APIENTRY __glim_Color3f(__GLcontext *gc,  GLfloat red, GLfloat green, GLfloat blue );
extern GLvoid GL_APIENTRY __glim_Color3i(__GLcontext *gc,  GLint red, GLint green, GLint blue );
extern GLvoid GL_APIENTRY __glim_Color3s(__GLcontext *gc,  GLshort red, GLshort green, GLshort blue );
extern GLvoid GL_APIENTRY __glim_Color3ub(__GLcontext *gc,  GLubyte red, GLubyte green, GLubyte blue );
extern GLvoid GL_APIENTRY __glim_Color3ui(__GLcontext *gc,  GLuint red, GLuint green, GLuint blue );
extern GLvoid GL_APIENTRY __glim_Color3us(__GLcontext *gc,  GLushort red, GLushort green, GLushort blue );
extern GLvoid GL_APIENTRY __glim_Color3bv(__GLcontext *gc,  const GLbyte *v );
extern GLvoid GL_APIENTRY __glim_Color3dv(__GLcontext *gc,  const GLdouble *v );
extern GLvoid GL_APIENTRY __glim_Color3fv(__GLcontext *gc,  const GLfloat *v );
extern GLvoid GL_APIENTRY __glim_Color3iv(__GLcontext *gc,  const GLint *v );
extern GLvoid GL_APIENTRY __glim_Color3sv(__GLcontext *gc,  const GLshort *v );
extern GLvoid GL_APIENTRY __glim_Color3ubv(__GLcontext *gc,  const GLubyte *v );
extern GLvoid GL_APIENTRY __glim_Color3uiv(__GLcontext *gc,  const GLuint *v );
extern GLvoid GL_APIENTRY __glim_Color3usv(__GLcontext *gc,  const GLushort *v );
extern GLvoid GL_APIENTRY __glim_Color4b(__GLcontext *gc,  GLbyte red, GLbyte green, GLbyte blue, GLbyte alpha );
extern GLvoid GL_APIENTRY __glim_Color4d(__GLcontext *gc,  GLdouble red, GLdouble green, GLdouble blue, GLdouble alpha );
extern GLvoid GL_APIENTRY __glim_Color4f(__GLcontext *gc,  GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha );
extern GLvoid GL_APIENTRY __glim_Color4i(__GLcontext *gc,  GLint red, GLint green, GLint blue, GLint alpha );
extern GLvoid GL_APIENTRY __glim_Color4s(__GLcontext *gc,  GLshort red, GLshort green, GLshort blue, GLshort alpha );
extern GLvoid GL_APIENTRY __glim_Color4ub(__GLcontext *gc,  GLubyte red, GLubyte green, GLubyte blue, GLubyte alpha );
extern GLvoid GL_APIENTRY __glim_Color4ui(__GLcontext *gc,  GLuint red, GLuint green, GLuint blue, GLuint alpha );
extern GLvoid GL_APIENTRY __glim_Color4us(__GLcontext *gc,  GLushort red, GLushort green, GLushort blue, GLushort alpha );
extern GLvoid GL_APIENTRY __glim_Color4bv(__GLcontext *gc,  const GLbyte *v );
extern GLvoid GL_APIENTRY __glim_Color4dv(__GLcontext *gc,  const GLdouble *v );
extern GLvoid GL_APIENTRY __glim_Color4fv(__GLcontext *gc,  const GLfloat *v );
extern GLvoid GL_APIENTRY __glim_Color4iv(__GLcontext *gc,  const GLint *v );
extern GLvoid GL_APIENTRY __glim_Color4sv(__GLcontext *gc,  const GLshort *v );
extern GLvoid GL_APIENTRY __glim_Color4ubv(__GLcontext *gc,  const GLubyte *v );
extern GLvoid GL_APIENTRY __glim_Color4uiv(__GLcontext *gc,  const GLuint *v );
extern GLvoid GL_APIENTRY __glim_Color4usv(__GLcontext *gc,  const GLushort *v );
extern GLvoid GL_APIENTRY __glim_EdgeFlag(__GLcontext *gc,  GLboolean flag );
extern GLvoid GL_APIENTRY __glim_EdgeFlagv(__GLcontext *gc,  const GLboolean *flag );
extern GLvoid GL_APIENTRY __glim_End(__GLcontext *gc);
extern GLvoid GL_APIENTRY __glim_Indexd(__GLcontext *gc,  GLdouble c );
extern GLvoid GL_APIENTRY __glim_Indexf(__GLcontext *gc,  GLfloat c );
extern GLvoid GL_APIENTRY __glim_Indexi(__GLcontext *gc,  GLint c );
extern GLvoid GL_APIENTRY __glim_Indexs(__GLcontext *gc,  GLshort c );
extern GLvoid GL_APIENTRY __glim_Indexdv(__GLcontext *gc,  const GLdouble *c );
extern GLvoid GL_APIENTRY __glim_Indexfv(__GLcontext *gc,  const GLfloat *c );
extern GLvoid GL_APIENTRY __glim_Indexiv(__GLcontext *gc,  const GLint *c );
extern GLvoid GL_APIENTRY __glim_Indexsv(__GLcontext *gc,  const GLshort *c );
extern GLvoid GL_APIENTRY __glim_Normal3b(__GLcontext *gc,  GLbyte nx, GLbyte ny, GLbyte nz );
extern GLvoid GL_APIENTRY __glim_Normal3d(__GLcontext *gc,  GLdouble nx, GLdouble ny, GLdouble nz );
extern GLvoid GL_APIENTRY __glim_Normal3f(__GLcontext *gc,  GLfloat nx, GLfloat ny, GLfloat nz );
extern GLvoid GL_APIENTRY __glim_Normal3i(__GLcontext *gc,  GLint nx, GLint ny, GLint nz );
extern GLvoid GL_APIENTRY __glim_Normal3s(__GLcontext *gc,  GLshort nx, GLshort ny, GLshort nz );
extern GLvoid GL_APIENTRY __glim_Normal3bv(__GLcontext *gc,  const GLbyte *v );
extern GLvoid GL_APIENTRY __glim_Normal3dv(__GLcontext *gc,  const GLdouble *v );
extern GLvoid GL_APIENTRY __glim_Normal3fv(__GLcontext *gc,  const GLfloat *v );
extern GLvoid GL_APIENTRY __glim_Normal3iv(__GLcontext *gc,  const GLint *v );
extern GLvoid GL_APIENTRY __glim_Normal3sv(__GLcontext *gc,  const GLshort *v );
extern GLvoid GL_APIENTRY __glim_RasterPos2d(__GLcontext *gc,  GLdouble x, GLdouble y );
extern GLvoid GL_APIENTRY __glim_RasterPos2f(__GLcontext *gc,  GLfloat x, GLfloat y );
extern GLvoid GL_APIENTRY __glim_RasterPos2i(__GLcontext *gc,  GLint x, GLint y );
extern GLvoid GL_APIENTRY __glim_RasterPos2s(__GLcontext *gc,  GLshort x, GLshort y );
extern GLvoid GL_APIENTRY __glim_RasterPos3d(__GLcontext *gc,  GLdouble x, GLdouble y, GLdouble z );
extern GLvoid GL_APIENTRY __glim_RasterPos3f(__GLcontext *gc,  GLfloat x, GLfloat y, GLfloat z );
extern GLvoid GL_APIENTRY __glim_RasterPos3i(__GLcontext *gc,  GLint x, GLint y, GLint z );
extern GLvoid GL_APIENTRY __glim_RasterPos3s(__GLcontext *gc,  GLshort x, GLshort y, GLshort z );
extern GLvoid GL_APIENTRY __glim_RasterPos4d(__GLcontext *gc,  GLdouble x, GLdouble y, GLdouble z, GLdouble w );
extern GLvoid GL_APIENTRY __glim_RasterPos4f(__GLcontext *gc,  GLfloat x, GLfloat y, GLfloat z, GLfloat w );
extern GLvoid GL_APIENTRY __glim_RasterPos4i(__GLcontext *gc,  GLint x, GLint y, GLint z, GLint w );
extern GLvoid GL_APIENTRY __glim_RasterPos4s(__GLcontext *gc,  GLshort x, GLshort y, GLshort z, GLshort w );
extern GLvoid GL_APIENTRY __glim_RasterPos2dv(__GLcontext *gc,  const GLdouble *v );
extern GLvoid GL_APIENTRY __glim_RasterPos2fv(__GLcontext *gc,  const GLfloat *v );
extern GLvoid GL_APIENTRY __glim_RasterPos2iv(__GLcontext *gc,  const GLint *v );
extern GLvoid GL_APIENTRY __glim_RasterPos2sv(__GLcontext *gc,  const GLshort *v );
extern GLvoid GL_APIENTRY __glim_RasterPos3dv(__GLcontext *gc,  const GLdouble *v );
extern GLvoid GL_APIENTRY __glim_RasterPos3fv(__GLcontext *gc,  const GLfloat *v );
extern GLvoid GL_APIENTRY __glim_RasterPos3iv(__GLcontext *gc,  const GLint *v );
extern GLvoid GL_APIENTRY __glim_RasterPos3sv(__GLcontext *gc,  const GLshort *v );
extern GLvoid GL_APIENTRY __glim_RasterPos4dv(__GLcontext *gc,  const GLdouble *v );
extern GLvoid GL_APIENTRY __glim_RasterPos4fv(__GLcontext *gc,  const GLfloat *v );
extern GLvoid GL_APIENTRY __glim_RasterPos4iv(__GLcontext *gc,  const GLint *v );
extern GLvoid GL_APIENTRY __glim_RasterPos4sv(__GLcontext *gc,  const GLshort *v );
extern GLvoid GL_APIENTRY __glim_Rectd(__GLcontext *gc,  GLdouble x1, GLdouble y1, GLdouble x2, GLdouble y2 );
extern GLvoid GL_APIENTRY __glim_Rectf(__GLcontext *gc,  GLfloat x1, GLfloat y1, GLfloat x2, GLfloat y2 );
extern GLvoid GL_APIENTRY __glim_Recti(__GLcontext *gc,  GLint x1, GLint y1, GLint x2, GLint y2 );
extern GLvoid GL_APIENTRY __glim_Rects(__GLcontext *gc,  GLshort x1, GLshort y1, GLshort x2, GLshort y2 );
extern GLvoid GL_APIENTRY __glim_Rectdv(__GLcontext *gc,  const GLdouble *v1, const GLdouble *v2 );
extern GLvoid GL_APIENTRY __glim_Rectfv(__GLcontext *gc,  const GLfloat *v1, const GLfloat *v2 );
extern GLvoid GL_APIENTRY __glim_Rectiv(__GLcontext *gc,  const GLint *v1, const GLint *v2 );
extern GLvoid GL_APIENTRY __glim_Rectsv(__GLcontext *gc,  const GLshort *v1, const GLshort *v2 );
extern GLvoid GL_APIENTRY __glim_TexCoord1d(__GLcontext *gc,  GLdouble s );
extern GLvoid GL_APIENTRY __glim_TexCoord1f(__GLcontext *gc,  GLfloat s );
extern GLvoid GL_APIENTRY __glim_TexCoord1i(__GLcontext *gc,  GLint s );
extern GLvoid GL_APIENTRY __glim_TexCoord1s(__GLcontext *gc,  GLshort s );
extern GLvoid GL_APIENTRY __glim_TexCoord2d(__GLcontext *gc,  GLdouble s, GLdouble t );
extern GLvoid GL_APIENTRY __glim_TexCoord2f(__GLcontext *gc,  GLfloat s, GLfloat t );
extern GLvoid GL_APIENTRY __glim_TexCoord2i(__GLcontext *gc,  GLint s, GLint t );
extern GLvoid GL_APIENTRY __glim_TexCoord2s(__GLcontext *gc,  GLshort s, GLshort t );
extern GLvoid GL_APIENTRY __glim_TexCoord3d(__GLcontext *gc,  GLdouble s, GLdouble t, GLdouble r );
extern GLvoid GL_APIENTRY __glim_TexCoord3f(__GLcontext *gc,  GLfloat s, GLfloat t, GLfloat r );
extern GLvoid GL_APIENTRY __glim_TexCoord3i(__GLcontext *gc,  GLint s, GLint t, GLint r );
extern GLvoid GL_APIENTRY __glim_TexCoord3s(__GLcontext *gc,  GLshort s, GLshort t, GLshort r );
extern GLvoid GL_APIENTRY __glim_TexCoord4d(__GLcontext *gc,  GLdouble s, GLdouble t, GLdouble r, GLdouble q );
extern GLvoid GL_APIENTRY __glim_TexCoord4f(__GLcontext *gc,  GLfloat s, GLfloat t, GLfloat r, GLfloat q );
extern GLvoid GL_APIENTRY __glim_TexCoord4i(__GLcontext *gc,  GLint s, GLint t, GLint r, GLint q );
extern GLvoid GL_APIENTRY __glim_TexCoord4s(__GLcontext *gc,  GLshort s, GLshort t, GLshort r, GLshort q );
extern GLvoid GL_APIENTRY __glim_TexCoord1dv(__GLcontext *gc,  const GLdouble *v );
extern GLvoid GL_APIENTRY __glim_TexCoord1fv(__GLcontext *gc,  const GLfloat *v );
extern GLvoid GL_APIENTRY __glim_TexCoord1iv(__GLcontext *gc,  const GLint *v );
extern GLvoid GL_APIENTRY __glim_TexCoord1sv(__GLcontext *gc,  const GLshort *v );
extern GLvoid GL_APIENTRY __glim_TexCoord2dv(__GLcontext *gc,  const GLdouble *v );
extern GLvoid GL_APIENTRY __glim_TexCoord2fv(__GLcontext *gc,  const GLfloat *v );
extern GLvoid GL_APIENTRY __glim_TexCoord2iv(__GLcontext *gc,  const GLint *v );
extern GLvoid GL_APIENTRY __glim_TexCoord2sv(__GLcontext *gc,  const GLshort *v );
extern GLvoid GL_APIENTRY __glim_TexCoord3dv(__GLcontext *gc,  const GLdouble *v );
extern GLvoid GL_APIENTRY __glim_TexCoord3fv(__GLcontext *gc,  const GLfloat *v );
extern GLvoid GL_APIENTRY __glim_TexCoord3iv(__GLcontext *gc,  const GLint *v );
extern GLvoid GL_APIENTRY __glim_TexCoord3sv(__GLcontext *gc,  const GLshort *v );
extern GLvoid GL_APIENTRY __glim_TexCoord4dv(__GLcontext *gc,  const GLdouble *v );
extern GLvoid GL_APIENTRY __glim_TexCoord4fv(__GLcontext *gc,  const GLfloat *v );
extern GLvoid GL_APIENTRY __glim_TexCoord4iv(__GLcontext *gc,  const GLint *v );
extern GLvoid GL_APIENTRY __glim_TexCoord4sv(__GLcontext *gc,  const GLshort *v );
extern GLvoid GL_APIENTRY __glim_Vertex2d(__GLcontext *gc,  GLdouble x, GLdouble y );
extern GLvoid GL_APIENTRY __glim_Vertex2f(__GLcontext *gc,  GLfloat x, GLfloat y );
extern GLvoid GL_APIENTRY __glim_Vertex2i(__GLcontext *gc,  GLint x, GLint y );
extern GLvoid GL_APIENTRY __glim_Vertex2s(__GLcontext *gc,  GLshort x, GLshort y );
extern GLvoid GL_APIENTRY __glim_Vertex3d(__GLcontext *gc,  GLdouble x, GLdouble y, GLdouble z );
extern GLvoid GL_APIENTRY __glim_Vertex3f(__GLcontext *gc,  GLfloat x, GLfloat y, GLfloat z );
extern GLvoid GL_APIENTRY __glim_Vertex3i(__GLcontext *gc,  GLint x, GLint y, GLint z );
extern GLvoid GL_APIENTRY __glim_Vertex3s(__GLcontext *gc,  GLshort x, GLshort y, GLshort z );
extern GLvoid GL_APIENTRY __glim_Vertex4d(__GLcontext *gc,  GLdouble x, GLdouble y, GLdouble z, GLdouble w );
extern GLvoid GL_APIENTRY __glim_Vertex4f(__GLcontext *gc,  GLfloat x, GLfloat y, GLfloat z, GLfloat w );
extern GLvoid GL_APIENTRY __glim_Vertex4i(__GLcontext *gc,  GLint x, GLint y, GLint z, GLint w );
extern GLvoid GL_APIENTRY __glim_Vertex4s(__GLcontext *gc,  GLshort x, GLshort y, GLshort z, GLshort w );
extern GLvoid GL_APIENTRY __glim_Vertex2dv(__GLcontext *gc,  const GLdouble *v );
extern GLvoid GL_APIENTRY __glim_Vertex2fv(__GLcontext *gc,  const GLfloat *v );
extern GLvoid GL_APIENTRY __glim_Vertex2iv(__GLcontext *gc,  const GLint *v );
extern GLvoid GL_APIENTRY __glim_Vertex2sv(__GLcontext *gc,  const GLshort *v );
extern GLvoid GL_APIENTRY __glim_Vertex3dv(__GLcontext *gc,  const GLdouble *v );
extern GLvoid GL_APIENTRY __glim_Vertex3fv(__GLcontext *gc,  const GLfloat *v );
extern GLvoid GL_APIENTRY __glim_Vertex3iv(__GLcontext *gc,  const GLint *v );
extern GLvoid GL_APIENTRY __glim_Vertex3sv(__GLcontext *gc,  const GLshort *v );
extern GLvoid GL_APIENTRY __glim_Vertex4dv(__GLcontext *gc,  const GLdouble *v );
extern GLvoid GL_APIENTRY __glim_Vertex4fv(__GLcontext *gc,  const GLfloat *v );
extern GLvoid GL_APIENTRY __glim_Vertex4iv(__GLcontext *gc,  const GLint *v );
extern GLvoid GL_APIENTRY __glim_Vertex4sv(__GLcontext *gc,  const GLshort *v );
extern GLvoid GL_APIENTRY __glim_ClipPlane(__GLcontext *gc,  GLenum plane, const GLdouble *equation );
extern GLvoid GL_APIENTRY __glim_ColorMaterial(__GLcontext *gc,  GLenum face, GLenum mode );
extern GLvoid GL_APIENTRY __glim_Fogf(__GLcontext *gc,  GLenum pname, GLfloat param );
extern GLvoid GL_APIENTRY __glim_Fogi(__GLcontext *gc,  GLenum pname, GLint param );
extern GLvoid GL_APIENTRY __glim_Fogfv(__GLcontext *gc,  GLenum pname, const GLfloat *params );
extern GLvoid GL_APIENTRY __glim_Fogiv(__GLcontext *gc,  GLenum pname, const GLint *params );
extern GLvoid GL_APIENTRY __glim_Lightf(__GLcontext *gc,  GLenum light, GLenum pname, GLfloat param );
extern GLvoid GL_APIENTRY __glim_Lighti(__GLcontext *gc,  GLenum light, GLenum pname, GLint param );
extern GLvoid GL_APIENTRY __glim_Lightfv(__GLcontext *gc,  GLenum light, GLenum pname, const GLfloat *params );
extern GLvoid GL_APIENTRY __glim_Lightiv(__GLcontext *gc,  GLenum light, GLenum pname, const GLint *params );
extern GLvoid GL_APIENTRY __glim_LightModelf(__GLcontext *gc,  GLenum pname, GLfloat param );
extern GLvoid GL_APIENTRY __glim_LightModeli(__GLcontext *gc,  GLenum pname, GLint param );
extern GLvoid GL_APIENTRY __glim_LightModelfv(__GLcontext *gc,  GLenum pname, const GLfloat *params );
extern GLvoid GL_APIENTRY __glim_LightModeliv(__GLcontext *gc,  GLenum pname, const GLint *params );
extern GLvoid GL_APIENTRY __glim_LineStipple(__GLcontext *gc,  GLint factor, GLushort pattern );
extern GLvoid GL_APIENTRY __glim_Materialf(__GLcontext *gc,  GLenum face, GLenum pname, GLfloat param );
extern GLvoid GL_APIENTRY __glim_Materiali(__GLcontext *gc,  GLenum face, GLenum pname, GLint param );
extern GLvoid GL_APIENTRY __glim_Materialfv(__GLcontext *gc,  GLenum face, GLenum pname, const GLfloat *params );
extern GLvoid GL_APIENTRY __glim_Materialiv(__GLcontext *gc,  GLenum face, GLenum pname, const GLint *params );
extern GLvoid GL_APIENTRY __glim_PointSize(__GLcontext *gc,  GLfloat size );
extern GLvoid GL_APIENTRY __glim_PolygonMode(__GLcontext *gc,  GLenum face, GLenum mode );
extern GLvoid GL_APIENTRY __glim_PolygonStipple(__GLcontext *gc,  const GLubyte *mask );
extern GLvoid GL_APIENTRY __glim_ShadeModel(__GLcontext *gc,  GLenum mode );
extern GLvoid GL_APIENTRY __glim_TexImage1D(__GLcontext *gc,  GLenum target, GLint level, GLint internalFormat, GLsizei width, GLint border, GLenum format, GLenum type, const GLvoid *pixels );
extern GLvoid GL_APIENTRY __glim_TexEnvf(__GLcontext *gc,  GLenum target, GLenum pname, GLfloat param );
extern GLvoid GL_APIENTRY __glim_TexEnvi(__GLcontext *gc,  GLenum target, GLenum pname, GLint param );
extern GLvoid GL_APIENTRY __glim_TexEnvfv(__GLcontext *gc,  GLenum target, GLenum pname, const GLfloat *params );
extern GLvoid GL_APIENTRY __glim_TexEnviv(__GLcontext *gc,  GLenum target, GLenum pname, const GLint *params );
extern GLvoid GL_APIENTRY __glim_TexGend(__GLcontext *gc,  GLenum coord, GLenum pname, GLdouble param );
extern GLvoid GL_APIENTRY __glim_TexGenf(__GLcontext *gc,  GLenum coord, GLenum pname, GLfloat param );
extern GLvoid GL_APIENTRY __glim_TexGeni(__GLcontext *gc,  GLenum coord, GLenum pname, GLint param );
extern GLvoid GL_APIENTRY __glim_TexGendv(__GLcontext *gc,  GLenum coord, GLenum pname, const GLdouble *params );
extern GLvoid GL_APIENTRY __glim_TexGenfv(__GLcontext *gc,  GLenum coord, GLenum pname, const GLfloat *params );
extern GLvoid GL_APIENTRY __glim_TexGeniv(__GLcontext *gc,  GLenum coord, GLenum pname, const GLint *params );
extern GLvoid GL_APIENTRY __glim_FeedbackBuffer(__GLcontext *gc,  GLsizei size, GLenum type, GLfloat *buffer );
extern GLvoid GL_APIENTRY __glim_SelectBuffer(__GLcontext *gc,  GLsizei size, GLuint *buffer );
extern GLint GL_APIENTRY __glim_RenderMode(__GLcontext *gc,  GLenum mode );
extern GLvoid GL_APIENTRY __glim_InitNames(__GLcontext *gc);
extern GLvoid GL_APIENTRY __glim_LoadName(__GLcontext *gc,  GLuint name );
extern GLvoid GL_APIENTRY __glim_PushName(__GLcontext *gc,  GLuint name );
extern GLvoid GL_APIENTRY __glim_PopName(__GLcontext *gc);
extern GLvoid GL_APIENTRY __glim_PassThrough(__GLcontext *gc,  GLfloat token );
extern GLvoid GL_APIENTRY __glim_DrawBuffer(__GLcontext *gc,  GLenum mode );
extern GLvoid GL_APIENTRY __glim_ClearAccum(__GLcontext *gc,  GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha );
extern GLvoid GL_APIENTRY __glim_ClearIndex(__GLcontext *gc,  GLfloat c );
extern GLvoid GL_APIENTRY __glim_ClearDepth(__GLcontext *gc,  GLclampd depth );
extern GLvoid GL_APIENTRY __glim_IndexMask(__GLcontext *gc,  GLuint mask );
extern GLvoid GL_APIENTRY __glim_Accum(__GLcontext *gc,  GLenum op, GLfloat value );
extern GLvoid GL_APIENTRY __glim_PushAttrib(__GLcontext *gc,  GLbitfield mask );
extern GLvoid GL_APIENTRY __glim_PopAttrib(__GLcontext *gc);
extern GLvoid GL_APIENTRY __glim_Map1d(__GLcontext *gc,  GLenum target, GLdouble u1, GLdouble u2, GLint stride, GLint order, const GLdouble *points );
extern GLvoid GL_APIENTRY __glim_Map1f(__GLcontext *gc,  GLenum target, GLfloat u1, GLfloat u2, GLint stride, GLint order, const GLfloat *points );
extern GLvoid GL_APIENTRY __glim_Map2d(__GLcontext *gc,  GLenum target, GLdouble u1, GLdouble u2, GLint ustride, GLint uorder, GLdouble v1, GLdouble v2, GLint vstride, GLint vorder, const GLdouble *points );
extern GLvoid GL_APIENTRY __glim_Map2f(__GLcontext *gc,  GLenum target, GLfloat u1, GLfloat u2, GLint ustride, GLint uorder, GLfloat v1, GLfloat v2, GLint vstride, GLint vorder, const GLfloat *points );
extern GLvoid GL_APIENTRY __glim_MapGrid1d(__GLcontext *gc,  GLint un, GLdouble u1, GLdouble u2 );
extern GLvoid GL_APIENTRY __glim_MapGrid1f(__GLcontext *gc,  GLint un, GLfloat u1, GLfloat u2 );
extern GLvoid GL_APIENTRY __glim_MapGrid2d(__GLcontext *gc,  GLint un, GLdouble u1, GLdouble u2, GLint vn, GLdouble v1, GLdouble v2 );
extern GLvoid GL_APIENTRY __glim_MapGrid2f(__GLcontext *gc,  GLint un, GLfloat u1, GLfloat u2, GLint vn, GLfloat v1, GLfloat v2 );
extern GLvoid GL_APIENTRY __glim_EvalCoord1d(__GLcontext *gc,  GLdouble u );
extern GLvoid GL_APIENTRY __glim_EvalCoord1f(__GLcontext *gc,  GLfloat u );
extern GLvoid GL_APIENTRY __glim_EvalCoord1dv(__GLcontext *gc,  const GLdouble *u );
extern GLvoid GL_APIENTRY __glim_EvalCoord1fv(__GLcontext *gc,  const GLfloat *u );
extern GLvoid GL_APIENTRY __glim_EvalCoord2d(__GLcontext *gc,  GLdouble u, GLdouble v );
extern GLvoid GL_APIENTRY __glim_EvalCoord2f(__GLcontext *gc,  GLfloat u, GLfloat v );
extern GLvoid GL_APIENTRY __glim_EvalCoord2dv(__GLcontext *gc,  const GLdouble *u );
extern GLvoid GL_APIENTRY __glim_EvalCoord2fv(__GLcontext *gc,  const GLfloat *u );
extern GLvoid GL_APIENTRY __glim_EvalPoint1(__GLcontext *gc,  GLint i );
extern GLvoid GL_APIENTRY __glim_EvalPoint2(__GLcontext *gc,  GLint i, GLint j );
extern GLvoid GL_APIENTRY __glim_EvalMesh1(__GLcontext *gc,  GLenum mode, GLint i1, GLint i2 );
extern GLvoid GL_APIENTRY __glim_EvalMesh2(__GLcontext *gc,  GLenum mode, GLint i1, GLint i2, GLint j1, GLint j2 );
extern GLvoid GL_APIENTRY __glim_AlphaFunc(__GLcontext *gc,  GLenum func, GLclampf ref );
extern GLvoid GL_APIENTRY __glim_LogicOp(__GLcontext *gc,  GLenum opcode );
extern GLvoid GL_APIENTRY __glim_PixelZoom(__GLcontext *gc,  GLfloat xfactor, GLfloat yfactor );
extern GLvoid GL_APIENTRY __glim_PixelTransferf(__GLcontext *gc,  GLenum pname, GLfloat param );
extern GLvoid GL_APIENTRY __glim_PixelTransferi(__GLcontext *gc,  GLenum pname, GLint param );
extern GLvoid GL_APIENTRY __glim_PixelStoref(__GLcontext *gc,  GLenum pname, GLfloat param );
extern GLvoid GL_APIENTRY __glim_PixelMapfv(__GLcontext *gc,  GLenum map, GLsizei mapsize, const GLfloat *values );
extern GLvoid GL_APIENTRY __glim_PixelMapuiv(__GLcontext *gc,  GLenum map, GLsizei mapsize, const GLuint *values );
extern GLvoid GL_APIENTRY __glim_PixelMapusv(__GLcontext *gc,  GLenum map, GLsizei mapsize, const GLushort *values );
extern GLvoid GL_APIENTRY __glim_GetClipPlane(__GLcontext *gc,  GLenum plane, GLdouble *equation );
extern GLvoid GL_APIENTRY __glim_GetDoublev(__GLcontext *gc,  GLenum pname, GLdouble *params );
extern GLvoid GL_APIENTRY __glim_GetLightfv(__GLcontext *gc,  GLenum light, GLenum pname, GLfloat *params );
extern GLvoid GL_APIENTRY __glim_GetLightiv(__GLcontext *gc,  GLenum light, GLenum pname, GLint *params );
extern GLvoid GL_APIENTRY __glim_GetMapdv(__GLcontext *gc,  GLenum target, GLenum query, GLdouble *v );
extern GLvoid GL_APIENTRY __glim_GetMapfv(__GLcontext *gc,  GLenum target, GLenum query, GLfloat *v );
extern GLvoid GL_APIENTRY __glim_GetMapiv(__GLcontext *gc,  GLenum target, GLenum query, GLint *v );
extern GLvoid GL_APIENTRY __glim_GetMaterialfv(__GLcontext *gc,  GLenum face, GLenum pname, GLfloat *params );
extern GLvoid GL_APIENTRY __glim_GetMaterialiv(__GLcontext *gc,  GLenum face, GLenum pname, GLint *params );
extern GLvoid GL_APIENTRY __glim_GetPixelMapfv(__GLcontext *gc,  GLenum map, GLfloat *values );
extern GLvoid GL_APIENTRY __glim_GetPixelMapuiv(__GLcontext *gc,  GLenum map, GLuint *values );
extern GLvoid GL_APIENTRY __glim_GetPixelMapusv(__GLcontext *gc,  GLenum map, GLushort *values );
extern GLvoid GL_APIENTRY __glim_GetPolygonStipple(__GLcontext *gc,  GLubyte *mask );
extern GLvoid GL_APIENTRY __glim_GetTexEnvfv(__GLcontext *gc,  GLenum target, GLenum pname, GLfloat *params );
extern GLvoid GL_APIENTRY __glim_GetTexEnviv(__GLcontext *gc,  GLenum target, GLenum pname, GLint *params );
extern GLvoid GL_APIENTRY __glim_GetTexGendv(__GLcontext *gc,  GLenum coord, GLenum pname, GLdouble *params );
extern GLvoid GL_APIENTRY __glim_GetTexGenfv(__GLcontext *gc,  GLenum coord, GLenum pname, GLfloat *params );
extern GLvoid GL_APIENTRY __glim_GetTexGeniv(__GLcontext *gc,  GLenum coord, GLenum pname, GLint *params );
extern GLvoid GL_APIENTRY __glim_GetTexImage(__GLcontext *gc,  GLenum target, GLint level, GLenum format, GLenum type, GLvoid *pixels );
extern GLvoid GL_APIENTRY __glim_DepthRange(__GLcontext *gc,  GLclampd near_val, GLclampd far_val );
extern GLvoid GL_APIENTRY __glim_Frustum(__GLcontext *gc,  GLdouble left, GLdouble right, GLdouble bottom, GLdouble top, GLdouble near_val, GLdouble far_val );
extern GLvoid GL_APIENTRY __glim_LoadIdentity(__GLcontext *gc);
extern GLvoid GL_APIENTRY __glim_LoadMatrixd(__GLcontext *gc,  const GLdouble *m );
extern GLvoid GL_APIENTRY __glim_LoadMatrixf(__GLcontext *gc,  const GLfloat *m );
extern GLvoid GL_APIENTRY __glim_MatrixMode(__GLcontext *gc,  GLenum mode );
extern GLvoid GL_APIENTRY __glim_MultMatrixd(__GLcontext *gc,  const GLdouble *m );
extern GLvoid GL_APIENTRY __glim_MultMatrixf(__GLcontext *gc,  const GLfloat *m );
extern GLvoid GL_APIENTRY __glim_Ortho(__GLcontext *gc,  GLdouble left, GLdouble right, GLdouble bottom, GLdouble top, GLdouble near_val, GLdouble far_val );
extern GLvoid GL_APIENTRY __glim_PushMatrix(__GLcontext *gc);
extern GLvoid GL_APIENTRY __glim_PopMatrix(__GLcontext *gc);
extern GLvoid GL_APIENTRY __glim_Rotated(__GLcontext *gc,  GLdouble angle, GLdouble x, GLdouble y, GLdouble z );
extern GLvoid GL_APIENTRY __glim_Rotatef(__GLcontext *gc,  GLfloat angle, GLfloat x, GLfloat y, GLfloat z );
extern GLvoid GL_APIENTRY __glim_Scaled(__GLcontext *gc,  GLdouble x, GLdouble y, GLdouble z );
extern GLvoid GL_APIENTRY __glim_Scalef(__GLcontext *gc,  GLfloat x, GLfloat y, GLfloat z );
extern GLvoid GL_APIENTRY __glim_Translated(__GLcontext *gc,  GLdouble x, GLdouble y, GLdouble z );
extern GLvoid GL_APIENTRY __glim_Translatef(__GLcontext *gc,  GLfloat x, GLfloat y, GLfloat z );
extern GLvoid GL_APIENTRY __glim_ArrayElement(__GLcontext *gc,  GLint i );
extern GLvoid GL_APIENTRY __glim_ColorPointer(__GLcontext *gc,  GLint size, GLenum type, GLsizei stride, const GLvoid *ptr );
extern GLvoid GL_APIENTRY __glim_EnableClientState(__GLcontext *gc,  GLenum cap );
extern GLvoid GL_APIENTRY __glim_DisableClientState(__GLcontext *gc,  GLenum cap );
extern GLvoid GL_APIENTRY __glim_EdgeFlagPointer(__GLcontext *gc,  GLsizei stride, const GLvoid *ptr );
extern GLvoid GL_APIENTRY __glim_IndexPointer(__GLcontext *gc,  GLenum type, GLsizei stride, const GLvoid *ptr );
extern GLvoid GL_APIENTRY __glim_InterleavedArrays(__GLcontext *gc,  GLenum format, GLsizei stride, const GLvoid *pointer );
extern GLvoid GL_APIENTRY __glim_NormalPointer(__GLcontext *gc,  GLenum type, GLsizei stride,  const GLvoid *ptr );
extern GLvoid GL_APIENTRY __glim_VertexPointer(__GLcontext *gc,  GLint size, GLenum type, GLsizei stride, const GLvoid *ptr );
extern GLvoid GL_APIENTRY __glim_TexCoordPointer(__GLcontext *gc,  GLint size, GLenum type, GLsizei stride, const GLvoid *ptr );
extern GLboolean GL_APIENTRY __glim_AreTexturesResident(__GLcontext *gc,  GLsizei n, const GLuint *textures, GLboolean *residences ) ;
extern GLvoid GL_APIENTRY __glim_CopyTexImage1D(__GLcontext *gc,  GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLint border );
extern GLvoid GL_APIENTRY __glim_CopyTexSubImage1D(__GLcontext *gc,  GLenum target, GLint level,  GLint xoffset, GLint x, GLint y,  GLsizei width );
extern GLvoid GL_APIENTRY __glim_PrioritizeTextures(__GLcontext *gc,  GLsizei n,  const GLuint *textures, const GLclampf *priorities );
extern GLvoid GL_APIENTRY __glim_TexSubImage1D(__GLcontext *gc,  GLenum target, GLint level,  GLint xoffset, GLsizei width, GLenum format, GLenum type, const GLvoid *pixels );
extern GLvoid GL_APIENTRY __glim_PushClientAttrib(__GLcontext *gc,  GLbitfield mask );
extern GLvoid GL_APIENTRY __glim_PopClientAttrib(__GLcontext *gc);
extern GLvoid GL_APIENTRY __glim_ColorTable(__GLcontext *gc,  GLenum target, GLenum internalformat, GLsizei width, GLenum format, GLenum type, const GLvoid *table );
extern GLvoid GL_APIENTRY __glim_ColorTableParameteriv(__GLcontext *gc, GLenum target, GLenum pname, const GLint *params);
extern GLvoid GL_APIENTRY __glim_ColorTableParameterfv(__GLcontext *gc, GLenum target, GLenum pname, const GLfloat *params);
extern GLvoid GL_APIENTRY __glim_CopyColorTable(__GLcontext *gc,  GLenum target, GLenum internalformat, GLint x, GLint y, GLsizei width );
extern GLvoid GL_APIENTRY __glim_GetColorTable(__GLcontext *gc,  GLenum target, GLenum format,  GLenum type, GLvoid *table );
extern GLvoid GL_APIENTRY __glim_GetColorTableParameterfv(__GLcontext *gc,  GLenum target, GLenum pname, GLfloat *params );
extern GLvoid GL_APIENTRY __glim_GetColorTableParameteriv(__GLcontext *gc,  GLenum target, GLenum pname,  GLint *params );
extern GLvoid GL_APIENTRY __glim_ColorSubTable(__GLcontext *gc,  GLenum target, GLsizei start, GLsizei count, GLenum format, GLenum type, const GLvoid *data );
extern GLvoid GL_APIENTRY __glim_CopyColorSubTable(__GLcontext *gc,  GLenum target, GLsizei start, GLint x, GLint y, GLsizei width );
extern GLvoid GL_APIENTRY __glim_ConvolutionFilter1D(__GLcontext *gc,  GLenum target, GLenum internalformat, GLsizei width, GLenum format, GLenum type, const GLvoid *image );
extern GLvoid GL_APIENTRY __glim_ConvolutionFilter2D(__GLcontext *gc,  GLenum target, GLenum internalformat, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid *image );
extern GLvoid GL_APIENTRY __glim_ConvolutionParameterf(__GLcontext *gc,  GLenum target, GLenum pname, GLfloat params );
extern GLvoid GL_APIENTRY __glim_ConvolutionParameterfv(__GLcontext *gc,  GLenum target, GLenum pname, const GLfloat *params );
extern GLvoid GL_APIENTRY __glim_ConvolutionParameteri(__GLcontext *gc,  GLenum target, GLenum pname, GLint params );
extern GLvoid GL_APIENTRY __glim_ConvolutionParameteriv(__GLcontext *gc,  GLenum target, GLenum pname, const GLint *params );
extern GLvoid GL_APIENTRY __glim_CopyConvolutionFilter1D(__GLcontext *gc,  GLenum target, GLenum internalformat, GLint x, GLint y, GLsizei width );
extern GLvoid GL_APIENTRY __glim_CopyConvolutionFilter2D(__GLcontext *gc,  GLenum target, GLenum internalformat, GLint x, GLint y, GLsizei width, GLsizei height);
extern GLvoid GL_APIENTRY __glim_GetConvolutionFilter(__GLcontext *gc,  GLenum target, GLenum format, GLenum type, GLvoid *image );
extern GLvoid GL_APIENTRY __glim_GetConvolutionParameterfv(__GLcontext *gc,  GLenum target, GLenum pname, GLfloat *params );
extern GLvoid GL_APIENTRY __glim_GetConvolutionParameteriv(__GLcontext *gc,  GLenum target, GLenum pname, GLint *params );
extern GLvoid GL_APIENTRY __glim_SeparableFilter2D(__GLcontext *gc,  GLenum target, GLenum internalformat, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid *row, const GLvoid *column );
extern GLvoid GL_APIENTRY __glim_GetSeparableFilter(__GLcontext *gc,  GLenum target, GLenum format, GLenum type, GLvoid *row, GLvoid *column, GLvoid *span );
extern GLvoid GL_APIENTRY __glim_Histogram(__GLcontext *gc,  GLenum target, GLsizei width, GLenum internalformat, GLboolean sink );
extern GLvoid GL_APIENTRY __glim_ResetHistogram(__GLcontext *gc,  GLenum target );
extern GLvoid GL_APIENTRY __glim_GetHistogram(__GLcontext *gc,  GLenum target, GLboolean reset, GLenum format, GLenum type, GLvoid *values );
extern GLvoid GL_APIENTRY __glim_GetHistogramParameterfv(__GLcontext *gc,  GLenum target, GLenum pname, GLfloat *params );
extern GLvoid GL_APIENTRY __glim_GetHistogramParameteriv(__GLcontext *gc,  GLenum target, GLenum pname, GLint *params );
extern GLvoid GL_APIENTRY __glim_Minmax(__GLcontext *gc,  GLenum target, GLenum internalformat, GLboolean sink );
extern GLvoid GL_APIENTRY __glim_ResetMinmax(__GLcontext *gc,  GLenum target );
extern GLvoid GL_APIENTRY __glim_GetMinmax(__GLcontext *gc,  GLenum target, GLboolean reset, GLenum format, GLenum types, GLvoid *values );
extern GLvoid GL_APIENTRY __glim_GetMinmaxParameterfv(__GLcontext *gc,  GLenum target, GLenum pname,  GLfloat *params );
extern GLvoid GL_APIENTRY __glim_GetMinmaxParameteriv(__GLcontext *gc,  GLenum target, GLenum pname, GLint *params );
extern GLvoid GL_APIENTRY __glim_ClientActiveTexture(__GLcontext *gc,  GLenum texture );
extern GLvoid GL_APIENTRY __glim_MultiTexCoord1d(__GLcontext *gc,  GLenum target, GLdouble s );
extern GLvoid GL_APIENTRY __glim_MultiTexCoord1dv(__GLcontext *gc,  GLenum target, const GLdouble *v );
extern GLvoid GL_APIENTRY __glim_MultiTexCoord1f(__GLcontext *gc,  GLenum target, GLfloat s );
extern GLvoid GL_APIENTRY __glim_MultiTexCoord1fv(__GLcontext *gc,  GLenum target, const GLfloat *v );
extern GLvoid GL_APIENTRY __glim_MultiTexCoord1i(__GLcontext *gc,  GLenum target, GLint s );
extern GLvoid GL_APIENTRY __glim_MultiTexCoord1iv(__GLcontext *gc,  GLenum target, const GLint *v );
extern GLvoid GL_APIENTRY __glim_MultiTexCoord1s(__GLcontext *gc,  GLenum target, GLshort s );
extern GLvoid GL_APIENTRY __glim_MultiTexCoord1sv(__GLcontext *gc,  GLenum target, const GLshort *v );
extern GLvoid GL_APIENTRY __glim_MultiTexCoord2d(__GLcontext *gc,  GLenum target, GLdouble s, GLdouble t );
extern GLvoid GL_APIENTRY __glim_MultiTexCoord2dv(__GLcontext *gc,  GLenum target, const GLdouble *v );
extern GLvoid GL_APIENTRY __glim_MultiTexCoord2f(__GLcontext *gc,  GLenum target, GLfloat s, GLfloat t );
extern GLvoid GL_APIENTRY __glim_MultiTexCoord2fv(__GLcontext *gc,  GLenum target, const GLfloat *v );
extern GLvoid GL_APIENTRY __glim_MultiTexCoord2i(__GLcontext *gc,  GLenum target, GLint s, GLint t );
extern GLvoid GL_APIENTRY __glim_MultiTexCoord2iv(__GLcontext *gc,  GLenum target, const GLint *v );
extern GLvoid GL_APIENTRY __glim_MultiTexCoord2s(__GLcontext *gc,  GLenum target, GLshort s, GLshort t );
extern GLvoid GL_APIENTRY __glim_MultiTexCoord2sv(__GLcontext *gc,  GLenum target, const GLshort *v );
extern GLvoid GL_APIENTRY __glim_MultiTexCoord3d(__GLcontext *gc,  GLenum target, GLdouble s, GLdouble t, GLdouble r );
extern GLvoid GL_APIENTRY __glim_MultiTexCoord3dv(__GLcontext *gc,  GLenum target, const GLdouble *v );
extern GLvoid GL_APIENTRY __glim_MultiTexCoord3f(__GLcontext *gc,  GLenum target, GLfloat s, GLfloat t, GLfloat r );
extern GLvoid GL_APIENTRY __glim_MultiTexCoord3fv(__GLcontext *gc,  GLenum target, const GLfloat *v );
extern GLvoid GL_APIENTRY __glim_MultiTexCoord3i(__GLcontext *gc,  GLenum target, GLint s, GLint t, GLint r );
extern GLvoid GL_APIENTRY __glim_MultiTexCoord3iv(__GLcontext *gc,  GLenum target, const GLint *v );
extern GLvoid GL_APIENTRY __glim_MultiTexCoord3s(__GLcontext *gc,  GLenum target, GLshort s, GLshort t, GLshort r );
extern GLvoid GL_APIENTRY __glim_MultiTexCoord3sv(__GLcontext *gc,  GLenum target, const GLshort *v );
extern GLvoid GL_APIENTRY __glim_MultiTexCoord4d(__GLcontext *gc,  GLenum target, GLdouble s, GLdouble t, GLdouble r, GLdouble q );
extern GLvoid GL_APIENTRY __glim_MultiTexCoord4dv(__GLcontext *gc,  GLenum target, const GLdouble *v );
extern GLvoid GL_APIENTRY __glim_MultiTexCoord4f(__GLcontext *gc,  GLenum target, GLfloat s, GLfloat t, GLfloat r, GLfloat q );
extern GLvoid GL_APIENTRY __glim_MultiTexCoord4fv(__GLcontext *gc,  GLenum target, const GLfloat *v );
extern GLvoid GL_APIENTRY __glim_MultiTexCoord4i(__GLcontext *gc,  GLenum target, GLint s, GLint t, GLint r, GLint q );
extern GLvoid GL_APIENTRY __glim_MultiTexCoord4iv(__GLcontext *gc,  GLenum target, const GLint *v );
extern GLvoid GL_APIENTRY __glim_MultiTexCoord4s(__GLcontext *gc,  GLenum target, GLshort s, GLshort t, GLshort r, GLshort q );
extern GLvoid GL_APIENTRY __glim_MultiTexCoord4sv(__GLcontext *gc,  GLenum target, const GLshort *v );
extern GLvoid GL_APIENTRY __glim_LoadTransposeMatrixd(__GLcontext *gc,  const GLdouble m[16] );
extern GLvoid GL_APIENTRY __glim_LoadTransposeMatrixf(__GLcontext *gc,  const GLfloat m[16] );
extern GLvoid GL_APIENTRY __glim_MultTransposeMatrixd(__GLcontext *gc,  const GLdouble m[16] );
extern GLvoid GL_APIENTRY __glim_MultTransposeMatrixf(__GLcontext *gc,  const GLfloat m[16] );
extern GLvoid GL_APIENTRY __glim_CompressedTexImage1D(__GLcontext *gc,  GLenum target, GLint level, GLenum internalformat, GLsizei width, GLint border, GLsizei imageSize, const GLvoid *data );
extern GLvoid GL_APIENTRY __glim_CompressedTexSubImage1D(__GLcontext *gc,  GLenum target, GLint level, GLint xoffset, GLsizei width, GLenum format, GLsizei imageSize, const GLvoid *data );
extern GLvoid GL_APIENTRY __glim_GetCompressedTexImage(__GLcontext *gc,  GLenum target, GLint lod, GLvoid *img );
extern GLvoid GL_APIENTRY __glim_FogCoordf(__GLcontext *gc, GLfloat coord);
extern GLvoid GL_APIENTRY __glim_FogCoordfv(__GLcontext *gc, const GLfloat *coord);
extern GLvoid GL_APIENTRY __glim_FogCoordd(__GLcontext *gc, GLdouble coord);
extern GLvoid GL_APIENTRY __glim_FogCoorddv(__GLcontext *gc, const GLdouble *coord);
extern GLvoid GL_APIENTRY __glim_FogCoordPointer(__GLcontext *gc, GLenum type, GLsizei stride, const void *pointer);
extern GLvoid GL_APIENTRY __glim_PointParameterf(__GLcontext *gc, GLenum pname, GLfloat param);
extern GLvoid GL_APIENTRY __glim_PointParameterfv(__GLcontext *gc, GLenum pname, const GLfloat *params);
extern GLvoid GL_APIENTRY __glim_PointParameteri(__GLcontext *gc, GLenum pname, GLint param);
extern GLvoid GL_APIENTRY __glim_PointParameteriv(__GLcontext *gc, GLenum pname, const GLint *params);
extern GLvoid GL_APIENTRY __glim_SecondaryColor3b(__GLcontext *gc, GLbyte red, GLbyte green, GLbyte blue);
extern GLvoid GL_APIENTRY __glim_SecondaryColor3bv(__GLcontext *gc, const GLbyte *v);
extern GLvoid GL_APIENTRY __glim_SecondaryColor3d(__GLcontext *gc, GLdouble red, GLdouble green, GLdouble blue);
extern GLvoid GL_APIENTRY __glim_SecondaryColor3dv(__GLcontext *gc, const GLdouble *v);
extern GLvoid GL_APIENTRY __glim_SecondaryColor3f(__GLcontext *gc, GLfloat red, GLfloat green, GLfloat blue);
extern GLvoid GL_APIENTRY __glim_SecondaryColor3fv(__GLcontext *gc, const GLfloat *v);
extern GLvoid GL_APIENTRY __glim_SecondaryColor3i(__GLcontext *gc, GLint red, GLint green, GLint blue);
extern GLvoid GL_APIENTRY __glim_SecondaryColor3iv(__GLcontext *gc, const GLint *v);
extern GLvoid GL_APIENTRY __glim_SecondaryColor3s(__GLcontext *gc, GLshort red, GLshort green, GLshort blue);
extern GLvoid GL_APIENTRY __glim_SecondaryColor3sv(__GLcontext *gc, const GLshort *v);
extern GLvoid GL_APIENTRY __glim_SecondaryColor3ub(__GLcontext *gc, GLubyte red, GLubyte green, GLubyte blue);
extern GLvoid GL_APIENTRY __glim_SecondaryColor3ubv(__GLcontext *gc, const GLubyte *v);
extern GLvoid GL_APIENTRY __glim_SecondaryColor3ui(__GLcontext *gc, GLuint red, GLuint green, GLuint blue);
extern GLvoid GL_APIENTRY __glim_SecondaryColor3uiv(__GLcontext *gc, const GLuint *v);
extern GLvoid GL_APIENTRY __glim_SecondaryColor3us(__GLcontext *gc, GLushort red, GLushort green, GLushort blue);
extern GLvoid GL_APIENTRY __glim_SecondaryColor3usv(__GLcontext *gc, const GLushort *v);
extern GLvoid GL_APIENTRY __glim_SecondaryColorPointer(__GLcontext *gc, GLint size, GLenum type, GLsizei stride, const void *pointer);
extern GLvoid GL_APIENTRY __glim_WindowPos2d(__GLcontext *gc, GLdouble x, GLdouble y);
extern GLvoid GL_APIENTRY __glim_WindowPos2dv(__GLcontext *gc, const GLdouble *v);
extern GLvoid GL_APIENTRY __glim_WindowPos2f(__GLcontext *gc, GLfloat x, GLfloat y);
extern GLvoid GL_APIENTRY __glim_WindowPos2fv(__GLcontext *gc, const GLfloat *v);
extern GLvoid GL_APIENTRY __glim_WindowPos2i(__GLcontext *gc, GLint x, GLint y);
extern GLvoid GL_APIENTRY __glim_WindowPos2iv(__GLcontext *gc, const GLint *v);
extern GLvoid GL_APIENTRY __glim_WindowPos2s(__GLcontext *gc, GLshort x, GLshort y);
extern GLvoid GL_APIENTRY __glim_WindowPos2sv(__GLcontext *gc, const GLshort *v);
extern GLvoid GL_APIENTRY __glim_WindowPos3d(__GLcontext *gc, GLdouble x, GLdouble y, GLdouble z);
extern GLvoid GL_APIENTRY __glim_WindowPos3dv(__GLcontext *gc, const GLdouble *v);
extern GLvoid GL_APIENTRY __glim_WindowPos3f(__GLcontext *gc, GLfloat x, GLfloat y, GLfloat z);
extern GLvoid GL_APIENTRY __glim_WindowPos3fv(__GLcontext *gc, const GLfloat *v);
extern GLvoid GL_APIENTRY __glim_WindowPos3i(__GLcontext *gc, GLint x, GLint y, GLint z);
extern GLvoid GL_APIENTRY __glim_WindowPos3iv(__GLcontext *gc, const GLint *v);
extern GLvoid GL_APIENTRY __glim_WindowPos3s(__GLcontext *gc, GLshort x, GLshort y, GLshort z);
extern GLvoid GL_APIENTRY __glim_WindowPos3sv(__GLcontext *gc, const GLshort *v);
extern GLvoid* GL_APIENTRY __glim_MapBuffer(__GLcontext *gc, GLenum target, GLenum access);
extern GLvoid GL_APIENTRY __glim_DrawPixels(__GLcontext *gc,  GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid *pixels );
extern GLvoid GL_APIENTRY __glim_CopyPixels(__GLcontext *gc,  GLint x, GLint y,  GLsizei width, GLsizei height, GLenum type );
extern GLvoid GL_APIENTRY __glim_Indexub(__GLcontext *gc,  GLubyte c );
extern GLvoid GL_APIENTRY __glim_Indexubv(__GLcontext *gc,  const GLubyte *c );

/* OpenGL ES 2.0 */

extern GLvoid GL_APIENTRY __glim_ActiveTexture(__GLcontext *gc, GLenum texture);
extern GLvoid GL_APIENTRY __glim_AttachShader(__GLcontext *gc, GLuint program, GLuint shader);
extern GLvoid GL_APIENTRY __glim_BindAttribLocation(__GLcontext *gc, GLuint program, GLuint index, const GLchar* name);
extern GLvoid GL_APIENTRY __glim_BindBuffer(__GLcontext *gc, GLenum target, GLuint buffer);
extern GLvoid GL_APIENTRY __glim_BindFramebuffer(__GLcontext *gc, GLenum target, GLuint framebuffer);
extern GLvoid GL_APIENTRY __glim_BindRenderbuffer(__GLcontext *gc, GLenum target, GLuint renderbuffer);
extern GLvoid GL_APIENTRY __glim_BindTexture(__GLcontext *gc, GLenum target, GLuint texture);
extern GLvoid GL_APIENTRY __glim_BlendColor(__GLcontext *gc, GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha);
extern GLvoid GL_APIENTRY __glim_BlendEquation(__GLcontext *gc, GLenum mode);
extern GLvoid GL_APIENTRY __glim_BlendEquationSeparate(__GLcontext *gc, GLenum modeRGB, GLenum modeAlpha);
extern GLvoid GL_APIENTRY __glim_BlendFunc(__GLcontext *gc, GLenum sfactor, GLenum dfactor);
extern GLvoid GL_APIENTRY __glim_BlendFuncSeparate(__GLcontext *gc, GLenum srcRGB, GLenum dstRGB, GLenum srcAlpha, GLenum dstAlpha);
extern GLvoid GL_APIENTRY __glim_BufferData(__GLcontext *gc, GLenum target, GLsizeiptr size, const GLvoid* data, GLenum usage);
extern GLvoid GL_APIENTRY __glim_BufferSubData(__GLcontext *gc, GLenum target, GLintptr offset, GLsizeiptr size, const GLvoid* data);
extern GLenum GL_APIENTRY __glim_CheckFramebufferStatus(__GLcontext *gc, GLenum target);
extern GLvoid GL_APIENTRY __glim_Clear(__GLcontext *gc, GLbitfield mask);
extern GLvoid GL_APIENTRY __glim_ClearColor(__GLcontext *gc, GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha);
extern GLvoid GL_APIENTRY __glim_ClearDepthf(__GLcontext *gc, GLfloat depth);
extern GLvoid GL_APIENTRY __glim_ClearStencil(__GLcontext *gc, GLint s);
extern GLvoid GL_APIENTRY __glim_ColorMask(__GLcontext *gc, GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha);
extern GLvoid GL_APIENTRY __glim_CompileShader(__GLcontext *gc, GLuint shader);
extern GLvoid GL_APIENTRY __glim_CompressedTexImage2D(__GLcontext *gc, GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLint border, GLsizei imageSize, const GLvoid* data);
extern GLvoid GL_APIENTRY __glim_CompressedTexSubImage2D(__GLcontext *gc, GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLsizei imageSize, const GLvoid* data);
extern GLvoid GL_APIENTRY __glim_CopyTexImage2D(__GLcontext *gc, GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border);
extern GLvoid GL_APIENTRY __glim_CopyTexSubImage2D(__GLcontext *gc, GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height);
extern GLuint GL_APIENTRY __glim_CreateProgram(__GLcontext *gc);
extern GLuint GL_APIENTRY __glim_CreateShader(__GLcontext *gc, GLenum type);
extern GLvoid GL_APIENTRY __glim_CullFace(__GLcontext *gc, GLenum mode);
extern GLvoid GL_APIENTRY __glim_DeleteBuffers(__GLcontext *gc, GLsizei n, const GLuint* buffers);
extern GLvoid GL_APIENTRY __glim_DeleteFramebuffers(__GLcontext *gc, GLsizei n, const GLuint* framebuffers);
extern GLvoid GL_APIENTRY __glim_DeleteProgram(__GLcontext *gc, GLuint program);
extern GLvoid GL_APIENTRY __glim_DeleteRenderbuffers(__GLcontext *gc, GLsizei n, const GLuint* renderbuffers);
extern GLvoid GL_APIENTRY __glim_DeleteShader(__GLcontext *gc, GLuint shader);
extern GLvoid GL_APIENTRY __glim_DeleteTextures(__GLcontext *gc, GLsizei n, const GLuint* textures);
extern GLvoid GL_APIENTRY __glim_DepthFunc(__GLcontext *gc, GLenum func);
extern GLvoid GL_APIENTRY __glim_DepthMask(__GLcontext *gc, GLboolean flag);
extern GLvoid GL_APIENTRY __glim_DepthRangef(__GLcontext *gc, GLfloat n, GLfloat f);
extern GLvoid GL_APIENTRY __glim_DetachShader(__GLcontext *gc, GLuint program, GLuint shader);
extern GLvoid GL_APIENTRY __glim_Disable(__GLcontext *gc, GLenum cap);
extern GLvoid GL_APIENTRY __glim_DisableVertexAttribArray(__GLcontext *gc, GLuint index);
extern GLvoid GL_APIENTRY __glim_DrawArrays(__GLcontext *gc, GLenum mode, GLint first, GLsizei count);
extern GLvoid GL_APIENTRY __glim_DrawElements(__GLcontext *gc, GLenum mode, GLsizei count, GLenum type, const GLvoid* indices);
extern GLvoid GL_APIENTRY __glim_Enable(__GLcontext *gc, GLenum cap);
extern GLvoid GL_APIENTRY __glim_EnableVertexAttribArray(__GLcontext *gc, GLuint index);
extern GLvoid GL_APIENTRY __glim_Finish(__GLcontext *gc);
extern GLvoid GL_APIENTRY __glim_Flush(__GLcontext *gc);
extern GLvoid GL_APIENTRY __glim_FramebufferRenderbuffer(__GLcontext *gc, GLenum target, GLenum attachment, GLenum renderbuffertarget, GLuint renderbuffer);
extern GLvoid GL_APIENTRY __glim_FramebufferTexture2D(__GLcontext *gc, GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level);
extern GLvoid GL_APIENTRY __glim_FrontFace(__GLcontext *gc, GLenum mode);
extern GLvoid GL_APIENTRY __glim_GenBuffers(__GLcontext *gc, GLsizei n, GLuint* buffers);
extern GLvoid GL_APIENTRY __glim_GenerateMipmap(__GLcontext *gc, GLenum target);
extern GLvoid GL_APIENTRY __glim_GenFramebuffers(__GLcontext *gc, GLsizei n, GLuint* framebuffers);
extern GLvoid GL_APIENTRY __glim_GenRenderbuffers(__GLcontext *gc, GLsizei n, GLuint* renderbuffers);
extern GLvoid GL_APIENTRY __glim_GenTextures(__GLcontext *gc, GLsizei n, GLuint* textures);
extern GLvoid GL_APIENTRY __glim_GetActiveAttrib(__GLcontext *gc, GLuint program, GLuint index, GLsizei bufsize, GLsizei* length, GLint* size, GLenum* type, GLchar* name);
extern GLvoid GL_APIENTRY __glim_GetActiveUniform(__GLcontext *gc, GLuint program, GLuint index, GLsizei bufsize, GLsizei* length, GLint* size, GLenum* type, GLchar* name);
extern GLvoid GL_APIENTRY __glim_GetAttachedShaders(__GLcontext *gc, GLuint program, GLsizei maxcount, GLsizei* count, GLuint* shaders);
extern GLint  GL_APIENTRY __glim_GetAttribLocation(__GLcontext *gc, GLuint program, const GLchar* name);
extern GLvoid GL_APIENTRY __glim_GetBooleanv(__GLcontext *gc, GLenum pname, GLboolean* params);
extern GLvoid GL_APIENTRY __glim_GetBufferParameteriv(__GLcontext *gc, GLenum target, GLenum pname, GLint* params);
extern GLenum GL_APIENTRY __glim_GetError(__GLcontext *gc);
extern GLvoid GL_APIENTRY __glim_GetFloatv(__GLcontext *gc, GLenum pname, GLfloat* params);
extern GLvoid GL_APIENTRY __glim_GetFramebufferAttachmentParameteriv(__GLcontext *gc, GLenum target, GLenum attachment, GLenum pname, GLint* params);
extern GLvoid GL_APIENTRY __glim_GetIntegerv(__GLcontext *gc, GLenum pname, GLint* params);
extern GLvoid GL_APIENTRY __glim_GetProgramiv(__GLcontext *gc, GLuint program, GLenum pname, GLint* params);
extern GLvoid GL_APIENTRY __glim_GetProgramInfoLog(__GLcontext *gc, GLuint program, GLsizei bufsize, GLsizei* length, GLchar* infolog);
extern GLvoid GL_APIENTRY __glim_GetRenderbufferParameteriv(__GLcontext *gc, GLenum target, GLenum pname, GLint* params);
extern GLvoid GL_APIENTRY __glim_GetShaderiv(__GLcontext *gc, GLuint shader, GLenum pname, GLint* params);
extern GLvoid GL_APIENTRY __glim_GetShaderInfoLog(__GLcontext *gc, GLuint shader, GLsizei bufsize, GLsizei* length, GLchar* infolog);
extern GLvoid GL_APIENTRY __glim_GetShaderPrecisionFormat(__GLcontext *gc, GLenum shadertype, GLenum precisiontype, GLint* range, GLint* precision);
extern GLvoid GL_APIENTRY __glim_GetShaderSource(__GLcontext *gc, GLuint shader, GLsizei bufsize, GLsizei* length, GLchar* source);
extern const GLubyte* GL_APIENTRY __glim_GetString(__GLcontext *gc, GLenum name);
extern GLvoid GL_APIENTRY __glim_GetTexParameterfv(__GLcontext *gc, GLenum target, GLenum pname, GLfloat* params);
extern GLvoid GL_APIENTRY __glim_GetTexParameteriv(__GLcontext *gc, GLenum target, GLenum pname, GLint* params);
extern GLvoid GL_APIENTRY __glim_GetUniformfv(__GLcontext *gc, GLuint program, GLint location, GLfloat* params);
extern GLvoid GL_APIENTRY __glim_GetUniformiv(__GLcontext *gc, GLuint program, GLint location, GLint* params);
extern GLint  GL_APIENTRY __glim_GetUniformLocation(__GLcontext *gc, GLuint program, const GLchar* name);
extern GLvoid GL_APIENTRY __glim_GetVertexAttribfv(__GLcontext *gc, GLuint index, GLenum pname, GLfloat* params);
extern GLvoid GL_APIENTRY __glim_GetVertexAttribiv(__GLcontext *gc, GLuint index, GLenum pname, GLint* params);
extern GLvoid GL_APIENTRY __glim_GetVertexAttribdv(__GLcontext *gc, GLuint index, GLenum pname, GLdouble* params);
extern GLvoid GL_APIENTRY __glim_GetVertexAttribPointerv(__GLcontext *gc, GLuint index, GLenum pname, GLvoid** pointer);
extern GLvoid GL_APIENTRY __glim_Hint(__GLcontext *gc, GLenum target, GLenum mode);
extern GLboolean GL_APIENTRY __glim_IsBuffer(__GLcontext *gc, GLuint buffer);
extern GLboolean GL_APIENTRY __glim_IsEnabled(__GLcontext *gc, GLenum cap);
extern GLboolean GL_APIENTRY __glim_IsFramebuffer(__GLcontext *gc, GLuint framebuffer);
extern GLboolean GL_APIENTRY __glim_IsProgram(__GLcontext *gc, GLuint program);
extern GLboolean GL_APIENTRY __glim_IsRenderbuffer(__GLcontext *gc, GLuint renderbuffer);
extern GLboolean GL_APIENTRY __glim_IsShader(__GLcontext *gc, GLuint shader);
extern GLboolean GL_APIENTRY __glim_IsTexture(__GLcontext *gc, GLuint texture);
extern GLvoid GL_APIENTRY __glim_LineWidth(__GLcontext *gc, GLfloat width);
extern GLvoid GL_APIENTRY __glim_LinkProgram(__GLcontext *gc, GLuint program);
extern GLvoid GL_APIENTRY __glim_PixelStorei(__GLcontext *gc, GLenum pname, GLint param);
extern GLvoid GL_APIENTRY __glim_PolygonOffset(__GLcontext *gc, GLfloat factor, GLfloat units);
extern GLvoid GL_APIENTRY __glim_ReadPixels(__GLcontext *gc, GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLvoid* pixels);
extern GLvoid GL_APIENTRY __glim_ReleaseShaderCompiler(__GLcontext *gc);
extern GLvoid GL_APIENTRY __glim_RenderbufferStorage(__GLcontext *gc, GLenum target, GLenum internalformat, GLsizei width, GLsizei height);
extern GLvoid GL_APIENTRY __glim_SampleCoverage(__GLcontext *gc, GLfloat value, GLboolean invert);
extern GLvoid GL_APIENTRY __glim_Scissor(__GLcontext *gc, GLint x, GLint y, GLsizei width, GLsizei height);
extern GLvoid GL_APIENTRY __glim_ShaderBinary(__GLcontext *gc, GLsizei n, const GLuint* shaders, GLenum binaryformat, const GLvoid* binary, GLsizei length);
extern GLvoid GL_APIENTRY __glim_ShaderSource(__GLcontext *gc, GLuint shader, GLsizei count, const GLchar* const* string, const GLint* length);
extern GLvoid GL_APIENTRY __glim_StencilFunc(__GLcontext *gc, GLenum func, GLint ref, GLuint mask);
extern GLvoid GL_APIENTRY __glim_StencilFuncSeparate(__GLcontext *gc, GLenum face, GLenum func, GLint ref, GLuint mask);
extern GLvoid GL_APIENTRY __glim_StencilMask(__GLcontext *gc, GLuint mask);
extern GLvoid GL_APIENTRY __glim_StencilMaskSeparate(__GLcontext *gc, GLenum face, GLuint mask);
extern GLvoid GL_APIENTRY __glim_StencilOp(__GLcontext *gc, GLenum fail, GLenum zfail, GLenum zpass);
extern GLvoid GL_APIENTRY __glim_StencilOpSeparate(__GLcontext *gc, GLenum face, GLenum fail, GLenum zfail, GLenum zpass);
extern GLvoid GL_APIENTRY __glim_TexImage2D(__GLcontext *gc, GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const GLvoid* pixels);
extern GLvoid GL_APIENTRY __glim_TexParameterf(__GLcontext *gc, GLenum target, GLenum pname, GLfloat param);
extern GLvoid GL_APIENTRY __glim_TexParameterfv(__GLcontext *gc, GLenum target, GLenum pname, const GLfloat* params);
extern GLvoid GL_APIENTRY __glim_TexParameteri(__GLcontext *gc, GLenum target, GLenum pname, GLint param);
extern GLvoid GL_APIENTRY __glim_TexParameteriv(__GLcontext *gc, GLenum target, GLenum pname, const GLint* params);
extern GLvoid GL_APIENTRY __glim_TexSubImage2D(__GLcontext *gc, GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid* pixels);
extern GLvoid GL_APIENTRY __glim_Uniform1f(__GLcontext *gc, GLint location, GLfloat x);
extern GLvoid GL_APIENTRY __glim_Uniform1fv(__GLcontext *gc, GLint location, GLsizei count, const GLfloat* v);
extern GLvoid GL_APIENTRY __glim_Uniform1i(__GLcontext *gc, GLint location, GLint x);
extern GLvoid GL_APIENTRY __glim_Uniform1iv(__GLcontext *gc, GLint location, GLsizei count, const GLint* v);
extern GLvoid GL_APIENTRY __glim_Uniform2f(__GLcontext *gc, GLint location, GLfloat x, GLfloat y);
extern GLvoid GL_APIENTRY __glim_Uniform2fv(__GLcontext *gc, GLint location, GLsizei count, const GLfloat* v);
extern GLvoid GL_APIENTRY __glim_Uniform2i(__GLcontext *gc, GLint location, GLint x, GLint y);
extern GLvoid GL_APIENTRY __glim_Uniform2iv(__GLcontext *gc, GLint location, GLsizei count, const GLint* v);
extern GLvoid GL_APIENTRY __glim_Uniform3f(__GLcontext *gc, GLint location, GLfloat x, GLfloat y, GLfloat z);
extern GLvoid GL_APIENTRY __glim_Uniform3fv(__GLcontext *gc, GLint location, GLsizei count, const GLfloat* v);
extern GLvoid GL_APIENTRY __glim_Uniform3i(__GLcontext *gc, GLint location, GLint x, GLint y, GLint z);
extern GLvoid GL_APIENTRY __glim_Uniform3iv(__GLcontext *gc, GLint location, GLsizei count, const GLint* v);
extern GLvoid GL_APIENTRY __glim_Uniform4f(__GLcontext *gc, GLint location, GLfloat x, GLfloat y, GLfloat z, GLfloat w);
extern GLvoid GL_APIENTRY __glim_Uniform4fv(__GLcontext *gc, GLint location, GLsizei count, const GLfloat* v);
extern GLvoid GL_APIENTRY __glim_Uniform4i(__GLcontext *gc, GLint location, GLint x, GLint y, GLint z, GLint w);
extern GLvoid GL_APIENTRY __glim_Uniform4iv(__GLcontext *gc, GLint location, GLsizei count, const GLint* v);
extern GLvoid GL_APIENTRY __glim_UniformMatrix2fv(__GLcontext *gc, GLint location, GLsizei count, GLboolean transpose, const GLfloat* value);
extern GLvoid GL_APIENTRY __glim_UniformMatrix3fv(__GLcontext *gc, GLint location, GLsizei count, GLboolean transpose, const GLfloat* value);
extern GLvoid GL_APIENTRY __glim_UniformMatrix4fv(__GLcontext *gc, GLint location, GLsizei count, GLboolean transpose, const GLfloat* value);
extern GLvoid GL_APIENTRY __glim_UseProgram(__GLcontext *gc, GLuint program);
extern GLvoid GL_APIENTRY __glim_ValidateProgram(__GLcontext *gc, GLuint program);
extern  GLvoid  GLAPIENTRY __glim_VertexAttrib1d(__GLcontext *gc, GLuint indx, GLdouble x);
extern  GLvoid  GLAPIENTRY __glim_VertexAttrib1dv(__GLcontext *gc, GLuint indx, const GLdouble *values);
extern  GLvoid  GLAPIENTRY __glim_VertexAttrib1f(__GLcontext *gc, GLuint indx, GLfloat x);
extern  GLvoid  GLAPIENTRY __glim_VertexAttrib1fv(__GLcontext *gc, GLuint indx, const GLfloat * values);
extern  GLvoid  GLAPIENTRY __glim_VertexAttrib1s(__GLcontext *gc, GLuint indx, GLshort x);
extern  GLvoid  GLAPIENTRY __glim_VertexAttrib1sv(__GLcontext *gc, GLuint indx, const GLshort * values);
extern  GLvoid  GLAPIENTRY __glim_VertexAttrib2d(__GLcontext *gc, GLuint indx, GLdouble x, GLdouble y);
extern  GLvoid  GLAPIENTRY __glim_VertexAttrib2dv(__GLcontext *gc, GLuint indx, const GLdouble * values);
extern  GLvoid  GLAPIENTRY __glim_VertexAttrib2f(__GLcontext *gc, GLuint indx, GLfloat x, GLfloat y);
extern  GLvoid  GLAPIENTRY __glim_VertexAttrib2fv(__GLcontext *gc, GLuint indx, const GLfloat * values);
extern  GLvoid  GLAPIENTRY __glim_VertexAttrib2s(__GLcontext *gc, GLuint indx, GLshort x, GLshort y);
extern  GLvoid  GLAPIENTRY __glim_VertexAttrib2sv(__GLcontext *gc, GLuint indx, const GLshort * values);
extern  GLvoid  GLAPIENTRY __glim_VertexAttrib3d(__GLcontext *gc, GLuint indx, GLdouble x, GLdouble y, GLdouble z);
extern  GLvoid  GLAPIENTRY __glim_VertexAttrib3dv(__GLcontext *gc, GLuint indx, const GLdouble * values);
extern  GLvoid  GLAPIENTRY __glim_VertexAttrib3f(__GLcontext *gc, GLuint indx, GLfloat x, GLfloat y, GLfloat z);
extern  GLvoid  GLAPIENTRY __glim_VertexAttrib3fv(__GLcontext *gc, GLuint indx, const GLfloat * values);
extern  GLvoid  GLAPIENTRY __glim_VertexAttrib3s(__GLcontext *gc, GLuint indx, GLshort x, GLshort y, GLshort z);
extern  GLvoid  GLAPIENTRY __glim_VertexAttrib3sv(__GLcontext *gc, GLuint indx, const GLshort * values);
extern  GLvoid  GLAPIENTRY __glim_VertexAttrib4Nbv(__GLcontext *gc, GLuint indx, const GLbyte * values);
extern  GLvoid  GLAPIENTRY __glim_VertexAttrib4Niv(__GLcontext *gc, GLuint indx, const GLint * values);
extern  GLvoid  GLAPIENTRY __glim_VertexAttrib4Nsv(__GLcontext *gc, GLuint indx, const GLshort * values);
extern  GLvoid  GLAPIENTRY __glim_VertexAttrib4Nub(__GLcontext *gc, GLuint indx, GLubyte x, GLubyte y, GLubyte z, GLubyte w);
extern  GLvoid  GLAPIENTRY __glim_VertexAttrib4Nubv(__GLcontext *gc, GLuint indx, const GLubyte * values);
extern  GLvoid  GLAPIENTRY __glim_VertexAttrib4Nuiv(__GLcontext *gc, GLuint indx, const GLuint * values);
extern  GLvoid  GLAPIENTRY __glim_VertexAttrib4Nusv(__GLcontext *gc, GLuint indx, const GLushort * values);
extern  GLvoid  GLAPIENTRY __glim_VertexAttrib4bv(__GLcontext *gc, GLuint indx, const GLbyte * values);
extern  GLvoid  GLAPIENTRY __glim_VertexAttrib4d(__GLcontext *gc, GLuint indx, GLdouble x, GLdouble y, GLdouble z, GLdouble w);
extern  GLvoid  GLAPIENTRY __glim_VertexAttrib4dv(__GLcontext *gc, GLuint indx, const GLdouble * values);
extern  GLvoid  GLAPIENTRY __glim_VertexAttrib4f(__GLcontext *gc, GLuint indx, GLfloat x, GLfloat y, GLfloat z, GLfloat w);
extern  GLvoid  GLAPIENTRY __glim_VertexAttrib4fv(__GLcontext *gc, GLuint indx, const GLfloat * values);
extern  GLvoid  GLAPIENTRY __glim_VertexAttrib4iv(__GLcontext *gc, GLuint indx, const GLint * values);
extern  GLvoid  GLAPIENTRY __glim_VertexAttrib4s(__GLcontext *gc, GLuint indx, GLshort x, GLshort y, GLshort z, GLshort w);
extern  GLvoid  GLAPIENTRY __glim_VertexAttrib4sv(__GLcontext *gc, GLuint indx, const GLshort * values);
extern  GLvoid  GLAPIENTRY __glim_VertexAttrib4ubv(__GLcontext *gc, GLuint indx, const GLubyte * values);
extern  GLvoid  GLAPIENTRY __glim_VertexAttrib4uiv(__GLcontext *gc, GLuint indx, const GLuint * values);
extern  GLvoid  GLAPIENTRY __glim_VertexAttrib4usv(__GLcontext *gc, GLuint indx, const GLushort * values);
extern GLvoid GL_APIENTRY __glim_VertexAttribPointer(__GLcontext *gc, GLuint indx, GLint size, GLenum type, GLboolean normalized, GLsizei stride, const GLvoid* ptr);
extern GLvoid GL_APIENTRY __glim_Viewport(__GLcontext *gc, GLint x, GLint y, GLsizei width, GLsizei height);

/* OpenGL ES 3.0 */

extern GLvoid GL_APIENTRY __glim_ReadBuffer(__GLcontext *gc, GLenum mode);
extern GLvoid GL_APIENTRY __glim_DrawRangeElements(__GLcontext *gc, GLenum mode, GLuint start, GLuint end, GLsizei count, GLenum type, const GLvoid* indices);
extern GLvoid GL_APIENTRY __glim_TexImage3D(__GLcontext *gc, GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLenum format, GLenum type, const GLvoid* pixels);
extern GLvoid GL_APIENTRY __glim_TexSubImage3D(__GLcontext *gc, GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, const GLvoid* pixels);
extern GLvoid GL_APIENTRY __glim_CopyTexSubImage3D(__GLcontext *gc, GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLint x, GLint y, GLsizei width, GLsizei height);
extern GLvoid GL_APIENTRY __glim_CompressedTexImage3D(__GLcontext *gc, GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLsizei imageSize, const GLvoid* data);
extern GLvoid GL_APIENTRY __glim_CompressedTexSubImage3D(__GLcontext *gc, GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLsizei imageSize, const GLvoid* data);
extern GLvoid GL_APIENTRY __glim_GenQueries(__GLcontext *gc, GLsizei n, GLuint* ids);
extern GLvoid GL_APIENTRY __glim_DeleteQueries(__GLcontext *gc, GLsizei n, const GLuint* ids);
extern GLboolean GL_APIENTRY __glim_IsQuery(__GLcontext *gc, GLuint id);
extern GLvoid GL_APIENTRY __glim_BeginQuery(__GLcontext *gc, GLenum target, GLuint id);
extern GLvoid GL_APIENTRY __glim_EndQuery(__GLcontext *gc, GLenum target);
extern GLvoid GL_APIENTRY __glim_GetQueryiv(__GLcontext *gc, GLenum target, GLenum pname, GLint* params);
extern GLvoid GL_APIENTRY __glim_GetQueryObjectuiv(__GLcontext *gc, GLuint id, GLenum pname, GLuint* params);
extern GLboolean GL_APIENTRY __glim_UnmapBuffer(__GLcontext *gc, GLenum target);
extern GLvoid GL_APIENTRY __glim_GetBufferPointerv(__GLcontext *gc, GLenum target, GLenum pname, GLvoid** params);
extern GLvoid GL_APIENTRY __glim_DrawBuffers(__GLcontext *gc, GLsizei n, const GLenum* bufs);
extern GLvoid GL_APIENTRY __glim_UniformMatrix2x3fv(__GLcontext *gc, GLint location, GLsizei count, GLboolean transpose, const GLfloat* value);
extern GLvoid GL_APIENTRY __glim_UniformMatrix3x2fv(__GLcontext *gc, GLint location, GLsizei count, GLboolean transpose, const GLfloat* value);
extern GLvoid GL_APIENTRY __glim_UniformMatrix2x4fv(__GLcontext *gc, GLint location, GLsizei count, GLboolean transpose, const GLfloat* value);
extern GLvoid GL_APIENTRY __glim_UniformMatrix4x2fv(__GLcontext *gc, GLint location, GLsizei count, GLboolean transpose, const GLfloat* value);
extern GLvoid GL_APIENTRY __glim_UniformMatrix3x4fv(__GLcontext *gc, GLint location, GLsizei count, GLboolean transpose, const GLfloat* value);
extern GLvoid GL_APIENTRY __glim_UniformMatrix4x3fv(__GLcontext *gc, GLint location, GLsizei count, GLboolean transpose, const GLfloat* value);
extern GLvoid GL_APIENTRY __glim_BlitFramebuffer(__GLcontext *gc, GLint srcX0, GLint srcY0, GLint srcX1, GLint srcY1, GLint dstX0, GLint dstY0, GLint dstX1, GLint dstY1, GLbitfield mask, GLenum filter);
extern GLvoid GL_APIENTRY __glim_RenderbufferStorageMultisample(__GLcontext *gc, GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height);
extern GLvoid GL_APIENTRY __glim_FramebufferTextureLayer(__GLcontext *gc, GLenum target, GLenum attachment, GLuint texture, GLint level, GLint layer);
extern GLvoid* GL_APIENTRY __glim_MapBufferRange(__GLcontext *gc, GLenum target, GLintptr offset, GLsizeiptr length, GLbitfield access);
extern GLvoid GL_APIENTRY __glim_FlushMappedBufferRange(__GLcontext *gc, GLenum target, GLintptr offset, GLsizeiptr length);
extern GLvoid GL_APIENTRY __glim_BindVertexArray(__GLcontext *gc, GLuint array);
extern GLvoid GL_APIENTRY __glim_DeleteVertexArrays(__GLcontext *gc, GLsizei n, const GLuint* arrays);
extern GLvoid GL_APIENTRY __glim_GenVertexArrays(__GLcontext *gc, GLsizei n, GLuint* arrays);
extern GLboolean GL_APIENTRY __glim_IsVertexArray(__GLcontext *gc, GLuint array);
extern GLvoid GL_APIENTRY __glim_GetIntegeri_v(__GLcontext *gc, GLenum target, GLuint index, GLint* data);
extern GLvoid GL_APIENTRY __glim_BeginTransformFeedback(__GLcontext *gc, GLenum primitiveMode);
extern GLvoid GL_APIENTRY __glim_EndTransformFeedback(__GLcontext *gc);
extern GLvoid GL_APIENTRY __glim_BindBufferRange(__GLcontext *gc, GLenum target, GLuint index, GLuint buffer, GLintptr offset, GLsizeiptr size);
extern GLvoid GL_APIENTRY __glim_BindBufferBase(__GLcontext *gc, GLenum target, GLuint index, GLuint buffer);
extern GLvoid GL_APIENTRY __glim_TransformFeedbackVaryings(__GLcontext *gc, GLuint program, GLsizei count, const GLchar* const* varyings, GLenum bufferMode);
extern GLvoid GL_APIENTRY __glim_GetTransformFeedbackVarying(__GLcontext *gc, GLuint program, GLuint index, GLsizei bufSize, GLsizei* length, GLsizei* size, GLenum* type, GLchar* name);
extern GLvoid GL_APIENTRY __glim_VertexAttribIPointer(__GLcontext *gc, GLuint index, GLint size, GLenum type, GLsizei stride, const GLvoid* pointer);
extern GLvoid GL_APIENTRY __glim_GetVertexAttribIiv(__GLcontext *gc, GLuint index, GLenum pname, GLint* params);
extern GLvoid GL_APIENTRY __glim_GetVertexAttribIuiv(__GLcontext *gc, GLuint index, GLenum pname, GLuint* params);
extern GLvoid GL_APIENTRY __glim_VertexAttribI4i(__GLcontext *gc, GLuint index, GLint x, GLint y, GLint z, GLint w);
extern GLvoid GL_APIENTRY __glim_VertexAttribI4ui(__GLcontext *gc, GLuint index, GLuint x, GLuint y, GLuint z, GLuint w);
extern GLvoid GL_APIENTRY __glim_VertexAttribI4iv(__GLcontext *gc, GLuint index, const GLint* v);
extern GLvoid GL_APIENTRY __glim_VertexAttribI4uiv(__GLcontext *gc, GLuint index, const GLuint* v);
extern GLvoid GL_APIENTRY __glim_GetUniformuiv(__GLcontext *gc, GLuint program, GLint location, GLuint* params);
extern GLint  GL_APIENTRY __glim_GetFragDataLocation(__GLcontext *gc, GLuint program, const GLchar *name);
extern GLvoid GL_APIENTRY __glim_Uniform1ui(__GLcontext *gc, GLint location, GLuint v0);
extern GLvoid GL_APIENTRY __glim_Uniform2ui(__GLcontext *gc, GLint location, GLuint v0, GLuint v1);
extern GLvoid GL_APIENTRY __glim_Uniform3ui(__GLcontext *gc, GLint location, GLuint v0, GLuint v1, GLuint v2);
extern GLvoid GL_APIENTRY __glim_Uniform4ui(__GLcontext *gc, GLint location, GLuint v0, GLuint v1, GLuint v2, GLuint v3);
extern GLvoid GL_APIENTRY __glim_Uniform1uiv(__GLcontext *gc, GLint location, GLsizei count, const GLuint* value);
extern GLvoid GL_APIENTRY __glim_Uniform2uiv(__GLcontext *gc, GLint location, GLsizei count, const GLuint* value);
extern GLvoid GL_APIENTRY __glim_Uniform3uiv(__GLcontext *gc, GLint location, GLsizei count, const GLuint* value);
extern GLvoid GL_APIENTRY __glim_Uniform4uiv(__GLcontext *gc, GLint location, GLsizei count, const GLuint* value);
extern GLvoid GL_APIENTRY __glim_ClearBufferiv(__GLcontext *gc, GLenum buffer, GLint drawbuffer, const GLint* value);
extern GLvoid GL_APIENTRY __glim_ClearBufferuiv(__GLcontext *gc, GLenum buffer, GLint drawbuffer, const GLuint* value);
extern GLvoid GL_APIENTRY __glim_ClearBufferfv(__GLcontext *gc, GLenum buffer, GLint drawbuffer, const GLfloat* value);
extern GLvoid GL_APIENTRY __glim_ClearBufferfi(__GLcontext *gc, GLenum buffer, GLint drawbuffer, GLfloat depth, GLint stencil);
extern const GLubyte* GL_APIENTRY __glim_GetStringi(__GLcontext *gc, GLenum name, GLuint index);
extern GLvoid GL_APIENTRY __glim_CopyBufferSubData(__GLcontext *gc, GLenum readTarget, GLenum writeTarget, GLintptr readOffset, GLintptr writeOffset, GLsizeiptr size);
extern GLvoid GL_APIENTRY __glim_GetUniformIndices(__GLcontext *gc, GLuint program, GLsizei uniformCount, const GLchar* const* uniformNames, GLuint* uniformIndices);
extern GLvoid GL_APIENTRY __glim_GetActiveUniformsiv(__GLcontext *gc, GLuint program, GLsizei uniformCount, const GLuint* uniformIndices, GLenum pname, GLint* params);
extern GLuint GL_APIENTRY __glim_GetUniformBlockIndex(__GLcontext *gc, GLuint program, const GLchar* uniformBlockName);
extern GLvoid GL_APIENTRY __glim_GetActiveUniformBlockiv(__GLcontext *gc, GLuint program, GLuint uniformBlockIndex, GLenum pname, GLint* params);
extern GLvoid GL_APIENTRY __glim_GetActiveUniformBlockName(__GLcontext *gc, GLuint program, GLuint uniformBlockIndex, GLsizei bufSize, GLsizei* length, GLchar* uniformBlockName);
extern GLvoid GL_APIENTRY __glim_UniformBlockBinding(__GLcontext *gc, GLuint program, GLuint uniformBlockIndex, GLuint uniformBlockBinding);
extern GLvoid GL_APIENTRY __glim_DrawArraysInstanced(__GLcontext *gc, GLenum mode, GLint first, GLsizei count, GLsizei instanceCount);
extern GLvoid GL_APIENTRY __glim_DrawElementsInstanced(__GLcontext *gc, GLenum mode, GLsizei count, GLenum type, const GLvoid* indices, GLsizei instanceCount);
extern GLsync GL_APIENTRY __glim_FenceSync(__GLcontext *gc, GLenum condition, GLbitfield flags);
extern GLboolean GL_APIENTRY __glim_IsSync(__GLcontext *gc, GLsync sync);
extern GLvoid GL_APIENTRY __glim_DeleteSync(__GLcontext *gc, GLsync sync);
extern GLenum GL_APIENTRY __glim_ClientWaitSync(__GLcontext *gc, GLsync sync, GLbitfield flags, GLuint64 timeout);
extern GLvoid GL_APIENTRY __glim_WaitSync(__GLcontext *gc, GLsync sync, GLbitfield flags, GLuint64 timeout);
extern GLvoid GL_APIENTRY __glim_GetInteger64v(__GLcontext *gc, GLenum pname, GLint64* params);
extern GLvoid GL_APIENTRY __glim_GetSynciv(__GLcontext *gc, GLsync sync, GLenum pname, GLsizei bufSize, GLsizei* length, GLint* values);
extern GLvoid GL_APIENTRY __glim_GetInteger64i_v(__GLcontext *gc, GLenum target, GLuint index, GLint64* data);
extern GLvoid GL_APIENTRY __glim_GetBufferParameteri64v(__GLcontext *gc, GLenum target, GLenum pname, GLint64* params);
extern GLvoid GL_APIENTRY __glim_GenSamplers(__GLcontext *gc, GLsizei count, GLuint* samplers);
extern GLvoid GL_APIENTRY __glim_DeleteSamplers(__GLcontext *gc, GLsizei count, const GLuint* samplers);
extern GLboolean GL_APIENTRY __glim_IsSampler(__GLcontext *gc, GLuint sampler);
extern GLvoid GL_APIENTRY __glim_BindSampler(__GLcontext *gc, GLuint unit, GLuint sampler);
extern GLvoid GL_APIENTRY __glim_SamplerParameteri(__GLcontext *gc, GLuint sampler, GLenum pname, GLint param);
extern GLvoid GL_APIENTRY __glim_SamplerParameteriv(__GLcontext *gc, GLuint sampler, GLenum pname, const GLint* param);
extern GLvoid GL_APIENTRY __glim_SamplerParameterf(__GLcontext *gc, GLuint sampler, GLenum pname, GLfloat param);
extern GLvoid GL_APIENTRY __glim_SamplerParameterfv(__GLcontext *gc, GLuint sampler, GLenum pname, const GLfloat* param);
extern GLvoid GL_APIENTRY __glim_GetSamplerParameteriv(__GLcontext *gc, GLuint sampler, GLenum pname, GLint* params);
extern GLvoid GL_APIENTRY __glim_GetSamplerParameterfv(__GLcontext *gc, GLuint sampler, GLenum pname, GLfloat* params);
extern GLvoid GL_APIENTRY __glim_VertexAttribDivisor(__GLcontext *gc, GLuint index, GLuint divisor);
extern GLvoid GL_APIENTRY __glim_BindTransformFeedback(__GLcontext *gc, GLenum target, GLuint id);
extern GLvoid GL_APIENTRY __glim_DeleteTransformFeedbacks(__GLcontext *gc, GLsizei n, const GLuint* ids);
extern GLvoid GL_APIENTRY __glim_GenTransformFeedbacks(__GLcontext *gc, GLsizei n, GLuint* ids);
extern GLboolean GL_APIENTRY __glim_IsTransformFeedback(__GLcontext *gc, GLuint id);
extern GLvoid GL_APIENTRY __glim_PauseTransformFeedback(__GLcontext *gc);
extern GLvoid GL_APIENTRY __glim_ResumeTransformFeedback(__GLcontext *gc);
extern GLvoid GL_APIENTRY __glim_GetProgramBinary(__GLcontext *gc, GLuint program, GLsizei bufSize, GLsizei* length, GLenum* binaryFormat, GLvoid* binary);
extern GLvoid GL_APIENTRY __glim_ProgramBinary(__GLcontext *gc, GLuint program, GLenum binaryFormat, const GLvoid* binary, GLsizei length);
extern GLvoid GL_APIENTRY __glim_ProgramParameteri(__GLcontext *gc, GLuint program, GLenum pname, GLint value);
extern GLvoid GL_APIENTRY __glim_InvalidateFramebuffer(__GLcontext *gc, GLenum target, GLsizei numAttachments, const GLenum* attachments);
extern GLvoid GL_APIENTRY __glim_InvalidateSubFramebuffer(__GLcontext *gc, GLenum target, GLsizei numAttachments, const GLenum* attachments, GLint x, GLint y, GLsizei width, GLsizei height);
extern GLvoid GL_APIENTRY __glim_TexStorage2D(__GLcontext *gc, GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height);
extern GLvoid GL_APIENTRY __glim_TexStorage3D(__GLcontext *gc, GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth);
extern GLvoid GL_APIENTRY __glim_GetInternalformativ(__GLcontext *gc, GLenum target, GLenum internalformat, GLenum pname, GLsizei bufSize, GLint* params);

/* OpenGL ES 3.1 */

extern GLvoid GL_APIENTRY __glim_DispatchCompute(__GLcontext *gc, GLuint num_groups_x, GLuint num_groups_y, GLuint num_groups_z);
extern GLvoid GL_APIENTRY __glim_DispatchComputeIndirect(__GLcontext *gc, GLintptr indirect);
extern GLvoid GL_APIENTRY __glim_DrawArraysIndirect(__GLcontext *gc, GLenum mode, const void *indirect);
extern GLvoid GL_APIENTRY __glim_DrawElementsIndirect(__GLcontext *gc, GLenum mode, GLenum type, const void *indirect);
extern GLvoid GL_APIENTRY __glim_FramebufferParameteri(__GLcontext *gc, GLenum target, GLenum pname, GLint param);
extern GLvoid GL_APIENTRY __glim_GetFramebufferParameteriv(__GLcontext *gc, GLenum target, GLenum pname, GLint *params);
extern GLvoid GL_APIENTRY __glim_GetProgramInterfaceiv(__GLcontext *gc, GLuint program, GLenum programInterface, GLenum pname, GLint *params);
extern GLuint GL_APIENTRY __glim_GetProgramResourceIndex(__GLcontext *gc, GLuint program, GLenum programInterface, const GLchar *name);
extern GLvoid GL_APIENTRY __glim_GetProgramResourceName(__GLcontext *gc, GLuint program, GLenum programInterface, GLuint index, GLsizei bufSize, GLsizei *length, GLchar *name);
extern GLvoid GL_APIENTRY __glim_GetProgramResourceiv(__GLcontext *gc, GLuint program, GLenum programInterface, GLuint index, GLsizei propCount, const GLenum *props, GLsizei bufSize, GLsizei *length, GLint *params);
extern GLint GL_APIENTRY __glim_GetProgramResourceLocation(__GLcontext *gc, GLuint program, GLenum programInterface, const GLchar *name);
extern GLvoid GL_APIENTRY __glim_UseProgramStages(__GLcontext *gc, GLuint pipeline, GLbitfield stages, GLuint program);
extern GLvoid GL_APIENTRY __glim_ActiveShaderProgram(__GLcontext *gc, GLuint pipeline, GLuint program);
extern GLuint GL_APIENTRY __glim_CreateShaderProgramv(__GLcontext *gc, GLenum type, GLsizei count, const GLchar *const*strings);
extern GLvoid GL_APIENTRY __glim_BindProgramPipeline(__GLcontext *gc, GLuint pipeline);
extern GLvoid GL_APIENTRY __glim_DeleteProgramPipelines(__GLcontext *gc, GLsizei n, const GLuint *pipelines);
extern GLvoid GL_APIENTRY __glim_GenProgramPipelines(__GLcontext *gc, GLsizei n, GLuint *pipelines);
extern GLboolean GL_APIENTRY __glim_IsProgramPipeline(__GLcontext *gc, GLuint pipeline);
extern GLvoid GL_APIENTRY __glim_GetProgramPipelineiv(__GLcontext *gc, GLuint pipeline, GLenum pname, GLint *params);
extern GLvoid GL_APIENTRY __glim_ProgramUniform1i(__GLcontext *gc, GLuint program, GLint location, GLint v0);
extern GLvoid GL_APIENTRY __glim_ProgramUniform2i(__GLcontext *gc, GLuint program, GLint location, GLint v0, GLint v1);
extern GLvoid GL_APIENTRY __glim_ProgramUniform3i(__GLcontext *gc, GLuint program, GLint location, GLint v0, GLint v1, GLint v2);
extern GLvoid GL_APIENTRY __glim_ProgramUniform4i(__GLcontext *gc, GLuint program, GLint location, GLint v0, GLint v1, GLint v2, GLint v3);
extern GLvoid GL_APIENTRY __glim_ProgramUniform1ui(__GLcontext *gc, GLuint program, GLint location, GLuint v0);
extern GLvoid GL_APIENTRY __glim_ProgramUniform2ui(__GLcontext *gc, GLuint program, GLint location, GLuint v0, GLuint v1);
extern GLvoid GL_APIENTRY __glim_ProgramUniform3ui(__GLcontext *gc, GLuint program, GLint location, GLuint v0, GLuint v1, GLuint v2);
extern GLvoid GL_APIENTRY __glim_ProgramUniform4ui(__GLcontext *gc, GLuint program, GLint location, GLuint v0, GLuint v1, GLuint v2, GLuint v3);
extern GLvoid GL_APIENTRY __glim_ProgramUniform1f(__GLcontext *gc, GLuint program, GLint location, GLfloat v0);
extern GLvoid GL_APIENTRY __glim_ProgramUniform2f(__GLcontext *gc, GLuint program, GLint location, GLfloat v0, GLfloat v1);
extern GLvoid GL_APIENTRY __glim_ProgramUniform3f(__GLcontext *gc, GLuint program, GLint location, GLfloat v0, GLfloat v1, GLfloat v2);
extern GLvoid GL_APIENTRY __glim_ProgramUniform4f(__GLcontext *gc, GLuint program, GLint location, GLfloat v0, GLfloat v1, GLfloat v2, GLfloat v3);
extern GLvoid GL_APIENTRY __glim_ProgramUniform1iv(__GLcontext *gc, GLuint program, GLint location, GLsizei count, const GLint *value);
extern GLvoid GL_APIENTRY __glim_ProgramUniform2iv(__GLcontext *gc, GLuint program, GLint location, GLsizei count, const GLint *value);
extern GLvoid GL_APIENTRY __glim_ProgramUniform3iv(__GLcontext *gc, GLuint program, GLint location, GLsizei count, const GLint *value);
extern GLvoid GL_APIENTRY __glim_ProgramUniform4iv(__GLcontext *gc, GLuint program, GLint location, GLsizei count, const GLint *value);
extern GLvoid GL_APIENTRY __glim_ProgramUniform1uiv(__GLcontext *gc, GLuint program, GLint location, GLsizei count, const GLuint *value);
extern GLvoid GL_APIENTRY __glim_ProgramUniform2uiv(__GLcontext *gc, GLuint program, GLint location, GLsizei count, const GLuint *value);
extern GLvoid GL_APIENTRY __glim_ProgramUniform3uiv(__GLcontext *gc, GLuint program, GLint location, GLsizei count, const GLuint *value);
extern GLvoid GL_APIENTRY __glim_ProgramUniform4uiv(__GLcontext *gc, GLuint program, GLint location, GLsizei count, const GLuint *value);
extern GLvoid GL_APIENTRY __glim_ProgramUniform1fv(__GLcontext *gc, GLuint program, GLint location, GLsizei count, const GLfloat *value);
extern GLvoid GL_APIENTRY __glim_ProgramUniform2fv(__GLcontext *gc, GLuint program, GLint location, GLsizei count, const GLfloat *value);
extern GLvoid GL_APIENTRY __glim_ProgramUniform3fv(__GLcontext *gc, GLuint program, GLint location, GLsizei count, const GLfloat *value);
extern GLvoid GL_APIENTRY __glim_ProgramUniform4fv(__GLcontext *gc, GLuint program, GLint location, GLsizei count, const GLfloat *value);
extern GLvoid GL_APIENTRY __glim_ProgramUniformMatrix2fv(__GLcontext *gc, GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
extern GLvoid GL_APIENTRY __glim_ProgramUniformMatrix3fv(__GLcontext *gc, GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
extern GLvoid GL_APIENTRY __glim_ProgramUniformMatrix4fv(__GLcontext *gc, GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
extern GLvoid GL_APIENTRY __glim_ProgramUniformMatrix2x3fv(__GLcontext *gc, GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
extern GLvoid GL_APIENTRY __glim_ProgramUniformMatrix3x2fv(__GLcontext *gc, GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
extern GLvoid GL_APIENTRY __glim_ProgramUniformMatrix2x4fv(__GLcontext *gc, GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
extern GLvoid GL_APIENTRY __glim_ProgramUniformMatrix4x2fv(__GLcontext *gc, GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
extern GLvoid GL_APIENTRY __glim_ProgramUniformMatrix3x4fv(__GLcontext *gc, GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
extern GLvoid GL_APIENTRY __glim_ProgramUniformMatrix4x3fv(__GLcontext *gc, GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
extern GLvoid GL_APIENTRY __glim_ValidateProgramPipeline(__GLcontext *gc, GLuint pipeline);
extern GLvoid GL_APIENTRY __glim_GetProgramPipelineInfoLog(__GLcontext *gc, GLuint pipeline, GLsizei bufSize, GLsizei *length, GLchar *infoLog);
extern GLvoid GL_APIENTRY __glim_BindImageTexture(__GLcontext *gc, GLuint unit, GLuint texture, GLint level, GLboolean layered, GLint layer, GLenum access, GLenum format);
extern GLvoid GL_APIENTRY __glim_GetBooleani_v(__GLcontext *gc, GLenum target, GLuint index, GLboolean *data);
extern GLvoid GL_APIENTRY __glim_MemoryBarrier(__GLcontext *gc, GLbitfield barriers);
extern GLvoid GL_APIENTRY __glim_MemoryBarrierByRegion(__GLcontext *gc, GLbitfield barriers);
extern GLvoid GL_APIENTRY __glim_TexStorage2DMultisample(__GLcontext *gc, GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height, GLboolean fixedsamplelocations);
extern GLvoid GL_APIENTRY __glim_GetMultisamplefv(__GLcontext *gc, GLenum pname, GLuint index, GLfloat *val);
extern GLvoid GL_APIENTRY __glim_SampleMaski(__GLcontext *gc, GLuint maskNumber, GLbitfield mask);
extern GLvoid GL_APIENTRY __glim_GetTexLevelParameteriv(__GLcontext *gc, GLenum target, GLint level, GLenum pname, GLint *params);
extern GLvoid GL_APIENTRY __glim_GetTexLevelParameterfv(__GLcontext *gc, GLenum target, GLint level, GLenum pname, GLfloat *params);
extern GLvoid GL_APIENTRY __glim_BindVertexBuffer(__GLcontext *gc, GLuint bindingindex, GLuint buffer, GLintptr offset, GLsizei stride);
extern GLvoid GL_APIENTRY __glim_VertexAttribFormat(__GLcontext *gc, GLuint attribindex, GLint size, GLenum type, GLboolean normalized, GLuint relativeoffset);
extern GLvoid GL_APIENTRY __glim_VertexAttribIFormat(__GLcontext *gc, GLuint attribindex, GLint size, GLenum type, GLuint relativeoffset);
extern GLvoid GL_APIENTRY __glim_VertexAttribBinding(__GLcontext *gc, GLuint attribindex, GLuint bindingindex);
extern GLvoid GL_APIENTRY __glim_VertexBindingDivisor(__GLcontext *gc, GLuint bindingindex, GLuint divisor);

/* OpenGL ES 3.2 */
extern GLvoid GL_APIENTRY __glim_TexStorage3DMultisample(__GLcontext *gc, GLenum target, GLsizei samples, GLenum sizedinternalformat, GLsizei width, GLsizei height, GLsizei depth, GLboolean fixedsamplelocations);

extern GLvoid GL_APIENTRY __glim_BlendBarrier(__GLcontext *gc);

extern GLvoid GL_APIENTRY __glim_DebugMessageControl(__GLcontext *gc, GLenum source, GLenum type, GLenum severity, GLsizei count, const GLuint* ids, GLboolean enabled);
extern GLvoid GL_APIENTRY __glim_DebugMessageInsert(__GLcontext *gc, GLenum source, GLenum type, GLuint id, GLenum severity, GLsizei length, const GLchar* buf);
extern GLvoid GL_APIENTRY __glim_DebugMessageCallback(__GLcontext *gc, GLDEBUGPROCKHR callback, const GLvoid* userParam);
extern GLuint GL_APIENTRY __glim_GetDebugMessageLog(__GLcontext *gc, GLuint count, GLsizei bufSize, GLenum* sources, GLenum* types, GLuint* ids, GLenum* severities, GLsizei* lengths, GLchar* messageLog);
extern GLvoid GL_APIENTRY __glim_GetPointerv(__GLcontext *gc, GLenum pname, GLvoid** params);
extern GLvoid GL_APIENTRY __glim_PushDebugGroup(__GLcontext *gc, GLenum source, GLuint id, GLsizei length, const GLchar * message);
extern GLvoid GL_APIENTRY __glim_PopDebugGroup(__GLcontext *gc);
extern GLvoid GL_APIENTRY __glim_ObjectLabel(__GLcontext *gc, GLenum identifier, GLuint name, GLsizei length, const GLchar *label);
extern GLvoid GL_APIENTRY __glim_GetObjectLabel(__GLcontext *gc, GLenum identifier, GLuint name, GLsizei bufSize, GLsizei *length, GLchar *label);
extern GLvoid GL_APIENTRY __glim_ObjectPtrLabel(__GLcontext *gc, const GLvoid* ptr, GLsizei length, const GLchar *label);
extern GLvoid GL_APIENTRY __glim_GetObjectPtrLabel(__GLcontext *gc, const GLvoid* ptr, GLsizei bufSize, GLsizei *length, GLchar *label);


extern GLenum GL_APIENTRY __glim_GetGraphicsResetStatus(__GLcontext *gc);
extern GLvoid GL_APIENTRY __glim_ReadnPixels(__GLcontext *gc, GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLsizei bufSize, GLvoid *data);
extern GLvoid GL_APIENTRY __glim_GetnUniformfv(__GLcontext *gc, GLuint program, GLint location, GLsizei bufSize, GLfloat *params);
extern GLvoid GL_APIENTRY __glim_GetnUniformiv(__GLcontext *gc, GLuint program, GLint location, GLsizei bufSize, GLint *params);
extern GLvoid GL_APIENTRY __glim_GetnUniformuiv(__GLcontext *gc, GLuint program, GLint location, GLsizei bufSize, GLuint *params);

extern GLvoid GL_APIENTRY __glim_BlendEquationi(__GLcontext * gc, GLuint buf, GLenum mode);
extern GLvoid GL_APIENTRY __glim_BlendEquationSeparatei(__GLcontext * gc, GLuint buf, GLenum modeRGB, GLenum modeAlpha);
extern GLvoid GL_APIENTRY __glim_BlendFunci(__GLcontext * gc, GLuint buf, GLenum sfactor, GLenum dfactor);
extern GLvoid GL_APIENTRY __glim_BlendFuncSeparatei(__GLcontext * gc, GLuint buf, GLenum sfactorRGB,GLenum dfactorRGB,GLenum sfactorAlpha,GLenum dfactorAlpha);
extern GLvoid GL_APIENTRY __glim_ColorMaski(__GLcontext * gc,GLuint buf, GLboolean r, GLboolean g, GLboolean b, GLboolean a);
extern GLvoid GL_APIENTRY __glim_Enablei(__GLcontext *gc, GLenum target, GLuint index);
extern GLvoid GL_APIENTRY __glim_Disablei(__GLcontext *gc, GLenum target, GLuint index);
extern GLboolean GL_APIENTRY __glim_IsEnabledi(__GLcontext * gc, GLenum target, GLuint index);

extern GLvoid GL_APIENTRY __glim_TexParameterIiv(__GLcontext *gc, GLenum target, GLenum pname, const GLint *params);
extern GLvoid GL_APIENTRY __glim_TexParameterIuiv(__GLcontext *gc, GLenum target, GLenum pname, const GLuint *params);
extern GLvoid GL_APIENTRY __glim_GetTexParameterIiv(__GLcontext *gc, GLenum target, GLenum pname, GLint *params);
extern GLvoid GL_APIENTRY __glim_GetTexParameterIuiv(__GLcontext *gc, GLenum target, GLenum pname, GLuint *params);
extern GLvoid GL_APIENTRY __glim_SamplerParameterIiv(__GLcontext *gc, GLuint sampler, GLenum pname, const GLint *param);
extern GLvoid GL_APIENTRY __glim_SamplerParameterIuiv(__GLcontext *gc, GLuint sampler, GLenum pname, const GLuint *param);
extern GLvoid GL_APIENTRY __glim_GetSamplerParameterIiv(__GLcontext *gc, GLuint sampler, GLenum pname, GLint *params);
extern GLvoid GL_APIENTRY __glim_GetSamplerParameterIuiv(__GLcontext *gc, GLuint sampler, GLenum pname, GLuint *params);

extern GLvoid GL_APIENTRY __glim_TexBuffer(__GLcontext *gc, GLenum target, GLenum internalformat, GLuint buffer);
extern GLvoid GL_APIENTRY __glim_TexBufferRange(__GLcontext *gc, GLenum target, GLenum internalformat,
                                                   GLuint buffer, GLintptr offset, GLsizeiptr size);
GLvoid GL_APIENTRY __glim_PatchParameteri(__GLcontext *gc, GLenum pname, GLint value);

GLvoid GL_APIENTRY __glim_FramebufferTexture(__GLcontext *gc, GLenum target, GLenum attachment, GLuint texture, GLint level);

GLvoid GL_APIENTRY __glim_MinSampleShading(__GLcontext *gc, GLfloat value);

GLvoid GL_APIENTRY __glim_CopyImageSubData(__GLcontext *gc,
                                           GLuint srcName, GLenum srcTarget, GLint srcLevel, GLint srcX, GLint srcY, GLint srcZ,
                                           GLuint dstName, GLenum dstTarget, GLint dstLevel, GLint dstX, GLint dstY, GLint dstZ,
                                           GLsizei srcWidth, GLsizei srcHeight, GLsizei srcDepth);

extern GLvoid GL_APIENTRY __glim_DrawElementsBaseVertex(__GLcontext *gc, GLenum mode, GLsizei count, GLenum type, const void *indices, GLint basevertex);
extern GLvoid GL_APIENTRY __glim_DrawRangeElementsBaseVertex(__GLcontext *gc, GLenum mode, GLuint start, GLuint end, GLsizei count, GLenum type, const void *indices, GLint basevertex);
extern GLvoid GL_APIENTRY __glim_DrawElementsInstancedBaseVertex(__GLcontext *gc, GLenum mode, GLsizei count, GLenum type, const void *indices, GLsizei instancecount, GLint basevertex);
extern GLvoid GL_APIENTRY __glim_PrimitiveBoundingBox(__GLcontext *gc, GLfloat minX, GLfloat minY, GLfloat minZ, GLfloat minW, GLfloat maxX, GLfloat maxY, GLfloat maxZ, GLfloat maxW);

/* OpenGL ES extension */
#if GL_OES_EGL_image
extern GLvoid GL_APIENTRY __glim_EGLImageTargetTexture2DOES(__GLcontext *gc, GLenum target, GLeglImageOES image);
extern GLvoid GL_APIENTRY __glim_EGLImageTargetRenderbufferStorageOES(__GLcontext *gc, GLenum target, GLeglImageOES image);
#endif

#if GL_EXT_multi_draw_arrays
extern GLvoid GL_APIENTRY __glim_MultiDrawArraysEXT(__GLcontext *gc, GLenum mode, const GLint *first, const GLsizei *count, GLsizei primcount);
extern GLvoid GL_APIENTRY __glim_MultiDrawElementsEXT(__GLcontext *gc, GLenum mode, const GLsizei *count, GLenum type, const GLvoid*const*indices, GLsizei primcount);
#if GL_EXT_draw_elements_base_vertex
extern GLvoid GL_APIENTRY __glim_MultiDrawElementsBaseVertexEXT(__GLcontext *gc, GLenum mode, const GLsizei * count, GLenum type, const void *const*indices, GLsizei drawcount, const GLint * basevertex);
#endif
#endif

#if GL_OES_mapbuffer
extern GLvoid GL_APIENTRY __glim_GetBufferPointervOES(__GLcontext *gc, GLenum target, GLenum pname, GLvoid** params);
extern GLvoid* GL_APIENTRY __glim_MapBufferOES(__GLcontext *gc, GLenum target, GLenum access);
extern GLboolean GL_APIENTRY __glim_UnmapBufferOES(__GLcontext *gc, GLenum target);
#endif

#if GL_EXT_discard_framebuffer
extern GLvoid GL_APIENTRY __glim_DiscardFramebufferEXT(__GLcontext *gc, GLenum target, GLsizei numAttachments, const GLenum *attachments);
#endif

#if GL_EXT_multisampled_render_to_texture
extern GLvoid GL_APIENTRY __glim_RenderbufferStorageMultisampleEXT(__GLcontext *gc, GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height);
extern GLvoid GL_APIENTRY __glim_FramebufferTexture2DMultisampleEXT(__GLcontext *gc, GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level, GLsizei samples);
#endif

#if GL_VIV_direct_texture
extern GLvoid GL_APIENTRY __glim_TexDirectVIV(__GLcontext *gc, GLenum target, GLsizei width, GLsizei height, GLenum format, GLvoid ** pixels);
extern GLvoid GL_APIENTRY __glim_TexDirectInvalidateVIV(__GLcontext *gc, GLenum target);
extern GLvoid GL_APIENTRY __glim_TexDirectVIVMap(__GLcontext *gc, GLenum target, GLsizei width, GLsizei height, GLenum format, GLvoid ** logical, const GLuint * physical);
extern GLvoid GL_APIENTRY __glim_TexDirectTiledMapVIV(__GLcontext *gc, GLenum target, GLsizei width, GLsizei height, GLenum format, GLvoid ** logical, const GLuint * physical);
#endif

#if GL_EXT_multi_draw_indirect
extern GLvoid GL_APIENTRY __glim_MultiDrawArraysIndirectEXT(__GLcontext *gc, GLenum mode, const void *indirect, GLsizei drawcount, GLsizei stride);
extern GLvoid GL_APIENTRY __glim_MultiDrawElementsIndirectEXT(__GLcontext *gc, GLenum mode, GLenum type, const void *indirect, GLsizei drawcount, GLsizei stride);
#endif

extern GLvoid GL_APIENTRY __glim_GetObjectParameterivARB (__GLcontext *gc, UINT obj, GLenum pname, GLint *params);

extern GLvoid APIENTRY __glim_DrawElements_Validate( __GLcontext *gc, GLenum, GLsizei, GLenum, const GLvoid *);
extern GLvoid APIENTRY __glim_ArrayElement_Validate( __GLcontext *gc, GLint);
extern GLvoid APIENTRY __glim_DrawArrays_Validate( __GLcontext *gc, GLenum, GLint, GLsizei);

extern GLboolean GLAPIENTRY __glim_IsRenderbufferEXT( __GLcontext *gc,  GLuint renderbuffer);
extern GLvoid GLAPIENTRY __glim_BindRenderbufferEXT(__GLcontext *gc,  GLenum target, GLuint renderbuffer);
extern GLvoid GLAPIENTRY __glim_DeleteRenderbuffersEXT(__GLcontext *gc,  GLsizei n, const GLuint *renderbuffers);
extern GLvoid GLAPIENTRY __glim_GenRenderbuffersEXT(__GLcontext *gc,  GLsizei n, GLuint *renderbuffers);
extern GLvoid GLAPIENTRY __glim_RenderbufferStorageEXT(__GLcontext *gc,  GLenum target, GLenum internalformat, GLsizei width, GLsizei height);
extern GLvoid GLAPIENTRY __glim_GetRenderbufferParameterivEXT(__GLcontext *gc,  GLenum target, GLenum pname, GLint* params);
extern GLboolean GLAPIENTRY __glim_IsFramebufferEXT(__GLcontext *gc,  GLuint framebuffer);
extern GLvoid GLAPIENTRY __glim_BindFramebufferEXT(__GLcontext *gc,  GLenum target, GLuint framebuffer);
extern GLvoid GLAPIENTRY __glim_DeleteFramebuffersEXT(__GLcontext *gc,  GLsizei n, const GLuint *framebuffers);
extern GLvoid GLAPIENTRY __glim_GenFramebuffersEXT(__GLcontext *gc,  GLsizei n, GLuint *framebuffers);
extern GLenum GLAPIENTRY __glim_CheckFramebufferStatusEXT(__GLcontext *gc,  GLenum target);
extern GLvoid GLAPIENTRY __glim_FramebufferTexture1DEXT(__GLcontext *gc,  GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level);
extern GLvoid GLAPIENTRY __glim_FramebufferTexture2DEXT(__GLcontext *gc,  GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level);
extern GLvoid GLAPIENTRY __glim_FramebufferTexture3DEXT(__GLcontext *gc,  GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level, GLint zoffset);
extern GLvoid GLAPIENTRY __glim_FramebufferRenderbufferEXT(__GLcontext *gc,  GLenum target, GLenum attachment, GLenum renderbuffertarget, GLuint renderbuffer);
extern GLvoid GLAPIENTRY __glim_GetFramebufferAttachmentParameterivEXT(__GLcontext *gc,  GLenum target, GLenum attachment, GLenum pname, GLint *params);
extern GLvoid GLAPIENTRY __glim_GenerateMipmapEXT(__GLcontext *gc,  GLenum target);
extern GLvoid GLAPIENTRY __glim_BlitFramebufferEXT(__GLcontext *gc,  GLint srcX0, GLint srcY0, GLint srcX1, GLint srcY1, GLint dstX0, GLint dstY0, GLint dstX1, GLint dstY1,GLbitfield mask, GLenum filter);

#endif /* __gc_es_protos_h__ */
