##############################################################################
#
#    Copyright 2012 - 2017 Vivante Corporation, Santa Clara, California.
#    All Rights Reserved.
#
#    Permission is hereby granted, free of charge, to any person obtaining
#    a copy of this software and associated documentation files (the
#    'Software'), to deal in the Software without restriction, including
#    without limitation the rights to use, copy, modify, merge, publish,
#    distribute, sub license, and/or sell copies of the Software, and to
#    permit persons to whom the Software is furnished to do so, subject
#    to the following conditions:
#
#    The above copyright notice and this permission notice (including the
#    next paragraph) shall be included in all copies or substantial
#    portions of the Software.
#
#    THE SOFTWARE IS PROVIDED 'AS IS', WITHOUT WARRANTY OF ANY KIND,
#    EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
#    MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT.
#    IN NO EVENT SHALL VIVANTE AND/OR ITS SUPPLIERS BE LIABLE FOR ANY
#    CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
#    TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
#    SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
##############################################################################


######################################################
# Include global definitions.
#

include ./makefile.linux.def

######################################################
# Components of the project.

FUNCTIONS_AND_KERNELS			:= function_and_kernels
INITIALIZERS				:= initializers
MULTIDIM_ARRAYS				:= multi_dimensional_arrays
ILLEGAL_VECTOR_SIZES			:= illegal_vector_sizes
STRUCTS_AND_ENUMS			:= structs_and_enums
RESERVED_DATA_TYPES			:= reserved_data_types
THREAD_SAFETY				:= thread_safety
UNIONS					:= unions
UNSUPP_EXTENSTIONS			:= unsupported_extensions

VIVANTE_TEST	:= $(FUNCTIONS_AND_KERNELS)
VIVANTE_TEST	+= $(INITIALIZERS)
VIVANTE_TEST	+= $(MULTIDIM_ARRAYS)
VIVANTE_TEST	+= $(ILLEGAL_VECTOR_SIZES)
VIVANTE_TEST	+= $(STRUCTS_AND_ENUMS)
VIVANTE_TEST	+= $(RESERVED_DATA_TYPES)
VIVANTE_TEST	+= $(UNIONS)
VIVANTE_TEST	+= $(UNSUPP_EXTENSTIONS)
#VIVANTE_TEST	+= $(THREAD_SAFETY)

######################################################
# Define the macros used in the common file.

MODULES		:= $(VIVANTE_TEST)
MAIN_MODULE	:= $(VIVANTE_TEST)

######################################################
# Include the common makefile.

include $(AQROOT)/common.node

