/****************************************************************************
*
*    Copyright (c) 2005 - 2015 by Vivante Corp.  All rights reserved.
*
*    The material in this file is confidential and contains trade secrets
*    of Vivante Corporation. This is proprietary information owned by
*    Vivante Corporation. No part of this work may be disclosed,
*    reproduced, copied, transmitted, or used in any way for any purpose,
*    without the express written permission of Vivante Corporation.
*
*****************************************************************************/


#ifndef __gl_glapioffset_h_
#define __gl_glapioffset_h_

#define _gloffset_NewList 0
#define _gloffset_EndList 1
#define _gloffset_CallList 2
#define _gloffset_CallLists 3
#define _gloffset_DeleteLists 4
#define _gloffset_GenLists 5
#define _gloffset_ListBase 6
#define _gloffset_Begin 7
#define _gloffset_Bitmap 8
#define _gloffset_Color3b 9
#define _gloffset_Color3bv 10
#define _gloffset_Color3d 11
#define _gloffset_Color3dv 12
#define _gloffset_Color3f 13
#define _gloffset_Color3fv 14
#define _gloffset_Color3i 15
#define _gloffset_Color3iv 16
#define _gloffset_Color3s 17
#define _gloffset_Color3sv 18
#define _gloffset_Color3ub 19
#define _gloffset_Color3ubv 20
#define _gloffset_Color3ui 21
#define _gloffset_Color3uiv 22
#define _gloffset_Color3us 23
#define _gloffset_Color3usv 24
#define _gloffset_Color4b 25
#define _gloffset_Color4bv 26
#define _gloffset_Color4d 27
#define _gloffset_Color4dv 28
#define _gloffset_Color4f 29
#define _gloffset_Color4fv 30
#define _gloffset_Color4i 31
#define _gloffset_Color4iv 32
#define _gloffset_Color4s 33
#define _gloffset_Color4sv 34
#define _gloffset_Color4ub 35
#define _gloffset_Color4ubv 36
#define _gloffset_Color4ui 37
#define _gloffset_Color4uiv 38
#define _gloffset_Color4us 39
#define _gloffset_Color4usv 40
#define _gloffset_EdgeFlag 41
#define _gloffset_EdgeFlagv 42
#define _gloffset_End 43
#define _gloffset_Indexd 44
#define _gloffset_Indexdv 45
#define _gloffset_Indexf 46
#define _gloffset_Indexfv 47
#define _gloffset_Indexi 48
#define _gloffset_Indexiv 49
#define _gloffset_Indexs 50
#define _gloffset_Indexsv 51
#define _gloffset_Normal3b 52
#define _gloffset_Normal3bv 53
#define _gloffset_Normal3d 54
#define _gloffset_Normal3dv 55
#define _gloffset_Normal3f 56
#define _gloffset_Normal3fv 57
#define _gloffset_Normal3i 58
#define _gloffset_Normal3iv 59
#define _gloffset_Normal3s 60
#define _gloffset_Normal3sv 61
#define _gloffset_RasterPos2d 62
#define _gloffset_RasterPos2dv 63
#define _gloffset_RasterPos2f 64
#define _gloffset_RasterPos2fv 65
#define _gloffset_RasterPos2i 66
#define _gloffset_RasterPos2iv 67
#define _gloffset_RasterPos2s 68
#define _gloffset_RasterPos2sv 69
#define _gloffset_RasterPos3d 70
#define _gloffset_RasterPos3dv 71
#define _gloffset_RasterPos3f 72
#define _gloffset_RasterPos3fv 73
#define _gloffset_RasterPos3i 74
#define _gloffset_RasterPos3iv 75
#define _gloffset_RasterPos3s 76
#define _gloffset_RasterPos3sv 77
#define _gloffset_RasterPos4d 78
#define _gloffset_RasterPos4dv 79
#define _gloffset_RasterPos4f 80
#define _gloffset_RasterPos4fv 81
#define _gloffset_RasterPos4i 82
#define _gloffset_RasterPos4iv 83
#define _gloffset_RasterPos4s 84
#define _gloffset_RasterPos4sv 85
#define _gloffset_Rectd 86
#define _gloffset_Rectdv 87
#define _gloffset_Rectf 88
#define _gloffset_Rectfv 89
#define _gloffset_Recti 90
#define _gloffset_Rectiv 91
#define _gloffset_Rects 92
#define _gloffset_Rectsv 93
#define _gloffset_TexCoord1d 94
#define _gloffset_TexCoord1dv 95
#define _gloffset_TexCoord1f 96
#define _gloffset_TexCoord1fv 97
#define _gloffset_TexCoord1i 98
#define _gloffset_TexCoord1iv 99
#define _gloffset_TexCoord1s 100
#define _gloffset_TexCoord1sv 101
#define _gloffset_TexCoord2d 102
#define _gloffset_TexCoord2dv 103
#define _gloffset_TexCoord2f 104
#define _gloffset_TexCoord2fv 105
#define _gloffset_TexCoord2i 106
#define _gloffset_TexCoord2iv 107
#define _gloffset_TexCoord2s 108
#define _gloffset_TexCoord2sv 109
#define _gloffset_TexCoord3d 110
#define _gloffset_TexCoord3dv 111
#define _gloffset_TexCoord3f 112
#define _gloffset_TexCoord3fv 113
#define _gloffset_TexCoord3i 114
#define _gloffset_TexCoord3iv 115
#define _gloffset_TexCoord3s 116
#define _gloffset_TexCoord3sv 117
#define _gloffset_TexCoord4d 118
#define _gloffset_TexCoord4dv 119
#define _gloffset_TexCoord4f 120
#define _gloffset_TexCoord4fv 121
#define _gloffset_TexCoord4i 122
#define _gloffset_TexCoord4iv 123
#define _gloffset_TexCoord4s 124
#define _gloffset_TexCoord4sv 125
#define _gloffset_Vertex2d 126
#define _gloffset_Vertex2dv 127
#define _gloffset_Vertex2f 128
#define _gloffset_Vertex2fv 129
#define _gloffset_Vertex2i 130
#define _gloffset_Vertex2iv 131
#define _gloffset_Vertex2s 132
#define _gloffset_Vertex2sv 133
#define _gloffset_Vertex3d 134
#define _gloffset_Vertex3dv 135
#define _gloffset_Vertex3f 136
#define _gloffset_Vertex3fv 137
#define _gloffset_Vertex3i 138
#define _gloffset_Vertex3iv 139
#define _gloffset_Vertex3s 140
#define _gloffset_Vertex3sv 141
#define _gloffset_Vertex4d 142
#define _gloffset_Vertex4dv 143
#define _gloffset_Vertex4f 144
#define _gloffset_Vertex4fv 145
#define _gloffset_Vertex4i 146
#define _gloffset_Vertex4iv 147
#define _gloffset_Vertex4s 148
#define _gloffset_Vertex4sv 149
#define _gloffset_ClipPlane 150
#define _gloffset_ColorMaterial 151
#define _gloffset_CullFace 152
#define _gloffset_Fogf 153
#define _gloffset_Fogfv 154
#define _gloffset_Fogi 155
#define _gloffset_Fogiv 156
#define _gloffset_FrontFace 157
#define _gloffset_Hint 158
#define _gloffset_Lightf 159
#define _gloffset_Lightfv 160
#define _gloffset_Lighti 161
#define _gloffset_Lightiv 162
#define _gloffset_LightModelf 163
#define _gloffset_LightModelfv 164
#define _gloffset_LightModeli 165
#define _gloffset_LightModeliv 166
#define _gloffset_LineStipple 167
#define _gloffset_LineWidth 168
#define _gloffset_Materialf 169
#define _gloffset_Materialfv 170
#define _gloffset_Materiali 171
#define _gloffset_Materialiv 172
#define _gloffset_PointSize 173
#define _gloffset_PolygonMode 174
#define _gloffset_PolygonStipple 175
#define _gloffset_Scissor 176
#define _gloffset_ShadeModel 177
#define _gloffset_TexParameterf 178
#define _gloffset_TexParameterfv 179
#define _gloffset_TexParameteri 180
#define _gloffset_TexParameteriv 181
#define _gloffset_TexImage1D 182
#define _gloffset_TexImage2D 183
#define _gloffset_TexEnvf 184
#define _gloffset_TexEnvfv 185
#define _gloffset_TexEnvi 186
#define _gloffset_TexEnviv 187
#define _gloffset_TexGend 188
#define _gloffset_TexGendv 189
#define _gloffset_TexGenf 190
#define _gloffset_TexGenfv 191
#define _gloffset_TexGeni 192
#define _gloffset_TexGeniv 193
#define _gloffset_FeedbackBuffer 194
#define _gloffset_SelectBuffer 195
#define _gloffset_RenderMode 196
#define _gloffset_InitNames 197
#define _gloffset_LoadName 198
#define _gloffset_PassThrough 199
#define _gloffset_PopName 200
#define _gloffset_PushName 201
#define _gloffset_DrawBuffer 202
#define _gloffset_Clear 203
#define _gloffset_ClearAccum 204
#define _gloffset_ClearIndex 205
#define _gloffset_ClearColor 206
#define _gloffset_ClearStencil 207
#define _gloffset_ClearDepth 208
#define _gloffset_StencilMask 209
#define _gloffset_ColorMask 210
#define _gloffset_DepthMask 211
#define _gloffset_IndexMask 212
#define _gloffset_Accum 213
#define _gloffset_Disable 214
#define _gloffset_Enable 215
#define _gloffset_Finish 216
#define _gloffset_Flush 217
#define _gloffset_PopAttrib 218
#define _gloffset_PushAttrib 219
#define _gloffset_Map1d 220
#define _gloffset_Map1f 221
#define _gloffset_Map2d 222
#define _gloffset_Map2f 223
#define _gloffset_MapGrid1d 224
#define _gloffset_MapGrid1f 225
#define _gloffset_MapGrid2d 226
#define _gloffset_MapGrid2f 227
#define _gloffset_EvalCoord1d 228
#define _gloffset_EvalCoord1dv 229
#define _gloffset_EvalCoord1f 230
#define _gloffset_EvalCoord1fv 231
#define _gloffset_EvalCoord2d 232
#define _gloffset_EvalCoord2dv 233
#define _gloffset_EvalCoord2f 234
#define _gloffset_EvalCoord2fv 235
#define _gloffset_EvalMesh1 236
#define _gloffset_EvalPoint1 237
#define _gloffset_EvalMesh2 238
#define _gloffset_EvalPoint2 239
#define _gloffset_AlphaFunc 240
#define _gloffset_BlendFunc 241
#define _gloffset_LogicOp 242
#define _gloffset_StencilFunc 243
#define _gloffset_StencilOp 244
#define _gloffset_DepthFunc 245
#define _gloffset_PixelZoom 246
#define _gloffset_PixelTransferf 247
#define _gloffset_PixelTransferi 248
#define _gloffset_PixelStoref 249
#define _gloffset_PixelStorei 250
#define _gloffset_PixelMapfv 251
#define _gloffset_PixelMapuiv 252
#define _gloffset_PixelMapusv 253
#define _gloffset_ReadBuffer 254
#define _gloffset_CopyPixels 255
#define _gloffset_ReadPixels 256
#define _gloffset_DrawPixels 257
#define _gloffset_GetBooleanv 258
#define _gloffset_GetClipPlane 259
#define _gloffset_GetDoublev 260
#define _gloffset_GetError 261
#define _gloffset_GetFloatv 262
#define _gloffset_GetIntegerv 263
#define _gloffset_GetLightfv 264
#define _gloffset_GetLightiv 265
#define _gloffset_GetMapdv 266
#define _gloffset_GetMapfv 267
#define _gloffset_GetMapiv 268
#define _gloffset_GetMaterialfv 269
#define _gloffset_GetMaterialiv 270
#define _gloffset_GetPixelMapfv 271
#define _gloffset_GetPixelMapuiv 272
#define _gloffset_GetPixelMapusv 273
#define _gloffset_GetPolygonStipple 274
#define _gloffset_GetString 275
#define _gloffset_GetTexEnvfv 276
#define _gloffset_GetTexEnviv 277
#define _gloffset_GetTexGendv 278
#define _gloffset_GetTexGenfv 279
#define _gloffset_GetTexGeniv 280
#define _gloffset_GetTexImage 281
#define _gloffset_GetTexParameterfv 282
#define _gloffset_GetTexParameteriv 283
#define _gloffset_GetTexLevelParameterfv 284
#define _gloffset_GetTexLevelParameteriv 285
#define _gloffset_IsEnabled 286
#define _gloffset_IsList 287
#define _gloffset_DepthRange 288
#define _gloffset_Frustum 289
#define _gloffset_LoadIdentity 290
#define _gloffset_LoadMatrixf 291
#define _gloffset_LoadMatrixd 292
#define _gloffset_MatrixMode 293
#define _gloffset_MultMatrixf 294
#define _gloffset_MultMatrixd 295
#define _gloffset_Ortho 296
#define _gloffset_PopMatrix 297
#define _gloffset_PushMatrix 298
#define _gloffset_Rotated 299
#define _gloffset_Rotatef 300
#define _gloffset_Scaled 301
#define _gloffset_Scalef 302
#define _gloffset_Translated 303
#define _gloffset_Translatef 304
#define _gloffset_Viewport 305
/* #if GL_VERSION_1_1 */
#define _gloffset_ArrayElement 306
#define _gloffset_BindTexture 307
#define _gloffset_ColorPointer 308
#define _gloffset_DisableClientState 309
#define _gloffset_DrawArrays 310
#define _gloffset_DrawElements 311
#define _gloffset_EdgeFlagPointer 312
#define _gloffset_EnableClientState 313
#define _gloffset_IndexPointer 314
#define _gloffset_Indexub 315
#define _gloffset_Indexubv 316
#define _gloffset_InterleavedArrays 317
#define _gloffset_NormalPointer 318
#define _gloffset_PolygonOffset 319
#define _gloffset_TexCoordPointer 320
#define _gloffset_VertexPointer 321
#define _gloffset_AreTexturesResident 322
#define _gloffset_CopyTexImage1D 323
#define _gloffset_CopyTexImage2D 324
#define _gloffset_CopyTexSubImage1D 325
#define _gloffset_CopyTexSubImage2D 326
#define _gloffset_DeleteTextures 327
#define _gloffset_GenTextures 328
#define _gloffset_GetPointerv 329
#define _gloffset_IsTexture 330
#define _gloffset_PrioritizeTextures 331
#define _gloffset_TexSubImage1D 332
#define _gloffset_TexSubImage2D 333
#define _gloffset_PopClientAttrib 334
#define _gloffset_PushClientAttrib 335
/* #endif */
/* #if GL_VERSION_1_2 */
#define _gloffset_BlendColor 336
#define _gloffset_BlendEquation 337
#define _gloffset_DrawRangeElements 338
#define _gloffset_ColorTable 339
#define _gloffset_ColorTableParameterfv 340
#define _gloffset_ColorTableParameteriv 341
#define _gloffset_CopyColorTable 342
#define _gloffset_GetColorTable 343
#define _gloffset_GetColorTableParameterfv 344
#define _gloffset_GetColorTableParameteriv 345
#define _gloffset_ColorSubTable 346
#define _gloffset_CopyColorSubTable 347
#define _gloffset_ConvolutionFilter1D 348
#define _gloffset_ConvolutionFilter2D 349
#define _gloffset_ConvolutionParameterf 350
#define _gloffset_ConvolutionParameterfv 351
#define _gloffset_ConvolutionParameteri 352
#define _gloffset_ConvolutionParameteriv 353
#define _gloffset_CopyConvolutionFilter1D 354
#define _gloffset_CopyConvolutionFilter2D 355
#define _gloffset_GetConvolutionFilter 356
#define _gloffset_GetConvolutionParameterfv 357
#define _gloffset_GetConvolutionParameteriv 358
#define _gloffset_GetSeparableFilter 359
#define _gloffset_SeparableFilter2D 360
#define _gloffset_GetHistogram 361
#define _gloffset_GetHistogramParameterfv 362
#define _gloffset_GetHistogramParameteriv 363
#define _gloffset_GetMinmax 364
#define _gloffset_GetMinmaxParameterfv 365
#define _gloffset_GetMinmaxParameteriv 366
#define _gloffset_Histogram 367
#define _gloffset_Minmax 368
#define _gloffset_ResetHistogram 369
#define _gloffset_ResetMinmax 370
#define _gloffset_TexImage3D 371
#define _gloffset_TexSubImage3D 372
#define _gloffset_CopyTexSubImage3D 373
/* #endif */
/* #if GL_VERSION_1_3 */
#define _gloffset_ActiveTexture 374
#define _gloffset_ClientActiveTexture 375
#define _gloffset_MultiTexCoord1d 376
#define _gloffset_MultiTexCoord1dv 377
#define _gloffset_MultiTexCoord1f 378
#define _gloffset_MultiTexCoord1fv 379
#define _gloffset_MultiTexCoord1i 380
#define _gloffset_MultiTexCoord1iv 381
#define _gloffset_MultiTexCoord1s 382
#define _gloffset_MultiTexCoord1sv 383
#define _gloffset_MultiTexCoord2d 384
#define _gloffset_MultiTexCoord2dv 385
#define _gloffset_MultiTexCoord2f 386
#define _gloffset_MultiTexCoord2fv 387
#define _gloffset_MultiTexCoord2i 388
#define _gloffset_MultiTexCoord2iv 389
#define _gloffset_MultiTexCoord2s 390
#define _gloffset_MultiTexCoord2sv 391
#define _gloffset_MultiTexCoord3d 392
#define _gloffset_MultiTexCoord3dv 393
#define _gloffset_MultiTexCoord3f 394
#define _gloffset_MultiTexCoord3fv 395
#define _gloffset_MultiTexCoord3i 396
#define _gloffset_MultiTexCoord3iv 397
#define _gloffset_MultiTexCoord3s 398
#define _gloffset_MultiTexCoord3sv 399
#define _gloffset_MultiTexCoord4d 400
#define _gloffset_MultiTexCoord4dv 401
#define _gloffset_MultiTexCoord4f 402
#define _gloffset_MultiTexCoord4fv 403
#define _gloffset_MultiTexCoord4i 404
#define _gloffset_MultiTexCoord4iv 405
#define _gloffset_MultiTexCoord4s 406
#define _gloffset_MultiTexCoord4sv 407
#define _gloffset_LoadTransposeMatrixf 408
#define _gloffset_LoadTransposeMatrixd 409
#define _gloffset_MultTransposeMatrixf 410
#define _gloffset_MultTransposeMatrixd 411
#define _gloffset_SampleCoverage 412
#define _gloffset_CompressedTexImage3D 413
#define _gloffset_CompressedTexImage2D 414
#define _gloffset_CompressedTexImage1D 415
#define _gloffset_CompressedTexSubImage3D 416
#define _gloffset_CompressedTexSubImage2D 417
#define _gloffset_CompressedTexSubImage1D 418
#define _gloffset_GetCompressedTexImage 419
/* #endif */
/* #if GL_VERSION_1_4 */
#define _gloffset_BlendFuncSeparate 420
#define _gloffset_FogCoordf 421
#define _gloffset_FogCoordfv 422
#define _gloffset_FogCoordd 423
#define _gloffset_FogCoorddv 424
#define _gloffset_FogCoordPointer 425
#define _gloffset_MultiDrawArrays 426
#define _gloffset_MultiDrawElements 427
#define _gloffset_PointParameterf 428
#define _gloffset_PointParameterfv 429
#define _gloffset_PointParameteri 430
#define _gloffset_PointParameteriv 431
#define _gloffset_SecondaryColor3b 432
#define _gloffset_SecondaryColor3bv 433
#define _gloffset_SecondaryColor3d 434
#define _gloffset_SecondaryColor3dv 435
#define _gloffset_SecondaryColor3f 436
#define _gloffset_SecondaryColor3fv 437
#define _gloffset_SecondaryColor3i 438
#define _gloffset_SecondaryColor3iv 439
#define _gloffset_SecondaryColor3s 440
#define _gloffset_SecondaryColor3sv 441
#define _gloffset_SecondaryColor3ub 442
#define _gloffset_SecondaryColor3ubv 443
#define _gloffset_SecondaryColor3ui 444
#define _gloffset_SecondaryColor3uiv 445
#define _gloffset_SecondaryColor3us 446
#define _gloffset_SecondaryColor3usv 447
#define _gloffset_SecondaryColorPointer 448
#define _gloffset_WindowPos2d 449
#define _gloffset_WindowPos2dv 450
#define _gloffset_WindowPos2f 451
#define _gloffset_WindowPos2fv 452
#define _gloffset_WindowPos2i 453
#define _gloffset_WindowPos2iv 454
#define _gloffset_WindowPos2s 455
#define _gloffset_WindowPos2sv 456
#define _gloffset_WindowPos3d 457
#define _gloffset_WindowPos3dv 458
#define _gloffset_WindowPos3f 459
#define _gloffset_WindowPos3fv 460
#define _gloffset_WindowPos3i 461
#define _gloffset_WindowPos3iv 462
#define _gloffset_WindowPos3s 463
#define _gloffset_WindowPos3sv 464
/* #endif */
/* #if GL_VERSION_1_5 */
#define _gloffset_GenQueries 465
#define _gloffset_DeleteQueries 466
#define _gloffset_IsQuery 467
#define _gloffset_BeginQuery 468
#define _gloffset_EndQuery 469
#define _gloffset_GetQueryiv 470
#define _gloffset_GetQueryObjectiv 471
#define _gloffset_GetQueryObjectuiv 472
#define _gloffset_BindBuffer 473
#define _gloffset_DeleteBuffers 474
#define _gloffset_GenBuffers 475
#define _gloffset_IsBuffer 476
#define _gloffset_BufferData 477
#define _gloffset_BufferSubData 478
#define _gloffset_GetBufferSubData 479
#define _gloffset_MapBuffer 480
#define _gloffset_UnmapBuffer 481
#define _gloffset_GetBufferParameteriv 482
#define _gloffset_GetBufferPointerv 483
/* #endif */
/* #if GL_VERSION_2_0 */
#define _gloffset_BlendEquationSeparate 484
#define _gloffset_DrawBuffers 485
#define _gloffset_StencilOpSeparate 486
#define _gloffset_StencilFuncSeparate 487
#define _gloffset_StencilMaskSeparate 488
#define _gloffset_AttachShader 489
#define _gloffset_BindAttribLocation 490
#define _gloffset_CompileShader 491
#define _gloffset_CreateProgram 492
#define _gloffset_CreateShader 493
#define _gloffset_DeleteProgram 494
#define _gloffset_DeleteShader 495
#define _gloffset_DetachShader 496
#define _gloffset_DisableVertexAttribArray 497
#define _gloffset_EnableVertexAttribArray 498
#define _gloffset_GetActiveAttrib 499
#define _gloffset_GetActiveUniform 500
#define _gloffset_GetAttachedShaders 501
#define _gloffset_GetAttribLocation 502
#define _gloffset_GetProgramiv 503
#define _gloffset_GetProgramInfoLog 504
#define _gloffset_GetShaderiv 505
#define _gloffset_GetShaderInfoLog 506
#define _gloffset_GetShaderSource 507
#define _gloffset_GetUniformLocation 508
#define _gloffset_GetUniformfv 509
#define _gloffset_GetUniformiv 510
#define _gloffset_GetVertexAttribdv 511
#define _gloffset_GetVertexAttribfv 512
#define _gloffset_GetVertexAttribiv 513
#define _gloffset_GetVertexAttribPointerv 514
#define _gloffset_IsProgram 515
#define _gloffset_IsShader 516
#define _gloffset_LinkProgram 517
#define _gloffset_ShaderSource 518
#define _gloffset_UseProgram 519
#define _gloffset_Uniform1f 520
#define _gloffset_Uniform2f 521
#define _gloffset_Uniform3f 522
#define _gloffset_Uniform4f 523
#define _gloffset_Uniform1i 524
#define _gloffset_Uniform2i 525
#define _gloffset_Uniform3i 526
#define _gloffset_Uniform4i 527
#define _gloffset_Uniform1fv 528
#define _gloffset_Uniform2fv 529
#define _gloffset_Uniform3fv 530
#define _gloffset_Uniform4fv 531
#define _gloffset_Uniform1iv 532
#define _gloffset_Uniform2iv 533
#define _gloffset_Uniform3iv 534
#define _gloffset_Uniform4iv 535
#define _gloffset_UniformMatrix2fv 536
#define _gloffset_UniformMatrix3fv 537
#define _gloffset_UniformMatrix4fv 538
#define _gloffset_ValidateProgram 539
#define _gloffset_VertexAttrib1d 540
#define _gloffset_VertexAttrib1dv 541
#define _gloffset_VertexAttrib1f 542
#define _gloffset_VertexAttrib1fv 543
#define _gloffset_VertexAttrib1s 544
#define _gloffset_VertexAttrib1sv 545
#define _gloffset_VertexAttrib2d 546
#define _gloffset_VertexAttrib2dv 547
#define _gloffset_VertexAttrib2f 548
#define _gloffset_VertexAttrib2fv 549
#define _gloffset_VertexAttrib2s 550
#define _gloffset_VertexAttrib2sv 551
#define _gloffset_VertexAttrib3d 552
#define _gloffset_VertexAttrib3dv 553
#define _gloffset_VertexAttrib3f 554
#define _gloffset_VertexAttrib3fv 555
#define _gloffset_VertexAttrib3s 556
#define _gloffset_VertexAttrib3sv 557
#define _gloffset_VertexAttrib4Nbv 558
#define _gloffset_VertexAttrib4Niv 559
#define _gloffset_VertexAttrib4Nsv 560
#define _gloffset_VertexAttrib4Nub 561
#define _gloffset_VertexAttrib4Nubv 562
#define _gloffset_VertexAttrib4Nuiv 563
#define _gloffset_VertexAttrib4Nusv 564
#define _gloffset_VertexAttrib4bv 565
#define _gloffset_VertexAttrib4d 566
#define _gloffset_VertexAttrib4dv 567
#define _gloffset_VertexAttrib4f 568
#define _gloffset_VertexAttrib4fv 569
#define _gloffset_VertexAttrib4iv 570
#define _gloffset_VertexAttrib4s 571
#define _gloffset_VertexAttrib4sv 572
#define _gloffset_VertexAttrib4ubv 573
#define _gloffset_VertexAttrib4uiv 574
#define _gloffset_VertexAttrib4usv 575
#define _gloffset_VertexAttribPointer 576
/* #endif */
/* #if GL_VERSION_2_1 */
#define _gloffset_UniformMatrix2x3fv 577
#define _gloffset_UniformMatrix2x4fv 578
#define _gloffset_UniformMatrix3x2fv 579
#define _gloffset_UniformMatrix3x4fv 580
#define _gloffset_UniformMatrix4x2fv 581
#define _gloffset_UniformMatrix4x3fv 582
/* #endif */

/* #if GL_ARB_vertex_program */
#define _gloffset_ProgramStringARB 583
#define _gloffset_BindProgramARB 584
#define _gloffset_DeleteProgramsARB 585
#define _gloffset_GenProgramsARB 586
#define _gloffset_ProgramEnvParameter4dARB 587
#define _gloffset_ProgramEnvParameter4dvARB 588
#define _gloffset_ProgramEnvParameter4fARB 589
#define _gloffset_ProgramEnvParameter4fvARB 590
#define _gloffset_ProgramLocalParameter4dARB 591
#define _gloffset_ProgramLocalParameter4dvARB 592
#define _gloffset_ProgramLocalParameter4fARB 593
#define _gloffset_ProgramLocalParameter4fvARB 594
#define _gloffset_GetProgramEnvParameterdvARB 595
#define _gloffset_GetProgramEnvParameterfvARB 596
#define _gloffset_GetProgramLocalParameterdvARB 597
#define _gloffset_GetProgramLocalParameterfvARB 598
#define _gloffset_GetProgramivARB 599
#define _gloffset_GetProgramStringARB 600
#define _gloffset_IsProgramARB 601
/* #endif */

/* #if GL_ARB_shader_objects */
#define _gloffset_DeleteObjectARB 602
#define _gloffset_GetHandleARB 603
#define _gloffset_GetInfoLogARB 604
#define _gloffset_GetObjectParameterfvARB 605
#define _gloffset_GetObjectParameterivARB 606
/* #endif */

/* #if GL_ATI_vertex_array_object */
#define _gloffset_NewObjectBufferATI 607
#define _gloffset_IsObjectBufferATI 608
#define _gloffset_UpdateObjectBufferATI 609
#define _gloffset_GetObjectBufferfvATI 610
#define _gloffset_GetObjectBufferivATI 611
#define _gloffset_FreeObjectBufferATI 612
#define _gloffset_ArrayObjectATI 613
#define _gloffset_GetArrayObjectfvATI 614
#define _gloffset_GetArrayObjectivATI 615
#define _gloffset_VariantArrayObjectATI 616
#define _gloffset_GetVariantArrayObjectfvATI 617
#define _gloffset_GetVariantArrayObjectivATI 618
/* #endif */

/* #if GL_ATI_vertex_attrib_array_object */
#define _gloffset_VertexAttribArrayObjectATI 619
#define _gloffset_GetVertexAttribArrayObjectfvATI 620
#define _gloffset_GetVertexAttribArrayObjectivATI 621
/* #endif */

/* #if GL_ATI_element_array */
#define _gloffset_ElementPointerATI 622
#define _gloffset_DrawElementArrayATI 623
#define _gloffset_DrawRangeElementArrayATI 624
/* #endif */

/* #if GL_EXT_stencil_two_side */
#define _gloffset_ActiveStencilFaceEXT 625
/* #endif */

#define _gloffset_AddSwapHintRectWIN 626

/* #if GL_EXT_depth_bounds_test */
#define _gloffset_DepthBoundsEXT 627
/* #endif */

/* #if GL_EXT_framebuffer_object */
#define _gloffset_IsRenderbufferEXT 628
#define _gloffset_BindRenderbufferEXT 629
#define _gloffset_DeleteRenderbuffersEXT 630
#define _gloffset_GenRenderbuffersEXT 631
#define _gloffset_RenderbufferStorageEXT 632
#define _gloffset_GetRenderbufferParameterivEXT 633
#define _gloffset_IsFramebufferEXT 634
#define _gloffset_BindFramebufferEXT 635
#define _gloffset_DeleteFramebuffersEXT 636
#define _gloffset_GenFramebuffersEXT 637
#define _gloffset_CheckFramebufferStatusEXT 638
#define _gloffset_FramebufferTexture1DEXT 639
#define _gloffset_FramebufferTexture2DEXT 640
#define _gloffset_FramebufferTexture3DEXT 641
#define _gloffset_FramebufferRenderbufferEXT 642
#define _gloffset_GetFramebufferAttachmentParameterivEXT 643
#define _gloffset_GenerateMipmapEXT 644
#define _gloffset_BlitFramebufferEXT 645
#define _gloffset_RenderbufferStorageMultisampleEXT 646
/* #endif */

/* #if GL_NV_occlusion_query */
#define _gloffset_BeginQueryNV 647
#define _gloffset_EndQueryNV 648
/* #endif */

/* #if GL_EXT_bindable_uniform */
#define _gloffset_UniformBufferEXT 649
#define _gloffset_GetUniformBufferSizeEXT 650
#define _gloffset_GetUniformOffsetEXT 651
/* #endif */

/* #if GL_EXT_texture_integer */
#define _gloffset_ClearColorIiEXT 652
#define _gloffset_ClearColorIuiEXT 653
#define _gloffset_TexParameterIivEXT 654
#define _gloffset_TexParameterIuivEXT 655
#define _gloffset_GetTexParameterIivEXT 656
#define _gloffset_GetTexParameterIuivEXT 657
/* #endif */

/* #if GL_EXT_gpu_shader4 */
#define _gloffset_VertexAttribI1iEXT 658
#define _gloffset_VertexAttribI2iEXT 659
#define _gloffset_VertexAttribI3iEXT 660
#define _gloffset_VertexAttribI4iEXT 661
#define _gloffset_VertexAttribI1uiEXT 662
#define _gloffset_VertexAttribI2uiEXT 663
#define _gloffset_VertexAttribI3uiEXT 664
#define _gloffset_VertexAttribI4uiEXT 665
#define _gloffset_VertexAttribI1ivEXT 666
#define _gloffset_VertexAttribI2ivEXT 667
#define _gloffset_VertexAttribI3ivEXT 668
#define _gloffset_VertexAttribI4ivEXT 669
#define _gloffset_VertexAttribI1uivEXT 670
#define _gloffset_VertexAttribI2uivEXT 671
#define _gloffset_VertexAttribI3uivEXT 672
#define _gloffset_VertexAttribI4uivEXT 673
#define _gloffset_VertexAttribI4bvEXT 674
#define _gloffset_VertexAttribI4svEXT 675
#define _gloffset_VertexAttribI4ubvEXT 676
#define _gloffset_VertexAttribI4usvEXT 677
#define _gloffset_VertexAttribIPointerEXT 678
#define _gloffset_GetVertexAttribIivEXT 679
#define _gloffset_GetVertexAttribIuivEXT 680
#define _gloffset_Uniform1uiEXT 681
#define _gloffset_Uniform2uiEXT 682
#define _gloffset_Uniform3uiEXT 683
#define _gloffset_Uniform4uiEXT 684
#define _gloffset_Uniform1uivEXT 685
#define _gloffset_Uniform2uivEXT 686
#define _gloffset_Uniform3uivEXT 687
#define _gloffset_Uniform4uivEXT 688
#define _gloffset_GetUniformuivEXT 689
#define _gloffset_BindFragDataLocationEXT 690
#define _gloffset_GetFragDataLocationEXT 691
/* #endif */

/* #if GL_EXT_geometry_shader4 */
#define _gloffset_ProgramParameteriEXT 692
#define _gloffset_FramebufferTextureEXT 693
#define _gloffset_FramebufferTextureLayerEXT 694
#define _gloffset_FramebufferTextureFaceEXT 695
/* #endif */

/* #if GL_EXT_draw_buffers2 */
#define _gloffset_ColorMaskIndexedEXT 696
#define _gloffset_GetBooleanIndexedvEXT 697
#define _gloffset_GetIntegerIndexedvEXT 698
#define _gloffset_EnableIndexedEXT 699
#define _gloffset_DisableIndexedEXT 700
#define _gloffset_IsEnabledIndexedEXT 701
/* #endif */

/* #if GL_EXT_texture_buffer_object */
#define _gloffset_TexBufferEXT 702
/* #endif */

/* #if GL_EXT_gpu_program_parameters*/
#define _gloffset_ProgramEnvParameters4fvEXT 703
#define _gloffset_ProgramLocalParameters4fvEXT 704
/* #endif */

/* #if GL_EXT_draw_instanced */
#define _gloffset_DrawArraysInstancedEXT 705
#define _gloffset_DrawElementsInstancedEXT 706
/* #endif */

/* #if GL_ARB_color_buffer_float */
#define _gloffset_ClampColorARB 707
/* #endif*/

/* #if GL_EXT_timer_query */
#define _gloffset_GetQueryObjecti64vEXT 708
#define _gloffset_GetQueryObjectui64vEXT 709
/* #endif */

/* if GL_ATI_stencil_separate */
#define _gloffset_StencilFuncSeparateATI 710
/* #endif */

#define _gloffset_LAST             711

#endif /* __gl_glapioffset_h_ */
