##############################################################################
#
#    Copyright 2012 - 2017 Vivante Corporation, Santa Clara, California.
#    All Rights Reserved.
#
#    Permission is hereby granted, free of charge, to any person obtaining
#    a copy of this software and associated documentation files (the
#    'Software'), to deal in the Software without restriction, including
#    without limitation the rights to use, copy, modify, merge, publish,
#    distribute, sub license, and/or sell copies of the Software, and to
#    permit persons to whom the Software is furnished to do so, subject
#    to the following conditions:
#
#    The above copyright notice and this permission notice (including the
#    next paragraph) shall be included in all copies or substantial
#    portions of the Software.
#
#    THE SOFTWARE IS PROVIDED 'AS IS', WITHOUT WARRANTY OF ANY KIND,
#    EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
#    MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT.
#    IN NO EVENT SHALL VIVANTE AND/OR ITS SUPPLIERS BE LIABLE FOR ANY
#    CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
#    TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
#    SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
##############################################################################


######################################################
# Include common definitions.

include  ../makefile.linux.def

######################################################
# Define the program.

PROGRAM			:= 1
TARGET_NAME		:= initializers

######################################################
# Describe object files.

OBJECTS			:=	$(OBJ_DIR)/main.o \
				$(OBJ_DIR)/initializers_scalar_array.o \
				$(OBJ_DIR)/initializers_scalar_array_union.o \
				$(OBJ_DIR)/initializers_scalar.o \
				$(OBJ_DIR)/initializers_scalar_union.o \
				$(OBJ_DIR)/initializers_struct_multiple.o \
				$(OBJ_DIR)/initializers_struct_multiple_vector16.o \
				$(OBJ_DIR)/initializers_struct_multiple_vector2.o \
				$(OBJ_DIR)/initializers_struct_multiple_vector3.o \
				$(OBJ_DIR)/initializers_struct_multiple_vector4.o \
				$(OBJ_DIR)/initializers_struct_multiple_vector8.o \
				$(OBJ_DIR)/initializers_union_multiple.o \
				$(OBJ_DIR)/initializers_union_multiple_vector16.o \
				$(OBJ_DIR)/initializers_union_multiple_vector2.o \
				$(OBJ_DIR)/initializers_union_multiple_vector3.o \
				$(OBJ_DIR)/initializers_union_multiple_vector4.o \
				$(OBJ_DIR)/initializers_union_multiple_vector8.o \
				$(OBJ_DIR)/initializers_vector16_array.o \
				$(OBJ_DIR)/initializers_vector16_array_union.o \
				$(OBJ_DIR)/initializers_vector16.o \
				$(OBJ_DIR)/initializers_vector16_union.o \
				$(OBJ_DIR)/initializers_vector2_array.o \
				$(OBJ_DIR)/initializers_vector2_array_union.o \
				$(OBJ_DIR)/initializers_vector2.o \
				$(OBJ_DIR)/initializers_vector2_union.o \
				$(OBJ_DIR)/initializers_vector3_array.o \
				$(OBJ_DIR)/initializers_vector3_array_union.o \
				$(OBJ_DIR)/initializers_vector3.o \
				$(OBJ_DIR)/initializers_vector3_union.o \
				$(OBJ_DIR)/initializers_vector4_array.o \
				$(OBJ_DIR)/initializers_vector4_array_union.o \
				$(OBJ_DIR)/initializers_vector4.o \
				$(OBJ_DIR)/initializers_vector4_union.o \
				$(OBJ_DIR)/initializers_vector8_array.o \
				$(OBJ_DIR)/initializers_vector8_array_union.o \
				$(OBJ_DIR)/initializers_vector8.o \
				$(OBJ_DIR)/initializers_vector8_union.o \

CFLAGS += -Wno-narrowing

######################################################
# Describe installation directory
#
INSTALL_DIR		:= $(SDK_DIR)/samples/cl11/UnitTest/test_vivante

######################################################
# Include the common makefile.

include $(AQROOT)/common.target

######################################################
# Extra installation.

install: extra_install

.PHONY: extra_install

extra_install:
	@mkdir -p $(INSTALL_DIR)

