/****************************************************************************
*
*    Copyright (c) 2005 - 2016 by Vivante Corp.  All rights reserved.
*
*    The material in this file is confidential and contains trade secrets
*    of Vivante Corporation. This is proprietary information owned by
*    Vivante Corporation. No part of this work may be disclosed,
*    reproduced, copied, transmitted, or used in any way for any purpose,
*    without the express written permission of Vivante Corporation.
*
*****************************************************************************/


/* Generated by wayland-scanner 1.11.0 */

#ifndef VIVANTE_SERVER_PROTOCOL_H
#define VIVANTE_SERVER_PROTOCOL_H

#include <stdint.h>
#include <stddef.h>
#include "wayland-server.h"

#ifdef __cplusplus
extern "C" {
#endif

struct wl_client;
struct wl_resource;

/**
 * @page page_vivante The vivante protocol
 * @section page_ifaces_vivante Interfaces
 * - @subpage page_iface_wl_viv -
 */
struct wl_buffer;
struct wl_viv;

/**
 * @page page_iface_wl_viv wl_viv
 * @section page_iface_wl_viv_api API
 * See @ref iface_wl_viv.
 */
/**
 * @defgroup iface_wl_viv The wl_viv interface
 */
extern const struct wl_interface wl_viv_interface;

/**
 * @ingroup iface_wl_viv
 * @struct wl_viv_interface
 */
struct wl_viv_interface {
    /**
     */
    void (*create_buffer)(struct wl_client *client,
                  struct wl_resource *resource,
                  uint32_t id,
                  uint32_t width,
                  uint32_t height,
                  uint32_t stride,
                  int32_t format,
                  int32_t type,
                  uint32_t node,
                  int32_t pool,
                  uint32_t size);
};


#ifdef __cplusplus
}
#endif

#endif
