##############################################################################
#
#    Copyright (c) 2005 - 2020 by Vivante Corp.  All rights reserved.
#
#    The material in this file is confidential and contains trade secrets
#    of Vivante Corporation. This is proprietary information owned by
#    Vivante Corporation. No part of this work may be disclosed,
#    reproduced, copied, transmitted, or used in any way for any purpose,
#    without the express written permission of Vivante Corporation.
#
##############################################################################


#
# Linux build file for user HAL layer.
#

################################################################################
# Include common definitions.

include $(AQROOT)/makefile.linux.def
#include ../makefile.linux.def

################################################################################
# Define target module name.

ifeq ($(gcdSTATIC_LINK),1)
STATIC              := 1
TARGET_NAME         := libarchmodelSw.a
else
DYNAMIC             := 1
TARGET_NAME         := libArchModelSw.so
TARGET_SONAME       := libArchModelSw.so
endif
TARGET_MODULE       := $(OBJ_DIR)/$(TARGET_NAME)
################################################################################
# Installation directory.

INSTALL_DIR         := $(SDK_DIR)/drivers

################################################################################
# Supply additional include directories.

INCLUDE := -I$(AQROOT)/compiler/libVSC/include \
           -I$(AQROOT)/sdk/inc \
           -I$(AQROOT)/driver/khronos/libOpenVX/vipArchPerfMdl_dev/libarchmodelSw/include \
           -I$(AQROOT)/driver/khronos/libOpenVX/libarchmodelInterface/include \
           -I$(AQROOT)/driver/khronos/libOpenVX/vipArchPerfMdl_dev/vipArchPerf \

CFLAGS += $(INCLUDE)

CFLAGS += -DUSE_LIB_NN_ARCH_PERF

#Add extra flags for object files.

################################################################################
ifneq ($(USE_ARMCC),1)
  CFLAGS += -fPIC -Wall -fno-builtin

    CFLAGS += -Werror -ansi
endif
################################################################################
# Define flags for the linker.

ifneq ($(USE_ARMCC),1)
    LDFLAGS += -Wl,--version-script=libarchmodelSw.map
endif

ifeq ($(USE_ARMCC),1)
    LDFLAGS += --shared -L--soname=,$(TARGET_SONAME)
else
    LDFLAGS += -Wall -Wl,-z,defs -shared -Wl,-soname,$(TARGET_SONAME)
endif

################################################################################
# Supply dependent libraries.
LIBS += -lm -lpthread -ldl -lrt
LIBS += -lstdc++
LIBS += -L $(SDK_DIR)/drivers
LIBS += -l NNArchPerf

################################################################################
# Describe object files.

OBJECTS := $(OBJ_DIR)/archSwCommon.o \
           $(OBJ_DIR)/archSwPerf.o \

################################################################################
# Define targets.

.PHONY: all clean install

all: $(TARGET_MODULE)

clean:
	@rm -rf $(OBJ_DIR)

install: all
	@mkdir -p $(INSTALL_DIR)
	@-cp $(TARGET_MODULE) $(INSTALL_DIR)

################################################################################
# Module rules.

ifeq ($(STATIC),1)
$(TARGET_MODULE): $(OBJECTS)
	@echo "  ARCHIVE \033[1m$(notdir $@)\033[0m"
	@$(AR) -r -c $@ $(OBJECTS)
ifneq ($(USE_ARMCC),1)
	@$(RANLIB) $@
endif
endif

ifeq ($(DYNAMIC),1)
$(TARGET_MODULE): $(OBJECTS)
	@echo "  LINK    \033[1m$(notdir $@)\033[0m"
	@$(CC) $(LDFLAGS) -o $@ $(OBJECTS) $(LIBS)
endif

################################################################################
# Object rules.

$(OBJ_DIR)/%.o: %.cpp
	@echo "  COMPILE $(abspath $<)"
	@mkdir -p $(OBJ_DIR)
	@$(CC) -c $(CFLAGS) -MMD -o $@ $<

# object dependencies.
-include $(OBJECTS:.o=.d)

