/****************************************************************************
*
*    Copyright (c) 2005 - 2020 by Vivante Corp.  All rights reserved.
*
*    The material in this file is confidential and contains trade secrets
*    of Vivante Corporation. This is proprietary information owned by
*    Vivante Corporation. No part of this work may be disclosed,
*    reproduced, copied, transmitted, or used in any way for any purpose,
*    without the express written permission of Vivante Corporation.
*
*****************************************************************************/


/* Please do NOT edit this file. */

#ifndef __gc_gralloc_priv_h_
#define __gc_gralloc_priv_h_

#include "gralloc_priv.h"

/*
 * Private gralloc usage(s) for render target allocation.
 *
 * TODO (Soc-vendor): Soc-vendor please determine the values. Make sure the
 * bits are not conflicted with other usage bits.
 */
#define GRALLOC_USAGE_PRIVATE_0_VIV         0x01000000
#define GRALLOC_USAGE_PRIVATE_1_VIV         0x02000000
#define GRALLOC_USAGE_PRIVATE_2_VIV         0x04000000
#define GRALLOC_USAGE_PRIVATE_3_VIV         0x08000000


/* Buffer types combined from private gralloc usage bits. */
/* 001: gcvSURF_RENDER_TARGET. */
#define GRALLOC_USAGE_RENDER_TARGET_VIV \
    (GRALLOC_USAGE_PRIVATE_0_VIV)

/* 010: gcvSURF_RENDER_TARGET_NO_TILE_STATUS. */
#define GRALLOC_USAGE_RENDER_TARGET_NO_TS_VIV \
    (GRALLOC_USAGE_PRIVATE_1_VIV)

/* 011: gcvSURF_RENDER_TARGET | gcv_SURF_NO_COMPRESSION. */
#define GRALLOC_USAGE_RENDER_TARGET_NO_CC_VIV \
    (GRALLOC_USAGE_PRIVATE_1_VIV | GRALLOC_USAGE_PRIVATE_0_VIV)

/* 100: gcvSURF_RENDER_TARGET + MSAA. */
#define GRALLOC_USAGE_RENDER_TARGET_MSAA_VIV \
    (GRALLOC_USAGE_PRIVATE_2_VIV)

/* 101: gcvSURF_TEXTURE. */
#define GRALLOC_USAGE_TEXTURE_VIV \
    (GRALLOC_USAGE_PRIVATE_2_VIV | GRALLOC_USAGE_PRIVATE_0_VIV)

/* 110: gcvSURF_BITMAP, VG. */
#define GRALLOC_USAGE_HW_VG_RENDER_VIV \
    (GRALLOC_USAGE_PRIVATE_2_VIV | GRALLOC_USAGE_PRIVATE_1_VIV)

/* Type mask. */
#define GRALLOC_USAGE_PRIVATE_MASK_VIV \
    (GRALLOC_USAGE_PRIVATE_2_VIV | GRALLOC_USAGE_PRIVATE_1_VIV | GRALLOC_USAGE_PRIVATE_0_VIV)

/* Dummy bit. */
#define GRALLOC_USAGE_DUMMY_VIV \
    (GRALLOC_USAGE_PRIVATE_3_VIV)


struct gc_native_handle_t
{
    int64_t surface;

    int     shBuf;

    int     reserved;

    int     width;
    int     height;
    int     format;
    int     stride;

    int     halFormat;
    int     type;
    int     samples;

    int     node;
    int     nodePool;
    int     nodeSize;

    int     tsNode;
    int     tsNodePool;
    int     tsNodeSize;

    int     hwDoneSignal;

    int     lockUsage;
    int     allocUsage;
    int     clientPID;
}
__attribute__((aligned(sizeof(int)),packed));

typedef struct gc_native_handle_t gc_native_handle_t;

/* Get gc_native_handle_t from buffer handle.  */
static inline gc_native_handle_t *
gc_native_handle_get(
    buffer_handle_t Handle
    )
{
    struct private_handle_t * hnd = (struct private_handle_t *) Handle;
    return (gc_native_handle_t *) hnd->viv_priv;
}

/* Get buffer handle from gc_native_handle. */
static inline struct private_handle_t *
private_handle_get(
    gc_native_handle_t * Handle
    )
{
    struct private_handle_t * hnd = 0;
    intptr_t offset = (intptr_t) &hnd->viv_priv;

    return (struct private_handle_t *) ((intptr_t) Handle - offset);
}

#endif /* __gc_gralloc_priv_h_ */

