##############################################################################
#
#    Copyright 2012 - 2020 Vivante Corporation, Santa Clara, California.
#    All Rights Reserved.
#
#    Permission is hereby granted, free of charge, to any person obtaining
#    a copy of this software and associated documentation files (the
#    'Software'), to deal in the Software without restriction, including
#    without limitation the rights to use, copy, modify, merge, publish,
#    distribute, sub license, and/or sell copies of the Software, and to
#    permit persons to whom the Software is furnished to do so, subject
#    to the following conditions:
#
#    The above copyright notice and this permission notice (including the
#    next paragraph) shall be included in all copies or substantial
#    portions of the Software.
#
#    THE SOFTWARE IS PROVIDED 'AS IS', WITHOUT WARRANTY OF ANY KIND,
#    EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
#    MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT.
#    IN NO EVENT SHALL VIVANTE AND/OR ITS SUPPLIERS BE LIABLE FOR ANY
#    CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
#    TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
#    SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
##############################################################################


MAKEOPTONS :=

ifeq ($(DEBUG), 1)
MAKEOPTIONS :=DEBUG=1
endif

ifeq ($(gcdSTATIC_LINK), 1)
MAKEOPTIONS +=gcdSTATIC_LINK=1
endif

.PHONY: all util lib res app install clean

all: app

util:
#	make -C utils/resource -f resource.mk

res: util
#	make -C src -f resources.mk

lib: res
	make -C lib/math -f makefile.linux $(MAKEOPTIONS)
	make -C lib/glutils -f makefile.linux $(MAKEOPTIONS)
	make -C lib/rc -f makefile.linux $(MAKEOPTIONS)

app: lib
	make -C src -f makefile.linux $(MAKEOPTIONS)

install: all
	make -C src -f makefile.linux $(MAKEOPTIONS) install

clean:
	make -C lib/math -f makefile.linux clean
	make -C lib/glutils -f makefile.linux clean
	make -C lib/rc -f makefile.linux clean
	make -C src -f makefile.linux clean
#	make -C utils/resource -f resource.mk clean
#	make -C src -f resources.mk clean

