##############################################################################
#
#    Copyright 2012 - 2020 Vivante Corporation, Santa Clara, California.
#    All Rights Reserved.
#
#    Permission is hereby granted, free of charge, to any person obtaining
#    a copy of this software and associated documentation files (the
#    'Software'), to deal in the Software without restriction, including
#    without limitation the rights to use, copy, modify, merge, publish,
#    distribute, sub license, and/or sell copies of the Software, and to
#    permit persons to whom the Software is furnished to do so, subject
#    to the following conditions:
#
#    The above copyright notice and this permission notice (including the
#    next paragraph) shall be included in all copies or substantial
#    portions of the Software.
#
#    THE SOFTWARE IS PROVIDED 'AS IS', WITHOUT WARRANTY OF ANY KIND,
#    EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
#    MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT.
#    IN NO EVENT SHALL VIVANTE AND/OR ITS SUPPLIERS BE LIABLE FOR ANY
#    CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
#    TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
#    SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
##############################################################################


######################################################
#include global difinitions.
#

include $(AQROOT)/makefile.linux.def

######################################################
# vv_launcher
VVLAUNCHER                := vv_launcher

######################################################
# vv_launcher
TEX_LOD_BIAS              := texture_lod_bias

######################################################
# VTT test suite
VTT_TEST_SUITE            := VTT

######################################################
# TexDirect Tests

TEX_DIRECT_ES20	          := TexDirect
TEX_DIRECT_MAP_ES20       := TexDirectMap
TEX_DIRECT_TILED_MAP_ES20 := TexDirectTiledMap

TEX_DIRECT_ES20_TEST      := $(TEX_DIRECT_ES20)
TEX_DIRECT_ES20_TEST      += $(TEX_DIRECT_MAP_ES20)
TEX_DIRECT_ES20_TEST      += $(TEX_DIRECT_TILED_MAP_ES20)


#Components of the project.
ES20_TEST   := $(VVLAUNCHER)
ES20_TEST   += $(TEX_LOD_BIAS)
ES20_TEST   += $(VTT_TEST_SUITE)
ES20_TEST   += $(TEX_DIRECT_ES20_TEST)

######################################################
# Define the macros used in the common file.

MODULES		:= $(ES20_TEST)
MAIN_MODULE	:= $(ES20_TEST)

######################################################
# Include the common makefile.

include $(AQROOT)/common.node

######################################################
# Define the denpendencies.

