##############################################################################
#
#    Copyright (c) 2005 - 2019 by Vivante Corp.  All rights reserved.
#
#    The material in this file is confidential and contains trade secrets
#    of Vivante Corporation. This is proprietary information owned by
#    Vivante Corporation. No part of this work may be disclosed,
#    reproduced, copied, transmitted, or used in any way for any purpose,
#    without the express written permission of Vivante Corporation.
#
##############################################################################


LIST=COMPONENTS
ENABLE_VG ?= 0

EARLY_DIRS=halkernel halarchkernel halarchkernel_vg galcore halosuser halarchuser halarchuser_vg gal vsc egl vdk gles11 gles20sc gles30 clc cl vg11 vg11_vg archmodel vx
include recurse.mk
